project_id = "echs-math"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[functions.account-api]
verify_jwt = false

[functions.institution-api]
verify_jwt = false

[functions.learning-sync]
verify_jwt = false
