const VERSION = "echs-platform-initial-setup-v1";
const STATIC_CACHE = `${VERSION}-static`;
const RUNTIME_CACHE = `${VERSION}-runtime`;
const SHELL = [
  "./","./index.html","./offline.html","./manifest.json","./login.html","./config/institution.json",
  "./css/portal.css","./css/practice-integration.css","./css/official-ap-integration.css","./css/platform-foundation.css","./css/institution.css","./css/institution-polish.css","./css/institution-premium.css","./css/institution-responsive.css","./css/institution-completion.css",
  "./data/courses.js","./data/ap-calculus-update.js","./data/ap-precalculus-update.js",
  "./js/portal.js","./js/practice-integration.js","./js/official-ap-integration.js","./js/platform-foundation.js","./js/lesson-learning-bridge.js","./js/institution-client.js","./js/institution-experience.js","./js/institution-completion.js","./js/institution-portal.js","./js/login.js",
  "./question-bank/index.html","./question-bank/practice.html","./question-bank/exam.html","./question-bank/dashboard.html","./question-bank/mistakes.html","./question-bank/student.html","./question-bank/teacher.html","./question-bank/parent.html","./question-bank/admin.html",
  "./question-bank/css/bank.css","./question-bank/css/practice-studio.css","./question-bank/css/learning-system.css",
  "./question-bank/js/learning-system.js","./question-bank/js/sync-adapter.js","./question-bank/js/bank.js","./question-bank/js/learning-home.js","./question-bank/js/practice.js","./question-bank/js/exam.js","./question-bank/js/dashboard.js","./question-bank/js/mistakes.js","./question-bank/js/student-cloud.js","./question-bank/js/teacher-cloud.js","./question-bank/js/parent-cloud.js","./question-bank/js/admin-accounts.js",
  "./question-bank/data/catalog.json","./question-bank/data/blackboard-addon.json",
  "./assets/echs_logo.png","./assets/icon-192.png","./assets/icon-512.png"
];
self.addEventListener("install",event=>{event.waitUntil(caches.open(STATIC_CACHE).then(cache=>cache.addAll(SHELL)).then(()=>self.skipWaiting()))});
self.addEventListener("activate",event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith("echs-")&&![STATIC_CACHE,RUNTIME_CACHE].includes(key)).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
async function networkFirst(request,fallbackUrl){const cache=await caches.open(RUNTIME_CACHE);try{const response=await fetch(request);if(response&&response.ok&&response.type!=="opaque")cache.put(request,response.clone());return response}catch(_error){return(await cache.match(request))||(await caches.match(request))||(fallbackUrl?caches.match(fallbackUrl):Response.error())}}
async function staleWhileRevalidate(request){const cache=await caches.open(RUNTIME_CACHE),cached=await cache.match(request)||await caches.match(request);const network=fetch(request).then(response=>{if(response&&response.ok&&(response.type==="basic"||response.type==="cors"))cache.put(request,response.clone());return response}).catch(()=>cached);return cached||network}
self.addEventListener("fetch",event=>{const request=event.request;if(request.method!=="GET")return;const url=new URL(request.url);const setupPage=url.origin===location.origin&&/\/setup\.html$/i.test(url.pathname);if(setupPage){event.respondWith(fetch(request,{cache:"no-store"}));return}if(request.mode==="navigate"){event.respondWith(networkFirst(request,"./offline.html"));return}if(url.origin!==location.origin){const privateApi=/\/functions\/v1\/(?:account-api|institution-api|learning-sync|setup-api)(?:\/|$)/.test(url.pathname);if(privateApi){event.respondWith(fetch(request));return}event.respondWith(staleWhileRevalidate(request));return}const isQuestionPayload=/\/question-bank\/data\/(imported|ap|courses)\//.test(url.pathname),isJson=url.pathname.endsWith(".json");if(isQuestionPayload||isJson){event.respondWith(networkFirst(request));return}if(["style","script","image","font"].includes(request.destination)){event.respondWith(staleWhileRevalidate(request));return}event.respondWith(networkFirst(request))});
self.addEventListener("message",event=>{if(event.data==="SKIP_WAITING")self.skipWaiting()});
