import {make,task,notes,sim,choice,number,table,graph} from './content-helpers.mjs';
export const LESSONS={
  '1.1':make('1.1',[
    'Connect a function rule, table, graph and verbal description.',
    'Distinguish output sign, direction of change and qualitative concavity.',
    'Identify domains, images, preimages and zeros with suitable precision.'
  ],[
    task('battery','Warm-up: what is the battery doing?',
      'A battery has the recorded charge below. Which statement describes these observations?',
      ['Every recorded charge is positive, but the outputs decrease as time increases.',
       'The equal one-minute intervals have equal changes of −10 percentage points. A linear model fits these samples.',
       'A finite table alone does not determine every value between the observations.'],
      {table:table(['Time / min','Charge / %'],[[0,80],[1,70],[2,60],[3,50],[4,40]]),
       answer:choice(['Positive outputs mean the function is increasing.','The charge is positive and decreases at a constant recorded rate.','The rate increases because the charge is positive.'],1)}),
    notes('function','One input, one output',
      'The pairs are (1,2), (2,2), (3,5). Is this a function? Does a repeated output cause a problem?',
      ['Each input has exactly one output, so this is a function.',
       'The domain is {1,2,3}. The range is {2,5}. The preimage of output 2 is {1,2}.',
       'A repeated output is allowed. Assigning two different outputs to the same input would fail the function definition.']),
    task('preimages','Your turn: images and preimages',
      'For \\(f(x)=x^2-4\\) on \\([-3,3]\\), find the image of 2 and all preimages of 0.',
      ['The image of 2 is \\(f(2)=2^2-4=0\\).',
       'For preimages, solve \\(x^2-4=0\\), giving \\(x=-2\\) and \\(x=2\\). Both are in the domain.',
       'The preimage of 0 is the set \\(\\{-2,2\\}\\). Each input still has only one output.'],
      {graph:graph([1,0,-4],[-3,3],[-5,6]),hint:'For the image substitute the input. For the preimage set the output equal to 0.'}),
    notes('equal-functions','When are two functions equal?',
      'Compare \\(f(x)=(x^2-1)/(x-1)\\) and \\(g(x)=x+1\\), each with its natural domain. Are they the same function?',
      ['For \\(x\\ne1\\), cancellation gives \\(f(x)=x+1\\).',
       'The natural domain of f excludes 1. The domain of g includes 1, and \\(g(1)=2\\).',
       'Equal functions need the same domain and the same output at every input in that domain. These functions are not equal on their natural domains.']),
    notes('sign-direction','Sign and direction answer different questions',
      'On \\([0,3]\\), \\(p(x)=-8+2x\\). Are the outputs positive or negative? Is p increasing or decreasing?',
      ['The outputs range from −8 to −2, so they are negative.',
       'For larger inputs the outputs are larger, so p is increasing.',
       'Output sign describes position relative to the horizontal axis. Direction describes changes as the input increases.'],
      {graph:graph([2,-8],[0,3],[-9,1])}),
    task('concavity','A rising graph can become less steep',
      'The table describes \\(q(x)=-(x-4)^2+16\\) for \\(0\\le x\\le4\\). Describe the outputs and their changes.',
      ['The outputs 0,7,12,15,16 increase.',
       'Their consecutive changes are 7,5,3,1 over equal input intervals, so the rates decrease.',
       'The given quadratic is increasing on this part of its domain and concave down.'],
      {table:table(['x','q(x)'],[[0,0],[1,7],[2,12],[3,15],[4,16]]),
       answer:choice(['Increasing and concave up','Increasing and concave down','Decreasing and concave up'],1),
       graph:graph([-1,8,0],[0,4],[-1,17])}),
    notes('four-combinations','Direction and concavity together',
      'Can a decreasing function have an increasing rate of change? Use \\(r(x)=x^2\\) from x=−3 to x=0.',
      ['The outputs are 9,4,1,0, so the function decreases.',
       'The changes over the unit intervals are −5,−3,−1. These rates increase because they become less negative.',
       'The graph is decreasing and concave up. Increasing rates do not necessarily mean increasing outputs.'],
      {graph:graph([1,0,0],[-3,0],[-1,10])}),
    sim('toy-car','Activity: the toy car and the wall',
      'Predict the distance pattern during one full lap. How will doubling the radius or the lap time change the graph?',
      {kind:'native',selector:'#toy-car-lab [data-context-lab]'},
      ['Read the distance and graph at the start, quarter lap, half lap and complete lap.',
       'Double only the radius, then restore it and double only the lap time. Compare the range and repetition time.',
       'Explain why constant speed around a circle does not produce a constant rate of change of distance from a wall.']),
    sim('vase','Activity: constant inflow, changing depth',
      'Predict which vessel produces a straight height-versus-time graph. How does horizontal area affect the rise in water depth?',
      {kind:'native',selector:'#filling-vessels-lab [data-context-lab]'},
      ['Test a cylinder, a widening vessel and a narrowing vessel using equal increments of time.',
       'The same added volume makes a smaller height increase where the cross-sectional area is larger.',
       'State which quantity has a constant rate: volume increases at constant inflow, while height need not.']),
    task('piecewise','Student activity: sketch the pump story',
      'A tank starts with 10 L. It gains 6 L/min for 3 minutes, stays unchanged for 2 minutes, then loses 4 L/min for 4 minutes. Sketch volume versus time and find the final volume.',
      ['From t=0 to 3 the graph rises from (0,10) to (3,28).',
       'From t=3 to 5 it is horizontal at 28 L. From t=5 to 9 it falls to 12 L.',
       'The final volume is \\(28-4(4)=12\\) L. The slopes express inflow, no net change, and outflow.'],
      {answer:number(12,'L'),hint:'Calculate the volume at each change of stage. A horizontal section means no output change.'}),
    notes('zeros','Zeros and intercepts',
      'For \\(f(x)=(x-1)(x+3)\\), distinguish the zeros, the x-intercepts and the y-intercept.',
      ['The zeros are inputs −3 and 1 because these make f(x)=0.',
       'The x-intercepts are the ordered pairs (−3,0) and (1,0).',
       'The y-intercept is \\((0,f(0))=(0,-3)\\).'],
      {graph:graph([1,2,-3],[-4,2],[-5,7])}),
    task('endpoints','Challenge: endpoint evidence',
      'A continuous function satisfies f(0)=2 and f(6)=8. Must it be increasing throughout the interval?',
      ['No. Its final output is greater, but that does not establish increasing behavior throughout the interval.',
       'For example, connect (0,2), (2,10), (4,1), (6,8) by straight segments. This continuous function both rises and falls.',
       'An increasing function requires the appropriate output ordering for every pair of increasing inputs in the interval.'],
      {answer:choice(['Yes, because 8 is greater than 2.','No, a higher final value allows rises and falls in between.'],1)}),
    task('exit-check','Exit check: defend the description',
      'A function has negative outputs and rises more slowly as x increases. Choose its direction and concavity.',
      ['The function is increasing because its outputs rise.',
       'Its rates decrease, so the described smooth graph is concave down.',
       'Negative outputs do not change either conclusion.'],
      {answer:choice(['Decreasing, concave down','Increasing, concave up','Increasing, concave down'],2)})
  ],[['ECHS_AP_Precalculus_Lessons_1_1_and_1_2.pptx','2–29']]),
  '1.2':make('1.2',[
    'Calculate and interpret average rates using consistent endpoint order and units.',
    'Connect a secant slope to a table, formula and graph.',
    'Distinguish an interval average from an estimate of an instantaneous rate.'
  ],[
    task('warm-up','Warm-up: amount or rate?',
      'A reservoir increases from 20 L to 44 L over 6 minutes. What is its average rate of change?',
      ['The volume change is \\(44-20=24\\) L.',
       'Divide by the input change: \\(24/6=4\\) L/min.',
       'The volume increases by 4 litres per minute, on average, over this interval.'],
      {answer:number(4,'L/min')}),
    notes('definition','The average rate of change',
      'Why do we divide output change by input change rather than report output change alone?',
      ['For \\(a\\ne b\\), the average rate is \\((f(b)-f(a))/(b-a)\\).',
       'The quotient compares change per input unit. It is the slope of the secant through the two endpoint points.',
       'The units are output units divided by input units. The input need not be time.']),
    task('graph-endpoints','Worked example: read the two endpoints',
      'The graph includes A=(1,2) and B=(3,4). Find the average rate from x=1 to x=3.',
      ['The output change is \\(4-2=2\\) and the input change is \\(3-1=2\\).',
       'The average rate is \\((4-2)/(3-1)=1\\).',
       'This is the slope of the secant through A and B, whether the curve between them is straight or curved.'],
      {answer:number(1,'output units per input unit'),table:table(['Point','x','f(x)'],[['A',1,2],['B',3,4]])}),
    task('table-rate','Your turn: a table with unequal spacing',
      'Find the average rate of change of distance from t=13 to t=25 seconds. Give an exact fraction and interpret its sign.',
      ['Use d(13)=76 and d(25)=30. Intermediate rows do not change the full-interval endpoint quotient.',
       'The rate is \\((30-76)/(25-13)=-46/12=-23/6\\) m/s.',
       'The measured distance decreases by about 3.833 metres per second, on average, over this interval. This distance is not automatically total distance travelled.'],
      {table:table(['t / s','d(t) / m'],[[10,80],[13,76],[19,43],[25,30]]),answer:number(-23/6,'m/s')}),
    task('units','Context: the input is distance',
      'A hypothetical sound model gives S(5)=96 dB and S(85)=52 dB. Find the average rate of sound level with respect to distance.',
      ['The change in sound level is \\(52-96=-44\\) dB.',
       'The input interval has width \\(85-5=80\\) metres. The rate is \\(-44/80=-0.55\\) dB/m.',
       'From 5 to 85 metres, sound level decreases by 0.55 decibel per additional metre, on average. These numbers are hypothetical.'],
      {answer:number(-.55,'dB/m')}),
    notes('subtraction','Endpoint order must match',
      'A student uses \\((f(b)-f(a))/(a-b)\\). What went wrong?',
      ['The numerator uses ending output minus starting output, while the denominator uses the reverse input order.',
       'Reverse both differences together or reverse neither. Reversing both preserves the quotient.',
       'Reversing only one difference changes the sign and gives the wrong rate.']),
    task('formula','Your turn: endpoints from a formula',
      'For \\(h(t)=3t-t^2\\), find the average rate on \\([2,5]\\).',
      ['Evaluate \\(h(2)=6-4=2\\) and \\(h(5)=15-25=-10\\).',
       'Compute \\((-10-2)/(5-2)=-12/3=-4\\).',
       'The average is negative even though the graph need not decrease over every possible interval.'],
      {answer:number(-4),graph:graph([-1,3,0],[0,5],[-11,4])}),
    sim('secant','Simulation: move the secant endpoints',
      'Predict how the average rate of a quadratic changes when both endpoints move, then test your prediction.',
      {kind:'rates',initial:{a:1,b:0,c:0,start:0,width:1}},
      ['Keep the interval width fixed and move its starting input. Compare the new endpoint values and secant slopes.',
       'Keep the starting input fixed and increase the width. Explain the new quotient.',
       'Set the quadratic coefficient to zero and check why the interval rate becomes independent of position.']),
    task('same-average','Equal averages do not fix the path',
      'Two functions agree at the interval endpoints. Must they have the same average rate? Must they have the same interior graph?',
      ['They have the same average rate because the quotient uses the same endpoint inputs and outputs.',
       'They need not agree between the endpoints. A straight line and a curve can share the same endpoints.',
       'A single average rate does not establish a constant instantaneous rate.'],
      {answer:choice(['Same average and same graph.','Same average, but the interior graphs can differ.','Different averages because the curves differ.'],1)}),
    notes('local-estimate','Nearby averages estimate a local rate',
      'For \\(f(x)=x^2\\), compare averages on \\([2-h,2]\\) and \\([2,2+h]\\), where h>0.',
      ['The left average is \\((4-(2-h)^2)/h=4-h\\).',
       'The right average is \\(((2+h)^2-4)/h=4+h\\).',
       'For small positive h, both are near 4. Nearby interval slopes support a local-rate estimate without equating a fixed secant to a tangent.']),
    task('nearby-table','Calculator activity: compare two sides',
      'Use the given values to find the average rates immediately to the left and right of x=2. What local rate do they suggest?',
      ['The left rate is \\((4-3.9601)/(2-1.99)=3.99\\).',
       'The right rate is \\((4.0401-4)/(2.01-2)=4.01\\).',
       'The values suggest a local rate near 4. The formula \\(f(x)=x^2\\) confirms the symmetric pattern as intervals shrink.'],
      {calculator:'Calculator optional',table:table(['x','x²'],[[1.99,3.9601],[2,4],[2.01,4.0401]])}),
    notes('ti84','TI-84 Plus CE: a secant calculation',
      'How can you use the calculator while preserving the mathematical setup?',
      ['Enter the function in Y₁ using Y=. Use parentheses around complete numerators and denominators.',
       'On the home screen evaluate \\((Y_1(b)-Y_1(a))/(b-a)\\). Insert Y₁ through VARS, Y-VARS, Function, Y₁.',
       'Use GRAPH or TABLE to check the endpoint outputs and a suitable window. Report the quotient with units and the named interval.'],
      {calculator:'TI-84 Plus CE'}),
    task('symmetric','Challenge: zero average, changing output',
      'For \\(p(x)=(x-3)^2\\), calculate the average rate on \\([1,5]\\). Does a zero average mean p is constant?',
      ['The endpoint outputs are \\(p(1)=4\\) and \\(p(5)=4\\), so the average rate is 0.',
       'The function decreases to p(3)=0 and then increases. It is not constant.',
       'Zero average rate establishes equal endpoint outputs for a nonzero input width.'],
      {answer:number(0),graph:graph([1,-6,9],[1,5],[-1,5])}),
    task('exit-check','Exit check: write the interpretation',
      'A model has W(2)=15 m³ and W(7)=5 m³. Find its average rate and state what the negative sign means.',
      ['Compute \\((5-15)/(7-2)=-2\\) m³ per input unit.',
       'Over the named interval, the modeled volume decreases by 2 m³ per input unit, on average.',
       'If the input is time in hours, the units are m³/h. State the input units before interpreting a contextual rate.'],
      {answer:number(-2,'m³ per input unit')})
  ],[['AP_Precalculus_Lesson_1.2_Worksheet_ECHS(1).pptx','1–17'],['ECHS_AP_Precalculus_Lessons_1_1_and_1_2.pptx','30–66']]),
  '1.3':make('1.3',[
    'Compare interval rates for linear and quadratic functions.',
    'Distinguish output differences, changes in average rates and rates of those changes.',
    'Use equal spacing and function-family assumptions when interpreting numerical patterns.'
  ],[
    task('warm-up','Warm-up: differences or rates?',
      'The inputs are 0,2,4,6 and outputs are 1,5,9,13. What is the common average rate?',
      ['Each output change is 4, while each input change is 2.',
       'Every interval rate is \\(4/2=2\\), not 4.',
       'A linear model with this rate is \\(f(x)=2x+1\\).'],
      {table:table(['x','f(x)'],[[0,1],[2,5],[4,9],[6,13]]),answer:number(2)}),
    notes('linear','Linear functions have a fixed secant slope',
      'For \\(f(x)=mx+b\\), why does every nonzero-width interval have average rate m?',
      ['Substitute the endpoints: \\(f(v)-f(u)=(mv+b)-(mu+b)=m(v-u)\\).',
       'Divide by \\(v-u\\ne0\\). The average rate is m.',
       'The intercept cancels. Changing b changes output values but not interval slopes.']),
    task('linear-turn','Your turn: compare two intervals',
      'For \\(D(t)=12t+5\\) km, with t in hours, compare the averages on \\([0,1.5]\\) and \\([2,5]\\).',
      ['The first quotient is \\((23-5)/1.5=12\\) km/h.',
       'The second is \\((65-29)/3=12\\) km/h.',
       'The initial 5 km changes the outputs, while the coefficient 12 determines the constant rate.'],
      {answer:number(12,'km/h')}),
    notes('quadratic-pattern','Quadratic averages form a linear pattern',
      'For \\(f(x)=x^2-2x\\), predict the average rates on consecutive unit intervals from [1,2] through [5,6].',
      ['The endpoint values are −1,0,3,8,15,24.',
       'The averages on the five unit intervals are 1,3,5,7,9.',
       'Consecutive averages increase by 2 for every one-unit shift in interval position.'],
      {table:table(['x','f(x)'],[[1,-1],[2,0],[3,3],[4,8],[5,15],[6,24]])}),
    task('quadratic-turn','Your turn: use the endpoint rule',
      'For \\(g(x)=2x^2+2x+1\\), find the average rate on \\([2,5]\\).',
      ['Evaluate \\(g(2)=13\\) and \\(g(5)=61\\).',
       'The average rate is \\((61-13)/(5-2)=48/3=16\\).',
       'Unlike a linear function, a quadratic generally has different rates on different intervals.'],
      {answer:number(16)}),
    notes('quadratic-rule','A rule for a general interval',
      'For \\(f(x)=Ax^2+Bx+C\\), simplify its average rate on \\([u,u+h]\\), h≠0.',
      ['The output change is \\(A(2uh+h^2)+Bh\\).',
       'Dividing by h gives \\(2Au+Ah+B\\). This depends linearly on the starting input u.',
       'The constant C cancels. For a genuine quadratic A is nonzero.']),
    sim('rate-model','Activity: the three difference layers',
      'Predict what changes when the common input step h doubles. Test the output differences and the interval rates separately.',
      {kind:'rates',initial:{a:1,b:2,c:1,start:0,width:1}},
      ['Keep the formula fixed and double h. Compare raw output differences with the averages that divide them by h.',
       'For a quadratic, raw second differences are 2Ah². Changes in consecutive average rates are 2Ah.',
       'Divide that change in average rate by the input shift h to obtain 2A, with output per input squared units.']),
    task('width-two','Your turn: a step of two',
      'For \\(f(x)=x^2\\) at x=0,2,4,6, find the raw first differences, the averages and the change in averages.',
      ['The values are 0,4,16,36. Raw first differences are 4,12,20.',
       'Divide by h=2 to obtain average rates 2,6,10. Consecutive averages differ by 4.',
       'The raw second difference is 8. The rate of change of the averages is \\(4/2=2\\). Do not mix these quantities.'],
      {answer:choice(['Raw second difference 8; change in averages 4; rate of that change 2.','All three quantities are 8.','All three quantities are 4.'],0)}),
    notes('units','The units of a rate of a rate',
      'If distance is in metres and time is in seconds, what units describe the rate of change of interval speeds?',
      ['An interval distance rate has units m/s.',
       'A change in that rate still has units m/s.',
       'Dividing the change by a shift in seconds gives \\((\\mathrm{m/s})/\\mathrm{s}=\\mathrm{m/s^2}\\).']),
    task('nonconsecutive','Equal width, equally spaced positions',
      'For \\(f(x)=x^2\\), compare the rates on [0,1], [2,3] and [4,5]. The intervals are not consecutive. Do their rates still have constant differences?',
      ['The interval rates are 1,5,9.',
       'The starts 0,2,4 are equally spaced, so the averages increase by 4 for each shift of 2.',
       'Dividing by the shift gives \\(4/2=2\\). Consecutive intervals are one sufficient arrangement, but equal-width intervals at equally spaced positions also show this quadratic pattern.'],
      {answer:choice(['No, intervals must touch.','Yes, equal widths and equally spaced starts give the linear rate pattern.'],1)}),
    task('unequal-starts','Equal width alone is insufficient',
      'For \\(f(x)=x^2\\), compare the rates on [0,1], [2,3] and [5,6]. Explain the different changes.',
      ['The rates are 1,5,11, with changes 4 and 6.',
       'The starts shift by 2 and then 3, so the rate changes per start-input unit are \\(4/2=2\\) and \\(6/3=2\\).',
       'Equal interval width alone does not make raw differences between rates constant when the interval positions are unevenly spaced.']),
    notes('concavity','Rates explain concavity',
      'For a quadratic, what does the sign of A tell you about its averages and concavity?',
      ['For increasing interval positions, A>0 makes equal-width average rates increase. The graph is concave up.',
       'A<0 makes these rates decrease. The graph is concave down.',
       'The signs of the individual rates still determine increase or decrease of outputs. A negative rate can become less negative.']),
    task('finite-evidence','Challenge: do four values prove a quadratic?',
      'Equally spaced samples have a constant nonzero second difference. Must the underlying function be exactly quadratic?',
      ['A quadratic is consistent with the pattern and is the natural choice among suitable polynomial models.',
       'Finite samples do not uniquely determine an arbitrary function. One can add a term that vanishes at all sampled inputs.',
       'State the function-family assumption when making a model claim, then check more evidence or residuals.'],
      {answer:choice(['Yes, finite samples prove the complete function.','They support a quadratic model, but need a family assumption for a global conclusion.'],1)}),
    task('exit-check','Exit check: explain three quantities',
      'For \\(p(x)=3x^2-x+2\\) and h=2, give the raw second difference, change in consecutive averages, and rate of change of those averages.',
      ['The raw second difference is \\(2Ah^2=2(3)(2^2)=24\\).',
       'The change in averages is \\(2Ah=2(3)(2)=12\\).',
       'Divide by the shift h=2: the rate of change of the averages is 6.'],
      {answer:choice(['24,12,6','12,12,12','6,12,24'],0)})
  ],[['AP_Precalculus_Lesson_1.3_Worksheet_ECHS(1).pptx','1–20'],['AP_Precalculus_Equal_Intervals_Examples.pptx','1–2']])
};
