import {make,task,notes,sim,choice,number,table} from './content-helpers.mjs';
export const LESSONS={
 '1.7':make('1.7',[
   'Retain all original denominator restrictions.',
   'Describe both rational-function tails using the leading terms or division.',
   'Distinguish a horizontal or slant asymptote from a domain boundary.'
 ],[
   task('warm-up','Warm-up: which input is excluded?',
     'Find the excluded input for \\(R(x)=(3x+2)/(x-4)\\).',
     ['The denominator is zero when x−4=0.',
      'The input x=4 is excluded. The numerator does not determine denominator restrictions.',
      'The natural domain is all real numbers except 4.'],
     {answer:number(4,'excluded input')}),
   notes('allowed','Restrictions come from the original rule',
     'For \\(R(x)=(x^2-4)/(x-2)\\), can cancellation make x=2 an allowed input?',
     ['The original denominator excludes x=2.',
      'For other inputs, the formula simplifies to x+2.',
      'The restriction survives simplification. The original rational function has a missing point at (2,4).']),
   notes('equal-degree','Equal degrees give a finite tail level',
     'Find both end limits of \\(R(x)=(3x+2)/(x-4)\\).',
     ['Divide numerator and denominator by x for large nonzero x: \\((3+2/x)/(1-4/x)\\).',
      'As x tends in either unbounded direction, the quotient tends to 3.',
      'The line y=3 is a horizontal asymptote. This describes end behavior, while x=4 is a separate domain restriction.']),
   task('equal-turn','Your turn: keep the leading signs',
     'Find the horizontal asymptote of \\(R(x)=(-6x^2+x+1)/(2x^2+5)\\).',
     ['The numerator and denominator have the same degree.',
      'Their leading-coefficient ratio is −6/2=−3.',
      'Both end limits are −3, and y=−3 is the horizontal asymptote. The denominator is positive for every real x.'],
     {answer:number(-3,'horizontal-asymptote output')}),
   notes('lower-degree','A lower numerator degree',
     'What happens to \\(R(x)=4/(x^2+1)\\) as x becomes large positive or large negative?',
     ['The denominator grows without bound in both directions while the numerator remains 4.',
      'Both end limits are 0. The horizontal asymptote is y=0.',
      'The function is positive at every real input and approaches 0 from above.']),
   task('degree-trap','Your turn: the coefficient-ratio trap',
     'Does \\(R(x)=(x^2+1)/(x-1)\\) have horizontal asymptote y=1 because both leading coefficients are 1?',
     ['No. The numerator degree is one greater than the denominator degree.',
      'Division gives \\(R(x)=x+1+2/(x-1)\\).',
      'The remainder term tends to 0, so the slant asymptote is y=x+1. There is no horizontal asymptote.'],
     {answer:choice(['Yes, always use the coefficient ratio.','No, the degrees differ and division gives a slant asymptote.'],1)}),
   notes('dominant','A leading-term model can be unbounded',
     'Describe both tails of \\(R(x)=(-2x^3+5)/(x^2+1)\\).',
     ['The leading-term quotient is −2x.',
      'For large negative x the outputs tend to positive infinity. For large positive x they tend to negative infinity.',
      'A ratio of leading coefficients by itself is a horizontal-asymptote rule only when the degrees match.']),
   sim('rational-model','Simulation: degrees, restrictions and tails',
     'Predict when the far outputs level off. Then change the numerator and denominator factors separately.',
     {kind:'rational',key:'ap-rational-tails'},
     ['Compare the declared numerator and denominator degrees with the plotted tails.',
      'Change a factor and inspect the original excluded inputs, even when a factor cancels.',
      'Use the tail formula or division to explain the numerical pattern. A bounded graphing window alone is not a proof.']),
   task('cost','Context: a hypothetical average cost',
     'A workshop has fixed cost 360 QAR and variable cost 18 QAR per item. For n positive integer items, its average cost is C(n)=18+360/n. Find C(120).',
     ['The fixed cost per item is 360/120=3 QAR.',
      'C(120)=18+3=21 QAR per item.',
      'As n grows, the model approaches 18 QAR per item. The practical domain is positive integers and the costs are hypothetical.'],
     {answer:number(21,'QAR per item')}),
   task('cost-limit','What does the asymptote mean?',
     'Under the cost model C(n)=18+360/n for positive integer n, can the average cost equal 18 QAR for any finite production size?',
     ['For every allowed finite n, 360/n is positive.',
      'The average cost remains above 18 QAR per item.',
      'It approaches 18 as n grows. A limit need not be attained by this model.'],
     {answer:choice(['Yes, once n is sufficiently large.','No, the finite fixed-cost contribution remains positive.'],1)}),
   notes('crossing','A horizontal asymptote can be crossed',
     'For \\(R(x)=(2x^2+x-3)/(x^2+1)\\), find where the function equals its horizontal asymptote y=2.',
     ['The equal degrees give the horizontal asymptote y=2.',
      'Solve \\(2x^2+x-3=2(x^2+1)\\), which gives x=5.',
      'The denominator is nonzero there. The graph crosses the horizontal asymptote at (5,2). End behavior does not forbid finite intersections.']),
   notes('ti84','TI-84 Plus CE: compare far inputs',
     'Use the calculator to support the end behavior of \\((3x+2)/(x-4)\\).',
     ['Enter Y₁=(3X+2)/(X−4) with parentheses around numerator and denominator.',
      'Evaluate large positive and negative inputs on the home screen or with a manually chosen table. Compare outputs with 3.',
      'Check the domain algebraically. A graph that draws near x=4 does not make that input defined.'],
     {calculator:'TI-84 Plus CE'}),
   task('exit-check','Exit check: classify three degree cases',
     'For a nonzero rational function, match numerator degree below, equal to, and one above denominator degree with the possible tail models.',
     ['Below: the end output tends to 0.',
      'Equal: the end output tends to the leading-coefficient ratio.',
      'One above: polynomial division yields a linear quotient, giving a slant asymptote after the remainder term tends to 0.'],
     {answer:choice(['0; coefficient ratio; linear quotient','Coefficient ratio in every case','No rational function has an unbounded tail'],0)})
 ],[['AP_Precalculus_1.7_ECHS.pptx','1–46']]),
 '1.8':make('1.8',[
   'Accept a numerator root as a zero only when it lies in the original domain.',
   'Use factors and sign tables to solve rational equations and inequalities.',
   'Distinguish zeros, holes and vertical-asymptote candidates.'
 ],[
   task('warm-up','Warm-up: a zero must be defined',
     'For \\(R(x)=(x-3)/(x+2)\\), find the zero.',
     ['The numerator is zero at x=3.',
      'The denominator at 3 is 5, so this input is allowed.',
      'The zero is 3, and the x-intercept is (3,0).'],
     {answer:number(3,'zero')}),
   notes('decision','Two checks for each candidate',
     'Why is solving the numerator equation not enough to identify a rational-function zero?',
     ['A zero must produce an actual output of 0.',
      'First find numerator roots, then check the original denominator at each one.',
      'A candidate with denominator 0 is outside the domain and cannot be a zero of the original function.']),
   task('canceled-zero','Your turn: exclude the canceled candidate',
     'Find the zeros of \\(R(x)=((x-2)(x+1))/((x-2)(x-4))\\).',
     ['The original domain excludes 2 and 4. Numerator candidates are 2 and −1.',
      'Reject 2 because it is excluded. At −1 the denominator is nonzero.',
      'The only zero is −1. The canceled factor leaves a hole at x=2.'],
     {answer:number(-1,'zero')}),
   notes('intercepts','Zeros and the y-intercept are separate',
     'For \\(R(x)=(x-3)/(x+2)\\), find both intercepts.',
     ['The x-intercept is (3,0), from the allowed numerator root.',
      'Evaluate the formula at x=0: R(0)=−3/2.',
      'The y-intercept is (0,−3/2). If 0 were excluded, there would be no y-intercept.']),
   task('no-zero','Your turn: no real numerator root',
     'Does \\(R(x)=(x^2+1)/(x-2)\\) have a real zero?',
     ['For real x, x²+1 is always positive.',
      'Its numerator cannot be zero at any real input.',
      'There are no real zeros, although x=2 is a denominator restriction.'],
     {answer:choice(['The zero is 2.','There are no real zeros.','The zero is −1.'],1)}),
   notes('sign-table','A rational sign table',
     'Solve \\((x+1)/(x-2)\\ge0\\).',
     ['Separate the real line at the zero −1 and the excluded input 2.',
      'Test signs: positive on x<−1, negative on −1<x<2, positive on x>2.',
      'Include −1 because it gives zero, and exclude 2 because the denominator vanishes. The solution is \\((-\\infty,-1]\\cup(2,\\infty)\\).']),
   task('strict-sign','Your turn: a strict inequality',
     'Solve \\((x-1)^2/(x+2)<0\\).',
     ['The numerator is nonnegative and is zero only at 1.',
      'The quotient is negative for x<−2, where the denominator is negative and the numerator is positive.',
      'The solution is x<−2. Exclude −2 because it is outside the domain.'],
     {answer:choice(['x<−2','−2<x<1','x≤1'],0)}),
   sim('zero-model','Simulation: which zeros survive?',
     'Predict what happens when a numerator root matches a denominator root. Test the zero and exclusion ledgers.',
     {kind:'rational',key:'ap-rational-zeros'},
     ['Move a numerator root to coincide with a denominator root.',
      'Check the original domain, surviving zeros and missing-point classification together.',
      'Change multiplicity and compare the sign on either side of each feature.']),
   task('zero-count','How many distinct real zeros?',
     'For \\(R(x)=((x+3)(x-1)^2)/((x+3)(x-4))\\), how many distinct real zeros remain?',
     ['The domain excludes −3 and 4.',
      'The numerator candidates −3 and 1 must both be checked. Reject −3 and retain 1.',
      'There is one distinct real zero, x=1, with multiplicity 2 in the reduced numerator.'],
     {answer:number(1,'distinct real zero')}),
   notes('equal-signs','Even multiplicity and sign',
     'Why does a factor with even multiplicity often keep the sign the same on both sides?',
     ['An even power is positive on either side of its root.',
      'If the other factors stay nonzero and keep their signs nearby, that even-power factor introduces no sign reversal.',
      'Apply this after checking cancellation and the original domain. An excluded point remains excluded even if the signs agree.']),
   notes('ti84','TI-84 Plus CE: a zero is more than a graph crossing',
     'How do you find and verify a calculator-supported zero?',
     ['Enter the complete rational expression in Y₁ with parentheses.',
      'Use GRAPH and 2nd TRACE, zero, with suitable left and right bounds. A repeated zero may touch rather than cross, so also inspect the factors.',
      'Substitute the candidate into the original denominator and verify it is nonzero. Calculator output does not override the domain.'],
     {calculator:'TI-84 Plus CE'}),
   task('squared-denominator','Challenge: a squared denominator',
     'Solve \\((x-3)/(x+1)^2>0\\).',
     ['The denominator is positive at every allowed input and excludes −1.',
      'The quotient sign is therefore the sign of x−3.',
      'The solution is x>3. The strict inequality excludes the zero 3.'],
     {answer:choice(['x>3','x>−1','−1<x<3'],0)}),
   task('exit-check','Exit check: explain a missing zero',
     'A numerator and denominator both contain the factor x−5. Is x=5 necessarily a zero?',
     ['The original denominator excludes x=5.',
      'An excluded input cannot be a zero of the original rational function.',
      'After cancellation, remaining factors determine whether the feature is a finite hole or a vertical asymptote.'],
     {answer:choice(['Yes, every numerator root is a zero.','No, the original domain excludes it.'],1)})
 ],[['AP_Precalculus_Lesson_1.8_ECHS.pptx','1–32']]),
 '1.9':make('1.9',[
   'Find vertical asymptotes using factors after cancellation and the original domain.',
   'Describe one-sided unbounded behavior with correct signs.',
   'Connect numerical tables, multiplicity and graph branches.'
 ],[
   task('warm-up','Warm-up: value versus nearby behavior',
     'For \\(R(x)=1/(x-2)\\), what is R(2)?',
     ['The denominator is zero at x=2.',
      'R(2) is undefined. Positive or negative infinity is not a function value.',
      'Nearby outputs can be unbounded even though no output exists at the excluded input.'],
     {answer:choice(['0','∞','Undefined'],2)}),
   notes('one-sided','Reading one-sided behavior',
     'What do \\(x\\to2^-\\) and \\(x\\to2^+\\) mean?',
     ['The minus sign describes inputs smaller than 2 approaching 2.',
      'The plus sign describes inputs larger than 2 approaching 2.',
      'They describe the side of approach, not the sign of the function output.']),
   task('simple-pole','Worked example: opposite infinities',
     'For \\(R(x)=(x+1)/(x-2)\\), describe the output behavior on both sides of x=2.',
     ['Near 2 the numerator is positive and close to 3.',
      'On the left the denominator is negative and tends to 0, so the outputs tend to −∞.',
      'On the right the denominator is positive and tends to 0, so the outputs tend to +∞. The line x=2 is a vertical asymptote.'],
     {answer:choice(['Left −∞, right +∞','Both +∞','Left +∞, right −∞'],0)}),
   task('near-table','Numerical activity: approaching an exclusion',
     'Use the table to describe how the outputs of (x+1)/(x−2) behave near 2. Which input cannot appear as a finite evaluated row?',
     ['As the left inputs approach 2, the negative outputs grow in magnitude.',
      'The right outputs are positive and grow in magnitude as those inputs approach 2.',
      'At x=2 the expression is undefined. The table supports the two one-sided conclusions; the factored formula explains them.'],
     {table:table(['x','R(x)'],[[1.9,-29],[1.99,-299],[2.01,301],[2.1,31]])}),
   notes('even-pole','An even remaining denominator power',
     'For \\(R(x)=(x+1)/(x-2)^2\\), compare the two sides of x=2.',
     ['Near 2 the numerator is positive.',
      'The squared denominator is positive on both sides and tends to 0.',
      'Both one-sided outputs tend to +∞. Even remaining denominator multiplicity gives the same side sign when the other nearby factors keep their sign.']),
   task('negative-even','Your turn: keep the numerator sign',
     'For \\(R(x)=-3/(x+1)^2\\), what happens on both sides of x=−1?',
     ['The denominator is positive on either side and tends to 0.',
      'The numerator remains negative.',
      'Both one-sided outputs tend to −∞.'],
     {answer:choice(['Both −∞','Both +∞','Left −∞, right +∞'],0)}),
   notes('remaining-factor','Cancellation can leave a pole',
     'Classify x=2 for \\(R(x)=(x-2)/(x-2)^2\\).',
     ['The original expression excludes x=2.',
      'Cancel one factor for allowed inputs, giving R(x)=1/(x−2).',
      'A denominator factor remains, so x=2 is a vertical asymptote rather than a finite hole. Compare multiplicities before classifying.']),
   task('full-cancellation','Your turn: no denominator factor remains',
     'Classify x=2 for \\(R(x)=(x-2)^4/(x-2)^2\\).',
     ['The original domain excludes 2.',
      'For allowed inputs, R(x)=(x−2)². The nearby output tends to 0.',
      'There is a hole at (2,0), with no vertical asymptote at 2. The excluded input is not a zero of the original function.'],
     {answer:choice(['Vertical asymptote at 2','Hole at (2,0)','A restored zero at 2'],1)}),
   sim('pole-model','Simulation: poles, holes and side signs',
     'Predict which denominator restrictions remain vertical asymptotes after changing numerator multiplicities.',
     {kind:'rational',key:'ap-rational-poles'},
     ['Change numerator and denominator multiplicities at a common root.',
      'Compare remaining denominator multiplicity with the nearby sign and the exclusion ledger.',
      'Read one-sided outputs and explain them algebraically. Keep missing function values separate from limits.']),
   task('two-poles','Two asymptotes, four approaches',
     'For \\(R(x)=(x+1)/((x-2)(x+3))\\), describe both sides of x=−3 and both sides of x=2.',
     ['At −3, the numerator is negative and x−2 stays negative. Approaching from the left gives −∞, and from the right gives +∞.',
      'At 2, the numerator and x+3 are positive. Approaching from the left gives −∞, and from the right gives +∞.',
      'The vertical asymptotes are x=−3 and x=2. A sign table verifies all four approaches.']),
   notes('ti84','TI-84 Plus CE: test both sides',
     'How can the calculator support a one-sided asymptote claim?',
     ['Enter the function in Y₁ with a parenthesized denominator.',
      'Use manually chosen inputs approaching the excluded input from both sides, such as 1.9,1.99,1.999 and 2.1,2.01,2.001 near 2.',
      'Use the factored rule for the sign and unboundedness. A steep connecting pixel or a large value alone does not prove a vertical asymptote.'],
     {calculator:'TI-84 Plus CE'}),
   task('exit-check','Exit check: multiplicity after cancellation',
     'For \\(R(x)=(x-1)^2/(x-1)^3\\), classify x=1 and describe the two sides.',
     ['The original function excludes x=1.',
      'On its domain it simplifies to 1/(x−1), leaving one denominator factor.',
      'The line x=1 is a vertical asymptote. Left outputs tend to −∞ and right outputs tend to +∞.'],
     {answer:choice(['Hole at (1,0)','Vertical asymptote, left −∞ and right +∞','Vertical asymptote, both +∞'],1)})
 ],[['AP_Precalculus_Lesson_1.9_ECHS.pptx','1–24']])
};
