import {make,task,notes,sim,choice,number,table,graph} from './content-helpers.mjs';
export const LESSONS={
 '1.10':make('1.10',[
   'Find finite holes using the reduced formula and original domain.',
   'Distinguish complete cancellation from a remaining denominator factor.',
   'Explain the difference between a rational function and its continuous extension.'
 ],[
   task('warm-up','Warm-up: simplify and keep the restriction',
     'Simplify \\((x^2-9)/(x-3)\\) and state the original excluded input.',
     ['Factor x²−9=(x−3)(x+3).',
      'The formula reduces to x+3 for x≠3.',
      'The original function excludes 3. Cancellation changes the expression used for allowed inputs, not the original domain.'],
     {answer:number(3,'excluded input')}),
   notes('hole','The coordinates of a hole',
     'Where is the hole in \\(R(x)=(x^2-9)/(x-3)\\)?',
     ['The denominator restriction is x=3 and the common factor cancels completely.',
      'Use the reduced formula x+3 to find the nearby output at that input: 3+3=6.',
      'The hole is (3,6). R(3) remains undefined. The nearby limit is 6.']),
   task('hole-turn','Your turn: a finite missing point',
     'For \\(R(x)=(x^2-4)/(x+2)\\), find the missing point ordinate.',
     ['The domain excludes −2. Factor x²−4=(x−2)(x+2).',
      'The reduced formula is x−2, giving nearby output −2−2=−4.',
      'The hole is (−2,−4). The remaining zero is x=2.'],
     {answer:number(-4,'hole ordinate')}),
   notes('mixed','One hole and one vertical asymptote',
     'Classify both excluded inputs of \\(R(x)=((x-1)(x+2))/((x-1)(x-4))\\).',
     ['The original domain excludes 1 and 4.',
      'The reduced formula is (x+2)/(x−4). At 1 this has finite value −1, so the hole is (1,−1).',
      'The denominator factor x−4 remains, so x=4 is a vertical asymptote.']),
   task('multiplicities','Your turn: compare multiplicities',
     'Classify x=2 for \\((x-2)^3/(x-2)\\). Is 2 a zero of the original function?',
     ['The input 2 is excluded in the original rule.',
      'The reduced formula is (x−2)², whose nearby limit at 2 is 0.',
      'The original function has a hole at (2,0), and 2 is not one of its zeros.'],
     {answer:choice(['A restored zero','A hole at (2,0), not an original zero','A vertical asymptote'],1)}),
   sim('hole-model','Simulation: move and classify missing points',
     'Predict which inputs become holes and which remain poles as you change numerator multiplicities.',
     {kind:'rational',key:'ap-rational-holes'},
     ['Inspect each original denominator exclusion before and after cancellation.',
      'Read a finite hole ordinate from the reduced rule, keeping its point out of the original domain.',
      'Compare remaining numerator and denominator multiplicities. Use the table to support the classification.']),
   notes('extension','Filling a hole creates a different function',
     'If R(x)=(x²−9)/(x−3) for x≠3, which value at 3 would make a continuous extension?',
     ['The nearby outputs follow x+3 and approach 6.',
      'Define a new function with the old outputs for x≠3 and the value 6 at x=3.',
      'The new function is continuous there but has a different domain from the original rational function.']),
   task('wrong-fill','Your turn: filling at the wrong height',
     'Suppose the missing value at x=3 is assigned to be 0 instead of 6. Does that fill the hole continuously?',
     ['The nearby output limit is still 6.',
      'The assigned function value 0 does not match the limit.',
      'Continuity requires the assigned value to match the finite nearby limit.'],
     {answer:choice(['Yes, any assigned value fills it continuously.','No, only the value 6 matches the nearby limit.'],1)}),
   task('two-holes','Challenge: two canceled factors',
     'For \\(R(x)=((x-1)(x+2)(x-3))/((x-1)(x+2))\\), give the coordinates of both holes.',
     ['The original denominator excludes 1 and −2.',
      'The reduced formula is x−3. Its nearby values are −2 at x=1 and −5 at x=−2.',
      'The holes are (1,−2) and (−2,−5). The original function still has the zero 3.']),
   notes('ti84','TI-84 Plus CE: a hole may be invisible',
     'Why might a calculator graph look like a complete line when the function has a hole?',
     ['A pixel display can miss a single excluded input.',
      'Enter the original expression and evaluate the excluded input directly. Use nearby table inputs to inspect the finite trend.',
      'Factor algebraically to identify the original restriction and calculate the hole coordinates.'],
     {calculator:'TI-84 Plus CE'}),
   task('exit-check','Exit check: hole or pole?',
     'For \\((x-5)/(x-5)^2\\), what happens at x=5?',
     ['The original domain excludes 5.',
      'One denominator factor remains after cancellation, giving 1/(x−5).',
      'The line x=5 is a vertical asymptote, not a finite hole.'],
     {answer:choice(['Hole at (5,0)','Vertical asymptote at 5','A defined zero at 5'],1)})
 ]),
 '1.11':make('1.11',[
   'Choose polynomial forms that reveal zeros, extrema or tails.',
   'Use quotient and remainder forms to explain rational end behavior.',
   'Preserve domains when simplifying or comparing representations.'
 ],[
   task('warm-up','Warm-up: which form shows the zeros?',
     'For \\(p(x)=x^2-6x+8\\), which form makes the zeros easiest to read?',
     ['Factor to get (x−2)(x−4).',
      'The factors show zeros 2 and 4.',
      'The expanded form is useful for the leading term, while the vertex form is useful for the minimum.'],
     {answer:choice(['(x−2)(x−4)','x²−6x+8','The constant 8 alone'],0)}),
   notes('three-forms','One quadratic, three useful forms',
     'Express \\(x^2-6x+8\\) in factored and vertex forms. What does each form reveal?',
     ['Factored: (x−2)(x−4), revealing zeros 2 and 4.',
      'Complete the square: (x−3)²−1, revealing the vertex (3,−1).',
      'Expanded: x²−6x+8, revealing the positive leading coefficient, degree 2 and y-intercept 8.']),
   task('vertex-turn','Your turn: a minimum from a form',
     'Find the absolute minimum value of \\(p(x)=2(x-4)^2-7\\) on all real inputs.',
     ['The square is nonnegative, and multiplying by 2 preserves that inequality.',
      'The smallest possible output is −7, reached when x=4.',
      'The vertex is (4,−7) and both tails rise.'],
     {answer:number(-7,'minimum value'),graph:graph([2,-16,25],[1,7],[-8,13])}),
   notes('division','Quotient plus remainder',
     'Rewrite \\((x^2+1)/(x-1)\\) to make its long-run behavior visible.',
     ['Polynomial division gives quotient x+1 and remainder 2.',
      'Thus \\((x^2+1)/(x-1)=x+1+2/(x-1)\\), for x≠1.',
      'The remainder term tends to 0 at both ends, so y=x+1 is the slant asymptote.']),
   task('division-turn','Your turn: verify the quotient',
     'Divide \\(x^3-2x^2-5x+6\\) by x−1. Give the quotient and explain the restriction in the corresponding rational function.',
     ['Synthetic or long division gives x²−x−6 with remainder 0.',
      'Multiplication verifies (x−1)(x²−x−6)=x³−2x²−5x+6.',
      'The polynomial identity holds everywhere, but the rational quotient remains undefined at x=1. Its reduced polynomial gives the hole ordinate −6.']),
   sim('division-model','Simulation: the quotient and remainder',
     'Predict how the remainder affects the gap between a rational function and its polynomial quotient.',
     {kind:'equivalence',key:'ap-equivalent-forms',scene:'equivalence-division-explorer'},
     ['Change the quotient and remainder parameters and inspect the same function in both forms.',
      'Compare finite values and original exclusions.',
      'Explain why a remainder divided by a growing denominator can vanish in the tails.']),
   notes('binomial','A binomial expansion preserves the function',
     'Expand \\((x+2)^3\\). Why is replacing it by x³+8 incorrect?',
     ['The binomial coefficients are 1,3,3,1.',
      'Expansion gives x³+6x²+12x+8.',
      'The mixed terms are required. For example, at x=1 the correct value is 27, while x³+8 gives only 9.']),
   task('expansion-turn','Your turn: the coefficient of x',
     'In \\((x+2)^3\\), what is the coefficient of x after expansion?',
     ['The x-term is \\(3x(2^2)=12x\\).',
      'Its coefficient is 12.',
      'The complete expansion is x³+6x²+12x+8.'],
     {answer:number(12,'coefficient')}),
   sim('binomial-model','Simulation: coefficients and equivalent values',
     'Predict how changing a binomial parameter changes the expansion coefficients, then compare evaluations.',
     {kind:'equivalence',key:'ap-equivalent-forms',scene:'equivalence-binomial-explorer'},
     ['Inspect the coefficient row and the corresponding terms.',
      'Test the original and expanded expressions at the same input.',
      'Explain how a polynomial identity establishes equality for every input, beyond a few numerical checks.']),
   task('domain-equality','Challenge: equality needs a domain',
     'Are \\(f(x)=(x^2-1)/(x-1)\\) with its natural domain and \\(g(x)=x+1\\) on all real inputs equal functions?',
     ['They agree at every x≠1.',
      'Their domains differ: f excludes 1, whereas g is defined there.',
      'They become equal only if g is restricted to the same domain.'],
     {answer:choice(['Yes, cancellation makes the domains equal.','No on their natural domains.'],1)}),
   task('exit-check','Exit check: choose a representation',
     'Which form of a quadratic most directly displays a vertex?',
     ['The form a(x−h)²+k directly displays the vertex (h,k).',
      'The sign of a determines whether it is a minimum or maximum on the full real domain.',
      'Factored and expanded forms reveal different features without changing the polynomial.'],
     {answer:choice(['a(x−h)²+k','a(x−r)(x−s)','ax²+bx+c'],0)})
 ]),
 '1.12':make('1.12',[
   'Connect inside and outside transformations with changes in coordinates.',
   'Combine translations, dilations and reflections in a point mapping.',
   'Transform domains, ranges and asymptotes along with the rule.'
 ],[
   task('warm-up','Warm-up: inside or outside?',
     'If g(x)=f(x)+3, what happens to each output?',
     ['The input to f stays x.',
      'Every output increases by 3, giving a vertical shift up 3.',
      'The domain stays the same and the range shifts up 3.'],
     {answer:choice(['Shift right 3','Shift up 3','Multiply outputs by 3'],1)}),
   notes('horizontal','An inside translation changes the input',
     'For g(x)=f(x−4), where does a feature originally at input u move?',
     ['The old input u is produced when x−4=u.',
      'Solving gives x=u+4, so the feature moves right 4.',
      'The output at the new input remains f(u). Solve the inside-input equation to avoid guessing the direction.']),
   notes('dilation','Inside scaling reverses the width factor',
     'For g(x)=f(2x), where does the old point (u,v) move?',
     ['The old input u occurs when 2x=u.',
      'The new point is (u/2,v). The horizontal width scale is 1/2.',
      'For f(x)=x² the new rule is 4x², which is narrower than the parent graph at the same output levels.']),
   task('point-turn','Your turn: a horizontal scale',
     'If f(6)=5 and g(x)=f(3x), which point is guaranteed on g?',
     ['Solve 3x=6, giving x=2.',
      'The corresponding output remains 5.',
      'The guaranteed point is (2,5).'],
     {answer:choice(['(18,5)','(2,5)','(6,15)'],1)}),
   notes('combined','A combined point mapping',
     'For \\(g(x)=a f(b(x-h))+k\\), with a and b nonzero, where does an old point (u,v) move?',
     ['Solve b(x−h)=u to get x=u/b+h.',
      'The new output is av+k.',
      'The point mapping is \\((u,v)\\mapsto(u/b+h,av+k)\\). Negative a or b introduces the corresponding reflection.']),
   task('combined-turn','Your turn: map a known point',
     'Given f(4)=5 and \\(g(x)=-2f(2(x-3))+1\\), find the corresponding new point.',
     ['Solve 2(x−3)=4, so x=5.',
      'Transform the output: −2(5)+1=−9.',
      'The new point is (5,−9).'],
     {answer:choice(['(5,−9)','(11,−9)','(5,11)'],0)}),
   sim('transformation-model','Simulation: one point, linked graphs',
     'Predict the new location of a point before changing the transformation controls.',
     {kind:'modeling',key:'ap-function-transformations'},
     ['Change a single parameter and compare the old point with its mapped point.',
      'Use negative inside and outside factors to distinguish horizontal and vertical reflections.',
      'Check the formula, graph and point-mapping table together.']),
   task('parabola','Worked example: vertex and range',
     'For \\(g(x)=-2(x-3)^2+5\\), give the vertex, direction of opening and range.',
     ['The vertex is (3,5), and the negative coefficient makes the parabola open downward.',
      'The square is nonnegative, so g(x)≤5, with equality at x=3.',
      'The domain is all real numbers and the range is \\((-\\infty,5]\\).'],
     {graph:graph([-2,12,-13],[0,6],[-14,6])}),
   notes('reciprocal','Transforming asymptotes',
     'For \\(g(x)=1/(x-2)+3\\), how do the asymptotes of 1/x move?',
     ['The input translation excludes x=2 and moves the vertical asymptote to x=2.',
      'The outside +3 moves the horizontal asymptote from y=0 to y=3.',
      'The domain excludes 2 and the range excludes 3.']),
   task('domain-turn','Your turn: transform a domain',
     'If f has domain [−2,4], find the domain of g(x)=f(2(x−1)).',
     ['Require −2≤2(x−1)≤4.',
      'Divide by 2, then add 1, giving 0≤x≤3.',
      'The transformed domain is [0,3].'],
     {answer:choice(['[−3,3]','[0,3]','[−4,8]'],1)}),
   task('hole-map','Challenge: transform a missing point',
     'A graph has a hole at (1,4). Under \\(g(x)=2f(-(x-3))-2\\), where does that hole move?',
     ['The inside equation −(x−3)=1 gives x=2.',
      'The output mapping gives 2(4)−2=6.',
      'The hole moves to (2,6), and that new input remains excluded.'],
     {answer:choice(['(2,6)','(4,6)','(2,2)'],0)}),
   task('exit-check','Exit check: justify the direction',
     'For g(x)=f(x+2), which direction does a feature move?',
     ['The old input u is produced by x+2=u.',
      'The new input is u−2, so the feature moves left 2.',
      'Use this equation to justify the horizontal transformation.'],
     {answer:choice(['Right 2','Left 2','Up 2'],1)})
 ]),
 '1.13':make('1.13',[
   'Select a model family from multiple representations and contextual assumptions.',
   'Inspect residuals rather than rely on appearance or exact sample matches alone.',
   'State practical domains and limits of interpolation and extrapolation.'
 ],[
   task('warm-up','Warm-up: what pattern supports a model?',
     'The equal-step outputs are 2,5,10,17. Which polynomial family is consistent with their differences?',
     ['First differences are 3,5,7.',
      'Second differences are 2,2, supporting a quadratic among suitable polynomial models.',
      'Finite samples do not uniquely determine an arbitrary function.'],
     {table:table(['x','y'],[[0,2],[1,5],[2,10],[3,17]]),answer:choice(['Constant','Linear','Quadratic'],2)}),
   notes('assumptions','A model selection is a justified choice',
     'What should accompany the choice of a function family?',
     ['Connect the pattern in the data or graph with the proposed family.',
      'State assumptions about quantities, units, domain and how the data were obtained.',
      'Check model errors and contextual plausibility. An algebraic fit alone is not a complete model justification.']),
   task('residual','Worked example: observed minus predicted',
     'A line L(x)=4x+2 predicts the data below. What is the residual at x=1?',
     ['The predicted output is L(1)=6.',
      'The observed output is 5, so the residual is 5−6=−1.',
      'A negative residual means the observed value is below the prediction.'],
     {table:table(['x','Observed y'],[[0,2],[1,5],[2,10]]),answer:number(-1,'residual')}),
   notes('residual-pattern','A residual pattern can expose a poor family',
     'If residuals systematically curve from positive to negative to positive, what should you investigate?',
     ['A systematic pattern means the errors are not merely scattered around zero.',
      'The model family may be missing curvature or another structural feature.',
      'Compare a justified alternative and its residuals. Consider the context and data quality before adding complexity.']),
   sim('selection-model','Simulation: compare model families and residuals',
     'Predict which model will best match the supplied dataset and which errors it will leave.',
     {kind:'modeling',key:'ap-model-selection'},
     ['Compare the declared candidate families with the same observations.',
      'Inspect the residual table and plot, including changes of sign and systematic patterns.',
      'Explain your choice with a data pattern, an error pattern and a contextual assumption.']),
   task('fit-versus-function','Exact fit does not prove the full rule',
     'A quadratic fits four sampled points exactly. Can another function agree at those points and differ elsewhere?',
     ['Yes. A nonzero multiple of \\((x-x_1)(x-x_2)(x-x_3)(x-x_4)\\) vanishes at every sampled input.',
      'Adding that term to the quadratic preserves the four observations but can change the graph between them.',
      'An exact fit identifies the polynomial only with an appropriate degree or family assumption.'],
     {answer:choice(['No, four matching values prove equality everywhere.','Yes, finite agreement leaves other possible functions.'],1)}),
   notes('domains','The practical domain belongs to the model',
     'A workshop cost model uses number of items n. What restrictions arise from the context?',
     ['An item count is usually an integer. A cost per item requires n>0.',
      'Physical capacity or the range of observed data may further restrict useful predictions.',
      'An algebraic formula defined at negative or fractional n does not make those inputs meaningful for this situation.']),
   task('interpolation','Your turn: classify a prediction',
     'A dataset covers times from 0 to 8 hours. A model predicts at 3 hours and at 20 hours. Which prediction is extrapolation?',
     ['The 3-hour input lies inside the observed range, so it is interpolation.',
      'The 20-hour input lies outside that range, so it is extrapolation.',
      'Both require a suitable model, but the further extrapolation demands stronger contextual justification.'],
     {answer:choice(['3 hours','20 hours','Both are interpolation'],1)}),
   task('regression','Calculator activity: check a fitted line',
     'A fitted line for the given data is y=2x+1. Calculate the residuals and describe what they show.',
     ['The fitted outputs are 1,3,5,7.',
      'Observed minus fitted gives residuals 0,−0.1,0.2,−0.1.',
      'They are small for this scale, but four points are limited evidence. Assess the context, measurement accuracy and further observations.'],
     {calculator:'Calculator optional',table:table(['x','Observed y'],[[0,1],[1,2.9],[2,5.2],[3,6.9]])}),
   notes('ti84','TI-84 Plus CE: regression with residuals',
     'How can you fit a polynomial model and inspect its errors?',
     ['Use STAT, EDIT to enter inputs in L1 and outputs in L2. Check row pairing and units.',
      'Use STAT, CALC and choose LinReg, QuadReg, CubicReg or QuartReg when the candidate family is justified. Store the equation in Y₁.',
      'Compare the scatter plot and fitted curve. In a list, compute L2−Y₁(L1) for residuals, then plot residuals against L1. Explain their pattern.'],
     {calculator:'TI-84 Plus CE'}),
   task('overfit','Challenge: more parameters',
     'A higher-degree polynomial passes through all observations, but oscillates wildly between them. Is it automatically the best model?',
     ['No. Exact sample agreement can coexist with implausible interior behavior.',
      'Inspect interpolation, validation observations and contextual constraints.',
      'Choose a family for explanatory and predictive reasons, not merely because it removes every training residual.'],
     {answer:choice(['Yes, exact fit is the only criterion.','No, check predictive behavior and contextual plausibility.'],1)}),
   task('exit-check','Exit check: support a model claim',
     'Which explanation best supports selecting a quadratic model?',
     ['Use equal input spacing to compare numerical differences.',
      'Check whether the residuals show unexplained structure.',
      'State the contextual assumptions and useful prediction domain.'],
     {answer:choice(['The curve looks nice.','A numerical quadratic pattern, suitable residuals and stated contextual assumptions support it.','Four data points prove the true rule everywhere.'],1)})
 ]),
 '1.14':make('1.14',[
   'Construct a function from zeros, vertices, asymptotes or paired observations.',
   'Determine remaining parameters from additional evidence.',
   'Use the completed model with units, a practical domain and a check of every condition.'
 ],[
   task('warm-up','Warm-up: choose the structural form',
     'A quadratic has zeros −1 and 3. Which form is a suitable starting point?',
     ['The factors corresponding to the zeros are x+1 and x−3.',
      'Use p(x)=a(x+1)(x−3), with a nonzero.',
      'The zeros do not yet determine a. An additional point can fix the scale.'],
     {answer:choice(['a(x−1)(x+3)','a(x+1)(x−3)','a(x+1)+a(x−3)'],1)}),
   task('scale','Worked example: fix the remaining parameter',
     'The quadratic has zeros −1 and 3 and satisfies p(0)=−6. Find a in p(x)=a(x+1)(x−3).',
     ['Substitute x=0: p(0)=a(1)(−3)=−3a.',
      'Set −3a=−6, giving a=2.',
      'The completed model is p(x)=2(x+1)(x−3). Verify both zeros and the given output.'],
     {answer:number(2,'scale parameter')}),
   notes('vertex','A vertex suggests a vertex form',
     'A parabola has vertex (3,9) and passes through (0,0). Construct its rule.',
     ['Begin with h(x)=a(x−3)²+9.',
      'Substitute (0,0): 0=9a+9, so a=−1.',
      'The rule is h(x)=−(x−3)²+9=−x²+6x.']),
   task('arch-domain','Context: a hypothetical arch',
     'Use h(x)=−x²+6x metres for the height of a hypothetical arch above ground. What physical horizontal domain has nonnegative height?',
     ['Factor h(x)=x(6−x). The ground contacts are x=0 and x=6.',
      'The height is nonnegative between the contacts.',
      'For this arch model use 0≤x≤6 metres. The full algebraic parabola outside that interval does not represent the physical arch.'],
     {answer:choice(['All real x','[0,6]','x≥6'],1),graph:graph([-1,6,0],[0,6],[-1,10])}),
   task('construct-from-table','Your turn: use paired observations',
     'A quadratic has vertex (2,0) and passes through (0,4). Find its leading coefficient and verify the middle observation.',
     ['Use q(x)=a(x−2)².',
      'At x=0, 4=4a, so a=1.',
      'Thus q(x)=(x−2)², and q(1)=1. It matches the given table.'],
     {table:table(['x','q(x)'],[[0,4],[1,1],[2,0]]),answer:number(1,'leading coefficient')}),
   notes('rational-form','Build a rational model from features',
     'Construct a rational function with zero −1, vertical asymptote 2 and horizontal asymptote 3.',
     ['Use numerator factor x+1 and denominator factor x−2.',
      'The same degrees make the leading-coefficient ratio the horizontal tail level. Choose R(x)=3(x+1)/(x−2).',
      'At −1 the denominator is nonzero, at 2 a denominator factor remains, and both end limits are 3. Verify every requirement.']),
   task('add-hole','Your turn: add a missing point',
     'Modify 3(x+1)/(x−2) to add a hole at x=1 without changing the existing zero and asymptotes.',
     ['Multiply numerator and denominator by x−1.',
      'The new original denominator excludes 1 and 2. At allowed inputs the old formula remains unchanged.',
      'The hole ordinate is 3(1+1)/(1−2)=−6, so the missing point is (1,−6).'],
     {answer:number(-6,'hole ordinate')}),
   sim('construction-model','Simulation: construct from constraints',
     'Predict which form and parameter values will meet the supplied constraints, then test every condition.',
     {kind:'modeling',key:'ap-model-construction'},
     ['Choose a structural family and use the feature conditions to set parameters.',
      'Compare the declared constraints with the generated graph and table.',
      'Explain which conditions determine the form and which determine the remaining scale.']),
   task('box','Application: a box from a sheet',
     'A 12 cm by 10 cm sheet has squares of side x cut from its corners and is folded into an open box. Find its volume when x=2 cm.',
     ['The base dimensions become 12−2x and 10−2x, and the height is x.',
      'The volume model is V(x)=x(12−2x)(10−2x).',
      'At x=2, V=2(8)(6)=96 cm³. Positive dimensions require 0<x<5.'],
     {answer:number(96,'cm³')}),
   notes('model-domain','Every geometric dimension must be valid',
     'Why is x=6 invalid for the 12 cm by 10 cm box model?',
     ['The shorter base dimension would be 10−2(6)=−2 cm.',
      'A negative length cannot represent the box, even if the polynomial can be evaluated there.',
      'The physical constraints give 0<x<5. Use the model only on its meaningful domain.']),
   task('cubic-construct','Challenge: zeros, multiplicity and a point',
     'Construct a cubic with a simple zero at −2, a double zero at 1, and p(0)=4.',
     ['Use p(x)=a(x+2)(x−1)².',
      'The condition p(0)=4 gives 2a=4, so a=2.',
      'The model 2(x+2)(x−1)² has degree 3, crosses at −2, touches at 1, and has y-intercept 4.']),
   notes('ti84','TI-84 Plus CE: test the completed model',
     'How do you validate a model after finding its parameters?',
     ['Enter the completed rule in Y₁ and evaluate the supplied input-output conditions.',
      'Check GRAPH and TABLE over the practical domain, including intercepts and relevant extrema or restrictions.',
      'Compare numerical values with the required precision and state units. If using regression, distinguish fitted evidence from exact constraints.'],
     {calculator:'TI-84 Plus CE'}),
   task('exit-check','Exit check: why one more point?',
     'Two zeros are given for a quadratic. Why is another condition normally needed to determine a unique quadratic?',
     ['The zeros determine the two linear factors.',
      'Any nonzero scale a produces a quadratic with those same zeros.',
      'An additional nonzero output condition or equivalent scale information can fix a.'],
     {answer:choice(['The zeros do not determine the vertical scale.','Two zeros always determine a unique monic and nonmonic quadratic.'],0)})
 ])
};
