import {make,task,notes,sim,choice,number,table,graph} from './content-helpers.mjs';
export const LESSONS={
 '1.4':make('1.4',[
   'Identify polynomial degree and the leading coefficient after simplification.',
   'Describe local and absolute extrema, including restricted-domain endpoints.',
   'Connect graph behavior, average rates and finite differences.'
 ],[
   task('warm-up','Warm-up: which rule is polynomial?',
     'Choose a polynomial function of x with real coefficients.',
     ['Polynomial powers of x are nonnegative integers.',
      '\\(3x^4-2x+7\\) meets this requirement. The other expressions contain a negative or fractional power of x.',
      'A nonzero constant has degree 0. The zero polynomial has no defined degree.'],
     {answer:choice(['3x⁴−2x+7','x⁻¹+2','√x+1'],0)}),
   notes('degree','The leading term comes after simplification',
     'Find the degree and leading coefficient of \\(p(x)=14x^2+6x-2x^6+1\\).',
     ['In descending powers, \\(p(x)=-2x^6+14x^2+6x+1\\).',
      'The leading term is \\(-2x^6\\). The degree is 6 and the leading coefficient is −2.',
      'The first printed term need not be the leading term. Combine like terms before finding the highest surviving power.']),
   task('cancel-degree','Your turn: a canceled leading term',
     'Find the degree of \\(q(x)=(x^3+2x^2)-(x^3-5x+1)\\).',
     ['Distribute the subtraction: \\(q(x)=x^3+2x^2-x^3+5x-1\\).',
      'The cubic terms cancel, leaving \\(2x^2+5x-1\\).',
      'The degree is 2 and the leading coefficient is 2.'],
     {answer:number(2,'degree')}),
   notes('extrema','Local and absolute extrema',
     'On \\([-1,2]\\), consider \\(p(x)=3-x^2\\). Which outputs are local extrema and which are absolute extrema?',
     ['The interior peak is p(0)=3. The included endpoints give p(−1)=2 and p(2)=−1.',
      'Relative to this restricted domain, both included endpoints are local minima by one-sided comparisons. The point x=0 is a local maximum.',
      'The absolute maximum is 3 at x=0 and the absolute minimum is −1 at x=2. Compare all outputs on the stated domain.'],
     {graph:graph([-1,0,3],[-1,2],[-2,4])}),
   task('domain-extrema','Your turn: a domain changes the conclusion',
     'For \\(f(x)=x^2\\) on \\([1,3]\\), find the absolute minimum value and where it occurs.',
     ['The function increases throughout the stated positive-input domain.',
      'The included left endpoint has the smallest output: f(1)=1.',
      'The absolute minimum is 1 at x=1. It is also a local minimum within this restricted domain.'],
     {answer:number(1,'minimum value'),graph:graph([1,0,0],[1,3],[0,10])}),
   notes('turns','Degree bounds turning points',
     'A degree-4 polynomial has three turning points. Is this possible? Must every degree-4 polynomial have three?',
     ['A nonconstant degree-n polynomial has at most n−1 turning points.',
      'Three turning points are possible for degree 4.',
      'The bound is an upper limit. For example, x⁴ has only one turning point. A stationary point need not be a turn.']),
   task('stationary','A flat point need not turn',
     'The graph of \\(p(x)=x^3\\) is flat at the origin. Does it change from increasing to decreasing there?',
     ['For a<b, \\(a^3<b^3\\), so the function is increasing on its full real domain.',
      'It does not turn at x=0 and has no local maximum or minimum there.',
      'The graph changes concavity at the origin. A stationary inflection and a turning point describe different behavior.'],
     {answer:choice(['Yes, every flat point is a maximum.','No, the graph continues increasing through the origin.'],1),
      graph:graph([1,0,0,0],[-2,2],[-9,9])}),
   sim('poly-model','Simulation: direction, extrema and secants',
     'Predict how the cubic shape changes when its shape parameter changes sign. Then compare its turns and interval averages.',
     {kind:'polynomial',key:'ap-polynomial-rates'},
     ['Move the shape parameter and identify where the graph changes direction.',
      'Change the domain endpoints and compare restricted local extrema with the full-domain behavior.',
      'Move the secant endpoints. Explain why a zero interval average can coexist with nonconstant outputs.']),
   task('cubic-average','Your turn: one average across a cubic',
     'For \\(p(x)=x^3-3x\\), find the average rate from x=−2 to x=2.',
     ['Compute p(−2)=−2 and p(2)=2.',
      'The secant slope is \\((2-(-2))/(2-(-2))=1\\).',
      'The single average does not describe every local rise and fall within the interval.'],
     {answer:number(1),graph:graph([1,0,-3,0],[-2,2],[-3,3])}),
   notes('differences','Finite differences need equal spacing',
     'The outputs of \\(x^3\\) at x=0,1,2,3,4 are 0,1,8,27,64. What happens to successive difference layers?',
     ['The first differences are 1,7,19,37.',
      'The second differences are 6,12,18, and the third differences are 6,6.',
      'The exact cubic has constant third differences for equal input spacing. Finite observations alone do not determine an arbitrary function.'],
     {table:table(['x','x³'],[[0,0],[1,1],[2,8],[3,27],[4,64]])}),
   task('degree-bound','Challenge: infer a minimum possible degree',
     'A polynomial graph has four distinct turning points. What is its minimum possible degree?',
     ['For degree n the number of turns cannot exceed n−1.',
      'Four turns require n−1≥4, so n≥5.',
      'The least possible degree is 5. This is a bound, not an exact degree determination.'],
     {answer:number(5,'minimum degree')}),
   notes('ti84','TI-84 Plus CE: extrema in a stated domain',
     'How do you check a graph extremum without overlooking included endpoints?',
     ['Enter the polynomial in Y₁ and set a window that contains the given domain.',
      'Use 2nd TRACE, maximum or minimum, and bracket an interior candidate with left and right bounds.',
      'Evaluate every included endpoint separately. Compare all candidate outputs and keep more digits until the final answer.'],
     {calculator:'TI-84 Plus CE'}),
   task('exit-check','Exit check: classify the endpoint',
     'For \\(p(x)=x^2\\) on \\([0,2]\\), which statement correctly includes the domain endpoints?',
     ['The absolute minimum is 0 at x=0 and the absolute maximum is 4 at x=2.',
      'The included endpoints are also local extrema relative to the restricted domain.',
      'Those statements change when the domain changes to all real numbers.'],
     {answer:choice(['Only interior points can be extrema on the restricted domain.','The included endpoints give a local and absolute minimum at 0 and a local and absolute maximum at 2.'],1)})
 ],[['AP_Precalculus_Lesson_1.4_Worksheet_ECHS (ready).pptx','1–21']]),
 '1.5':make('1.5',[
   'Connect factors, real zeros, intercepts and multiplicity.',
   'Count complex zeros with multiplicity and use conjugate pairs for real coefficients.',
   'Use symmetry and sign intervals to describe polynomial behavior.'
 ],[
   task('warm-up','Warm-up: a zero or an intercept?',
     'If p(−2)=0, which point is an x-intercept?',
     ['A zero is the input −2.',
      'The corresponding graph point is (−2,0).',
      'An x-intercept includes both coordinates. It does not specify the y-intercept.'],
     {answer:choice(['(0,−2)','(−2,0)','(−2,−2)'],1)}),
   notes('factors','Factors reveal zeros',
     'For \\(p(x)=(x+2)(x-1)^2\\), find the real zeros and their multiplicities.',
     ['The factor x+2 gives the zero x=−2 with multiplicity 1.',
      'The factor (x−1)² gives x=1 with multiplicity 2.',
      'The total multiplicity is 3, matching this polynomial degree. The x-intercepts are (−2,0) and (1,0).']),
   task('multiplicity','Your turn: does the graph cross?',
     'At x=1, the polynomial \\((x+2)(x-1)^2\\) has a zero of multiplicity 2. Does its sign change across this zero?',
     ['Near x=1, x+2 is positive and (x−1)² is nonnegative on both sides.',
      'The graph touches the axis and keeps the same sign.',
      'An even-multiplicity real zero does not change sign. An odd-multiplicity zero changes sign.'],
     {answer:choice(['It changes sign because every zero is a crossing.','It keeps its sign and touches the axis.'],1),
      graph:graph([1,0,-3,2],[-3,2],[-5,6])}),
   notes('complex','Some zeros are not real intercepts',
     'Solve \\(x^2+4=0\\). Why does the real graph have no x-intercepts?',
     ['The equation gives x²=−4.',
      'Over the complex numbers, the zeros are \\(2i\\) and \\(-2i\\).',
      'For real x, x²+4 is positive. Complex zeros are not points where a real-input graph crosses the x-axis.']),
   task('count-zeros','Your turn: count with multiplicity',
     'For \\(p(x)=(x-2)^2(x^2+9)\\), how many complex zeros are there counting multiplicity?',
     ['The real zero 2 has multiplicity 2.',
      'The quadratic factor gives the nonreal zeros 3i and −3i, each with multiplicity 1.',
      'There are four zeros counted with multiplicity, although only three distinct complex zero values.'],
     {answer:number(4,'zeros counting multiplicity')}),
   notes('conjugates','Real coefficients give conjugate pairs',
     'A polynomial with real coefficients has 1+2i as a zero. What other zero is guaranteed, and what quadratic factor follows?',
     ['The conjugate 1−2i is also a zero.',
      'Multiply \\((x-(1+2i))(x-(1-2i))=(x-1)^2+4\\).',
      'The real quadratic factor is \\(x^2-2x+5\\). The conjugate-pair conclusion requires real coefficients.']),
   task('construct','Your turn: construct the polynomial',
     'A monic cubic has zeros −1, 2+i and 2−i. Write it in factored and expanded forms.',
     ['Use \\(p(x)=(x+1)((x-2)^2+1)=(x+1)(x^2-4x+5)\\).',
      'Expand to \\(p(x)=x^3-3x^2+x+5\\).',
      'The monic condition fixes the leading coefficient. Without it, any nonzero scalar multiple would have these same zeros.']),
   sim('zero-model','Simulation: real zeros and a complex pair',
     'Predict how the graph changes when a real-zero multiplicity changes and when a conjugate pair reaches the real axis.',
     {kind:'polynomial',key:'ap-polynomial-zeros'},
     ['Change the real-zero multiplicity and compare touching with crossing.',
      'Change the imaginary magnitude. Keep the real graph and the complex zero diagram distinct.',
      'Check that the count with multiplicity matches the declared degree, including coincident zeros.']),
   notes('even-odd','Symmetry comes from a rule',
     'Compare \\(f(x)=2x^4-3x^2\\), \\(g(x)=x^3-4x\\), and \\(h(x)=x^2+x\\).',
     ['For f, f(−x)=f(x), so f is even and its graph has y-axis symmetry.',
      'For g, g(−x)=−g(x), so g is odd and has origin symmetry.',
      'For h neither equality holds for all x. A symmetric domain is part of these definitions.']),
   task('symmetry-turn','Your turn: a reflected point',
     'An odd function with a symmetric domain contains the point (3,−5). Which point is guaranteed?',
     ['Odd symmetry means f(−3)=−f(3).',
      'Since f(3)=−5, f(−3)=5.',
      'The reflected point is (−3,5).'],
     {answer:choice(['(−3,−5)','(−3,5)','(3,5)'],1)}),
   notes('signs','A sign table uses zeros as boundaries',
     'Solve \\((x+2)(x-1)\\le0\\). Explain the endpoints.',
     ['The zeros are −2 and 1. Test the three intervals separated by them.',
      'The signs are positive, negative, positive. The polynomial is nonpositive between the zeros.',
      'The equality includes both zeros, so the solution is \\([-2,1]\\).']),
   task('inequality-turn','Your turn: a repeated zero',
     'Solve \\((x-1)^2(x+2)<0\\).',
     ['The squared factor is positive except at x=1, where the product is zero.',
      'The product is negative exactly when x+2<0, so x<−2.',
      'The strict inequality excludes x=−2. The point x=1 gives zero and is outside the negative interval.'],
     {answer:choice(['x<−2','−2<x<1','x<1'],0)}),
   task('exit-check','Exit check: identify the missing zero',
     'A degree-3 polynomial with real coefficients has zeros 4 and 1+i. Give the third zero.',
     ['The nonreal zero must have its conjugate 1−i.',
      'These three zeros already account for the degree when counted with multiplicity.',
      'The real zero 4 gives an x-intercept. The nonreal pair does not.'],
     {answer:choice(['−4','−1−i','1−i'],2)})
 ],[['AP_Precalculus_Lesson_1.5_Worksheet_ECHS.pptx','1–36']]),
 '1.6':make('1.6',[
   'Describe both polynomial tails with precise input and output directions.',
   'Use the leading term and parity to justify end behavior.',
   'Distinguish a finite graphing window from the full-domain conclusion.'
 ],[
   task('warm-up','Warm-up: read the input direction',
     'In \\(\\lim_{x\\to-\\infty}p(x)=+\\infty\\), which graph end is being described?',
     ['The input x tends to negative infinity, so this describes the left end.',
      'The output tends to positive infinity, so that end rises without bound.',
      'The input direction and output direction have different roles in the notation.'],
     {answer:choice(['Left end up','Right end up','Left end down'],0)}),
   notes('leading','The leading term controls the tails',
     'Why does \\(p(x)=-2x^5+100x^4-7\\) eventually behave like \\(-2x^5\\)?',
     ['Divide by x⁵ for large nonzero x: \\(p(x)/x^5=-2+100/x-7/x^5\\).',
      'The lower-power contributions relative to x⁵ tend to zero.',
      'The leading coefficient and odd degree determine the two tails, even if a small window looks different.']),
   task('odd-negative','Your turn: an odd negative leading term',
     'Give both end limits for \\(p(x)=-2x^5+100x^4-7\\).',
     ['For large negative x, x⁵ is negative, so −2x⁵ is positive.',
      'For large positive x, −2x⁵ is negative.',
      'Therefore \\(\\lim_{x\\to-\\infty}p(x)=+\\infty\\) and \\(\\lim_{x\\to+\\infty}p(x)=-\\infty\\).'],
     {answer:choice(['Left up, right down','Both ends down','Left down, right up'],0)}),
   notes('even','Even degree gives matching tails',
     'Compare the ends of \\(3x^6-x+1\\) and \\(-3x^6-x+1\\).',
     ['An even power is positive for both large positive and large negative inputs.',
      'A positive leading coefficient gives both ends up.',
      'A negative leading coefficient gives both ends down. These statements concern nonconstant polynomials on their full real domain.']),
   task('even-turn','Your turn: keep the coefficient sign',
     'For \\(q(x)=5x^3-9x^2+x^7-3x^8\\), determine both tails.',
     ['The highest surviving power is 8, and the leading term is −3x⁸.',
      'The degree is even and the leading coefficient is negative.',
      'Both end limits are negative infinity.'],
     {answer:choice(['Both up','Both down','Left up, right down'],1)}),
   notes('four-cases','The four tail patterns',
     'Describe the four combinations of parity and leading-coefficient sign.',
     ['Even positive: left up and right up. Even negative: left down and right down.',
      'Odd positive: left down and right up. Odd negative: left up and right down.',
      'These patterns do not determine the exact degree, the number of turns, or all zeros.']),
   sim('tail-model','Simulation: change degree and widen the window',
     'Predict how the two tails change when degree changes parity or the leading coefficient changes sign.',
     {kind:'polynomial',key:'ap-polynomial-tails'},
     ['Change only the degree and compare even with odd powers.',
      'Change the leading coefficient sign and compare the two tails.',
      'Increase the window size to see leading-term dominance. Explain why finite plotted samples need algebraic support.']),
   task('construct-even','Student sketch: construct matching tails',
     'Give one polynomial whose left and right limits are both negative infinity. Sketch it.',
     ['Choose an even positive degree with a negative leading coefficient.',
      'One valid example is \\(p(x)=-x^4+2\\).',
      'Its two tails go down. Many other formulas satisfy the same two end limits.'],
     {graph:graph([-1,0,0,0,2],[-2,2],[-15,3]),hint:'The coefficient sign determines whether matching tails rise or fall.'}),
   task('construct-odd','Student sketch: construct opposite tails',
     'Give one polynomial with left limit positive infinity and right limit negative infinity.',
     ['Choose an odd degree with a negative leading coefficient.',
      'For example, \\(p(x)=-x^3+x\\) has the requested ends.',
      'The lower-degree term can change the middle of the graph without changing these tails.'],
     {graph:graph([-1,0,1,0],[-2,2],[-7,7])}),
   notes('global','Even-degree polynomials and absolute extrema',
     'Why does a nonconstant even-degree polynomial on all real inputs have an absolute extremum?',
     ['It is continuous and its two tails tend in the same unbounded direction.',
      'Both tails up give an absolute minimum. Both tails down give an absolute maximum.',
      'It can also have other local extrema. A quadratic has its absolute extremum at its vertex.']),
   notes('ti84','TI-84 Plus CE: use more than one window',
     'How can a graphing window mislead you about end behavior?',
     ['Enter the polynomial in Y₁ and inspect GRAPH. A small window shows only a bounded portion.',
      'Increase the x-range and use TABLE for large positive and negative inputs. Adjust y-bounds so clipped values are not mistaken for endpoints.',
      'Use the leading term to justify the actual end limits. The calculator provides supporting numerical evidence.'],
     {calculator:'TI-84 Plus CE'}),
   task('exit-check','Exit check: what can the tails tell you?',
     'A nonconstant polynomial has both tails up. What must be true?',
     ['Its degree is even and its leading coefficient is positive.',
      'This does not fix the exact degree. Degree 2,4,6 and higher even degrees can fit.',
      'It has an absolute minimum on its full real domain.'],
     {answer:choice(['Degree exactly 2','Even degree and positive leading coefficient','Odd degree and positive leading coefficient'],1)})
 ],[['AP_Precalculus_Lesson_1.6_Worksheet_ECHS.pptx','1–14']])
};
