import {createServer} from 'node:http';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {chromium} from '../../foundations/question-bank/official/tools/node_modules/playwright/index.mjs';
const here=new URL('./',import.meta.url),prior=new URL('../c04-learning-p2b-candidate/',here),hash=b=>createHash('sha256').update(b).digest('hex');
const file=name=>readFileSync(new URL(name,here));
if(!process.argv[2]||existsSync(process.argv[2]))throw Error('Fresh report filename required');
const priorManifest=readFileSync(new URL('candidate-manifest.json',prior));if(hash(priorManifest)!=='817c3395b1589c74391cce55fd7dffdae9de3a28c2b1f9fd90e371428c788722')throw Error('Original manifest changed');
const copy=JSON.parse(file('COPY_RECEIPT.json'));for(const r of [...copy.source_files,...copy.preserved_original_tests]){const raw=readFileSync(new URL(r.path,prior));if(raw.length!==r.bytes||hash(raw)!==r.sha256)throw Error('Original source/test changed '+r.path)}
const names=['source/js/owned-learning-store.mjs','source/js/owned-learning-transport.mjs','source/question-bank/js/learning-transition.mjs','source/question-bank/js/practice-flow.mjs','browser-page.mjs','test_browser.mjs','source/js/wire-binding-model.mjs','source/js/journal/wire.mjs','source/js/journal/contract.mjs','source/js/journal/pending-intent.mjs','test_adversarial.mjs'];
const before=names.map(path=>({path,bytes:file(path).length,sha256:hash(file(path))}));
const routes=new Map();for(const name of names.filter(n=>n!=='test_browser.mjs'))routes.set('/candidate/'+name,file(name));
for(const name of ['js/owned-learning-store.mjs','question-bank/js/learning-transition.mjs','question-bank/js/practice-flow.mjs'])routes.set('/original/'+name,readFileSync(new URL('source/'+name,prior)));
const network=[],unexpected=[],errors=[];let origin;
const server=createServer((req,res)=>{network.push(req.url);res.setHeader('cache-control','no-store');if(req.url==='/'){res.setHeader('content-type','text/html');res.end('<!doctype html><title>T3 native receipt fixture</title><script type="module" src="/candidate/browser-page.mjs"></script>');return}if(routes.has(req.url)){res.setHeader('content-type','text/javascript');res.end(routes.get(req.url));return}unexpected.push(req.url);res.writeHead(404);res.end()});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--host-resolver-rules=MAP * ~NOTFOUND, EXCLUDE 127.0.0.1']});
const outcomes=[];const assert=(value,label)=>{if(!value)throw Error(label)};
async function page(context){const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(origin);await p.waitForFunction(()=>!!window.fixture);return p}
async function test(name,fn){const context=await browser.newContext();let deadline;await context.route('**/*',route=>route.request().url().startsWith(origin+'/')?route.continue():(unexpected.push(route.request().url()),route.abort()));try{const p=await page(context);const details=await Promise.race([fn(p,context),new Promise((_,reject)=>{deadline=setTimeout(()=>reject(Error('Native test deadline')),60000)})]);outcomes.push({name,status:'PASS',details:details??null});process.stdout.write('PASS '+name+'\n')}catch(e){outcomes.push({name,status:'FAIL',error:String(e.stack||e)});process.stdout.write('FAIL '+name+' '+e.message+'\n')}finally{clearTimeout(deadline);await context.close()}}
try{
await test('X01 actual native ACK quota refusal preserves receipt and pending transaction',async(p,c)=>{
 const setup=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();await s.commit(s.prepare('recordAttempt',[{question:fixture.q('physical-quota'),correct:true}]));const w=await s.materializeNext(),before=await fixture.dump();s.dispose();return {id:w.intent.id,before}});
 await p.reload();await p.waitForFunction(()=>!!window.fixture);const cdp=await c.newCDPSession(p);await cdp.send('Storage.overrideQuotaForOrigin',{origin,quotaSize:1024});let result,usage,version;
 try{usage=await cdp.send('Storage.getUsageAndQuota',{origin});version=await cdp.send('Browser.getVersion');assert(usage.overrideActive,'actual quota override');await new Promise(resolve=>setTimeout(resolve,32000));result=await p.evaluate(async id=>{await fixture.open({initialize:false});const s=fixture.stores[0],errors=[],original=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(...args){const tx=original.apply(this,args);tx.addEventListener('abort',()=>errors.push(tx.error?.name??null));return tx};fixture.deliveryHook(async({requestRaw})=>{const raw=await fixture.syntheticReply(requestRaw).text(),chunks=[];for(let i=0;i<14;i++){const bytes=crypto.getRandomValues(new Uint8Array(64000));chunks.push(Array.from(bytes,b=>String.fromCharCode([32,9,13,10][b%4])).join(''))}return new Response(chunks.join('')+raw,{headers:{'content-type':'application/json'}})});let code,value;try{value=await s.deliverNext({operation_id:id})}catch(e){code=e.code}IDBDatabase.prototype.transaction=original;return {code,value,errors,dump:await fixture.dump()}},setup.id)}finally{await cdp.send('Storage.overrideQuotaForOrigin',{origin});await cdp.detach()}
 assert(result.code==='storage_error'&&result.errors.includes('QuotaExceededError')&&JSON.stringify(result.dump)===JSON.stringify(setup.before),'physical ACK quota rollback '+JSON.stringify({code:result.code,value:result.value,errors:result.errors}));const retried=await p.evaluate(async id=>{fixture.deliveryHook(null);const result=await fixture.stores[0].deliverNext({operation_id:id});return {result,dump:await fixture.dump()}},setup.id);assert(retried.result.acknowledged&&retried.dump.records.length===0,'exact request succeeds after quota restored');return {code:result.code,native_abort_errors:result.errors,usage_before:usage.usage,quota_override:usage.quota,retry_acknowledged:retried.result.acknowledged,browser_build:version,write_free_wait_ms:32000,fixture:'Actual Chromium quota override after close/reload, valid randomized-whitespace raw reply; no mocked IndexedDB errors.'};
});
for(const mode of ['acknowledged-cursor','acknowledged-inflight','pending-wrong-cursor'])await test('X02 '+mode+' queue corruption cannot mutate valid wire evidence',async p=>{
 const result=await p.evaluate(async mode=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();await s.commit(s.prepare('recordAttempt',[{question:fixture.q('queue-corrupt'),correct:true}]));const w=await s.materializeNext();if(mode!=='pending-wrong-cursor')await s.deliverNext({operation_id:w.intent.id});const owner=s.binding(),key=[owner.organization_id,owner.account_id,owner.incarnation_id,1];await fixture.mutate('owners',key,v=>({...v,...(mode==='acknowledged-cursor'?{queue_cursor:1}:mode==='acknowledged-inflight'?{in_flight_operation_id:w.intent.id}:{queue_cursor:0})}));const before=await fixture.dump();let code;try{await s.materializeNext()}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await fixture.dump())}},mode);assert(result.code===(mode==='acknowledged-cursor'?'ack_queue':'wire_pointer')&&result.same,'fail closed without rewriting retained ACK');
});
await test('X03 wrong predecessor source index cannot resolve a new wire',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();await s.commit(s.prepare('recordAttempt',[{question:fixture.q('wrong-index'),correct:false}]));await s.deliverNext();fixture.tick();const local=await s.commit(s.prepare('recordAttempt',[{question:fixture.q('wrong-index'),correct:true}])),owner=s.binding(),key=[owner.organization_id,owner.account_id,owner.incarnation_id,1,local.operation_id];await fixture.mutate('bindings',key,v=>({...v,origin:{...v.origin,rows:v.origin.rows.map(r=>r.type==='predecessor'?{...r,source_record_index:0}:r)}}));const before=await fixture.dump();let code;try{await s.materializeNext()}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await fixture.dump())}});assert(result.code==='predecessor_source'&&result.same,'wrong tuple does not borrow receipt');
});
await test('X04 known old ACK replay leaves a newer in-flight pointer and rows intact',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();await s.commit(s.prepare('recordAttempt',[{question:fixture.q('old-replay'),correct:false}]));const first=await s.materializeNext();await s.deliverNext({operation_id:first.intent.id});fixture.tick();await s.commit(s.prepare('recordAttempt',[{question:fixture.q('old-replay'),correct:true}]));const second=await s.materializeNext(),before=await fixture.dump(),replay=await s.deliverNext({operation_id:first.intent.id}),after=await fixture.dump();return {replay,same:JSON.stringify(before)===JSON.stringify(after),pointer:after.owners[0].in_flight_operation_id,second:second.intent.id,last:await s.deliverNext({operation_id:second.intent.id})}});assert(result.replay.duplicate&&result.same&&result.pointer===result.second&&result.last.acknowledged,'old replay cannot clear next operation');
});
await test('X05 changed stored mapping during delivery retains pending state',async p=>{
 await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();await s.commit(s.prepare('recordAttempt',[{question:fixture.q('mapping'),correct:true}]));const w=await s.materializeNext();window.operation=w.intent.id;fixture.deliveryHook(async()=>{await new Promise(resolve=>window.releaseDelivery=resolve)});window.delivering=s.deliverNext({operation_id:w.intent.id}).then(value=>({value}),error=>({code:error.code}))});await p.waitForFunction(()=>!!window.releaseDelivery);
 const result=await p.evaluate(async()=>{const owner=fixture.stores[0].binding(),key=[owner.organization_id,owner.account_id,owner.incarnation_id,1,window.operation];await fixture.mutate('wire',key,v=>({...v,exact_raw:v.exact_raw+' '}));const before=await fixture.dump();window.releaseDelivery();const r=await window.delivering;return {...r,same:JSON.stringify(before)===JSON.stringify(await fixture.dump())}});assert(result.code==='wire_changed'&&result.same,'old response cannot accept changed stored request');
});
await test('X06 native version change aborts a pending delivery before ACK',async p=>{
 await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();await s.commit(s.prepare('recordAttempt',[{question:fixture.q('version-delivery'),correct:true}]));const w=await s.materializeNext();window.before=await fixture.dump();fixture.deliveryHook(({signal})=>{window.started=true;signal.addEventListener('abort',()=>window.aborted=true,{once:true});return new Promise(()=>{})});window.delivering=s.deliverNext({operation_id:w.intent.id}).then(value=>({value}),error=>({code:error.code}))});await p.waitForFunction(()=>window.started);
 const result=await p.evaluate(async()=>{const r=indexedDB.open(fixture.DATABASE,2),db=await new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});const result=await window.delivering,dump={};await new Promise(resolve=>{const tx=db.transaction(fixture.names);for(const name of fixture.names){const read=tx.objectStore(name).getAll();read.onsuccess=()=>dump[name]=read.result}tx.oncomplete=resolve});db.close();return {...result,aborted:window.aborted,same:JSON.stringify(window.before)===JSON.stringify(dump)}});assert(result.code==='version_changed'&&result.aborted&&result.same,'native version fence cancels delivery');
});
await test('X07 owner invalidation after native pending delete success rolls back the ACK',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();await s.commit(s.prepare('recordAttempt',[{question:fixture.q('delete-lifetime'),correct:true}]));const w=await s.materializeNext(),before=await fixture.dump();fixture.injectDelete(()=>fixture.change({status:'inactive'}));let code;try{await s.deliverNext({operation_id:w.intent.id})}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await fixture.dump())}});assert(result.code==='owner_changed'&&result.same,'native deletion cannot commit across revocation');
});
for(const mode of ['later-timing','earlier-missing-coverage'])await test('X08 terminal witness '+mode+' cannot replace captured origin',async p=>{
 const result=await p.evaluate(async mode=>{await fixture.open();const s=fixture.stores[0],question=fixture.q('origin-witness'),descriptor=s.query('topicDescriptor',[question]);let replacement;if(mode==='earlier-missing-coverage')replacement=await s.installRemoteContext({keys:[{kind:'sessions',record_id:'unused-before'}]});const original=await s.installRemoteContext({keys:[{kind:'review',record_id:question.id},{kind:'mastery',record_id:descriptor.key}]}),first=await s.commit(s.prepare('recordAttempt',[{question,correct:false}]));await s.deliverNext();if(mode==='later-timing')replacement=await s.installRemoteContext({keys:[{kind:'sessions',record_id:'unused-after'}]});fixture.tick();await s.commit(s.prepare('recordAttempt',[{question,correct:true}]));const next=await s.materializeNext();await s.wireIntent(next.intent.id);const owner=s.binding(),key=[owner.organization_id,owner.account_id,owner.incarnation_id,1,first.operation_id];await fixture.mutate('bindings',key,v=>({...v,origin:{...v.origin,context_id:replacement.context_id}}));const before=await fixture.dump();let code;try{await s.wireIntent(next.intent.id)}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await fixture.dump()),original:original.context_id,replacement:replacement.context_id}},mode);assert(result.code==='wire_source_origin'&&result.same&&result.original!==result.replacement,'terminal captured origin correspondence must remain exact');return {predecessor_probe:'c04-independent/t3-terminal-origin-counterexample-v2.json',scope:mode};
});
await test('X09 earlier valid equivalent coverage cannot rewrite acknowledged source origin',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0],question=fixture.q('earlier-valid'),descriptor=s.query('topicDescriptor',[question]);const earlier=await s.installRemoteContext({keys:[{kind:'review',record_id:question.id},{kind:'mastery',record_id:descriptor.key}]}),captured=await s.installRemoteContext({keys:[{kind:'sessions',record_id:'unused-extra'}]}),first=await s.commit(s.prepare('recordAttempt',[{question,correct:false}]));await s.deliverNext();fixture.tick();await s.commit(s.prepare('recordAttempt',[{question,correct:true}]));const next=await s.materializeNext(),owner=s.binding(),key=[owner.organization_id,owner.account_id,owner.incarnation_id,1,first.operation_id];await fixture.mutate('bindings',key,v=>({...v,origin:{...v.origin,context_id:earlier.context_id}}));const before=await fixture.dump();let code;try{await s.wireIntent(next.intent.id)}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await fixture.dump()),different:earlier.context_id!==captured.context_id}});assert(result.code==='wire_source_origin'&&result.same&&result.different,'equivalent coverage does not authorize origin rewriting');
});
for(const mode of ['later-timing','earlier-missing-coverage'])await test('X10 two-record origin rewrite still fails terminal '+mode+' validation',async p=>{
 const result=await p.evaluate(async mode=>{await fixture.open();const s=fixture.stores[0],question=fixture.q('own-origin'),descriptor=s.query('topicDescriptor',[question]);let replacement;if(mode==='earlier-missing-coverage')replacement=await s.installRemoteContext({keys:[{kind:'sessions',record_id:'unused-before'}]});await s.installRemoteContext({keys:[{kind:'review',record_id:question.id},{kind:'mastery',record_id:descriptor.key}]});const first=await s.commit(s.prepare('recordAttempt',[{question,correct:false}])),ack=await s.deliverNext();if(mode==='later-timing')replacement=await s.installRemoteContext({keys:[{kind:'sessions',record_id:'unused-after'}]});fixture.tick();await s.commit(s.prepare('recordAttempt',[{question,correct:true}]));const next=await s.materializeNext(),owner=s.binding(),key=[owner.organization_id,owner.account_id,owner.incarnation_id,1];await fixture.mutate('bindings',[...key,first.operation_id],v=>({...v,origin:{...v.origin,context_id:replacement.context_id}}));await fixture.mutate('wire',[...key,ack.operation_id],v=>({...v,source_origin:{...v.source_origin,context_id:replacement.context_id}}));const before=await fixture.dump();let code;try{await s.wireIntent(next.intent.id)}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await fixture.dump())}},mode);assert(result.code==='invalid_context_origin'&&result.same,'own context remains required independently of copied anchor');
});
}finally{await browser.close();await new Promise(resolve=>server.close(resolve))}
for(const r of before)assert(file(r.path).length===r.bytes&&hash(file(r.path))===r.sha256,'Source changed during tests');
const failed=outcomes.filter(x=>x.status==='FAIL').length,report={contract:'echs.c04.ack-adversarial-tests.v1',status:failed||unexpected.length||errors.length?'FAIL':'PASS',groups:outcomes.length,passed:outcomes.length-failed,failed,skipped:0,outcomes,source_files:before,original_manifest_sha256:hash(priorManifest),loopback_requests:network.length,unexpected_requests:unexpected,page_errors:errors,chromium_version:browser.version(),node_version:process.version,scope:'Supplemental native IndexedDB T3 adversarial cases; synthetic authority/delivery, actual Chromium physical quota. Original84 main cases have separate evidence. No real server or active adoption.'};
writeFileSync(process.argv[2],JSON.stringify(report,null,2)+'\n',{flag:'wx'});process.stdout.write(JSON.stringify({status:report.status,groups:report.groups,failed})+'\n');if(report.status!=='PASS')process.exitCode=1;
