import {createServer} from 'node:http';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {chromium} from '../../foundations/question-bank/official/tools/node_modules/playwright/index.mjs';
const here=new URL('./',import.meta.url),prior=new URL('../c04-learning-p2b-candidate/',here),hash=b=>createHash('sha256').update(b).digest('hex');
const file=name=>readFileSync(new URL(name,here));
if(!process.argv[2]||existsSync(process.argv[2]))throw Error('Fresh report filename required');
const priorManifest=readFileSync(new URL('candidate-manifest.json',prior));if(hash(priorManifest)!=='817c3395b1589c74391cce55fd7dffdae9de3a28c2b1f9fd90e371428c788722')throw Error('Original manifest changed');
const copy=JSON.parse(file('COPY_RECEIPT.json'));for(const r of [...copy.source_files,...copy.preserved_original_tests]){const raw=readFileSync(new URL(r.path,prior));if(raw.length!==r.bytes||hash(raw)!==r.sha256)throw Error('Original source/test changed '+r.path)}
const names=['source/js/owned-learning-store.mjs','source/js/owned-learning-transport.mjs','source/question-bank/js/learning-transition.mjs','source/question-bank/js/practice-flow.mjs','browser-page.mjs','test_browser.mjs','source/js/wire-binding-model.mjs','source/js/journal/wire.mjs','source/js/journal/contract.mjs','source/js/journal/pending-intent.mjs'];
const before=names.map(path=>({path,bytes:file(path).length,sha256:hash(file(path))}));
const routes=new Map();for(const name of names.filter(n=>n!=='test_browser.mjs'))routes.set('/candidate/'+name,file(name));
for(const name of ['js/owned-learning-store.mjs','question-bank/js/learning-transition.mjs','question-bank/js/practice-flow.mjs'])routes.set('/original/'+name,readFileSync(new URL('source/'+name,prior)));
const network=[],unexpected=[],errors=[];let origin;
const server=createServer((req,res)=>{network.push(req.url);res.setHeader('cache-control','no-store');if(req.url==='/'){res.setHeader('content-type','text/html');res.end('<!doctype html><title>T1 native source bundle fixture</title><script type="module" src="/candidate/browser-page.mjs"></script>');return}if(routes.has(req.url)){res.setHeader('content-type','text/javascript');res.end(routes.get(req.url));return}unexpected.push(req.url);res.writeHead(404);res.end()});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--host-resolver-rules=MAP * ~NOTFOUND, EXCLUDE 127.0.0.1']});
const outcomes=[];const assert=(value,label)=>{if(!value)throw Error(label)};
async function page(context){const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(origin);await p.waitForFunction(()=>!!window.fixture);return p}
async function test(name,fn){const context=await browser.newContext();let deadline;await context.route('**/*',route=>route.request().url().startsWith(origin+'/')?route.continue():(unexpected.push(route.request().url()),route.abort()));try{const p=await page(context);const details=await Promise.race([fn(p,context),new Promise((_,reject)=>{deadline=setTimeout(()=>reject(Error('Native test deadline')),60000)})]);outcomes.push({name,status:'PASS',details:details??null});process.stdout.write('PASS '+name+'\n')}catch(e){outcomes.push({name,status:'FAIL',error:String(e.stack||e)});process.stdout.write('FAIL '+name+' '+e.message+'\n')}finally{clearTimeout(deadline);await context.close()}}
try{
await test('S01 genuine P2b compound transitions retain exact state/results and immutable grouping',async p=>{
 const result=await p.evaluate(async()=>{const f=fixture;await f.open();await f.open({prior:true});const counts=[];
  for(const action of ['start','answer','checkpoint','answer','finish','start','discard']){const result=await f.compare('practice',[f.flow(action,action!=='answer'||counts.length===1)]),b=JSON.parse(result.bundle.raw);counts.push({action,rows:b.records.length,coverage:b.local_domains.map(x=>x.key),wire:b.wire_state});}
  const state=f.stores[0].projection(),bundles=await f.stores[0].sourceBundles();return {counts,revision:state.revision,bundles:bundles.length,summary:f.stores[0].query('summary'),held:await f.held()};
 });assert(result.bundles===8&&result.revision===8,'one bundle per command');assert(result.counts.map(x=>x.rows).join()=== '1,4,1,4,1,1,0','fixed compound row membership');assert(result.held.acknowledged===0&&result.held.status==='held'&&result.summary.mastered===0,'held/provisional');return result;
});
await test('S02 exact command retry and reload preserve one bundle and source row bytes',async p=>{
 const saved=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0],cmd=s.prepare('recordAttempt',[{question:fixture.q('retry'),correct:true,response:'0.5000000000000001'}]),a=await s.commit(cmd),first=await s.sourceBundle(a.operation_id),again=await s.commit(cmd);return {id:a.operation_id,raw:first.raw,duplicate:again.duplicate,count:(await s.sourceBundles()).length}});
 assert(saved.duplicate&&saved.count===2,'idempotent');await p.reload();await p.waitForFunction(()=>!!window.fixture);
 const found=await p.evaluate(async id=>{await fixture.open({initialize:false});return fixture.stores[0].sourceBundle(id)},saved.id);assert(found.raw===saved.raw,'exact raw reload');
});
await test('S03 coalesced review/mastery retain separate earlier source bundles',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0],ids=[];for(const correct of [false,true]){const r=await s.commit(s.prepare('recordAttempt',[{question:fixture.q('same'),correct,response:correct?'B':'C'}]));ids.push(r.operation_id);fixture.tick()}
  const values=await Promise.all(ids.map(id=>s.sourceBundle(id))),dump=await fixture.dump();return {values:values.map(v=>JSON.parse(v.raw)),pending:dump.records};});
 const reviews=result.values.map(b=>b.records.find(r=>r.kind==='review'));assert(reviews.length===2&&reviews[0].local_revision<reviews[1].local_revision&&reviews[0].value_json!==reviews[1].value_json,'separate revision values');assert(result.pending.filter(x=>x.kind==='review').length===1,'coalescing remains convenience only');
});
for(const name of ['history','attempts','records','bundles','owners','states','commands'])await test('S04 abort after native '+name+' write rolls back all seven stores',async p=>{
 const result=await p.evaluate(async name=>{await fixture.open();const before=await fixture.dump();fixture.injectWrite(name,tx=>tx.abort());let code;try{await fixture.stores[0].commit(fixture.stores[0].prepare('recordAttempt',[{question:fixture.q('abort'),correct:false}]))}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await fixture.dump())}},name);assert(result.code&&result.same,'atomic rollback '+name);
});
await test('S05 two tabs identical command commit once and preserve immutable receipt',async(p,c)=>{
 const q=await page(c);await p.evaluate(()=>fixture.open());await q.evaluate(()=>fixture.open({initialize:false}));const cmd=await p.evaluate(()=>fixture.stores[0].prepare('startSession',[{type:'practice',questionIds:['q1']}]))
 const results=await Promise.all([p,q].map(x=>x.evaluate(async cmd=>{cmd.owner=fixture.stores[0].binding();return fixture.stores[0].commit(cmd)},structuredClone(cmd))));assert(results.filter(r=>r.duplicate).length===1,'exact duplicate race');const count=await p.evaluate(async()=> (await fixture.stores[0].sourceBundles()).length);assert(count===2,'one new bundle');
});
await test('S06 two tabs stale session compounds conflict without partial bundles',async(p,c)=>{
 const q=await page(c);await p.evaluate(async()=>{await fixture.open();await fixture.stores[0].commit(fixture.stores[0].prepare('practice',[fixture.flow('start')]))});await q.evaluate(()=>fixture.open({initialize:false}));
 const cmds=await Promise.all([p,q].map(x=>x.evaluate(()=>fixture.stores[0].prepare('practice',[fixture.flow('answer')]))));
 const result=await Promise.all([p,q].map((x,i)=>x.evaluate(async cmd=>{try{return {ok:true,r:await fixture.stores[0].commit(cmd)}}catch(e){return {ok:false,code:e.code}}},cmds[i])));assert(result.filter(r=>r.ok).length===1&&result.some(r=>r.code==='state_conflict'),'one compound wins');const dump=await p.evaluate(()=>fixture.dump());assert(dump.bundles.length===3&&dump.history.length===1,'one attempt bundle');
});
await test('S07 reset records removal candidates and unbound barrier while retaining history/pending',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];await s.commit(s.prepare('recordAttempt',[{question:fixture.q('reset'),correct:false}]));fixture.tick();const before=await fixture.dump();const r=await s.commit(s.prepare('resetLearningData',[{keepProfile:true,keepTeacher:true}]));const bundle=JSON.parse((await s.sourceBundle(r.operation_id)).raw);fixture.tick();const later=await s.commit(s.prepare('recordAttempt',[{question:fixture.q('later'),correct:true}]));const after=await fixture.dump();return {bundle,later:JSON.parse((await s.sourceBundle(later.operation_id)).raw),before,after};});
 assert(result.bundle.unbound_reset_barrier&&result.bundle.wire_state==='unbound'&&result.bundle.records.length===0&&result.bundle.deletion_candidates.length===3,'explicit unbound reset');assert(result.after.history.length===2&&result.after.attempts.length===2&&result.after.records.length>=result.before.records.length,'history/pending retained');assert(result.later.prior_reset_barrier_id===result.bundle.id&&result.after.owners[0].revision>result.before.owners[0].revision,'barrier/counter retained');
});
await test('S08 native lost completion recovers both local receipt and bundle after reload',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0],cmd=s.prepare('recordAttempt',[{question:fixture.q('lost'),correct:true}]);fixture.loseCompletion();let code;try{await s.commit(cmd)}catch(e){code=e.code}return {id:cmd.operation_id,code}});assert(result.code==='timeout','unknown timeout');await p.reload();await p.waitForFunction(()=>!!window.fixture);const recovered=await p.evaluate(async id=>{await fixture.open({initialize:false});return {receipt:await fixture.stores[0].lookup(id),bundle:await fixture.stores[0].sourceBundle(id)}},result.id);assert(recovered.receipt.operation_id===result.id&&recovered.bundle.id===result.id,'reload reconciles both');
});
await test('S09 owner revocation after request success aborts source/state together',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const before=await fixture.dump();fixture.injectWrite('bundles',()=>fixture.change({revoked:true}));let code;try{await fixture.stores[0].commit(fixture.stores[0].prepare('recordAttempt',[{question:fixture.q('revoked'),correct:false}]))}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await fixture.dump())}});assert(result.code==='owner_changed'&&result.same,'revocation atomic');
});
await test('S10 same account with new incarnation cannot read old source bundles',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const r=await fixture.stores[0].commit(fixture.stores[0].prepare('recordAttempt',[{question:fixture.q('old'),correct:true}]));fixture.change({incarnation_id:'30000000-0000-4000-8000-000000000004'});const next=await fixture.open({initialize:false});let denied=false;try{await fixture.stores[0].sourceBundle(r.operation_id)}catch{denied=true}return {denied,newBundle:await fixture.stores[next].sourceBundle(r.operation_id),data:fixture.stores[next].projection().data,dump:await fixture.dump()}});assert(result.denied&&result.newBundle===null&&Object.keys(result.data).length===0&&result.dump.bundles.length===2,'incarnation isolation');assert(result.dump.bundles.every(r=>r.adoption_epoch===1),'all stored binding');
});
await test('S11 reentrant capture disposal during completion rejects known commit observation',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];fixture.injectWrite('commands',()=>fixture.hook(()=>{fixture.hook(null);s.dispose()}));let code;try{await s.commit(s.prepare('recordAttempt',[{question:fixture.q('reentrant'),correct:true}]))}catch(e){code=e.code}return {code,dump:await fixture.dump()}});assert(result.code==='disposed'&&result.dump.bundles.length===2,'commit exists but stale observer rejects');
});
await test('S12 corrupted bundle fails read and exact command receipt lookup',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0],r=await s.commit(s.prepare('recordAttempt',[{question:fixture.q('corrupt'),correct:true}])),b=await s.sourceBundle(r.operation_id);await fixture.mutate('bundles',[b.organization_id,b.account_id,b.incarnation_id,b.adoption_epoch,b.id],v=>({...v,raw:v.raw+' '}));const codes=[];for(const fn of [()=>s.sourceBundle(b.id),()=>s.lookup(b.id),()=>s.sourceBundles()])try{await fn();codes.push(null)}catch(e){codes.push(e.code)}return codes});assert(result.every(Boolean),'corrupt row rejection');
});
await test('S13 native quota refusal leaves no partial initial compound or source bundle',async(p,c)=>{
 await p.evaluate(()=>fixture.open({initialize:false}));const before=await p.evaluate(()=>fixture.dump());const cdp=await c.newCDPSession(p);await cdp.send('Storage.overrideQuotaForOrigin',{origin,quotaSize:1024});
 let result;try{assert((await cdp.send('Storage.getUsageAndQuota',{origin})).overrideActive,'quota override active');result=await p.evaluate(async()=>{let code;const response=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(45000))));try{await fixture.stores[0].commit(fixture.stores[0].prepare('recordAttempt',[{question:fixture.q('quota'),correct:true,response}]))}catch(e){code=e.code}return {code,dump:await fixture.dump()}})}finally{await cdp.send('Storage.overrideQuotaForOrigin',{origin});await cdp.detach()}assert(result.code==='storage_error'&&JSON.stringify(result.dump)===JSON.stringify(before),'quota rollback '+JSON.stringify({code:result.code,bundles:result.dump.bundles.length}));return {code:result.code,method:'actual Chromium quota override with incompressible record'};
});
await test('S14 native versionchange disposes old handle and refuses incompatible schema',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const q=indexedDB.open(fixture.DATABASE,2);await new Promise((resolve,reject)=>{q.onsuccess=()=>{q.result.close();resolve()};q.onerror=()=>reject(q.error)});let oldCode,newCode;try{await fixture.stores[0].sourceBundles()}catch(e){oldCode=e.code}try{await fixture.open()}catch(e){newCode=e.code}return {oldCode,newCode}});assert(result.oldCode==='version_changed'&&result.newCode==='storage_error','version fence');return result;
});
await test('S15 real blocked upgrade fails closed and late open cannot mutate schema',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();fixture.stores[0].dispose();const q=indexedDB.open(fixture.DATABASE,1),blocker=await new Promise((resolve,reject)=>{q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});blocker.onversionchange=()=>{};let code;try{await fixture.open({indexedDB:{open:name=>indexedDB.open(name,2)}})}catch(e){code=e.code}blocker.close();await new Promise(resolve=>setTimeout(resolve,30));const r=indexedDB.open(fixture.DATABASE,1),version=await new Promise((resolve,reject)=>{r.onsuccess=()=>{resolve(r.result.version);r.result.close()};r.onerror=()=>reject(r.error)});return {code,version}});assert(result.code==='storage_blocked'&&result.version===1,'blocked native upgrade retains schema');return result;
});
await test('S16 reentrant subscription and missed owner notifications fail closed',async p=>{
 const result=await p.evaluate(async()=>{const a=fixture.authority(),subscribe=a.subscribe;let removed=false,code;a.subscribe=fn=>{const off=subscribe(fn);fixture.change({revoked:true});return()=>{removed=true;off()}};try{await fixture.open({authority:a})}catch(e){code=e.code}fixture.change({revoked:false});await fixture.open();const before=await fixture.dump();fixture.change({session_id:'replacement_session_123456'},false);let missed;try{await fixture.stores[0].sourceBundles()}catch(e){missed=e.code}return {code,removed,listeners:fixture.listeners(),missed,same:JSON.stringify(before)===JSON.stringify(await fixture.dump())}});assert(result.code==='owner_changed'&&result.removed&&result.listeners===0&&result.missed==='owner_changed'&&result.same,'subscription/current guards');return result;
});
await test('S17 idle expiry aborts handles without a notification or read',async p=>{
 const result=await p.evaluate(async()=>{fixture.change({expires_at:fixture.now()+30});await fixture.open({initialize:false});const s=fixture.stores[0];fixture.expire();await new Promise(resolve=>setTimeout(resolve,60));return {aborted:s.signal.aborted,listeners:fixture.listeners()}});assert(result.aborted&&result.listeners===0,'idle expiry');return result;
});
await test('S18 strict durability refusal cannot partially create a command',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const before=await fixture.dump(),original=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(...args){const tx=original.apply(this,args);if(this.name===fixture.DATABASE&&args[1]==='readwrite'){IDBDatabase.prototype.transaction=original;Object.defineProperty(tx,'durability',{value:'relaxed'})}return tx};let code;try{await fixture.stores[0].commit(fixture.stores[0].prepare('saveSettings',[{dailyGoal:12}]))}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await fixture.dump())}});assert(result.code==='durability_unavailable'&&result.same,'strict durability refusal');return result;
});
await test('S19 locally unsupported and zero-row commands preserve original behavior and explicit coverage',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();await fixture.open({prior:true});const out=[];for(const [method,args]of [['saveProfile',[{name:'Synthetic student'}]],['saveSettings',[{dailyGoal:12}]],['clearContinue',[]],['evaluateAchievements',[]],['resetLearningData',[{keepProfile:false,keepTeacher:false}]]]){const r=await fixture.compare(method,args);out.push(JSON.parse(r.bundle.raw))}return out});assert(result.slice(0,4).every(b=>b.records.length===0&&b.wire_state==='local-only'),'zero-row local-only');assert(result[0].local_domains.some(d=>d.key==='echs_learning_profile_v2')&&result[1].local_domains.some(d=>d.key==='echs_learning_settings_v2'),'unsupported domains explicitly covered');assert(result[4].unbound_reset_barrier&&result[4].local_reset_options.keepProfile===false,'original reset options retained');
});
await test('S20 native bundle paging bounds aggregate bytes and retains every later bundle',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0],ids=Array.from({length:1000},(_,i)=>'q'+i+'x'.repeat(45)),r=await s.commit(s.prepare('startSession',[{questionIds:ids}]));for(let i=0;i<85;i++){fixture.tick();await s.commit(s.prepare('patchSession',[r.result.id,{questionIds:ids.map(id=>id+i)}]))}const first=await s.sourceBundles(),second=await s.sourceBundles({after_revision:first.at(-1).revision}),small=await s.sourceBundles({limit:5});return {total:(await fixture.dump()).bundles.length,first:first.length,bytes:first.reduce((n,x)=>n+x.bytes,0),second:second.length,next:second[0]?.revision,last:first.at(-1).revision,small:small.length}});assert(result.first<result.total&&result.bytes<=4194304&&result.first+result.second===result.total&&result.next===result.last+1&&result.small===5,'bounded raw byte pagination');return result;
});
await test('S21 bundle command linkage and owner accounting corruption reject bounded reads',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0],r=await s.commit(s.prepare('saveSettings',[{dailyGoal:12}])),b=await s.sourceBundle(r.operation_id),key=[b.organization_id,b.account_id,b.incarnation_id,b.adoption_epoch,b.id];await fixture.mutate('commands',key,v=>({...v,sha256:'f'.repeat(64)}));let linkage;try{await s.sourceBundles()}catch(e){linkage=e.code}await fixture.mutate('owners',key.slice(0,4),v=>({...v,bundle_count:1}));let accounting;try{await s.sourceBundles({after_revision:1})}catch(e){accounting=e.code}return {linkage,accounting}});assert(result.linkage==='invalid_source_bundle'&&result.accounting==='invalid_store','corrupt linkage/accounting');return result;
});
await test('S22 original session window eviction creates a retained candidate, never an inferred tombstone',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();await fixture.open({prior:true});await fixture.seedSessionWindow();const r=await fixture.compare('startSession',[{questionIds:['next']}]),b=JSON.parse(r.bundle.raw);return {bundle:b,count:fixture.stores[0].query('sessions').length,held:await fixture.held()}});assert(result.count===1000&&result.bundle.records.length===1&&result.bundle.deletion_candidates.length===1&&result.bundle.deletion_candidates[0].record_id==='window-0'&&result.bundle.deletion_candidates[0].reason==='source-window-removal'&&!result.bundle.unbound_reset_barrier&&result.bundle.wire_state==='unbound'&&result.held.acknowledged===0,'window candidate only');return {fixture:'Native stored engine seeded with the same synthetic 1000-session boundary for both exact original and successor transitions. This is test-only state setup, not an adoption API.',removed:result.bundle.deletion_candidates[0].record_id};
});
await test('S23 source-bundle capacity refusal aborts all command/state/history writes',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const f=fixture,s=f.stores[0],id=s.binding(),key=[id.organization_id,id.account_id,id.incarnation_id,id.adoption_epoch];await f.mutate('owners',key,v=>({...v,bundle_bytes:f.LIMITS.totalBytes}));const before=await f.dump();let code;try{await s.commit(s.prepare('recordAttempt',[{question:f.q('full'),correct:false}]))}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await f.dump())}});assert(result.code==='source_bundle_full'&&result.same,'capacity abort');return {code:result.code,fixture:'Native metadata capacity fault injection; no full-store size claim.'};
});
await test('T01 prior verified empty-owner context captures atomic origin and complete first wire body',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0],context=await s.installRemoteContext(),r=await s.commit(s.prepare('recordAttempt',[{question:fixture.q('fresh'),correct:true,response:'λ 0.5000000000000001',durationMs:0.30000000000000004}])),source=JSON.parse((await s.sourceBundle(r.operation_id)).raw),origin=await s.bundleOrigin(r.operation_id),bound=await s.materializeNext(),body=JSON.parse(bound.intent.exact_raw),dump=await fixture.dump();return {context,origin,bound:bound.status,transport:bound.transport,body,raw:bound.intent.exact_raw,source,wire:dump.wire.length,owner:dump.owners[0],observed:fixture.observed}});
 assert(result.context.installed&&result.origin.origin.context_id===result.context.context_id&&result.origin.origin.generation===0,'prior context captured');assert(result.bound==='bound'&&result.transport==='held'&&result.wire===1&&result.body.records.length===3,'whole first operation');assert(result.body.records.every(r=>r.kind==='attempts'?r.action==='append'&&!Object.hasOwn(r,'expected_revision'):r.expected_revision===0),'proved missing baseline');assert(result.source.records.every(r=>result.raw.includes('"value":'+r.value_json)),'exact source JSON spliced');assert(result.observed.every(r=>['state','heads'].includes(r.route)),'no apply');return {records:result.body.records.length,transport:result.transport,observation:'Synthetic injected read port with actual Response/raw V3 validation; no server executed'};
});
await test('T02 first binding survives exact retries and reload with one unresolved operation',async p=>{
 const before=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();await s.commit(s.prepare('recordAttempt',[{question:fixture.q('reload'),correct:false}]));const first=await s.materializeNext(),again=await s.materializeNext();return {intent:first.intent,duplicate:again.duplicate,same:first.intent.exact_raw===again.intent.exact_raw}});assert(before.duplicate&&before.same,'stable retry');await p.reload();await p.waitForFunction(()=>!!window.fixture);const after=await p.evaluate(async id=>{await fixture.open({initialize:false});const s=fixture.stores[0];return {read:await s.wireIntent(id),again:await s.materializeNext(),dump:await fixture.dump(),ackMethods:Object.keys(s).filter(k=>/acknowledge|send/i.test(k))}},before.intent.id);assert(after.read.exact_raw===before.intent.exact_raw&&after.again.intent.id===before.intent.id&&after.dump.wire.length===1&&after.ackMethods.length===0,'reload exact pending wire; no ACK API');
});
await test('T03 concurrent materializers share one persisted UUID and exact body',async(p,c)=>{
 await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();await s.commit(s.prepare('recordAttempt',[{question:fixture.q('race'),correct:true}]))});const q=await page(c);await q.evaluate(()=>fixture.open({initialize:false}));const results=await Promise.all([p,q].map(x=>x.evaluate(()=>fixture.stores[0].materializeNext())));assert(results[0].intent.id===results[1].intent.id&&results[0].intent.exact_raw===results[1].intent.exact_raw&&results.filter(x=>x.duplicate).length===1,'same persisted mapping');const d=await p.evaluate(()=>fixture.dump());assert(d.wire.length===1&&d.owners[0].wire_count===1,'one unresolved owner operation');
});
await test('T04 old unknown-origin work cannot acquire missing heads after another-device reset',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0],r=await s.commit(s.prepare('recordAttempt',[{question:fixture.q('old'),correct:true}])),before=await s.bundleOrigin(r.operation_id);fixture.remote({generation:1,revision:1});let code;try{await s.installRemoteContext({keys:[{kind:'review',record_id:'old'}]})}catch(e){code=e.code}return {code,before,after:await s.bundleOrigin(r.operation_id),held:await s.materializeNext(),dump:await fixture.dump(),reads:fixture.observed.length}});assert(result.code==='context_queue_held'&&result.before.origin.context_id===null&&JSON.stringify(result.before)===JSON.stringify(result.after),'no retroactive generation');assert(result.held.reason==='unknown_origin'&&result.dump.wire.length===0&&result.dump.contexts.length===0&&result.reads===0,'reset resurrection held before observation');
});
await test('T05 command prepared without context stays unknown when context appears before commit',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0],cmd=s.prepare('recordAttempt',[{question:fixture.q('prepared'),correct:true}]);await s.installRemoteContext();const r=await s.commit(cmd);return {origin:await s.bundleOrigin(r.operation_id),held:await s.materializeNext()}});assert(result.origin.origin.context_id===null&&result.held.reason==='unknown_origin','no retroactive prepared origin');
});
await test('T06 changed prepared context rejects without changing original learning state',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];fixture.remote({revision:5});await s.installRemoteContext({keys:[{kind:'review',record_id:'q1'}]});const cmd=s.prepare('saveSettings',[{dailyGoal:12}]);await s.installRemoteContext({keys:[{kind:'review',record_id:'q2'}]});const before=await fixture.dump();let code;try{await s.commit(cmd)}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await fixture.dump())}});assert(result.code==='context_changed'&&result.same,'prepared context cannot be replaced');
});
await test('T07 local mutation during remote observation invalidates its capture ticket',async p=>{
 await p.evaluate(async()=>{await fixture.open();let first=true;fixture.observationHook(async()=>{if(first){first=false;await new Promise(resolve=>window.releaseObservation=resolve)}});window.installing=fixture.stores[0].installRemoteContext().then(value=>({value}),e=>({code:e.code}))});await p.waitForFunction(()=>!!window.releaseObservation);
 const result=await p.evaluate(async()=>{const s=fixture.stores[0];await s.commit(s.prepare('saveSettings',[{dailyGoal:17}]));window.releaseObservation();const result=await window.installing;return {...result,dump:await fixture.dump()}});assert(result.code==='stale_observation'&&result.dump.contexts.length===0&&result.dump.states[0].revision===2,'late observation cannot install over new local revision');
});
await test('T08 changing remote observation window and nonmissing heads cannot establish a baseline',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];let count=0;fixture.observationHook(()=>{if(++count===2)fixture.remote({revision:1})});let changed;try{await s.installRemoteContext()}catch(e){changed=e.code}fixture.observationHook(null);fixture.remote({revision:5,heads:{'["review","q"]':{revision:2,value:{questionId:'q',score:0.75},value_sha256:'a'.repeat(64)}}});let present;try{await s.installRemoteContext({keys:[{kind:'review',record_id:'q'}]})}catch(e){present=e.code}return {changed,present,dump:await fixture.dump()}});assert(result.changed==='context_changed'&&result.present==='nonmissing_head'&&result.dump.contexts.length===0,'observation inconsistency/nonzero held');
});
await test('T09 caller verified flags, status207, wrong owner and protocol numbers fail response validation',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0],codes=[];for(const mode of ['verified','status','owner','number']){fixture.observationHook(()=>{
   if(mode==='verified')return {verified:true,status:200};if(mode==='status')return new Response('{}',{status:207,headers:{'content-type':'application/json'}});
   const owner=fixture.identity(),data={ok:true,contract:'echs.learning.server-journal.v1',organization_id:owner.organization_id,account_id:owner.account_id,incarnation_id:owner.incarnation_id,adoption_epoch:1,reset_generation:0,owner_revision:0,limits:fixture.SERVER_LIMITS,grading_authoritative:false};
   return new Response(mode==='number'?JSON.stringify(data).replace('"owner_revision":0','"owner_revision":0.0'):JSON.stringify({...data,account_id:'ffffffff-ffff-ffff-ffff-ffffffffffff'}),{headers:{'content-type':'application/json'}});
  });try{await s.installRemoteContext();codes.push(null)}catch(e){codes.push(e.code)}}return {codes,dump:await fixture.dump()}});assert(result.codes.every(Boolean)&&result.dump.contexts.length===0&&result.dump.wire.length===0,'untrusted responses rejected');return {codes:result.codes};
});
await test('T10 captured per-key absence permits first CAS0 without adopting other server values',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0],question=fixture.q('specific'),key=s.query('topicDescriptor',[question]).key;fixture.remote({revision:7});const context=await s.installRemoteContext({keys:[{kind:'review',record_id:'specific'},{kind:'mastery',record_id:key}]});const r=await s.commit(s.prepare('recordAttempt',[{question,correct:true}]));return {context,origin:await s.bundleOrigin(r.operation_id),bound:await s.materializeNext(),reads:fixture.observed}});assert(result.context.installed&&result.bound.status==='bound'&&JSON.parse(result.bound.intent.exact_raw).records.filter(r=>r.kind!=='attempts').every(r=>r.expected_revision===0),'specific first missing CAS');assert(result.reads.map(r=>r.route).join()==='state,heads,state','consistent three-read proof');
});
await test('T11 reset observed after captured source blocks materialization without replacing its generation',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();const r=await s.commit(s.prepare('recordAttempt',[{question:fixture.q('generation'),correct:true}]));fixture.remote({generation:1,revision:1});const observed=await s.installRemoteContext();return {observed,origin:await s.bundleOrigin(r.operation_id),held:await s.materializeNext(),dump:await fixture.dump()}});assert(result.observed.reason==='generation_changed'&&result.origin.origin.generation===0&&result.held.reason==='generation_changed'&&result.dump.wire.length===0&&result.dump.contexts.length===1,'old origin retained under reset hold');
});
await test('T12 coalesced later sources retain predecessor references and cannot advance without T3',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();const ids=[];for(const correct of [false,true]){const r=await s.commit(s.prepare('recordAttempt',[{question:fixture.q('chain'),correct}]));ids.push(r.operation_id);fixture.tick()}const origins=await Promise.all(ids.map(id=>s.bundleOrigin(id))),first=await s.materializeNext(),again=await s.materializeNext();return {ids,origins,first:first.intent.id,again:again.intent.id,dump:await fixture.dump()}});assert(result.origins[1].origin.rows.filter(r=>r.type==='predecessor').length===2&&result.origins[1].origin.rows.filter(r=>r.type==='predecessor').every(r=>r.bundle_id===result.ids[0]),'captured exact predecessor');assert(result.first===result.again&&result.dump.wire.length===1&&result.dump.records.length===4,'one unresolved wire retains later pending rows');
});
for(const name of ['bindings','lineage'])await test('T13 native future-T1 '+name+' write abort keeps all eleven stores atomic',async p=>{
 const result=await p.evaluate(async name=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();const before=await fixture.dump();fixture.injectWrite(name,tx=>tx.abort());let code;try{await s.commit(s.prepare('recordAttempt',[{question:fixture.q('abort-'+name),correct:false}]))}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await fixture.dump())}},name);assert(result.code&&result.same,'new T1 store rollback');
});
for(const name of ['wire','bindings','owners'])await test('T14 native T2 '+name+' write abort leaves no partial raw binding or queue pointer',async p=>{
 const result=await p.evaluate(async name=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();await s.commit(s.prepare('recordAttempt',[{question:fixture.q('wire-abort'),correct:false}]));const before=await fixture.dump();fixture.injectWrite(name,tx=>tx.abort());let code;try{await s.materializeNext()}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await fixture.dump())}},name);assert(result.code&&result.same,'T2 rollback');
});
await test('T15 lost T2 completion is recovered as the exact known persisted binding',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();await s.commit(s.prepare('recordAttempt',[{question:fixture.q('lost-wire'),correct:true}]));fixture.loseCompletion();let code;try{await s.materializeNext()}catch(e){code=e.code}return {code,dump:await fixture.dump()}});assert(result.code==='timeout'&&result.dump.wire.length===1,'unknown completion committed');await p.reload();await p.waitForFunction(()=>!!window.fixture);const recovered=await p.evaluate(async()=>{await fixture.open({initialize:false});return fixture.stores[0].materializeNext()});assert(recovered.duplicate&&recovered.intent.exact_raw===result.dump.wire[0].exact_raw,'reload recovers exact raw');
});
await test('T16 immutable wire corruption and retained-capacity refusal fail closed',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();await s.commit(s.prepare('recordAttempt',[{question:fixture.q('capacity'),correct:true}]));let d=await fixture.dump(),key=[d.owners[0].organization_id,d.owners[0].account_id,d.owners[0].incarnation_id,1];await fixture.mutate('owners',key,v=>({...v,wire_bytes:33554432}));const before=await fixture.dump();let capacity;try{await s.materializeNext()}catch(e){capacity=e.code}const same=JSON.stringify(before)===JSON.stringify(await fixture.dump());await fixture.mutate('owners',key,v=>({...v,wire_bytes:0}));const r=await s.materializeNext();await fixture.mutate('wire',[...key,r.intent.id],v=>({...v,exact_raw:v.exact_raw+' '}));let corrupted;try{await s.wireIntent(r.intent.id)}catch(e){corrupted=e.code}return {capacity,same,corrupted}});assert(result.capacity==='wire_full'&&result.same&&result.corrupted==='wire_changed','capacity and immutable raw');
});
await test('T17 corrupted local-only binding cannot skip an outbound source bundle',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();const r=await s.commit(s.prepare('recordAttempt',[{question:fixture.q('skip'),correct:true}])),owner=s.binding(),key=[owner.organization_id,owner.account_id,owner.incarnation_id,1,r.operation_id];await fixture.mutate('bindings',key,v=>({...v,state:'local-only'}));const before=await fixture.dump();let code;try{await s.materializeNext()}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await fixture.dump())}});assert(result.code==='binding_local_only'&&result.same,'outbound source cannot disappear behind local-only flag');
});
await test('T18 observation deadline aborts its port signal and cancels a late native response body',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();let aborted=false,cancelled=false,release;fixture.observationHook(({signal})=>{signal.addEventListener('abort',()=>aborted=true,{once:true});return new Promise(resolve=>release=resolve)});let code;try{await fixture.stores[0].installRemoteContext()}catch(e){code=e.code}const abortAtReturn=aborted;release(new Response(new ReadableStream({cancel(){cancelled=true}}),{headers:{'content-type':'application/json'}}));await new Promise(resolve=>setTimeout(resolve,0));return {code,abortAtReturn,cancelled,dump:await fixture.dump()}});assert(result.code==='observation_deadline'&&result.abortAtReturn&&result.cancelled&&result.dump.contexts.length===0,'timed-out operation is actually cancelled');
});
await test('T19 owner revocation cancels an unresolved observation without awaiting its response',async p=>{
 await p.evaluate(async()=>{await fixture.open();fixture.observationHook(({signal})=>{window.portStarted=true;signal.addEventListener('abort',()=>window.portAborted=true,{once:true});return new Promise(()=>{})});window.installing=fixture.stores[0].installRemoteContext().then(()=>({}),e=>({code:e.code}))});await p.waitForFunction(()=>window.portStarted);
 const result=await p.evaluate(async()=>{fixture.change({revoked:true});const r=await window.installing;return {...r,aborted:window.portAborted,dump:await fixture.dump()}});assert(result.code==='owner_changed'&&result.aborted&&result.dump.contexts.length===0,'lifetime abort settles pending ticket');
});
for(const field of ['context_id','generation'])await test('T20 corrupted predecessor lineage '+field+' cannot acquire another origin',async p=>{
 const result=await p.evaluate(async field=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();await s.commit(s.prepare('recordAttempt',[{question:fixture.q('lineage'),correct:false}]));const owner=s.binding(),key=[owner.organization_id,owner.account_id,owner.incarnation_id,1,'review','lineage'];await fixture.mutate('lineage',key,v=>({...v,[field]:field==='context_id'?'ffffffff-ffff-ffff-ffff-ffffffffffff':1}));const before=await fixture.dump();fixture.tick();let code;try{await s.commit(s.prepare('recordAttempt',[{question:fixture.q('lineage'),correct:true}]))}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await fixture.dump())}},field);assert(result.code==='lineage_origin'&&result.same,'lineage origin crosslink rolls back all local effects');
});
await test('T21 full retained envelopes and replaced lineages reconcile to native owner accounting',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();for(const correct of [false,true]){await s.commit(s.prepare('recordAttempt',[{question:fixture.q('accounting'),correct}]));fixture.tick()}await s.materializeNext();const d=await fixture.dump(),m=d.owners[0],totals={};for(const [kind,store]of [['context','contexts'],['binding','bindings'],['lineage','lineage'],['wire','wire']])totals[kind]={count:d[store].length,bytes:d[store].reduce((n,v)=>n+fixture.retainedBytes(v),0),recorded_count:m[kind+'_count'],recorded_bytes:m[kind+'_bytes']};return {totals,raw:d.wire[0].raw_bytes,pendingRaw:d.wire[0].pending_intent.raw===d.wire[0].exact_raw}});assert(Object.values(result.totals).every(v=>v.count===v.recorded_count&&v.bytes===v.recorded_bytes),'serialized envelope totals');assert(result.totals.wire.bytes>2*result.raw&&result.pendingRaw,'duplicated request strings both budgeted');return result;
});
for(const kind of ['binding','lineage'])await test('T22 '+kind+' retained metadata capacity aborts the whole future-T1 compound',async p=>{
 const result=await p.evaluate(async kind=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();const owner=s.binding(),key=[owner.organization_id,owner.account_id,owner.incarnation_id,1];await fixture.mutate('owners',key,v=>({...v,[kind+'_bytes']:33554432}));const before=await fixture.dump();let code;try{await s.commit(s.prepare('recordAttempt',[{question:fixture.q(kind),correct:true}]))}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await fixture.dump())}},kind);assert(result.code===kind+'_full'&&result.same,'metadata capacity atomicity');return {fixture:'Synthetic native owner-counter capacity fault; physical quota is covered separately by S13.'};
});
for(const mode of ['numeric-lexeme','duplicate-revision'])await test('T23 native source rejects '+mode+' corruption without normalizing it',async p=>{
 const result=await p.evaluate(async mode=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();const r=await s.commit(s.prepare('recordAttempt',[{question:fixture.q('raw'),correct:true}])),owner=s.binding(),key=[owner.organization_id,owner.account_id,owner.incarnation_id,1,r.operation_id];await fixture.mutate('bundles',key,v=>{const b=JSON.parse(v.raw);if(mode==='numeric-lexeme'){const row=JSON.parse(b.records[0].value_json);row.z=1;b.records[0].value_json=fixture.canonical(row).replace('"z":1','"z":1e0')}else b.records[1].local_revision=b.records[0].local_revision;const raw=fixture.canonical(b);return {...v,raw,bytes:new TextEncoder().encode(raw).length}});const before=await fixture.dump();let code;try{await s.materializeNext()}catch(e){code=e.code}return {code,same:JSON.stringify(before)===JSON.stringify(await fixture.dump())}},mode);assert(result.code==='invalid_source_bundle'&&result.same,'native canonical source corruption rejected');
});
for(const mode of ['record-limit','byte-limit'])await test('T24 native materialization holds the entire synthetic '+mode+' source',async p=>{
 const result=await p.evaluate(async mode=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();const r=await s.commit(s.prepare('recordAttempt',[{question:fixture.q('oversize'),correct:true}])),owner=s.binding(),key=[owner.organization_id,owner.account_id,owner.incarnation_id,1,r.operation_id];let rows;await fixture.mutate('bundles',key,v=>{const b=JSON.parse(v.raw);rows=Array.from({length:mode==='record-limit'?129:20},(_,i)=>({kind:'review',record_id:'synthetic-'+i,local_revision:i+1,value_json:fixture.canonical({questionId:'synthetic-'+i,payload:mode==='byte-limit'?'x'.repeat(60000):''})}));b.records=rows;const raw=fixture.canonical(b);return {...v,raw,bytes:new TextEncoder().encode(raw).length}});await fixture.mutate('bindings',key,v=>({...v,origin:{...v.origin,rows:rows.map(()=>({type:'missing',context_id:v.origin.context_id,expected_revision:0}))}}));const seeded=await fixture.dump();await fixture.mutate('owners',key.slice(0,4),v=>({...v,binding_bytes:seeded.bindings.reduce((n,b)=>n+fixture.retainedBytes(b),0),bundle_bytes:seeded.bundles.reduce((n,b)=>n+b.bytes,0)}));const before=await fixture.dump(),held=await s.materializeNext(),after=await fixture.dump();return {held,wire:after.wire.length,sourceSame:JSON.stringify(before.bundles)===JSON.stringify(after.bundles),records:rows.length}} ,mode);assert(result.held.reason===(mode==='record-limit'?'wire_record_limit':'wire_byte_limit')&&result.wire===0&&result.sourceSame,'no partial chunk or source deletion');return {records:result.records,fixture:'Native IndexedDB synthetic complete-source/binding boundary injection. This is not an original transition producer or import path.'};
});
await test('T25 pure builder preserves opaque numeric tokens and enforces 128 records and row bytes',async p=>{
 const result=await p.evaluate(async()=>{await fixture.open();const s=fixture.stores[0];await s.installRemoteContext();const r=await s.commit(s.prepare('recordAttempt',[{question:fixture.q('pure'),correct:true}])),bundle=JSON.parse((await s.sourceBundle(r.operation_id)).raw),binding=await s.bundleOrigin(r.operation_id),owner=s.binding(),scope=Object.fromEntries(['organization_id','account_id','incarnation_id','adoption_epoch'].map(k=>[k,owner[k]])),operation='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';const raw='{"id":'+JSON.stringify(bundle.records[0].record_id)+',"huge":900719925474099312345,"precise":0.123456789012345678901,"exponent":1e+400}';bundle.records[0].value_json=raw;const wire=fixture.makeWire(bundle,binding,scope,operation);const records=Array.from({length:128},(_,i)=>({kind:'attempts',record_id:'pure-'+i,local_revision:i+1,value_json:'{"id":"pure-'+i+'","n":1e+400}'})),b={...bundle,records},m={...binding,origin:{...binding.origin,rows:records.map(()=>({type:'append'}))}};const exact128=fixture.makeWire(b,m,scope,operation);let count,row;try{fixture.makeWire({...b,records:[...records,{...records[0],record_id:'last',local_revision:129}]},{...m,origin:{...m.origin,rows:[...m.origin.rows,{type:'append'}]}},scope,operation)}catch(e){count=e.code}try{fixture.makeWire({...bundle,records:bundle.records.map((r,i)=>i===0?{...r,value_json:'"'+'x'.repeat(65536)+'"'}:r)},binding,scope,operation)}catch(e){row=e.code}return {same:wire.exact_raw.includes('"value":'+raw),count,row,records:JSON.parse(exact128.exact_raw).records.length}});assert(result.same&&result.records===128&&result.count==='wire_record_limit'&&result.row==='wire_row_limit','opaque pure builder bounds');return {fixture:'Pure injected in-memory raw tokens through actual V3 parser, not native T1 import. Native noncanonical numbers are rejected by T23.'};
});
}finally{await browser.close();await new Promise(resolve=>server.close(resolve))}
for(const r of before)assert(file(r.path).length===r.bytes&&hash(file(r.path))===r.sha256,'Source changed during tests');
const failed=outcomes.filter(x=>x.status==='FAIL').length,report={contract:'echs.c04.wire-binding-browser-tests.v1',status:failed||unexpected.length||errors.length?'FAIL':'PASS',groups:outcomes.length,passed:outcomes.length-failed,failed,skipped:0,outcomes,source_files:before,original_manifest_sha256:hash(priorManifest),loopback_requests:network.length,unexpected_requests:unexpected,page_errors:errors,chromium_version:browser.version(),node_version:process.version,scope:'Native IndexedDB future-T1 plus first T2 binding. Synthetic injected authority/read-response port; original29 T1 cases preserved. No T3 ACK progression, actual server, active runtime, adoption or network acceptance.'};
writeFileSync(process.argv[2],JSON.stringify(report,null,2)+'\n',{flag:'wx'});process.stdout.write(JSON.stringify({status:report.status,groups:report.groups,failed})+'\n');if(report.status!=='PASS')process.exitCode=1;
