(function(){
  "use strict";

  const PATHWAYS={AA_HL:{short:"AA HL",label:"Analysis & Approaches HL"},AA_SL:{short:"AA SL",label:"Analysis & Approaches SL"},AI_HL:{short:"AI HL",label:"Applications & Interpretation HL"},AI_SL:{short:"AI SL",label:"Applications & Interpretation SL"}};
  const SKILLS={number:"Number & quantitative fluency",algebra:"Algebraic & symbolic fluency",functions:"Functions & representation",geometry:"Geometry & coordinate reasoning",trigonometry:"Trigonometric fluency",statistics:"Statistics & data analysis",probability:"Probability reasoning",modelling:"Mathematical modelling",reasoning:"Reasoning & justification",communication:"Mathematical communication"};
  const PATH_ORDER=Object.keys(PATHWAYS);
  const state={demo:new URLSearchParams(location.search).get("demo")==="1",account:null,overview:null,rows:[],filteredRows:[],schools:[],student:null,studentId:null,diagnostic:null,model:null,validation:null,currentView:"overview"};
  const $=(selector,root=document)=>root.querySelector(selector);
  const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
  const safeText=value=>String(value??"");
  const clamp=(value,min=0,max=100)=>{const n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):null};
  const fmt=value=>Number.isFinite(Number(value))?Math.round(Number(value)):"—";
  const pct=value=>Number.isFinite(Number(value))?`${Math.round(Number(value))}%`:"—";
  const esc=value=>safeText(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
  const slug=value=>safeText(value).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
  const today=()=>new Date().toISOString().slice(0,10);
  const shortDate=value=>{if(!value)return"—";const d=new Date(value);return Number.isNaN(d.valueOf())?safeText(value):d.toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"})};
  const latest=(rows,key="created_at")=>[...(rows||[])].sort((a,b)=>Date.parse(b?.[key]||0)-Date.parse(a?.[key]||0))[0]||null;
  const latestByPathway=snapshots=>Object.fromEntries(PATH_ORDER.map(path=>[path,latest((snapshots||[]).filter(row=>row.pathway===path))]));

  function notice(message,type="info",timeout=6500){
    const region=$("#noticeRegion");if(!region)return;
    const item=document.createElement("div");item.className=`readinessNotice ${type}`;item.textContent=message;region.prepend(item);
    if(timeout)setTimeout(()=>item.remove(),timeout);
  }
  function errorMessage(error){return error?.message||String(error||"Unexpected error")}
  async function api(path,options={}){
    if(state.demo)return demoApi(path,options);
    if(!window.ECHSInstitution?.api)throw new Error("Institutional API client is not available.");
    return await window.ECHSInstitution.api("readiness-api",path,options);
  }

  function syntheticSnapshot(path,score,offsetDays=0,full=true,variant=0){
    const band=score>=80?"Strong":score>=70?"On track":score>=55?"Developing":"Needs foundation";
    const date=new Date(Date.now()-offsetDays*86400000).toISOString();
    const skillBase={number:score+4,algebra:score+(path.startsWith("AA")?variant-6:variant),functions:score+(path.startsWith("AA")?variant-2:variant+1),geometry:score-1,trigonometry:score+(path.startsWith("AA")?-8:-2),statistics:score+(path.startsWith("AI")?8:1),probability:score+(path.startsWith("AI")?6:0),modelling:score+(path.startsWith("AI")?7:-1),reasoning:score-2,communication:score+2};
    const skill_profile=Object.fromEntries(Object.entries(skillBase).map(([key,value])=>[key,{score:clamp(value),sources:full?["MAP","MYP","Diagnostic"]:["MAP"]}]));
    const target=path.endsWith("HL")?72:66;
    const gaps=Object.entries(skill_profile).filter(([,data])=>data.score<target-4).sort((a,b)=>a[1].score-b[1].score).slice(0,4).map(([key,data],index)=>({skill_key:key,title:`Strengthen ${SKILLS[key]}`,current_score:Math.round(data.score),target_score:target,priority:index<2?"high":"medium",recommendation:`Build targeted practice in ${SKILLS[key].toLowerCase()} and reassess with fresh evidence.`,evidence_sources:data.sources}));
    return {id:`snap-${path}-${offsetDays}-${variant}`,pathway:path,readiness_index:score,score,band,confidence:full?"High":"Screening only",evidence_status:full?"full_profile":"screening_only",evidence_completeness:full?1:.4,components:{map:{available:true,score:clamp(score+(variant%3)-2),configured_weight:.4},myp:{available:full,score:full?clamp(score+2):null,configured_weight:.3},diagnostic:{available:full,score:full?clamp(score-1):null,configured_weight:.3}},skill_profile,gaps,reasons:[`Synthetic demonstration profile for ${PATHWAYS[path].short}.`,gaps[0]?`Highest-priority gap: ${SKILLS[gaps[0].skill_key]}.`:"No high-priority prerequisite gap in the demonstration profile."],created_at:date,model_version:1};
  }
  function demoStudents(){
    const names=["Alya Hassan","Omar Saleh","Lina Faris","Yousef Karim","Mariam Nasser","Hamad Ali","Sara Mansour","Rayan Khalid","Noor Samir","Adam Tarek","Dana Ibrahim","Zaid Kareem"];
    return names.map((name,index)=>{
      const id=`00000000-0000-4000-8000-${String(index+1).padStart(12,"0")}`;
      const full=index<7,partial=index>=7&&index<10;
      const evidence_status=full?"full_profile":partial?"partial_profile":"screening_only";
      const base=58+((index*7)%29);
      const pathways={
        AA_HL:syntheticSnapshot("AA_HL",clamp(base+(index%4===0?7:-5)),0,full,index),
        AA_SL:syntheticSnapshot("AA_SL",clamp(base+8),0,full||partial,index),
        AI_HL:syntheticSnapshot("AI_HL",clamp(base+(index%3===0?6:1)),0,full,index),
        AI_SL:syntheticSnapshot("AI_SL",clamp(base+11),0,full||partial,index),
      };
      Object.values(pathways).forEach(p=>{p.evidence_status=evidence_status;p.confidence=full?"High":partial?"Moderate":"Screening only";p.evidence_completeness=full?1:partial?.7:.4});
      return {id,display_name:name,username:`demo${index+1}`,email:`demo${index+1}@example.invalid`,external_id:`S-${1001+index}`,grade:index%2?"10":"9",status:"active",preferred_pathway:["AA_HL","AA_SL","AI_HL","AI_SL",null][index%5],school:[{id:"school-echs",name:"Education City High School",code:"ECHS"},{id:"school-qla",name:"Qatar Leadership Academy",code:"QLA"},{id:"school-awsaj",name:"Awsaj Academy",code:"AWSAJ"}][index%3],classes:[{id:`class-${index%3}`,name:["MYP 5 Mathematics A","MYP 5 Mathematics B","MYP 4 Mathematics"][index%3],course_key:"ib-myp-math",section:String.fromCharCode(65+index%3)}],evidence:{map:{student_id:id,test_date:"2026-05-15",overall_rit:228+index*2,percentile:58+index*3},myp:full||partial?{student_id:id,evidence_date:"2026-06-01",criterion_a:5+index%4,criterion_b:4+(index+1)%4,criterion_c:5+(index+2)%3,criterion_d:4+(index+3)%4}:null,diagnostic:full?{student_id:id,completed_at:"2026-08-30",score:62+index*3}:null},pathways};
    });
  }
  const DEMO_ROWS=demoStudents();
  function demoDetail(studentId){
    const row=DEMO_ROWS.find(student=>student.id===studentId)||DEMO_ROWS[0];
    const current=row.pathways;
    const snapshots=[];
    for(const path of PATH_ORDER){
      snapshots.push({...current[path],id:`${row.id}-${path}-now`});
      snapshots.push(syntheticSnapshot(path,clamp(current[path].readiness_index-6),48,current[path].evidence_status!=="screening_only",2));
      snapshots.push(syntheticSnapshot(path,clamp(current[path].readiness_index-11),96,current[path].evidence_status!=="screening_only",1));
    }
    const target=row.preferred_pathway||"AA_SL";
    const interventions=(current[target]?.gaps||[]).map((gap,index)=>({id:`00000000-0000-4000-9000-${String(index+1).padStart(12,"0")}`,student_id:row.id,pathway:target,skill_key:gap.skill_key,title:gap.title,recommendation:gap.recommendation,priority:gap.priority,status:index===0?"in_progress":"open",baseline_score:gap.current_score,target_score:gap.target_score,updated_at:new Date().toISOString()}));
    return {ok:true,student:{id:row.id,display_name:row.display_name,username:row.username,email:row.email,external_id:row.external_id,grade:row.grade,status:row.status,school:row.school},map_history:row.evidence.map?[{...row.evidence.map,season:"spring",growth_percentile:64,domains:{number:232,algebra:226,functions:229,geometry:224,data:235}}]:[],myp_history:row.evidence.myp?[row.evidence.myp]:[],diagnostic_history:row.evidence.diagnostic?[{...row.evidence.diagnostic,id:"demo-diag",diagnostic_version:"2026.1",correct:22,total:30,answered:30,skill_scores:current[target].skill_profile}]:[],snapshots,interventions,preference:{preferred_pathway:row.preferred_pathway,student_note:"Synthetic demonstration preference",updated_at:new Date().toISOString()}};
  }
  function demoOverview(){
    const evidence_profiles={full:0,partial:0,screening_only:0,no_index:0};const strongest_pathway_counts={AA_HL:0,AA_SL:0,AI_HL:0,AI_SL:0};const gaps=new Map();
    for(const row of DEMO_ROWS){const sample=row.pathways[row.preferred_pathway||"AA_SL"]||Object.values(row.pathways)[0];if(sample.evidence_status==="full_profile")evidence_profiles.full++;else if(sample.evidence_status==="partial_profile")evidence_profiles.partial++;else evidence_profiles.screening_only++;let best=null;for(const path of PATH_ORDER){const score=row.pathways[path]?.readiness_index;if(Number.isFinite(score)&&(!best||score>best.score))best={path,score};}if(best)strongest_pathway_counts[best.path]++;for(const gap of row.pathways[row.preferred_pathway||"AA_SL"]?.gaps||[])gaps.set(gap.skill_key,(gaps.get(gap.skill_key)||0)+1)}
    const schoolMap=new Map();for(const row of DEMO_ROWS){const school=row.school||{id:"unassigned",name:"Unassigned",code:"UNASSIGNED"};if(!schoolMap.has(school.id))schoolMap.set(school.id,{school_id:school.id,school_name:school.name,school_code:school.code,students:0,full_profiles:0,total:0,n:0});const item=schoolMap.get(school.id);item.students++;const current=row.pathways[row.preferred_pathway||"AA_SL"]||Object.values(row.pathways)[0];if(current?.evidence_status==="full_profile")item.full_profiles++;if(Number.isFinite(Number(current?.readiness_index))){item.total+=Number(current.readiness_index);item.n++;}}
    const school_summary=[...schoolMap.values()].map(item=>({school_id:item.school_id,school_name:item.school_name,school_code:item.school_code,students:item.students,full_profiles:item.full_profiles,average_target_readiness:item.n?item.total/item.n:null}));
    return {ok:true,students:DEMO_ROWS.length,evidence_profiles,strongest_pathway_counts,top_gaps:[...gaps.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([skill_key,count])=>({skill_key,count})),school_summary,rows:structuredClone(DEMO_ROWS)};
  }
  function demoModel(){
    const configuration={layer_weights:{map:.4,myp:.3,diagnostic:.3},thresholds:{strong:80,on_track:70,developing:55},success_grade_for_validation:5,pathways:{AA_HL:{map:{overall:.18,number:.10,algebra:.28,functions:.24,geometry:.14,data:.06},myp:{A:.43,B:.24,C:.13,D:.20},diagnostic:{number:.08,algebra:.24,functions:.19,geometry:.07,trigonometry:.15,statistics:.04,probability:.03,modelling:.05,reasoning:.10,communication:.05}},AA_SL:{map:{overall:.22,number:.12,algebra:.24,functions:.20,geometry:.13,data:.09},myp:{A:.40,B:.23,C:.15,D:.22},diagnostic:{number:.10,algebra:.20,functions:.17,geometry:.08,trigonometry:.12,statistics:.07,probability:.05,modelling:.07,reasoning:.08,communication:.06}},AI_HL:{map:{overall:.19,number:.10,algebra:.15,functions:.17,geometry:.10,data:.29},myp:{A:.31,B:.27,C:.17,D:.25},diagnostic:{number:.08,algebra:.11,functions:.14,geometry:.05,trigonometry:.07,statistics:.20,probability:.14,modelling:.12,reasoning:.05,communication:.04}},AI_SL:{map:{overall:.24,number:.13,algebra:.12,functions:.13,geometry:.10,data:.28},myp:{A:.28,B:.27,C:.19,D:.26},diagnostic:{number:.10,algebra:.10,functions:.12,geometry:.06,trigonometry:.05,statistics:.21,probability:.15,modelling:.12,reasoning:.04,communication:.05}}}};
    return {ok:true,model:{id:"demo-model",name:"Synthetic readiness baseline",version:1,status:"active",configuration,effective_configuration:configuration,notes:"Synthetic demo configuration."},default_model:configuration,pathways:PATHWAYS};
  }
  async function demoApi(path,options={}){
    await new Promise(resolve=>setTimeout(resolve,70));
    if(path==="/overview")return demoOverview();
    if(path==="/schools"&&(!options.method||options.method==="GET"))return {ok:true,schools:[{id:"school-echs",name:"Education City High School",code:"ECHS",status:"active"},{id:"school-qla",name:"Qatar Leadership Academy",code:"QLA",status:"active"},{id:"school-awsaj",name:"Awsaj Academy",code:"AWSAJ",status:"active"}]};
    if(path==="/schools"&&options.method==="POST")return {ok:true,school:{id:`demo-school-${Date.now()}`,name:options.body?.name||"New School",code:options.body?.code||"NEW",status:"active"}};
    if(path==="/schools/assign"&&options.method==="POST"){const school=(await demoApi("/schools")).schools.find(x=>x.id===options.body?.school_id);for(const id of options.body?.student_ids||[]){const row=DEMO_ROWS.find(x=>x.id===id);if(row&&school)row.school=school;}return {ok:true,assigned:(options.body?.student_ids||[]).length,student_ids:options.body?.student_ids||[]};}
    if(path==="/students")return {ok:true,students:structuredClone(DEMO_ROWS)};
    if(path==="/model"&&(!options.method||options.method==="GET"))return demoModel();
    if(path==="/validation")return {ok:true,summary:{n:84,correlation_readiness_to_grade:.61,accuracy:.76,sensitivity:.81,specificity:.68,success_grade:5,classification_threshold:70,bands:[{band:"Strong",n:19,observed_success_rate:.895,average_final_grade:6.1,average_readiness_index:86},{band:"On track",n:26,observed_success_rate:.769,average_final_grade:5.5,average_readiness_index:75},{band:"Developing",n:25,observed_success_rate:.56,average_final_grade:4.8,average_readiness_index:63},{band:"Needs foundation",n:14,observed_success_rate:.286,average_final_grade:3.8,average_readiness_index:48}],validation_status:"early_local_sample",warning:"Synthetic validation result for demonstration only."},linked_records:[]};
    if(path==="/diagnostic")return await fetch("diagnostic-demo.json",{cache:"no-store"}).then(r=>r.json());
    const detail=path.match(/^\/students\/([0-9a-f-]{36})$/i);if(detail)return demoDetail(detail[1]);
    const recompute=path.match(/^\/students\/([0-9a-f-]{36})\/recompute$/i);if(recompute)return {ok:true,...demoDetail(recompute[1]),pathways:DEMO_ROWS.find(row=>row.id===recompute[1])?.pathways||{}};
    if(path==="/recompute")return {ok:true,processed:(options.body?.student_ids||DEMO_ROWS).length,results:[]};
    if(path==="/preference"){const row=DEMO_ROWS.find(item=>item.id===options.body?.student_id);if(row)row.preferred_pathway=options.body?.preferred_pathway||null;return{ok:true,preferred_pathway:options.body?.preferred_pathway||null}}
    if(path.startsWith("/interventions/"))return{ok:true};
    if(path==="/myp/evidence")return{ok:true,evidence_id:"demo-evidence",recomputed:{}};
    if(path==="/map/import"||path==="/myp/import")return{ok:true,batch_id:"demo-batch",matched:options.body?.rows?.length||0,rejected:[],matched_student_ids:DEMO_ROWS.slice(0,Math.min(options.body?.rows?.length||0,DEMO_ROWS.length)).map(r=>r.id)};
    if(path==="/outcomes/import")return{ok:true,batch_id:"demo-outcomes",matched:options.body?.rows?.length||0,rejected:[]};
    if(path==="/model"&&options.method==="PUT")return{ok:true,model:{...demoModel().model,version:2,configuration:options.body?.configuration,effective_configuration:options.body?.configuration}};
    if(path==="/diagnostic/submit"){
      const responses=options.body?.responses||{};const answered=Object.keys(responses).length;const score=Math.min(100,Math.round(54+answered*1.05));const skill_scores=Object.fromEntries(Object.keys(SKILLS).map((key,index)=>[key,Math.min(100,score+(index%4-2)*5)]));return{ok:true,synthetic_demo:true,result:{version:"2026.1",answered,total:30,correct:Math.round(score*.3),score,skill_scores},recomputed:{}};
    }
    throw new Error(`Demo route not implemented: ${path}`);
  }

  function setRoleVisibility(){
    const role=state.demo?"demo":state.account?.role||"student";const staff=["admin","teacher","demo"].includes(role);const admin=["admin","demo"].includes(role);const teacher=["teacher","demo"].includes(role);
    $$(".staffOnly").forEach(node=>node.classList.toggle("hidden",!staff));$$(".adminOnly").forEach(node=>node.classList.toggle("hidden",!admin));$$(".teacherOnly").forEach(node=>node.classList.toggle("hidden",!teacher));$$(".secureOnly").forEach(node=>node.classList.toggle("hidden",state.demo));
    if(state.demo){$("[data-institution-name]").textContent="Synthetic Demo";$("[data-institution-username]").textContent="demo";$("[data-institution-role]").textContent="demo";$("[data-institution-org]").textContent="Readiness Demonstration";}else if(window.ECHSInstitution?.mountIdentity){window.ECHSInstitution.mountIdentity(state.account)}
    const roleHome=$("[data-role-home]");if(roleHome&&!state.demo)roleHome.href=window.ECHSInstitution.root(window.ECHSInstitution.roleHome(role));
    if(role==="student"){$$("[data-view='overview']").forEach(node=>node.textContent="My Readiness Overview");}
  }
  function setupMenu(){const button=$("[data-readiness-menu]"),side=$("#institutionSidebar");if(!button||!side)return;const set=open=>{side.classList.toggle("open",open);button.setAttribute("aria-expanded",String(open))};button.addEventListener("click",()=>set(!side.classList.contains("open")));document.addEventListener("keydown",event=>{if(event.key==="Escape")set(false)});document.addEventListener("click",event=>{if(innerWidth>950)return;if(side.classList.contains("open")&&!side.contains(event.target)&&!button.contains(event.target))set(false)});}
  function setView(name){
    const role=state.demo?"demo":state.account?.role||"student";if(name==="model"&&!["admin","demo"].includes(role))name="overview";if(name==="evidence"&&!['admin','teacher','demo'].includes(role))name="overview";
    state.currentView=name;$$(".readinessView").forEach(panel=>panel.classList.toggle("active",panel.dataset.viewPanel===name));$$(".readinessNavButton").forEach(button=>button.classList.toggle("active",button.dataset.view===name));
    const titles={overview:["Readiness & Pathway Intelligence","MAP + MYP evidence + IB-specific diagnostic → pathway readiness → targeted action."],student:["Student Readiness Passport","Explainable evidence, trajectory and pathway preparation at learner level."],diagnostic:["IB Mathematics Diagnostic","Focused prerequisite evidence for AA/AI pathway decisions."],evidence:["Evidence & Imports","Controlled MAP, MYP and completed DP outcome ingestion."],model:["Model & Validation","Versioned weights, thresholds and local empirical validation."]};const [title,subtitle]=titles[name]||titles.overview;$("#pageTitle").textContent=title;$("#pageSubtitle").textContent=subtitle;window.scrollTo({top:0,behavior:"smooth"});
    if(name==="model"&&!state.model)loadModel();if(name==="diagnostic")prepareDiagnosticChooser();
  }

  function evidenceStatus(row){const sample=row.preferred_pathway?row.pathways?.[row.preferred_pathway]:Object.values(row.pathways||{}).find(Boolean);return sample?.evidence_status||"none"}
  function evidenceLabel(status){return({full_profile:"Full profile",partial_profile:"Partial profile",screening_only:"Screening only",none:"No index",insufficient:"No index"})[status]||safeText(status).replaceAll("_"," ")}
  function scoreMarkup(result){if(!result||!Number.isFinite(Number(result.readiness_index)))return'<span class="scoreCell"><strong>—</strong><small>No index</small></span>';return `<span class="scoreCell"><strong>${fmt(result.readiness_index)}</strong><small>${esc(result.band||"")}</small></span>`}
  function renderOverview(){
    const data=state.overview;if(!data)return;const profiles=data.evidence_profiles||{};const partial=(profiles.partial||0)+(profiles.screening_only||0)+(profiles.no_index||0);const gapTotal=(data.top_gaps||[]).reduce((sum,row)=>sum+Number(row.count||0),0);
    $("#metricStudents").textContent=data.students??state.rows.length;$("#metricStudentsNote").textContent=state.demo?"Synthetic learner records":"Role-scoped directory";$("#metricFull").textContent=profiles.full??0;$("#metricFullRate").textContent=data.students?`${Math.round((profiles.full||0)/data.students*100)}% complete`:`0% complete`;$("#metricPartial").textContent=partial;$("#metricPartialNote").textContent=`${profiles.screening_only||0} screening-only`;$("#metricGaps").textContent=gapTotal;
    const counts=data.strongest_pathway_counts||{};const total=Math.max(1,Object.values(counts).reduce((a,b)=>a+Number(b||0),0));$("#pathwayLandscape").innerHTML=PATH_ORDER.map(path=>{const count=Number(counts[path]||0);return `<article class="landscapeCard pathColor-${path}"><small>${esc(PATHWAYS[path].label)}</small><strong>${count}</strong><p>${Math.round(count/total*100)}% have this as their strongest current pathway index.</p><div class="landscapeBar"><i style="width:${Math.round(count/total*100)}%"></i></div></article>`}).join("");
    populateSchoolFilter();populateClassFilter();filterRows();renderSystemGaps();renderSchoolComparison();populateStudentChoosers();
  }
  function populateSchoolFilter(){const select=$("#schoolFilter");if(!select)return;const current=select.value;const schools=[...new Map(state.rows.filter(row=>row.school).map(row=>[row.school.id,row.school])).values()].sort((a,b)=>safeText(a.name).localeCompare(safeText(b.name)));select.innerHTML='<option value="">All schools</option>'+schools.map(school=>`<option value="${esc(school.id)}">${esc(school.name)}</option>`).join("")+'<option value="unassigned">Unassigned</option>';if([...schools.map(s=>s.id),"unassigned"].includes(current))select.value=current;}
  function populateClassFilter(){const select=$("#classFilter");if(!select)return;const current=select.value;const names=[...new Set(state.rows.flatMap(row=>(row.classes||[]).map(cls=>cls.name)).filter(Boolean))].sort();select.innerHTML='<option value="">All classes</option>'+names.map(name=>`<option value="${esc(name)}">${esc(name)}</option>`).join("");if(names.includes(current))select.value=current;}
  function filterRows(){const q=$("#studentSearch")?.value.trim().toLowerCase()||"",ev=$("#evidenceFilter")?.value||"",path=$("#pathwayFilter")?.value||"",school=$("#schoolFilter")?.value||"",cls=$("#classFilter")?.value||"";state.filteredRows=state.rows.filter(row=>{const hay=[row.display_name,row.username,row.external_id,row.email,row.school?.name,...(row.classes||[]).map(c=>c.name)].join(" ").toLowerCase();if(q&&!hay.includes(q))return false;const status=evidenceStatus(row);if(ev&&status!==ev)return false;if(path==="unset"&&row.preferred_pathway)return false;if(path&&path!=="unset"&&row.preferred_pathway!==path)return false;if(school==="unassigned"&&row.school)return false;if(school&&school!=="unassigned"&&row.school?.id!==school)return false;if(cls&&!(row.classes||[]).some(c=>c.name===cls))return false;return true});renderCohortRows();}
  function renderCohortRows(){const tbody=$("#cohortRows");if(!tbody)return;if(!state.filteredRows.length){tbody.innerHTML='<tr><td colspan="8">No students match these filters.</td></tr>';return}tbody.innerHTML=state.filteredRows.map(row=>{const status=evidenceStatus(row);return `<tr data-student-row="${row.id}"><td class="studentCell"><strong>${esc(row.display_name)}</strong><small>${esc(row.external_id||row.username||"")} · Grade ${esc(row.grade||"—")}</small></td><td><span class="evidencePill ${slug(status)}">${esc(evidenceLabel(status))}</span></td>${PATH_ORDER.map(path=>`<td>${scoreMarkup(row.pathways?.[path])}</td>`).join("")}<td>${row.preferred_pathway?`<span class="bandPill ${slug(row.pathways?.[row.preferred_pathway]?.band||"")}">${esc(PATHWAYS[row.preferred_pathway]?.short||row.preferred_pathway)}</span>`:'<span class="evidencePill none">Not set</span>'}</td><td><button type="button" class="openStudent" data-open-student="${row.id}">Open</button></td></tr>`}).join("");}
  function renderSchoolComparison(){const schools=state.overview?.school_summary||[];const host=$("#schoolComparison");if(!host)return;host.innerHTML=schools.length?schools.map(item=>`<article class="schoolCard"><div class="schoolCardTop"><div><strong>${esc(item.school_name)}</strong><small>${esc(item.school_code||"")}</small></div><span class="cardBadge">${item.students} learners</span></div><div class="schoolCardMetrics"><div><b>${item.students}</b><span>learners</span></div><div><b>${item.students?Math.round((item.full_profiles||0)/item.students*100):0}%</b><span>full evidence</span></div><div><b>${fmt(item.average_target_readiness)}</b><span>avg target index</span></div></div></article>`).join(""):'<div class="readinessEmptyState"><p>No school assignments yet.</p></div>'; }
  function renderSystemGaps(){const gaps=state.overview?.top_gaps||[];const max=Math.max(1,...gaps.map(g=>Number(g.count||0)));$("#systemGaps").innerHTML=gaps.length?gaps.map(gap=>`<article class="systemGap"><b>${gap.count}</b><strong>${esc(SKILLS[gap.skill_key]||gap.skill_key)}</strong><span>students with an active preparation target</span><div class="gapMeter"><i style="width:${Math.round(Number(gap.count||0)/max*100)}%"></i></div></article>`).join(""):'<div class="readinessEmptyState"><h3>No active gaps yet</h3><p>Recompute profiles after evidence is available.</p></div>';}

  async function loadOverview(){try{const data=await api("/overview");state.overview=data;state.rows=data.rows||[];renderOverview();if((state.account?.role==="student")&&!state.demo&&state.rows.length===1){await openStudent(state.rows[0].id,false)}}catch(error){notice(`Could not load readiness overview: ${errorMessage(error)}`,"error",0);throw error}}
  async function openStudent(studentId,switchView=true){state.studentId=studentId;$("#studentEmpty").hidden=true;$("#studentProfile").hidden=false;$("#studentName").textContent="Loading…";try{state.student=await api(`/students/${studentId}`);renderStudent();if(switchView)setView("student");}catch(error){notice(`Could not load student readiness profile: ${errorMessage(error)}`,"error",0)}}
  function latestEvidenceCards(detail){const map=latest(detail.map_history,"test_date"),myp=latest(detail.myp_history,"evidence_date"),diag=latest(detail.diagnostic_history,"completed_at");return [
    {icon:"M",label:"MAP mathematics",value:map?(Number.isFinite(Number(map.overall_rit))?`RIT ${fmt(map.overall_rit)}`:`${fmt(map.percentile)}th percentile`):"Not available",copy:map?`${shortDate(map.test_date)} · ${esc(map.season||"")} · percentile ${fmt(map.percentile)}`:"Add an approved MAP export to strengthen the external evidence layer."},
    {icon:"MYP",label:"MYP Mathematics",value:myp?`A ${fmt(myp.criterion_a)} · B ${fmt(myp.criterion_b)} · C ${fmt(myp.criterion_c)} · D ${fmt(myp.criterion_d)}`:"Not available",copy:myp?`${shortDate(myp.evidence_date)} · ${esc(myp.source_title||"MYP evidence")}`:"Record criteria-based evidence from appropriate MYP Mathematics assessment tasks."},
    {icon:"◆",label:"IB prerequisite diagnostic",value:diag?`${fmt(diag.score)}%`:"Not completed",copy:diag?`${shortDate(diag.completed_at)} · version ${esc(diag.diagnostic_version||"")}`:"Complete the diagnostic to add pathway-specific prerequisite evidence."},
  ]}
  function renderStudent(){const detail=state.student;if(!detail)return;const student=detail.student;$("#studentName").textContent=student.display_name;$("#studentMeta").textContent=[student.external_id||`@${student.username}`,student.grade?`Grade ${student.grade}`:null,student.school?.name,student.email].filter(Boolean).join(" · ");$("#preferredPathway").value=detail.preference?.preferred_pathway||"";$("#evidenceTriad").innerHTML=latestEvidenceCards(detail).map(card=>`<article class="evidenceCard"><span class="evidenceIcon">${esc(card.icon)}</span><small>${esc(card.label)}</small><strong>${esc(card.value)}</strong><p>${card.copy}</p></article>`).join("");
    const paths=latestByPathway(detail.snapshots);$("#studentPathways").innerHTML=PATH_ORDER.map(path=>{const result=paths[path];if(!result)return `<article class="pathwayCard pathColor-${path}"><div class="pathwayHead"><strong>${PATHWAYS[path].short}</strong><span class="evidencePill none">No index</span></div><div class="readinessDial" style="--score:0"><div><b>—</b><small>index</small></div></div><p class="pathwayReason">Add evidence and recompute this pathway profile.</p></article>`;const components=result.components||{};const reason=(result.reasons||[]).find(text=>text.toLowerCase().includes("gap"))||(result.reasons||[])[0]||"Readiness index calculated from available evidence.";return `<article class="pathwayCard pathColor-${path} ${detail.preference?.preferred_pathway===path?"target":""}"><div class="pathwayHead"><strong>${PATHWAYS[path].short}</strong><span class="bandPill ${slug(result.band)}">${esc(result.band)}</span></div><div class="readinessDial" style="--score:${clamp(result.readiness_index)||0}"><div><b>${fmt(result.readiness_index)}</b><small>readiness</small></div></div><p class="pathwayReason">${esc(reason)}</p><span class="confidencePill ${slug(result.confidence)}">${esc(result.confidence)} · ${Math.round(Number(result.evidence_completeness||0)*100)}% evidence</span><div class="componentMini"><span>MAP<b>${fmt(components.map?.score)}</b></span><span>MYP<b>${fmt(components.myp?.score)}</b></span><span>Diagnostic<b>${fmt(components.diagnostic?.score)}</b></span></div></article>`}).join("");
    const selected=$("#trajectoryPathway").value||detail.preference?.preferred_pathway||"AA_HL";$("#trajectoryPathway").value=selected;renderTrajectory(selected);renderSkillProfile(detail.preference?.preferred_pathway||selected);renderInterventions();
  }
  function renderTrajectory(path){const points=(state.student?.snapshots||[]).filter(row=>row.pathway===path&&Number.isFinite(Number(row.readiness_index))).sort((a,b)=>Date.parse(a.created_at)-Date.parse(b.created_at));const host=$("#trajectoryChart");if(!host)return;if(!points.length){host.innerHTML='<div class="readinessEmptyState"><p>No trajectory points yet.</p></div>';return}const width=660,height=270,pad={l:42,r:18,t:18,b:34},x=i=>pad.l+(points.length===1?(width-pad.l-pad.r)/2:i*(width-pad.l-pad.r)/(points.length-1)),y=v=>pad.t+(100-v)*(height-pad.t-pad.b)/100;const grid=[0,20,40,55,70,80,100];const line=points.map((p,i)=>`${i?"L":"M"}${x(i).toFixed(1)},${y(p.readiness_index).toFixed(1)}`).join(" ");host.innerHTML=`<svg class="trajectorySvg" viewBox="0 0 ${width} ${height}" role="img" aria-label="${PATHWAYS[path].short} readiness trajectory"><rect class="trajectoryBandStrong" x="${pad.l}" y="${y(100)}" width="${width-pad.l-pad.r}" height="${y(80)-y(100)}"></rect><rect class="trajectoryBandTrack" x="${pad.l}" y="${y(80)}" width="${width-pad.l-pad.r}" height="${y(70)-y(80)}"></rect>${grid.map(v=>`<line class="trajectoryGrid" x1="${pad.l}" x2="${width-pad.r}" y1="${y(v)}" y2="${y(v)}"></line><text class="trajectoryAxis" x="${pad.l-8}" y="${y(v)+3}" text-anchor="end">${v}</text>`).join("")}<path class="trajectoryLine" d="${line}"></path>${points.map((p,i)=>`<circle class="trajectoryPoint" cx="${x(i)}" cy="${y(p.readiness_index)}" r="5"><title>${shortDate(p.created_at)}: ${fmt(p.readiness_index)}</title></circle><text class="trajectoryAxis" x="${x(i)}" y="${height-12}" text-anchor="middle">${shortDate(p.created_at).replace(/, \d{4}/,"")}</text>`).join("")}</svg>`;}
  function renderSkillProfile(path){const result=latestByPathway(state.student?.snapshots||[])[path]||Object.values(latestByPathway(state.student?.snapshots||[])).find(Boolean);const profile=result?.skill_profile||{};const entries=Object.entries(profile).sort((a,b)=>Number(a[1]?.score||0)-Number(b[1]?.score||0));$("#skillProfile").innerHTML=entries.length?entries.map(([key,data])=>`<div class="skillRow"><label>${esc(SKILLS[key]||key)}<small>${esc((data.sources||[]).join(" + "))}</small></label><strong>${fmt(data.score)}</strong><div class="skillBar"><i style="width:${clamp(data.score)||0}%"></i></div></div>`).join(""):'<p>No skill evidence yet.</p>';}
  function renderInterventions(){const items=(state.student?.interventions||[]).filter(item=>["open","in_progress"].includes(item.status));$("#studentInterventions").innerHTML=items.length?items.map(item=>`<article class="interventionCard"><div class="interventionTop"><div><span class="bandPill ${slug(item.priority)}">${esc(item.priority)}</span><h3>${esc(item.title)}</h3></div><span class="evidencePill ${slug(item.status)}">${esc(item.status.replaceAll("_"," "))}</span></div><p>${esc(item.recommendation)}</p><div class="interventionMeta"><span>${esc(PATHWAYS[item.pathway]?.short||item.pathway)}</span><span>Baseline ${fmt(item.baseline_score)}</span><span>Target ${fmt(item.target_score)}</span></div><div class="interventionActions">${((state.demo||["teacher","admin"].includes(state.account?.role))?["open","in_progress","mastered","dismissed"]:["open","in_progress"]).map(status=>`<button type="button" class="${item.status===status?"active":""}" data-intervention="${item.id}" data-status="${status}">${status.replaceAll("_"," ")}</button>`).join("")}</div></article>`).join(""):'<div class="readinessEmptyState"><span>✓</span><h3>No active preparation gaps</h3><p>Current evidence does not identify an unresolved gap for the selected target pathway.</p></div>';}

  async function savePreference(){if(!state.studentId)return;const preferred=$("#preferredPathway").value||null;try{await api("/preference",{method:"POST",body:{student_id:state.studentId,preferred_pathway:preferred}});if(state.student.preference)state.student.preference.preferred_pathway=preferred;else state.student.preference={preferred_pathway:preferred};const row=state.rows.find(item=>item.id===state.studentId);if(row)row.preferred_pathway=preferred;renderStudent();renderCohortRows();notice("Target pathway preference updated.","success");}catch(error){notice(`Could not update target pathway: ${errorMessage(error)}`,"error")}}
  async function updateIntervention(id,status){try{await api(`/interventions/${id}`,{method:"PATCH",body:{status}});const item=state.student?.interventions?.find(row=>row.id===id);if(item)item.status=status;renderInterventions();notice("Preparation route status updated.","success");}catch(error){notice(`Could not update intervention: ${errorMessage(error)}`,"error")}}
  async function recomputeStudent(){if(!state.studentId)return;const button=$("#recomputeStudent");button.disabled=true;try{await api(`/students/${state.studentId}/recompute`,{method:"POST",body:{}});await openStudent(state.studentId,false);await loadOverview();notice("Readiness recalculated from the latest evidence.","success");}catch(error){notice(`Recompute failed: ${errorMessage(error)}`,"error")}finally{button.disabled=false}}
  async function recomputeVisible(){const ids=state.filteredRows.map(row=>row.id);if(!ids.length)return notice("No visible students to recompute.","warning");const button=$("#recomputeVisible");button.disabled=true;let processed=0;try{for(let start=0;start<ids.length;start+=100){const chunk=ids.slice(start,start+100);const result=await api("/recompute",{method:"POST",body:{student_ids:chunk}});processed+=Number(result.processed||0);notice(`Recomputed ${processed} of ${ids.length} visible students…`,"info",1800)}await loadOverview();notice(`Readiness recalculated for ${processed} students.`,"success");}catch(error){notice(`Batch recompute stopped: ${errorMessage(error)}`,"error")}finally{button.disabled=false}}

  function populateStudentChoosers(){const options=state.rows.map(row=>`<option value="${row.id}">${esc(row.display_name)}${row.external_id?` · ${esc(row.external_id)}`:""}</option>`).join("");const diagnostic=$("#diagnosticStudent");if(diagnostic){const value=diagnostic.value;diagnostic.innerHTML='<option value="">Choose a student</option>'+options;if(state.studentId)diagnostic.value=state.studentId;else if(value)diagnostic.value=value;}}
  function prepareDiagnosticChooser(){populateStudentChoosers();const role=state.demo?"demo":state.account?.role;if(role==="student"){$("#diagnosticStudentChooser")?.classList.add("hidden");}else $("#diagnosticStudentChooser")?.classList.remove("hidden");}
  async function loadDiagnostic(){const role=state.demo?"demo":state.account?.role;if(role!=="student"){const chosen=$("#diagnosticStudent").value||state.studentId;if(!chosen)return notice("Choose a student before starting the diagnostic.","warning");state.studentId=chosen;}const button=$("#loadDiagnostic");button.disabled=true;try{state.diagnostic=await api("/diagnostic");renderDiagnostic();notice(`Diagnostic ${state.diagnostic.version} loaded.`,"success");}catch(error){notice(`Could not load diagnostic: ${errorMessage(error)}`,"error")}finally{button.disabled=false}}
  function renderDiagnostic(){const questions=state.diagnostic?.questions||[];$("#diagnosticQuestions").innerHTML=questions.map((q,index)=>`<article class="diagnosticQuestion"><div class="diagnosticQuestionHead"><span>Question ${index+1}</span><span>${esc(SKILLS[q.skill]||q.skill)}</span></div><p>${esc(q.prompt)}</p><div class="diagnosticOptions">${q.options.map((option,opt)=>`<label class="diagnosticOption"><input type="radio" name="${esc(q.id)}" value="${opt}"><span>${esc(option)}</span></label>`).join("")}</div></article>`).join("");$("#submitDiagnostic").disabled=true;updateDiagnosticProgress();}
  function updateDiagnosticProgress(){const total=state.diagnostic?.question_count||state.diagnostic?.questions?.length||30;const answered=new Set($$("#diagnosticForm input[type='radio']:checked").map(input=>input.name)).size;$("#diagnosticProgress").textContent=`${answered} of ${total} answered`;$("#submitDiagnostic").disabled=answered<Math.ceil(total*.75);}
  async function submitDiagnostic(event){event.preventDefault();if(!state.diagnostic)return;const responses={};$$("#diagnosticForm input[type='radio']:checked").forEach(input=>responses[input.name]=Number(input.value));const role=state.demo?"demo":state.account?.role;const body={responses};if(role!=="student")body.student_id=$("#diagnosticStudent").value||state.studentId;const button=$("#submitDiagnostic");button.disabled=true;try{const result=await api("/diagnostic/submit",{method:"POST",body});const r=result.result;$("#diagnosticResult").classList.remove("hidden");$("#diagnosticResult").innerHTML=`<h3>${state.demo?"Synthetic demo result":"Diagnostic completed"}: ${fmt(r.score)}%</h3><p>${r.correct} of ${r.total} items were scored correct. ${state.demo?"This score is deliberately synthetic and does not represent grading of the displayed items.":"All four readiness pathways have been recalculated using the new diagnostic evidence."}</p><div class="diagnosticSkillResult">${Object.entries(r.skill_scores||{}).map(([key,value])=>`<div><b>${fmt(value)}%</b><small>${esc(SKILLS[key]||key)}</small></div>`).join("")}</div>`;if(!state.demo){await loadOverview();if(body.student_id||state.account?.role==="student")await openStudent(body.student_id||state.account.id,false)}notice("Diagnostic submitted and readiness updated.","success");}catch(error){notice(`Diagnostic submission failed: ${errorMessage(error)}`,"error")}finally{updateDiagnosticProgress()}}

  const CSV_CONFIG={
    map:{endpoint:"/map/import",fields:[{key:"identifier",label:"Student identifier",aliases:["student id","student_id","school id","external id","student number","id","username","email"]},{key:"test_date",label:"Test date",aliases:["test date","date","test_date"]},{key:"season",label:"Season",aliases:["term","season","testing term","growth term"]},{key:"grade",label:"Grade",aliases:["grade","grade level"]},{key:"overall_rit",label:"Overall RIT",aliases:["rit","rit score","overall rit","overall_rit"]},{key:"percentile",label:"Percentile",aliases:["percentile","achievement percentile","percentile rank"]},{key:"growth_percentile",label:"Growth percentile",aliases:["growth percentile","growth_percentile"]},{key:"domain_number",label:"Number RIT",aliases:["number","number rit","number and operations"]},{key:"domain_algebra",label:"Algebra RIT",aliases:["algebra","algebra rit","operations and algebraic thinking"]},{key:"domain_functions",label:"Functions RIT",aliases:["functions","functions rit"]},{key:"domain_geometry",label:"Geometry RIT",aliases:["geometry","geometry rit"]},{key:"domain_data",label:"Data / statistics RIT",aliases:["data","data rit","statistics","statistics and probability"]}],defaults:{season:"spring"}},
    myp:{endpoint:"/myp/import",fields:[{key:"identifier",label:"Student identifier",aliases:["student id","student_id","school id","external id","student number","id","username","email"]},{key:"evidence_date",label:"Evidence date",aliases:["evidence date","date","evidence_date"]},{key:"criterion_a",label:"Criterion A",aliases:["criterion a","criterion_a","a"]},{key:"criterion_b",label:"Criterion B",aliases:["criterion b","criterion_b","b"]},{key:"criterion_c",label:"Criterion C",aliases:["criterion c","criterion_c","c"]},{key:"criterion_d",label:"Criterion D",aliases:["criterion d","criterion_d","d"]},{key:"source_title",label:"Source title",aliases:["source","task","assessment","source title"]},{key:"notes",label:"Notes",aliases:["notes","comment"]}],defaults:{evidence_date:today()}},
    outcomes:{endpoint:"/outcomes/import",fields:[{key:"identifier",label:"Student identifier",aliases:["student id","student_id","school id","external id","student number","id","username","email"]},{key:"pathway",label:"IB pathway",aliases:["pathway","course","ib math course"]},{key:"academic_year",label:"Academic year",aliases:["academic year","academic_year","year"]},{key:"final_grade",label:"Final IB grade",aliases:["final grade","ib grade","grade","final_grade"]},{key:"outcome_date",label:"Outcome date",aliases:["outcome date","date","outcome_date"]},{key:"course_completed",label:"Course completed",aliases:["completed","course completed"]},{key:"source_note",label:"Source note",aliases:["source note","notes","source"]}],defaults:{course_completed:"true"}},
  };
  const importState={map:null,myp:null,outcomes:null};
  function parseCSV(text){const rows=[];let row=[],field="",quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(quoted){if(ch==='"'&&next==='"'){field+='"';i++;}else if(ch==='"')quoted=false;else field+=ch;}else if(ch==='"')quoted=true;else if(ch===','){row.push(field);field="";}else if(ch==='\n'){row.push(field);rows.push(row);row=[];field="";}else if(ch!=='\r')field+=ch;}row.push(field);if(row.some(value=>safeText(value).trim()))rows.push(row);if(!rows.length)return{headers:[],rows:[]};const headers=rows.shift().map((h,index)=>safeText(h).trim()||`Column ${index+1}`);return{headers,rows:rows.filter(r=>r.some(v=>safeText(v).trim())).map(values=>Object.fromEntries(headers.map((h,i)=>[h,safeText(values[i]??"").trim()])))};}
  const normalHeader=value=>safeText(value).trim().toLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," ");
  function autoHeader(headers,aliases){const normalized=new Map(headers.map(h=>[normalHeader(h),h]));for(const alias of aliases||[]){if(normalized.has(normalHeader(alias)))return normalized.get(normalHeader(alias));}for(const h of headers){const nh=normalHeader(h);if((aliases||[]).some(alias=>nh.includes(normalHeader(alias))))return h;}return"";}
  function guessIdentifierType(header){const h=normalHeader(header);if(h.includes("email"))return"email";if(h.includes("user"))return"username";if(h==="id"||h.includes("uuid"))return"id";return"external_id";}
  async function prepareImport(type){const fileInput=$(type==="map"?"#mapFile":type==="myp"?"#mypFile":"#outcomeFile");const file=fileInput?.files?.[0];if(!file)return notice("Choose a CSV file first.","warning");const parsed=parseCSV(await file.text());if(!parsed.headers.length||!parsed.rows.length)return notice("The CSV file contains no usable rows.","error");const config=CSV_CONFIG[type];const mapping={};for(const field of config.fields)mapping[field.key]=autoHeader(parsed.headers,field.aliases);const identifierType=guessIdentifierType(mapping.identifier);importState[type]={file,parsed,mapping,identifierType,defaults:{...config.defaults}};renderImportWorkspace(type);}
  function renderImportWorkspace(type){const item=importState[type],config=CSV_CONFIG[type],host=$(type==="map"?"#mapImportWorkspace":type==="myp"?"#mypImportWorkspace":"#outcomeImportWorkspace");if(!item||!host)return;host.className="mappingWorkspace";host.innerHTML=`<div class="mappingGrid"><div class="iControl"><label>Identifier type</label><select data-identity-type="${type}">${["external_id","username","email","id"].map(value=>`<option value="${value}" ${item.identifierType===value?"selected":""}>${value}</option>`).join("")}</select></div>${config.fields.map(field=>`<div class="iControl"><label>${esc(field.label)}</label><select data-map-type="${type}" data-map-key="${field.key}"><option value="">${config.defaults[field.key]!==undefined?`Use default: ${esc(config.defaults[field.key])}`:"Not mapped"}</option>${item.parsed.headers.map(header=>`<option value="${esc(header)}" ${item.mapping[field.key]===header?"selected":""}>${esc(header)}</option>`).join("")}</select></div>`).join("")}</div><div class="mappingPreview">${previewTable(item.parsed.headers,item.parsed.rows.slice(0,5))}</div><div class="mappingFooter"><small>${item.parsed.rows.length} rows detected. Review the identifier and score mappings before import.</small><button class="iButton" type="button" data-run-import="${type}">Import ${type==="map"?"MAP":type==="myp"?"MYP":"outcome"} evidence</button></div>`;}
  function previewTable(headers,rows){return `<table><thead><tr>${headers.slice(0,12).map(h=>`<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.map(row=>`<tr>${headers.slice(0,12).map(h=>`<td>${esc(row[h])}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
  function mappedValue(item,key,row){const header=item.mapping[key];const value=header?row[header]:"";return value!==""?value:item.defaults[key]??"";}
  function normalizeImportRows(type){const item=importState[type];if(!item)return[];return item.parsed.rows.map(row=>{const identifier=mappedValue(item,"identifier",row);if(type==="map")return{identifier_type:item.identifierType,identifier,test_date:mappedValue(item,"test_date",row),season:mappedValue(item,"season",row),grade:mappedValue(item,"grade",row),overall_rit:mappedValue(item,"overall_rit",row),percentile:mappedValue(item,"percentile",row),growth_percentile:mappedValue(item,"growth_percentile",row),domains:{number:mappedValue(item,"domain_number",row),algebra:mappedValue(item,"domain_algebra",row),functions:mappedValue(item,"domain_functions",row),geometry:mappedValue(item,"domain_geometry",row),data:mappedValue(item,"domain_data",row)}};if(type==="myp")return{identifier_type:item.identifierType,identifier,evidence_date:mappedValue(item,"evidence_date",row),criterion_a:mappedValue(item,"criterion_a",row),criterion_b:mappedValue(item,"criterion_b",row),criterion_c:mappedValue(item,"criterion_c",row),criterion_d:mappedValue(item,"criterion_d",row),source_title:mappedValue(item,"source_title",row),notes:mappedValue(item,"notes",row)};return{identifier_type:item.identifierType,identifier,pathway:mappedValue(item,"pathway",row),academic_year:mappedValue(item,"academic_year",row),final_grade:mappedValue(item,"final_grade",row),outcome_date:mappedValue(item,"outcome_date",row),course_completed:mappedValue(item,"course_completed",row),source_note:mappedValue(item,"source_note",row)}});}
  async function runImport(type){const item=importState[type];if(!item)return;const rows=normalizeImportRows(type);if(!item.mapping.identifier)return notice("Map a student identifier column before importing.","error");const button=$(`[data-run-import='${type}']`);button.disabled=true;try{const result=await api(CSV_CONFIG[type].endpoint,{method:"POST",body:{file_name:item.file.name,headers:item.parsed.headers,rows}});if(result.rejected?.length){notice(`${result.matched} rows imported; ${result.rejected.length} rejected. First reasons: ${result.rejected.slice(0,3).map(r=>`row ${r.row} ${r.reason}`).join(", ")}.`,"warning",0)}else notice(`${result.matched} rows imported successfully.`,"success");if(type!=="outcomes"&&result.matched_student_ids?.length&&!state.demo){for(let i=0;i<result.matched_student_ids.length;i+=100)await api("/recompute",{method:"POST",body:{student_ids:result.matched_student_ids.slice(i,i+100)}});await loadOverview()}if(type==="outcomes")await loadValidation();}catch(error){notice(`Import failed: ${errorMessage(error)}`,"error",0)}finally{button.disabled=false}}

  function openMypDialog(){if(!state.studentId)return notice("Choose a student first.","warning");$("#mypEvidenceTitle").textContent=`Add MYP evidence · ${state.student?.student?.display_name||"student"}`;$("#mypDate").value=today();$("#mypSource").value="";for(const id of ["criterionA","criterionB","criterionC","criterionD"])$("#"+id).value="";$("#mypNotes").value="";$("#mypEvidenceDialog").showModal();}
  async function saveMypEvidence(event){event.preventDefault();const payload={student_id:state.studentId,evidence_date:$("#mypDate").value,source_title:$("#mypSource").value,notes:$("#mypNotes").value};for(const [key,id] of [["criterion_a","criterionA"],["criterion_b","criterionB"],["criterion_c","criterionC"],["criterion_d","criterionD"]]){const value=$("#"+id).value;if(value!=="")payload[key]=Number(value)}if(!["criterion_a","criterion_b","criterion_c","criterion_d"].some(key=>payload[key]!==undefined))return notice("Enter at least one MYP criterion score.","warning");try{await api("/myp/evidence",{method:"POST",body:payload});$("#mypEvidenceDialog").close();await openStudent(state.studentId,false);await loadOverview();notice("MYP evidence saved and readiness recalculated.","success");}catch(error){notice(`Could not save MYP evidence: ${errorMessage(error)}`,"error")}}

  async function loadSchools(){if(!["admin","demo"].includes(state.demo?"demo":state.account?.role))return;try{const result=await api("/schools");state.schools=result.schools||[];renderSchoolDirectory();}catch(error){notice(`Could not load school directory: ${errorMessage(error)}`,"error")}}
  function renderSchoolDirectory(){const list=$("#schoolDirectory"),select=$("#assignmentSchool");if(list)list.innerHTML=state.schools.map(school=>`<span class="schoolDirectoryItem"><strong>${esc(school.code)}</strong>${esc(school.name)}</span>`).join("");if(select){const current=select.value;select.innerHTML='<option value="">Choose school</option>'+state.schools.filter(s=>s.status!=="archived").map(s=>`<option value="${esc(s.id)}">${esc(s.name)} · ${esc(s.code)}</option>`).join("");if(state.schools.some(s=>s.id===current))select.value=current;}}
  async function createSchool(){const name=$("#newSchoolName").value.trim(),code=$("#newSchoolCode").value.trim();if(!name)return notice("Enter a school name.","warning");const button=$("#createSchool");button.disabled=true;try{const result=await api("/schools",{method:"POST",body:{name,code}});state.schools.push(result.school);$("#newSchoolName").value="";$("#newSchoolCode").value="";renderSchoolDirectory();notice(`${result.school.name} added to the readiness network.`,"success");}catch(error){notice(`Could not create school: ${errorMessage(error)}`,"error")}finally{button.disabled=false}}
  async function assignFilteredSchool(){const schoolId=$("#assignmentSchool").value,year=$("#assignmentYear").value.trim()||"2026-2027",ids=state.filteredRows.map(row=>row.id);if(!schoolId)return notice("Choose a school for assignment.","warning");if(!ids.length)return notice("No filtered learners are available to assign.","warning");if(ids.length>1000)return notice("Filter the cohort to 1,000 learners or fewer before assigning a school.","warning");if(!confirm(`Assign ${ids.length} currently filtered learner(s) to this school for ${year}?`))return;const button=$("#assignFilteredSchool");button.disabled=true;try{const result=await api("/schools/assign",{method:"POST",body:{school_id:schoolId,student_ids:ids,academic_year:year}});notice(`${result.assigned} learner(s) assigned.`,"success");await loadOverview();await loadSchools();}catch(error){notice(`School assignment failed: ${errorMessage(error)}`,"error")}finally{button.disabled=false}}

  async function loadModel(){try{const result=await api("/model");state.model=result.model;const effective=result.model?.effective_configuration||result.default_model||result.model?.configuration||{};$("#modelVersion").textContent=`Version ${result.model?.version??0}`;$("#modelName").value=result.model?.name||"";$("#modelNotes").value=result.model?.notes||"";$("#modelJson").value=JSON.stringify(effective,null,2);syncModelEditors(effective);await loadValidation();}catch(error){notice(`Could not load readiness model: ${errorMessage(error)}`,"error",0)}}
  function syncModelEditors(config){$("#weightMap").value=config.layer_weights?.map??.4;$("#weightMyp").value=config.layer_weights?.myp??.3;$("#weightDiagnostic").value=config.layer_weights?.diagnostic??.3;$("#thresholdStrong").value=config.thresholds?.strong??80;$("#thresholdOnTrack").value=config.thresholds?.on_track??70;$("#thresholdDeveloping").value=config.thresholds?.developing??55;updateWeightTotal();}
  function updateWeightTotal(){const total=["#weightMap","#weightMyp","#weightDiagnostic"].reduce((sum,id)=>sum+Number($(id).value||0),0);$("#weightTotal").textContent=`Total: ${total.toFixed(2)}${Math.abs(total-1)<.001?" ✓":" · should normally equal 1.00"}`;}
  function applyEditorToJson(){let config;try{config=JSON.parse($("#modelJson").value||"{}")}catch{return}config.layer_weights={...(config.layer_weights||{}),map:Number($("#weightMap").value),myp:Number($("#weightMyp").value),diagnostic:Number($("#weightDiagnostic").value)};config.thresholds={...(config.thresholds||{}),strong:Number($("#thresholdStrong").value),on_track:Number($("#thresholdOnTrack").value),developing:Number($("#thresholdDeveloping").value)};$("#modelJson").value=JSON.stringify(config,null,2);updateWeightTotal();}
  async function saveModel(){let configuration;try{configuration=JSON.parse($("#modelJson").value)}catch(error){return notice(`Model JSON is invalid: ${errorMessage(error)}`,"error")};const total=Number(configuration.layer_weights?.map||0)+Number(configuration.layer_weights?.myp||0)+Number(configuration.layer_weights?.diagnostic||0);if(total<=0)return notice("At least one evidence layer must have a positive weight.","error");if(!confirm("Activate this as a new institution-wide readiness model version? Existing historical snapshots will remain unchanged until recomputed."))return;const button=$("#saveModel");button.disabled=true;try{const result=await api("/model",{method:"PUT",body:{configuration,name:$("#modelName").value,notes:$("#modelNotes").value}});state.model=result.model;$("#modelVersion").textContent=`Version ${result.model.version}`;notice(`Model version ${result.model.version} activated. Recompute profiles to apply it.`,"success",0)}catch(error){notice(`Model activation failed: ${errorMessage(error)}`,"error",0)}finally{button.disabled=false}}
  async function loadValidation(){try{state.validation=await api("/validation");renderValidation()}catch(error){notice(`Validation could not be loaded: ${errorMessage(error)}`,"error")}}
  function renderValidation(){const s=state.validation?.summary||{};const entries=[['Linked outcomes',s.n??0,'completed DP records linked to prior snapshots'],['Correlation',Number.isFinite(Number(s.correlation_readiness_to_grade))?Number(s.correlation_readiness_to_grade).toFixed(2):'—','Pearson r: readiness index vs final grade'],['Accuracy',Number.isFinite(Number(s.accuracy))?pct(Number(s.accuracy)*100):'—','At the On track threshold'],['Sensitivity',Number.isFinite(Number(s.sensitivity))?pct(Number(s.sensitivity)*100):'—','Successful students flagged on track'],['Specificity',Number.isFinite(Number(s.specificity))?pct(Number(s.specificity)*100):'—','Below-success students below threshold']];$("#validationMetrics").innerHTML=entries.map(([label,value,note])=>`<article class="validationMetric"><small>${esc(label)}</small><strong>${esc(value)}</strong><span>${esc(note)}</span></article>`).join("");const bands=Array.isArray(s.bands)?s.bands:[];$("#validationBands").innerHTML=bands.length?bands.map(data=>`<article class="validationBand"><b>${esc(data.band)}</b><strong>${Number.isFinite(Number(data.observed_success_rate))?pct(Number(data.observed_success_rate)*100):"—"} observed success</strong><small>n=${data.n??0} · avg grade ${Number.isFinite(Number(data.average_final_grade))?Number(data.average_final_grade).toFixed(1):"—"} · success defined as grade ${s.success_grade??5}+</small></article>`).join(""):'<article class="validationBand"><b>No linked outcomes yet</b><small>Import completed DP Mathematics outcomes to begin local validation. Predictive claims should not be made before sufficient evidence exists.</small></article>';if(s.warning)notice(s.warning,state.demo?"warning":"info",0);}

  function exportCohort(){const headers=["student_name","student_id","grade","evidence_status","preferred_pathway","aa_hl_index","aa_hl_band","aa_sl_index","aa_sl_band","ai_hl_index","ai_hl_band","ai_sl_index","ai_sl_band"];const rows=state.filteredRows.map(row=>[row.display_name,row.external_id||row.username,row.grade,evidenceStatus(row),row.preferred_pathway||"",...PATH_ORDER.flatMap(path=>[row.pathways?.[path]?.readiness_index??"",row.pathways?.[path]?.band??""])]);downloadCSV("ib-math-readiness-cohort.csv",headers,rows)}
  function downloadCSV(filename,headers,rows){const quote=value=>`"${safeText(value).replaceAll('"','""')}"`;const text=[headers,...rows].map(row=>row.map(quote).join(",")).join("\r\n");const blob=new Blob([text],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}

  function bind(){
    setupMenu();$$(".readinessNavButton").forEach(button=>button.addEventListener("click",()=>setView(button.dataset.view)));$$("[data-go-view]").forEach(button=>button.addEventListener("click",()=>setView(button.dataset.goView)));$$("[data-close-dialog]").forEach(button=>button.addEventListener("click",()=>button.closest("dialog")?.close()));
    $("#openMethodology").addEventListener("click",()=>$("#methodologyDialog").showModal());$("#jumpCohort").addEventListener("click",()=>$("#cohortSection").scrollIntoView({behavior:"smooth"}));$("#jumpGaps").addEventListener("click",()=>$("#gapSection").scrollIntoView({behavior:"smooth"}));
    for(const id of ["studentSearch","evidenceFilter","pathwayFilter","schoolFilter","classFilter"])$("#"+id).addEventListener(id==="studentSearch"?"input":"change",filterRows);$("#exportCohort").addEventListener("click",exportCohort);$("#recomputeVisible").addEventListener("click",recomputeVisible);
    $("#cohortRows").addEventListener("click",event=>{const id=event.target.closest("[data-open-student]")?.dataset.openStudent||event.target.closest("[data-student-row]")?.dataset.studentRow;if(id)openStudent(id)});$("#preferredPathway").addEventListener("change",savePreference);$("#trajectoryPathway").addEventListener("change",event=>{renderTrajectory(event.target.value);renderSkillProfile(event.target.value)});$("#recomputeStudent").addEventListener("click",recomputeStudent);$("#studentInterventions").addEventListener("click",event=>{const button=event.target.closest("[data-intervention]");if(button)updateIntervention(button.dataset.intervention,button.dataset.status)});$("#openMypEvidence").addEventListener("click",openMypDialog);$("#mypEvidenceForm").addEventListener("submit",saveMypEvidence);
    $("#loadDiagnostic").addEventListener("click",loadDiagnostic);$("#diagnosticForm").addEventListener("change",updateDiagnosticProgress);$("#diagnosticForm").addEventListener("submit",submitDiagnostic);
    $("#createSchool").addEventListener("click",createSchool);$("#assignFilteredSchool").addEventListener("click",assignFilteredSchool);$("#prepareMap").addEventListener("click",()=>prepareImport("map"));$("#prepareMyp").addEventListener("click",()=>prepareImport("myp"));$("#prepareOutcomes").addEventListener("click",()=>prepareImport("outcomes"));document.addEventListener("change",event=>{const select=event.target.closest("[data-map-type]");if(select){const item=importState[select.dataset.mapType];if(item)item.mapping[select.dataset.mapKey]=select.value;}const identity=event.target.closest("[data-identity-type]");if(identity){const item=importState[identity.dataset.identityType];if(item)item.identifierType=identity.value;}});document.addEventListener("click",event=>{const button=event.target.closest("[data-run-import]");if(button)runImport(button.dataset.runImport)});
    for(const id of ["weightMap","weightMyp","weightDiagnostic","thresholdStrong","thresholdOnTrack","thresholdDeveloping"])$("#"+id).addEventListener("change",applyEditorToJson);$("#saveModel").addEventListener("click",saveModel);$("#refreshValidation").addEventListener("click",loadValidation);
  }

  async function initialise(){
    bind();try{
      if(state.demo){state.account={id:"demo",role:"demo",display_name:"Synthetic Demo",username:"demo"};$("#demoBanner").classList.remove("hidden");}
      else{if(!window.ECHSInstitution)throw new Error("Institutional session client is unavailable.");state.account=await window.ECHSInstitution.requireAuth();if(!state.account)return;}
      setRoleVisibility();await loadOverview();if(["admin","demo"].includes(state.account.role)){loadSchools();loadModel();}$("#readinessApp").hidden=false;$("#appLoading").remove();
      if(state.demo)notice("Demonstration mode uses synthetic learner records and synthetic validation outcomes only.","warning",0);
    }catch(error){$("#appLoading").innerHTML=`<strong>Readiness system could not start.</strong><span>${esc(errorMessage(error))}</span>`;}
  }
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initialise,{once:true});else initialise();
})();
