import { createClient } from "npm:@supabase/supabase-js@2";

type Role="admin"|"teacher"|"student"|"parent";type Account={account_id:string;organization_id:string;role:Role};
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")??"",SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const ALLOWED_ORIGINS=(Deno.env.get("ALLOWED_ORIGINS")??"https://2ed944-cloud.github.io,http://localhost:4173,http://127.0.0.1:4173").split(",").map(v=>v.trim()).filter(Boolean);
const db=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}}),BUCKET="teacher-upload-staging",MAX_BYTES=150*1024*1024,CHUNK_BYTES=40*1024*1024;
const TERMINAL=["completed","failed","cancelled"],ACTIVE=["queued","processing","pr-opened","completed"];
function headers(req:Request):HeadersInit{const origin=req.headers.get("origin")??"",allowed=ALLOWED_ORIGINS.includes(origin)?origin:ALLOWED_ORIGINS[0]??"";return{"access-control-allow-origin":allowed,"access-control-allow-headers":"authorization, content-type, x-upsert","access-control-allow-methods":"GET, POST, PATCH, DELETE, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff","vary":"Origin"}}
function reply(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:headers(req)})}function fail(req:Request,message:string,status=400,code="request_error"){return reply(req,{ok:false,error:{code,message}},status)}
async function hash(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function account(req:Request):Promise<Account|null>{const h=req.headers.get("authorization")??"",token=h.startsWith("Bearer ")?h.slice(7).trim():"";if(!token)return null;const{data,error}=await db.rpc("api_session_lookup",{p_token_hash:await hash(token)});if(error)throw error;return Array.isArray(data)&&data[0]?data[0] as Account:null}
function staff(v:Account|null):v is Account{return Boolean(v&&(v.role==="teacher"||v.role==="admin"))}function cleanName(v:string){return v.replace(/[^A-Za-z0-9._-]+/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"").slice(0,180)}function validSha(v:string){return/^[0-9a-f]{64}$/.test(v)}function validKind(v:string){return v==="private-bank"||v==="course-release"}function validCourse(v:string){return!v||["ap-precalculus","ib-math-ai","ap-calculus","algebra-2","grade-9"].includes(v)}
async function signed(path:string){const{data,error}=await db.storage.from(BUCKET).createSignedUploadUrl(path,{upsert:true});if(error)throw error;return{token:data.token,path:data.path,signed_url:data.signedUrl}}
function chunkMeta(base:string,size:number){const count=Math.ceil(size/CHUNK_BYTES),parts=Array.from({length:count},(_,i)=>({index:i,start:i*CHUNK_BYTES,end:Math.min(size,(i+1)*CHUNK_BYTES),path:`${base}.part-${String(i+1).padStart(3,"0")}`}));return{upload_mode:"chunked",chunk_size:CHUNK_BYTES,chunk_count:count,part_paths:parts.map(p=>p.path),parts}}
async function uploadPlan(meta:any){const uploads=[];for(const p of meta.parts){uploads.push({...await signed(p.path),index:p.index,start:p.start,end:p.end,total:meta.chunk_count,name:p.path.split("/").pop()})}return uploads}
async function removePaths(row:any){const staging=row?.result?.staging,paths=staging?.upload_mode==="chunked"?staging.part_paths:[row.object_path];const filtered=(paths??[]).map(String).filter(Boolean);if(filtered.length){const{error}=await db.storage.from(BUCKET).remove(filtered);if(error)throw error}}
async function createUpload(req:Request,current:Account){const body=await req.json() as any,kind=String(body.kind??""),filename=cleanName(String(body.filename??"")),size=Number(body.size??0),sha256=String(body.sha256??"").toLowerCase(),courseKey=String(body.course_key??"").trim(),unitKey=String(body.unit_key??"").trim();if(!validKind(kind))return fail(req,"Choose a supported upload type",400,"invalid_kind");if(!filename.toLowerCase().endsWith(".zip"))return fail(req,"Only ZIP packages are accepted",400,"invalid_file");if(!Number.isFinite(size)||size<=0||size>MAX_BYTES)return fail(req,"ZIP file must be between 1 byte and 150 MB",400,"invalid_size");if(!validSha(sha256))return fail(req,"A valid SHA-256 fingerprint is required",400,"invalid_sha256");if(!validCourse(courseKey))return fail(req,"Unsupported course",400,"invalid_course");if(kind==="course-release"&&(!courseKey||!unitKey))return fail(req,"Course and unit are required for a course release",400,"missing_release_scope");
 const{data:existing,error:existingError}=await db.from("teacher_upload_requests").select("*").eq("organization_id",current.organization_id).eq("sha256",sha256).eq("upload_kind",kind).maybeSingle();if(existingError)throw existingError;if(existing&&ACTIVE.includes(String(existing.status)))return reply(req,{ok:true,duplicate:true,request:existing});
 const requestId=existing?.id??crypto.randomUUID(),basePath=existing?.object_path??`${current.organization_id}/${requestId}/${filename}`,meta=chunkMeta(basePath,size),values={requested_by:current.account_id,course_key:courseKey||null,unit_key:unitKey||null,original_filename:filename,object_path:basePath,file_size_bytes:Math.floor(size),sha256,status:"created",progress:2,stage:`Secure upload prepared · ${meta.chunk_count} part${meta.chunk_count===1?"":"s"}`,result:{staging:meta},error_message:null,github_pr_url:null,started_at:null,completed_at:null,updated_at:new Date().toISOString()};let row:any;
 if(existing){await removePaths(existing);const{data,error}=await db.from("teacher_upload_requests").update(values).eq("id",requestId).eq("organization_id",current.organization_id).select("*").single();if(error)throw error;row=data}else{const{data,error}=await db.from("teacher_upload_requests").insert({id:requestId,organization_id:current.organization_id,upload_kind:kind,...values}).select("*").single();if(error)throw error;row=data}
 try{return reply(req,{ok:true,duplicate:false,retry:Boolean(existing),request:row,uploads:await uploadPlan(meta),chunk_size:CHUNK_BYTES})}catch(error){await db.from("teacher_upload_requests").update({status:"failed",progress:0,stage:"Could not create chunk upload URLs",error_message:error instanceof Error?error.message:String(error),completed_at:new Date().toISOString()}).eq("id",requestId);throw error}}
async function completeUpload(req:Request,current:Account,id:string){const{data:row,error}=await db.from("teacher_upload_requests").select("*").eq("id",id).eq("organization_id",current.organization_id).maybeSingle();if(error)throw error;if(!row)return fail(req,"Upload request not found",404,"not_found");if(["queued","processing","pr-opened","completed"].includes(row.status))return reply(req,{ok:true,request:row});const staging=row.result?.staging;if(!staging||staging.upload_mode!=="chunked")return fail(req,"Upload metadata is missing; retry the package",409,"missing_chunk_plan");let total=0;for(let i=0;i<staging.part_paths.length;i++){const path=String(staging.part_paths[i]),parts=path.split("/"),name=parts.pop()??"",folder=parts.join("/");const{data:objects,error:listError}=await db.storage.from(BUCKET).list(folder,{search:name,limit:5});if(listError)throw listError;const object=(objects??[]).find(item=>item.name===name);if(!object)return fail(req,`Upload part ${i+1} of ${staging.chunk_count} is incomplete`,409,"upload_incomplete");const actual=Number(object.metadata?.size??0),expected=Math.min(CHUNK_BYTES,Number(row.file_size_bytes)-i*CHUNK_BYTES);if(actual&&actual!==expected)return fail(req,`Upload part ${i+1} has the wrong size`,409,"size_mismatch");total+=actual||expected}if(total!==Number(row.file_size_bytes))return fail(req,"Uploaded parts do not match the selected ZIP size",409,"size_mismatch");const{data:updated,error:updateError}=await db.from("teacher_upload_requests").update({status:"queued",progress:12,stage:`${staging.chunk_count} parts uploaded securely · waiting for processing`,updated_at:new Date().toISOString(),error_message:null,completed_at:null}).eq("id",id).eq("organization_id",current.organization_id).select("*").single();if(updateError)throw updateError;return reply(req,{ok:true,request:updated})}
async function listRequests(req:Request,current:Account,url:URL){const limit=Math.min(50,Math.max(1,Number.parseInt(url.searchParams.get("limit")??"20",10)||20));const{data,error}=await db.from("teacher_upload_requests").select("id,upload_kind,course_key,unit_key,original_filename,file_size_bytes,sha256,status,progress,stage,result,error_message,github_pr_url,created_at,updated_at,completed_at").eq("organization_id",current.organization_id).order("created_at",{ascending:false}).limit(limit);if(error)throw error;return reply(req,{ok:true,requests:data??[]})}
async function detail(req:Request,current:Account,id:string){const{data,error}=await db.from("teacher_upload_requests").select("*").eq("id",id).eq("organization_id",current.organization_id).maybeSingle();if(error)throw error;if(!data)return fail(req,"Upload request not found",404,"not_found");return reply(req,{ok:true,request:data})}
async function cancel(req:Request,current:Account,id:string){const{data:row,error}=await db.from("teacher_upload_requests").select("*").eq("id",id).eq("organization_id",current.organization_id).maybeSingle();if(error)throw error;if(!row)return fail(req,"Upload request not found",404,"not_found");if(["processing","pr-opened","completed"].includes(row.status))return fail(req,"This request can no longer be cancelled",409,"already_processing");await removePaths(row);const{data,error:updateError}=await db.from("teacher_upload_requests").update({status:"cancelled",progress:0,stage:"Cancelled",completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id).select("*").single();if(updateError)throw updateError;return reply(req,{ok:true,request:data})}
async function deleteOne(req:Request,current:Account,id:string){const{data:row,error}=await db.from("teacher_upload_requests").select("*").eq("id",id).eq("organization_id",current.organization_id).maybeSingle();if(error)throw error;if(!row)return fail(req,"Upload request not found",404,"not_found");if(!TERMINAL.includes(String(row.status)))return fail(req,"Only completed, failed, or cancelled requests can be removed",409,"request_not_terminal");await removePaths(row);const{error:deleteError}=await db.from("teacher_upload_requests").delete().eq("id",id).eq("organization_id",current.organization_id);if(deleteError)throw deleteError;return reply(req,{ok:true,deleted:id})}
async function clearTerminal(req:Request,current:Account){const{data:rows,error}=await db.from("teacher_upload_requests").select("*").eq("organization_id",current.organization_id).in("status",TERMINAL);if(error)throw error;for(const row of rows??[])await removePaths(row);const ids=(rows??[]).map(r=>String(r.id));if(ids.length){const{error:deleteError}=await db.from("teacher_upload_requests").delete().eq("organization_id",current.organization_id).in("id",ids);if(deleteError)throw deleteError}return reply(req,{ok:true,deleted:ids.length})}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:headers(req)});const url=new URL(req.url),path=url.pathname.split("/upload-manager-api")[1]||"/";try{if(path==="/health"&&req.method==="GET")return reply(req,{ok:true,service:"echs-upload-manager-api",version:"1.3.0-free-tier-chunked",chunk_bytes:CHUNK_BYTES,max_bytes:MAX_BYTES});const current=await account(req);if(!staff(current))return fail(req,"Teacher or administrator sign-in is required",403,"forbidden");if(path==="/requests"&&req.method==="GET")return await listRequests(req,current,url);if(path==="/requests"&&req.method==="POST")return await createUpload(req,current);if(path==="/requests/terminal"&&req.method==="DELETE")return await clearTerminal(req,current);const m=path.match(/^\/requests\/([0-9a-f-]{36})$/);if(m&&req.method==="GET")return await detail(req,current,m[1]);if(m&&req.method==="DELETE")return await deleteOne(req,current,m[1]);const c=path.match(/^\/requests\/([0-9a-f-]{36})\/complete$/);if(c&&req.method==="POST")return await completeUpload(req,current,c[1]);const x=path.match(/^\/requests\/([0-9a-f-]{36})\/cancel$/);if(x&&req.method==="POST")return await cancel(req,current,x[1]);return fail(req,"Route not found",404,"not_found")}catch(error){console.error(error);return fail(req,error instanceof Error?error.message:"Unexpected upload manager error",400)}});
