const X={mode:document.getElementById('mode'),year:document.getElementById('year'),unit:document.getElementById('unit'),topic:document.getElementById('topic'),mcq:document.getElementById('mcqCount'),frq:document.getElementById('frqCount'),minutes:document.getElementById('minutes'),order:document.getElementById('order'),content:document.getElementById('contentScope'),build:document.getElementById('buildExam'),info:document.getElementById('examInfo'),builder:document.getElementById('builder'),area:document.getElementById('examArea')};
let rows=[],exam=[],questions=[],idx=0,responses={},flags=new Set(),remaining=0,timer=null,submitted=false;
function option(v,l){return`<option value="${ECHSOfficial.esc(v)}">${ECHSOfficial.esc(l)}</option>`}
function setup(){const c=ECHSOfficial.catalog;X.year.innerHTML=option('all','Choose year')+Object.keys(c.years).map(y=>option(y,`${y} (${c.years[y].total})`)).join('');X.unit.innerHTML=option('all','Choose unit')+Object.keys(c.units).sort((a,b)=>Number(a)-Number(b)).map(u=>option(u,`Unit ${u} (${c.units[u]})`)).join('');const p=ECHSOfficial.params();if(p.get('mode'))X.mode.value=p.get('mode');if(p.get('year'))X.year.value=p.get('year');if(p.get('unit'))X.unit.value=p.get('unit');updatePreset();X.mode.onchange=updatePreset;X.build.onclick=buildExam}
function updatePreset(){const m=X.mode.value;if(m==='full-ab'){X.mcq.value=45;X.frq.value=6;X.minutes.value=195}if(m==='full-bc'){X.mcq.value=45;X.frq.value=6;X.minutes.value=195}if(m==='year'){X.mcq.value=45;X.frq.value=6;X.minutes.value=195}if(m==='unit'){X.mcq.value=20;X.frq.value=2;X.minutes.value=60}if(m==='topic'){X.mcq.value=10;X.frq.value=1;X.minutes.value=35}if(m==='custom'){X.mcq.value=20;X.frq.value=2;X.minutes.value=60}X.info.innerHTML=`<span class="pill teal">${X.mcq.value} MCQ</span><span class="pill wine">${X.frq.value} FRQ</span><span class="pill gold">${X.minutes.value} minutes</span>`}
function sourceRows(){let r=[...rows],m=X.mode.value;if(m==='full-ab')r=r.filter(x=>x.course.includes('AB')||x.courseId==='ap-calculus-ab');if(m==='full-bc')r=r.filter(x=>x.course.includes('BC')||x.courseId==='ap-calculus-bc');if(m==='year')r=r.filter(x=>String(x.year)===X.year.value);if(m==='unit')r=r.filter(x=>String(x.unit)===X.unit.value);if(m==='topic'){const q=X.topic.value.toLowerCase();r=r.filter(x=>x.search.includes(q))}if(X.content?.value==='complete')r=r.filter(x=>x.contentStatus==='complete');if(X.content?.value==='indexed')r=r.filter(x=>x.contentStatus==='indexed-only');return r}
function pick(pool,type,count){let a=pool.filter(x=>x.type===type);if(X.order.value==='source')a.sort((x,y)=>(x.year||9999)-(y.year||9999)||String(x.number).localeCompare(String(y.number),undefined,{numeric:true}));else a=ECHSOfficial.shuffle(a);return a.slice(0,Math.min(count,a.length))}
async function buildExam(){const pool=sourceRows(),mcq=pick(pool,'mcq',Number(X.mcq.value)),frq=pick(pool,'frq',Number(X.frq.value));exam=[...mcq,...frq];if(!exam.length){X.area.innerHTML='<div class="empty">No questions are available for this blueprint.</div>';return}questions=await ECHSOfficial.questions(exam.map(x=>x.id));idx=0;responses={};flags=new Set();submitted=false;remaining=Number(X.minutes.value)*60;X.builder.classList.add('hidden');renderExam();startTimer()}
function startTimer(){clearInterval(timer);timer=setInterval(()=>{remaining--;const el=document.getElementById('timer');if(el)el.textContent=formatTime(remaining);if(remaining<=0){clearInterval(timer);submitExam()}},1000)}
function formatTime(s){s=Math.max(0,s);return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function saveCurrent(q){if(q.type==='mcq'){const sel=document.querySelector('.choice.selected')?.dataset.choice;if(sel)responses[q.id]=sel}else{responses[q.id]=[...document.querySelectorAll('[data-part]')].map(x=>({part:x.dataset.part,text:x.value}))}}
function renderExam(){const q=questions[idx];X.area.innerHTML=`<section class="panel"><div class="toolbar"><div class="pillRow"><span class="timer" id="timer">${formatTime(remaining)}</span><span class="pill">${idx+1} of ${questions.length}</span><span class="pill ${flags.has(q.id)?'gold':''}">${flags.has(q.id)?'Flagged':'Not flagged'}</span></div><div class="buttonRow" style="margin:0"><button class="button ghost" id="flagBtn">${flags.has(q.id)?'Unflag':'Flag for review'}</button><button class="button wine" id="submitBtn">Submit Exam</button></div></div><div class="questionNav" id="questionNav">${questions.map((x,i)=>`<button class="${i===idx?'current':''} ${responses[x.id]?'answered':''} ${flags.has(x.id)?'flagged':''}" data-go="${i}">${i+1}</button>`).join('')}</div></section><article class="questionCard">${ECHSOfficial.metaPills(q)}<h2>${ECHSOfficial.esc(q.classification.primaryTopic||q.assessmentFamily)}</h2>${ECHSOfficial.renderPrompt(q)}${ECHSOfficial.renderChoices(q,responses[q.id],submitted)}${q.type==='frq'?ECHSOfficial.renderParts(q):''}<div class="questionFooter"><button class="button ghost" id="back" ${idx===0?'disabled':''}>Back</button><button class="button primary" id="next">${idx===questions.length-1?'Review':'Next'}</button></div></article>`;if(q.type==='frq'&&Array.isArray(responses[q.id])){const map=new Map(responses[q.id].map(x=>[x.part,x.text]));document.querySelectorAll('[data-part]').forEach(x=>x.value=map.get(x.dataset.part)||'')}wire(q);ECHSOfficial.renderMath(X.area)}
function wire(q){document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{if(submitted)return;document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');responses[q.id]=b.dataset.choice;refreshNav()});document.querySelectorAll('[data-part]').forEach(x=>x.oninput=()=>saveCurrent(q));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{saveCurrent(q);idx=Number(b.dataset.go);renderExam()});document.getElementById('flagBtn').onclick=()=>{flags.has(q.id)?flags.delete(q.id):flags.add(q.id);renderExam()};document.getElementById('submitBtn').onclick=submitExam;document.getElementById('back').onclick=()=>{saveCurrent(q);if(idx>0){idx--;renderExam()}};document.getElementById('next').onclick=()=>{saveCurrent(q);if(idx<questions.length-1){idx++;renderExam()}else reviewScreen()}}
function refreshNav(){document.querySelectorAll('[data-go]').forEach((b,i)=>b.classList.toggle('answered',Boolean(responses[questions[i].id])))}
function reviewScreen(){X.area.innerHTML=`<article class="questionCard"><div class="topicNo">Review before submission</div><h2>${Object.keys(responses).length} of ${questions.length} questions have a response</h2><p>${flags.size} questions are flagged. You can return to any question before submitting.</p><div class="questionNav">${questions.map((q,i)=>`<button class="${responses[q.id]?'answered':''} ${flags.has(q.id)?'flagged':''}" data-go="${i}">${i+1}</button>`).join('')}</div><div class="heroActions"><button class="button wine" id="finalSubmit">Submit now</button><button class="button ghost" id="returnExam">Return to exam</button></div></article>`;document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{idx=Number(b.dataset.go);renderExam()});document.getElementById('finalSubmit').onclick=submitExam;document.getElementById('returnExam').onclick=()=>renderExam()}
function submitExam(){if(submitted)return;submitted=true;clearInterval(timer);let mcqTotal=0,mcqCorrect=0;for(const q of questions){if(q.type==='mcq'&&!ECHSOfficial.isIndexedOnly(q)){mcqTotal++;const correct=ECHSOfficial.answerCorrect(q,responses[q.id]);if(correct)mcqCorrect++;ECHSOfficial.saveAttempt({id:q.id,correct,course:q.courseId,unit:q.classification.primaryUnit,topic:q.classification.primaryTopic,topicCode:q.classification.topicCode,year:q.year,type:q.type,hints:0,confidence:'exam',response:responses[q.id]||''})}}
const pct=mcqTotal?Math.round(mcqCorrect/mcqTotal*100):0;localStorage.setItem(ECHSOfficial.examKey,JSON.stringify({at:new Date().toISOString(),ids:questions.map(q=>q.id),responses,mcqCorrect,mcqTotal,pct}));X.area.innerHTML=`<article class="questionCard"><div class="topicNo">Exam submitted</div><h2>${mcqCorrect}/${mcqTotal} MCQ correct · ${pct}%</h2><p>FRQs require rubric-based self-scoring. Open each question below to compare your response with the scoring criteria.</p><div class="stats"><div class="stat"><b>${pct}%</b><span>MCQ score</span></div><div class="stat"><b>${questions.filter(q=>q.type==='frq').length}</b><span>FRQs to self-score</span></div><div class="stat"><b>${flags.size}</b><span>Flagged questions</span></div><div class="stat"><b>${formatTime(remaining)}</b><span>Time remaining</span></div></div><div class="tableWrap"><table class="dataTable"><thead><tr><th>#</th><th>Question</th><th>Your answer</th><th>Result</th><th>Review</th></tr></thead><tbody>${questions.map((q,i)=>`<tr><td>${i+1}</td><td>${ECHSOfficial.esc(ECHSOfficial.rowLabel(q))}</td><td>${ECHSOfficial.esc(q.type==='mcq'?(responses[q.id]||'—'):'Written response')}</td><td>${ECHSOfficial.isIndexedOnly(q)?'Indexed record':q.type==='mcq'?(ECHSOfficial.answerCorrect(q,responses[q.id])?'Correct':'Incorrect'):'Self-score'}</td><td><button class="button ghost" data-review="${i}">Open</button></td></tr>`).join('')}</tbody></table></div><div class="heroActions"><a class="button primary" href="dashboard.html">View dashboard</a><button class="button ghost" id="newExam">Build another exam</button></div></article>`;document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>reviewQuestion(Number(b.dataset.review)));document.getElementById('newExam').onclick=()=>location.reload();ECHSOfficial.renderMath(X.area)}
function reviewQuestion(i){const q=questions[i],resp=responses[q.id];const mcq=q.type==='mcq';X.area.innerHTML=`<article class="questionCard">${ECHSOfficial.metaPills(q)}<h2>${ECHSOfficial.esc(q.classification.primaryTopic)}</h2>${ECHSOfficial.renderPrompt(q)}${mcq?ECHSOfficial.renderChoices(q,resp,true):ECHSOfficial.renderParts(q)}<div class="feedback show ${mcq&&ECHSOfficial.answerCorrect(q,resp)?'good':'bad'}"><h3>${mcq?'Answer: '+ECHSOfficial.esc(q.answer):'Rubric and solution'}</h3><p>${ECHSOfficial.fmt(q.workedSolution||q.explanation||q.studentExplanation||'No solution available.')}</p>${!mcq?(q.parts||[]).map(p=>`<h3>${ECHSOfficial.esc(p.label)}</h3><p>${ECHSOfficial.fmt(p.answer)}</p>${p.rubric?.length?`<ul>${p.rubric.map(r=>`<li>${ECHSOfficial.fmt(r.description||r.evidenceRequired)}</li>`).join('')}</ul>`:''}`).join(''):''}</div><div class="questionFooter"><button class="button ghost" id="backResults">Back to results</button></div></article>`;document.getElementById('backResults').onclick=()=>submitExamResults();ECHSOfficial.renderMath(X.area)}
function submitExamResults(){submitted=false;submitExam()}
async function init(){await ECHSOfficial.init();rows=ECHSOfficial.index;setup()}
document.addEventListener('DOMContentLoaded',init);
