document.querySelector('.navLink[href="dashboard.html"]')?.classList.add('active');
const labels={"ap-calculus":"AP Calculus","ap-precalculus":"AP Precalculus","algebra-2":"Algebra 2 Concepts","ib-math-ai":"IB Math AI","grade-9":"Grade 9 Pre-Precalculus"};
function pct(rows){const c=rows.filter(x=>x.correct).length;return rows.length?Math.round(c/rows.length*100):0;}
function render(){
 const a=ECHSBank.getAttempts(),correct=a.filter(x=>x.correct).length,accuracy=a.length?Math.round(correct/a.length*100):0,unique=new Set(a.map(x=>x.id)).size;
 document.getElementById('metrics').innerHTML=`<div class="metric"><b>${a.length}</b><span>Total attempts</span></div><div class="metric"><b>${correct}</b><span>Correct</span></div><div class="metric"><b>${accuracy}%</b><span>Accuracy</span></div><div class="metric"><b>${unique}</b><span>Unique questions</span></div>`;
 const keys=[...new Set(a.map(x=>`${x.course||'unassigned'}|${x.unit||'all'}`))];
 document.getElementById('rows').innerHTML=keys.length?keys.sort().map(key=>{const [course,unit]=key.split('|'),rows=a.filter(x=>`${x.course||'unassigned'}|${x.unit||'all'}`===key),p=pct(rows),c=rows.filter(x=>x.correct).length,href=course==='unassigned'?'practice.html':`practice.html?course=${encodeURIComponent(course)}${unit!=='all'?`&unit=${encodeURIComponent(unit)}`:''}`;return`<tr><td><b>${ECHSBank.escape(labels[course]||course)}</b>${unit!=='all'?` · Unit ${ECHSBank.escape(unit)}`:''}</td><td>${rows.length}</td><td>${c}</td><td>${p}%</td><td style="min-width:140px"><div class="bar"><i style="width:${p}%"></i></div></td><td><a class="button ghost" href="${href}">Practice</a></td></tr>`}).join(''):`<tr><td colspan="6">No attempts yet. Open a lesson and select Practice.</td></tr>`;
 const recent=[...a].reverse().slice(0,20);document.getElementById('recent').innerHTML=recent.length?recent.map(x=>`<div class="reviewItem ${x.correct?'correct':'incorrect'}"><strong>${x.correct?'Correct':'Review'} · ${ECHSBank.escape(labels[x.course]||x.course||'Question bank')}</strong><p>${ECHSBank.escape(x.lesson||`Unit ${x.unit||'—'}`)}</p><small>${new Date(x.at).toLocaleString()}</small></div>`).join(''):'<div class="empty">No recent activity.</div>';
}
document.getElementById('reset').onclick=()=>{if(confirm('Delete all question-bank attempts stored in this browser?')){localStorage.removeItem(ECHSBank.storeKey);render();}};render();
