
const X={group:document.getElementById('group'),bundle:document.getElementById('bundle'),bank:document.getElementById('bank'),difficulty:document.getElementById('difficulty'),count:document.getElementById('count'),minutes:document.getElementById('minutes'),start:document.getElementById('start'),setup:document.getElementById('setup'),exam:document.getElementById('exam')};let catalog,loaded=[],questions=[],answers={},seconds=0,timer=null;
document.querySelector('.navLink[href="exam.html"]').classList.add('active');
function fillGroups(selected){X.group.innerHTML=ECHSBank.bundleGroups(catalog).filter(g=>g.key!=="scopes").map(g=>`<option value="${g.key}" ${g.key===selected?'selected':''}>${ECHSBank.escape(g.label)}</option>`).join('');}
function fillBundles(selectedId){X.bundle.innerHTML=(catalog.bundles[X.group.value]||[]).map(r=>`<option value="${r.id}" ${r.id===selectedId?'selected':''}>${ECHSBank.escape(r.label)} (${r.auto_gradable_count})</option>`).join('');}
function currentBundle(){return(catalog.bundles[X.group.value]||[]).find(r=>r.id===X.bundle.value);}
async function load(){const row=currentBundle();if(!row)return;loaded=await ECHSBank.loadBundle(row);const banks=[...new Set(loaded.map(q=>q.bank_code))].sort();X.bank.innerHTML='<option value="all">All banks</option>'+banks.map(b=>`<option value="${b}">${b}</option>`).join('');}
function render(){X.exam.innerHTML=`<section class="panel examBar"><strong>${questions.length}-question assessment</strong><span class="timer" id="timer"></span><button class="button primary" id="submit">Submit Exam</button></section>`+questions.map((q,i)=>{const choices=ECHSBank.choiceOrder(q);return`<article class="questionCard" style="margin-top:1rem"><div class="pillRow"><span class="pill wine">${i+1}</span><span class="pill teal">${ECHSBank.escape(q.bank_code)}</span>${q.classification?.ap_topic?`<span class="pill gold">AP ${ECHSBank.escape(q.classification.ap_topic)}</span>`:''}<span class="pill">${ECHSBank.escape(q.source?.section||'')}</span></div><div class="prompt" style="margin-top:.8rem">${q.prompt_html}</div>${["mcq","true_false"].includes(q.type)?`<div class="choices">${choices.map((c,j)=>`<button class="choice" data-q="${q.id}" data-c="${ECHSBank.escape(c.id)}"><span class="choiceLabel">${String.fromCharCode(65+j)}</span><span>${c.html}</span></button>`).join('')}</div>`:`<div class="control" style="margin-top:1rem"><label>Answer</label><input data-input="${q.id}" autocomplete="off"></div>`}</article>`}).join('');document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{document.querySelectorAll(`.choice[data-q="${b.dataset.q}"]`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');answers[b.dataset.q]=b.dataset.c;});document.querySelectorAll('[data-input]').forEach(i=>i.oninput=()=>answers[i.dataset.input]=i.value);document.getElementById('submit').onclick=submit;tick();}
function tick(){const el=document.getElementById('timer');if(!el)return;const m=Math.floor(seconds/60),s=seconds%60;el.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;if(seconds<=0){submit();return;}seconds--;timer=setTimeout(tick,1000);}
async function start(){let rows=ECHSBank.filterQuestions(loaded,{bank:X.bank.value,difficulty:X.difficulty.value,type:'all',section:'all'}).filter(ECHSBank.isAutoGradable.bind(ECHSBank));questions=ECHSBank.shuffle(rows).slice(0,Number(X.count.value));answers={};seconds=Math.max(1,Number(X.minutes.value)||20)*60;X.setup.classList.add('hidden');render();}
function submit(){if(timer)clearTimeout(timer);let correct=0;const review=questions.map((q,i)=>{const response=answers[q.id]??'';const ok=ECHSBank.answerIsCorrect(q,response);if(ok)correct++;ECHSBank.saveAttempt(q,ok,response);const correctText=["mcq","true_false"].includes(q.type)?q.choices.filter(c=>q.correct_choice_ids.includes(c.id)).map(c=>c.text).join(' / '):(q.accepted_answers||[]).join(' / ');return`<div class="reviewItem ${ok?'correct':'incorrect'}"><strong>${i+1}. ${ok?'Correct':'Incorrect'}</strong><p>${ECHSBank.escape(q.prompt_text.slice(0,260))}</p><small>Correct answer: ${ECHSBank.escape(correctText||'See source key')}</small></div>`}).join('');const pct=questions.length?Math.round(correct/questions.length*100):0;X.exam.innerHTML=`<div class="result"><div class="resultScore">${correct} / ${questions.length} (${pct}%)</div><p>Your exam attempts were added to the local dashboard.</p><div class="heroActions"><a class="button wine" href="dashboard.html">Open Dashboard</a><button class="button ghost" onclick="location.reload()">Create another exam</button></div><div class="sectionHead"><div><h2>Review</h2></div></div>${review}</div>`;}
(async()=>{try{catalog=await ECHSBank.loadCatalog();const selected=ECHSBank.selectedBundleFromParams(catalog);fillGroups(selected.group);fillBundles(selected.row?.id);await load();X.group.onchange=async()=>{fillBundles();await load();};X.bundle.onchange=load;X.start.onclick=()=>start().catch(e=>X.exam.innerHTML=`<div class="notice">${ECHSBank.escape(e.message)}</div>`);}catch(e){X.exam.innerHTML=`<div class="notice">${ECHSBank.escape(e.message)}</div>`;}})();
