(async()=>{
"use strict";
const $=id=>document.getElementById(id),X=window.ECHSExperience,esc=X.escapeHTML;
const daysAgo=days=>new Date(Date.now()-days*86400000).toISOString();
const previewData={student:{id:"s1",display_name:"Amina Hassan",grade:"11"},counters:{mastery:74,accuracy:86,questions_today:7,streak:12,review_due:4,open_mistakes:6,mastered_topics:9,total_topics:16,weekly_minutes:94,attempts:186},strengths:[{title:"Polynomial modelling",course:"AP Precalculus",unit:"1",level:"Mastered",score:93},{title:"Exponential transformations",course:"AP Precalculus",unit:"2",level:"Mastered",score:88}],priorities:[{title:"Trigonometric equations",course:"AP Precalculus",unit:"3",level:"Developing",score:48},{title:"Derivative definition",course:"AP Calculus",unit:"2",level:"Developing",score:57}],assignments:[{title:"Unit 3 Targeted Review",activity_type:"adaptive",due_at:new Date(Date.now()+86400000).toISOString(),result:{status:"not_started"}},{title:"Derivative Definition Check",activity_type:"exam",due_at:new Date(Date.now()+3*86400000).toISOString(),result:{status:"submitted"}}],recent_sessions:[{mode:"adaptive",started_at:daysAgo(0),duration_minutes:18},{mode:"review",started_at:daysAgo(1),duration_minutes:11},{mode:"lesson",started_at:daysAgo(2),duration_minutes:22},{mode:"adaptive",started_at:daysAgo(4),duration_minutes:16}]};
function skills(rows,empty,color){return rows?.length?rows.map(row=>`<div class="premiumListRow" style="--row-color:${color}"><span class="rowIcon">${row.score>=80?"★":"◇"}</span><div><strong>${esc(row.title||row.topic||row.skill_key)}</strong><small>${esc([row.course,row.unit?`Unit ${row.unit}`:"",row.level].filter(Boolean).join(" · "))}</small><div class="progressMini"><i style="width:${X.safePercent(row.score)}%"></i></div></div><span class="rowValue">${Math.round(Number(row.score||0))}%</span></div>`).join(""):`<div class="emptyInstitution">${esc(empty)}</div>`}
function plan(data){const priorities=data.priorities||[],c=data.counters||{},first=priorities[0]?.title||"the current lesson";return[
{day:"Day 1",icon:"∫",color:"var(--px-navy-2)",title:"Review together",detail:`Spend 15 minutes reviewing ${first}. Ask the learner to explain one example aloud.`},
{day:"Day 2",icon:"✦",color:"var(--px-teal)",title:"Adaptive practice",detail:"Complete one short adaptive set. Focus on careful work rather than speed."},
{day:"Day 3",icon:"↻",color:"var(--px-maroon)",title:"Mistake recovery",detail:`Recover up to ${Math.min(c.open_mistakes||0,5)} mistake-bank items and discuss what changed.`},
{day:"Day 4",icon:"◷",color:"var(--px-gold)",title:"Rest and recall",detail:"Use five minutes of verbal recall: key ideas, vocabulary and one misconception."},
{day:"Day 5",icon:"✓",color:"var(--px-teal)",title:"Assignment check",detail:"Review due assignments and confirm that unfinished work has a clear plan."},
{day:"Day 6",icon:"★",color:"var(--px-gold)",title:"Confidence challenge",detail:"Complete one slightly harder set in a strong topic to build transfer and confidence."},
{day:"Day 7",icon:"⌂",color:"var(--px-maroon)",title:"Celebrate progress",detail:"Name one specific improvement in mastery, accuracy, effort or consistency."}
]}
function weekData(data){const rows=[...Array(7)].map((_,index)=>{const d=new Date();d.setDate(d.getDate()-(6-index));return{date:d.toISOString().slice(0,10),short:d.toLocaleDateString(undefined,{weekday:"narrow"}),label:d.toLocaleDateString(undefined,{weekday:"short"}),value:0,today:index===6}});(data.recent_sessions||[]).forEach(session=>{const found=rows.find(row=>row.date===new Date(session.started_at).toISOString().slice(0,10));if(found)found.value+=Number(session.duration_minutes||12)});return rows}
function render(data){
  const c=data.counters||{},student=data.student||{},name=student.display_name||"Student",mastery=c.mastery||0;
  $("familyHero").innerHTML=`${esc(name)}’s progress.<span>Support that makes a difference.</span>`;$("familyMessage").textContent=`${student.grade?`Grade ${student.grade} · `:""}${c.attempts||0} synchronized responses · ${c.mastered_topics||0} mastered topics`;
  $("familyMastery").textContent=`${mastery}%`;$("familyAccuracy").textContent=`${c.accuracy||0}%`;$("familyStreak").textContent=c.streak||0;$("familyDue").textContent=c.review_due||0;
  $("familyMasteryTrend").textContent=mastery>=80?"Mastery level":mastery>=65?"Proficient":"Developing";$("familyAccuracyTrend").textContent=(c.accuracy||0)>=80?"Strong precision":"Building accuracy";$("familyStreakTrend").textContent=c.streak>=7?"Weekly momentum":"Build consistency";$("familyReviewTrend").textContent=c.review_due?"Ready now":"Up to date";
  X.setRing("familyProgressRing",mastery);$("familyProgressValue").textContent=`${mastery}%`;$("familyProgressLabel").textContent=mastery>=80?"Strong mastery":mastery>=65?"Proficient progress":"Learning is growing";$("familyProgressTitle").textContent=mastery>=80?"Ready for extension":mastery>=65?"A secure foundation is forming":"A steady pathway is developing";$("familyProgressText").textContent=`${c.mastered_topics||0} topics mastered, ${c.review_due||0} reviews due and ${c.open_mistakes||0} mistakes still being recovered.`;$("familyProgressSteps").innerHTML=[{i:"★",t:`${c.mastered_topics||0} mastered topics`},{i:"🔥",t:`${c.streak||0}-day learning streak`},{i:"✓",t:`${c.questions_today||0} questions today`}].map(row=>`<div class="missionStep"><i>${row.i}</i><span>${row.t}</span></div>`).join("");
  X.setRing("parentMasteryMeter",mastery);X.setRing("parentAccuracyMeter",c.accuracy);X.setRing("parentTopicMeter",c.total_topics?c.mastered_topics/c.total_topics*100:0);X.setRing("parentEngagementMeter",(c.weekly_minutes||0)/120*100);
  $("parentMastered").textContent=c.mastered_topics||0;$("parentTopics").textContent=c.total_topics||0;$("parentMinutes").textContent=c.weekly_minutes||0;$("parentAttempts").textContent=c.attempts||0;$("parentMistakes").textContent=c.open_mistakes||0;$("parentReviews").textContent=c.review_due||0;$("parentToday").textContent=c.questions_today||0;
  $("familyNarrativeScore").style.setProperty("--value",mastery);$("familyNarrativeValue").textContent=`${mastery}%`;$("familyNarrativeTitle").textContent=mastery>=80?"Knowledge is becoming secure":mastery>=65?"Progress is on a healthy path":"The next small steps are clear";$("familyNarrativeText").textContent=mastery>=80?"The learner is showing strong transfer across practised skills. Extension and challenge are appropriate.":mastery>=65?"Most practised skills are becoming proficient. Consistency and focused review will strengthen retention.":"Prioritise short, regular practice and one mistake-recovery conversation at a time.";$("celebrationQuote").textContent=(data.strengths||[])[0]?`Celebrate this: ${data.strengths[0].title} is currently a strong area at ${Math.round(data.strengths[0].score||0)}%.`:"Celebrate the consistency required to build the first evidence.";
  $("familyWeeklyBadge").textContent=`${c.weekly_minutes||0} min`;X.renderWeekBars("familyWeeklyActivity",weekData(data));
  $("familyStrengths").innerHTML=skills(data.strengths,"Strengths appear after practice evidence is collected.","var(--px-teal)");$("familyPriorities").innerHTML=skills(data.priorities,"No priority areas are currently identified.","var(--px-maroon)");
  const assignments=data.assignments||[];$("familyAssignments").innerHTML=assignments.length?assignments.map(row=>{const status=row.result?.status||"not_started",due=row.due_at?new Date(row.due_at):null,overdue=due&&due<new Date()&&status!=="submitted";return`<div class="premiumListRow assignmentPremium ${overdue?"overdue":status==="submitted"?"submitted":""}"><span class="rowIcon">${X.icon(row.activity_type==="exam"?"test":"assignment")}</span><div><strong>${esc(row.title)}</strong><small>${esc((row.activity_type||"practice").toUpperCase())}${due?` · Due ${due.toLocaleDateString()}`:""}</small><div class="progressMini"><i style="width:${status==="submitted"?100:overdue?18:42}%"></i></div></div><span class="cardBadge ${overdue?"alert":status==="submitted"?"":"gold"}">${esc(overdue?"overdue":status.replace("_"," "))}</span></div>`}).join(""):'<div class="emptyInstitution">No current assignments.</div>';
  $("familyPlan").innerHTML=plan(data).map(item=>`<article class="planDay" data-day="${esc(item.day)}" style="--plan:${item.color}"><h3>${esc(item.title)}</h3><p>${esc(item.detail)}</p><i>${item.icon}</i></article>`).join("");
}
async function load(){const id=$("childSelector").value;if(!id){document.querySelector(".institutionMain").insertAdjacentHTML("afterbegin",'<div class="premiumPreview"><div><strong>No linked student</strong><br><span>Ask an administrator to create the parent–student link.</span></div></div>');return}render(await ECHSInstitution.api("institution-api",`/dashboard/student?student_id=${encodeURIComponent(id)}`))}
const current=await ECHSInstitution.requireAuth(["parent","admin","teacher"]);
if(!current&&document.documentElement.dataset.institution==="unconfigured"){
  const preview={display_name:"Hassan Family",username:"hassan.family",role:"parent",organization_name:"ECHS Mathematics"};ECHSInstitution.mountIdentity(preview);X.setIdentityAvatar(preview);X.showPreview("Illustrative family data is shown to review the complete family experience before the institutional backend is activated.");$("childSelector").innerHTML='<option value="s1">Amina Hassan · Grade 11</option>';render(previewData);$("printReport").onclick=()=>print();return;
}
if(!current)return;ECHSInstitution.mountIdentity(current);X.setIdentityAvatar(current);const children=(await ECHSInstitution.api("institution-api","/children")).students||[];$("childSelector").innerHTML=children.length?children.map(row=>`<option value="${row.id}">${esc(row.display_name)}${row.grade?` · Grade ${esc(row.grade)}`:""}</option>`).join(""):'<option value="">No linked student</option>';$("childSelector").onchange=load;$("printReport").onclick=()=>print();await load();
})().catch(error=>{console.error(error);window.ECHSExperience?.toast(error.message,"danger")});
