
const UI={group:document.getElementById("group"),bundle:document.getElementById("bundle"),bank:document.getElementById("bank"),type:document.getElementById("type"),difficulty:document.getElementById("difficulty"),section:document.getElementById("section"),count:document.getElementById("count"),start:document.getElementById("start"),status:document.getElementById("status"),shell:document.getElementById("shell")};
let catalog,loaded=[],set=[],state={index:0,response:null,checked:false,correct:0,graded:0,answered:new Set()};
document.querySelector('.navLink[href="practice.html"]').classList.add('active');
function groupRows(){return ECHSBank.bundleGroups(catalog);}
function fillGroups(selected){UI.group.innerHTML=groupRows().map(g=>`<option value="${g.key}" ${g.key===selected?'selected':''}>${ECHSBank.escape(g.label)}</option>`).join('');}
function fillBundles(selectedId){const rows=catalog.bundles[UI.group.value]||[];UI.bundle.innerHTML=rows.map(r=>`<option value="${ECHSBank.escape(r.id)}" ${r.id===selectedId?'selected':''}>${ECHSBank.escape(r.label)} (${r.count})</option>`).join('');}
function currentBundle(){return(catalog.bundles[UI.group.value]||[]).find(x=>x.id===UI.bundle.value);}
async function loadCurrent(){const row=currentBundle();if(!row)return;UI.status.innerHTML='<span class="pill">Loading…</span>';loaded=await ECHSBank.loadBundle(row);const banks=[...new Set(loaded.map(q=>q.bank_code))].sort();const wanted=ECHSBank.params().get('bank')||UI.bank.value;UI.bank.innerHTML='<option value="all">All banks</option>'+banks.map(code=>`<option value="${ECHSBank.escape(code)}" ${code===wanted?'selected':''}>${ECHSBank.escape(code)}</option>`).join('');const sections=new Map();loaded.forEach(q=>{const s=String(q.source?.section||'unmapped');sections.set(s,s==='unmapped'?'Unmapped':`${s} · ${q.source?.section_title||q.source?.skill_title||''}`)});UI.section.innerHTML='<option value="all">All sections</option>'+[...sections].sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true})).map(([v,l])=>`<option value="${ECHSBank.escape(v)}">${ECHSBank.escape(l)}</option>`).join('');UI.status.innerHTML=`<span class="pill teal">${loaded.length} loaded</span><span class="pill wine">${ECHSBank.escape(row.label)}</span>`;}
function filters(){return{bank:UI.bank.value,type:UI.type.value,difficulty:UI.difficulty.value,section:UI.section.value};}
function render(){const q=set[state.index];if(!q){UI.shell.innerHTML='<div class="empty">No question matches these filters.</div>';return;}state.response=null;state.checked=false;const choices=ECHSBank.choiceOrder(q),cls=q.classification||{},src=q.source||{},auto=ECHSBank.isAutoGradable(q);const responseHtml=["mcq","true_false"].includes(q.type)?`<div class="choices">${choices.map((c,i)=>`<button class="choice" data-id="${ECHSBank.escape(c.id)}"><span class="choiceLabel">${String.fromCharCode(65+i)}</span><span>${c.html}</span></button>`).join('')}</div>`:q.type==='fill_blank'?`<div class="control" style="margin-top:1rem"><label for="answerInput">Your answer</label><input id="answerInput" autocomplete="off"></div>`:`<div class="control" style="margin-top:1rem"><label for="answerInput">Your response</label><textarea id="answerInput" rows="7"></textarea></div>`;UI.shell.innerHTML=`<article class="questionCard"><div class="pillRow"><span class="pill wine">Question ${state.index+1} of ${set.length}</span><span class="pill teal">${ECHSBank.escape(q.bank_code)}</span>${cls.ap_topic?`<span class="pill gold">AP ${ECHSBank.escape(cls.ap_topic)}</span>`:''}<span class="pill">${ECHSBank.escape(src.section||'Unmapped')}</span><span class="pill">${ECHSBank.escape(ECHSBank.labelType(q.type))}</span>${q.metadata?.difficulty?`<span class="pill">Difficulty ${q.metadata.difficulty}</span>`:''}</div><div class="progressTrack"><i style="width:${((state.index+1)/set.length)*100}%"></i></div><h2>${ECHSBank.escape(cls.ap_topic_title||src.skill_title||src.section_title||q.pool_title)}</h2><div class="prompt">${q.prompt_html}</div>${responseHtml}<div id="feedback" class="feedback"></div><div class="questionFooter"><button class="button primary" id="check">${auto?'Check answer':'Reveal source answer / feedback'}</button><div><button class="button ghost" id="prev" ${state.index===0?'disabled':''}>Back</button> <button class="button wine" id="next">${state.index===set.length-1?'Finish':'Next'}</button></div></div></article>`;if(["mcq","true_false"].includes(q.type)){document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{if(state.checked)return;document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.response=b.dataset.id;});}document.getElementById('check').onclick=()=>check(q);document.getElementById('prev').onclick=()=>{if(state.index>0){state.index--;render();}};document.getElementById('next').onclick=()=>{if(state.index<set.length-1){state.index++;render();}else finish();};}
function check(q){if(state.checked)return;if(!["mcq","true_false"].includes(q.type)){state.response=document.getElementById('answerInput')?.value||'';}const auto=ECHSBank.isAutoGradable(q),correct=auto?ECHSBank.answerIsCorrect(q,state.response):null;state.checked=true;if(auto&&!state.answered.has(q.id)){state.graded++;if(correct)state.correct++;state.answered.add(q.id);ECHSBank.saveAttempt(q,correct,state.response);}if(["mcq","true_false"].includes(q.type)){document.querySelectorAll('.choice').forEach(b=>{if((q.correct_choice_ids||[]).includes(b.dataset.id))b.classList.add('correct');else if(b.dataset.id===state.response)b.classList.add('incorrect');});}const f=document.getElementById('feedback');f.className=`feedback show ${correct===false?'incorrect':'correct'}`;const accepted=(q.accepted_answers||[]).join(' / ');f.innerHTML=`<strong>${auto?(correct?'Correct.':'Not correct. Review the highlighted/source answer.'):'Open response: compare your work with the available source feedback.'}</strong>${accepted?`<p><b>Accepted answer:</b> ${ECHSBank.escape(accepted)}</p>`:''}${q.solution_html?`<div class="solution">${q.solution_html}</div>`:'<div class="solution">No worked solution was included in this export. The answer key is available for auto-gradable items; a detailed solution remains in the authoring queue.</div>'}`;}
function finish(){const pct=state.graded?Math.round(state.correct/state.graded*100):null;UI.shell.innerHTML=`<div class="result"><div class="resultScore">${pct==null?'Practice complete':`${state.correct} / ${state.graded} (${pct}%)`}</div><p>You reviewed ${set.length} question(s). ${state.graded?`${state.graded} auto-gradable response(s) were saved to your dashboard.`:'This set contained open-response items.'}</p><div class="heroActions"><a class="button wine" href="dashboard.html">Open Dashboard</a><button class="button ghost" onclick="location.reload()">Create another set</button></div></div>`;}
async function start(){let rows=ECHSBank.filterQuestions(loaded,filters());rows=ECHSBank.shuffle(rows);const n=UI.count.value==='all'?rows.length:Number(UI.count.value);set=rows.slice(0,n);state={index:0,response:null,checked:false,correct:0,graded:0,answered:new Set()};UI.status.innerHTML=`<span class="pill teal">${loaded.length} loaded</span><span class="pill wine">${set.length} selected</span>`;render();}
(async()=>{try{catalog=await ECHSBank.loadCatalog();const selected=ECHSBank.selectedBundleFromParams(catalog);fillGroups(selected.group);fillBundles(selected.row?.id);await loadCurrent();UI.group.onchange=async()=>{fillBundles();await loadCurrent();};UI.bundle.onchange=loadCurrent;UI.start.onclick=()=>start().catch(e=>UI.shell.innerHTML=`<div class="notice">${ECHSBank.escape(e.message)}</div>`);if(ECHSBank.params().get('autostart')==='1')start();}catch(e){UI.shell.innerHTML=`<div class="notice">${ECHSBank.escape(e.message)}. Serve the folder through HTTP rather than opening it with file://.</div>`;}})();
