(()=>{
let current=null,classes=[],selectedClass=null,classData=null,accounts=[],csvRows=[];
const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const date=v=>v?new Date(v).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}):"Never";
function close(){document.querySelectorAll("dialog[open]").forEach(d=>d.close())}document.querySelectorAll("[data-close-dialog]").forEach(b=>b.onclick=close);
function download(name,text){const u=URL.createObjectURL(new Blob([text],{type:"text/csv"})),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function csvEscape(v){return`"${String(v??"").replace(/"/g,'""')}"`}
function parseCSV(text){const rows=[];let row=[],f="",q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(q){if(c==='"'&&n==='"'){f+='"';i++}else if(c==='"')q=false;else f+=c}else if(c==='"')q=true;else if(c===","){row.push(f);f=""}else if(c==="\n"){row.push(f);rows.push(row);row=[];f=""}else if(c!=="\r")f+=c}row.push(f);if(row.some(x=>x.trim()))rows.push(row);const h=(rows.shift()||[]).map(x=>x.trim().toLowerCase().replace(/\s+/g,"_"));return rows.filter(r=>r.some(x=>x.trim())).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]?.trim()||""])))}
async function loadAccounts(){const p=await ECHSInstitution.api("account-api","/accounts");accounts=p.accounts||[]}
async function loadClasses(){const p=await ECHSInstitution.api("institution-api","/classes");classes=p.classes||[];$("classSelector").innerHTML=classes.length?classes.map(c=>`<option value="${c.id}">${esc(c.name)} · ${c.counts?.students||0} students</option>`).join(""):`<option value="">No classes yet</option>`;selectedClass=classes.find(c=>c.id===$("classSelector").value)||classes[0]||null;if(selectedClass)$("classSelector").value=selectedClass.id}
async function loadClass(){if(!selectedClass){renderEmpty();return}classData=await ECHSInstitution.api("institution-api",`/classes/${selectedClass.id}/dashboard`);renderClass()}
function renderEmpty(){$("studentRows").innerHTML=`<tr><td colspan="8"><div class="emptyInstitution"><h3>Create your first class</h3><p>Use Manage class to add a course and roster.</p></div></td></tr>`;["heroStudents","heroActive","heroSupport","assignmentCount","rosterCount"].forEach(id=>$(id).textContent="0");["heroMastery","classAccuracy","coverageMetric"].forEach(id=>$(id).textContent="0%")}
function renderClass(){const s=classData.summary||{},students=classData.students||[];$("classHeroTitle").innerHTML=`${esc(classData.class.name)}.<span>Clear evidence for every learner.</span>`;$("classHeroText").textContent=`${classData.class.course_key} · ${classData.class.academic_year||"Current year"} · ${students.length} students`;
$("heroStudents").textContent=s.students||0;$("heroActive").textContent=s.active_this_week||0;$("heroMastery").textContent=`${s.average_mastery||0}%`;$("heroSupport").textContent=s.need_support||0;$("classAccuracy").textContent=`${s.average_accuracy||0}%`;$("assignmentCount").textContent=(classData.assignments||[]).length;$("rosterCount").textContent=students.length;$("coverageMetric").textContent=`${students.length?Math.round(students.filter(r=>r.mastery>0).length/students.length*100):0}%`;
renderStudents();$("supportList").innerHTML=(classData.support_priorities||[]).length?classData.support_priorities.map(r=>`<div class="skillRow"><div><strong>${esc(r.title)}</strong><small>${r.students} learners represented</small><div class="progressBarI" style="margin-top:8px"><i style="width:${r.mastery}%"></i></div></div><span class="skillScore">${r.mastery}%</span></div>`).join(""):`<div class="emptyInstitution">Mastery priorities appear after students practice.</div>`;
const bins=[{l:"Starting",min:0,max:34},{l:"Developing",min:35,max:64},{l:"Proficient",min:65,max:84},{l:"Mastered",min:85,max:100}];$("distributionChart").innerHTML=bins.map(b=>{const n=students.filter(r=>r.mastery>=b.min&&r.mastery<=b.max).length,p=students.length?Math.round(n/students.length*100):0;return`<div class="skillRow"><div><strong>${b.l}</strong><small>${n} students</small><div class="progressBarI" style="margin-top:8px"><i style="width:${p}%"></i></div></div><span class="skillScore">${p}%</span></div>`}).join("");
$("assignmentList").innerHTML=(classData.assignments||[]).length?classData.assignments.map(r=>`<div class="assignmentRow"><div><strong>${esc(r.title)}</strong><small>${esc(r.activity_type.toUpperCase())}${r.due_at?` · Due ${date(r.due_at)}`:""}</small></div><span class="statusPill ${esc(r.status)}">${esc(r.status)}</span></div>`).join(""):`<div class="emptyInstitution">No assignments yet.</div>`}
function renderStudents(){const q=$("studentSearch").value.trim().toLowerCase(),students=(classData?.students||[]).filter(r=>!q||[r.display_name,r.username,r.grade,r.external_id].some(v=>String(v??"").toLowerCase().includes(q)));$("studentRows").innerHTML=students.length?students.map(r=>`<tr><td><div class="accountIdentity"><span class="avatarInitial">${ECHSInstitution.initials(r.display_name)}</span><div><strong>${esc(r.display_name)}</strong><br><small>${esc(r.grade||"")}</small></div></div></td><td><strong>${esc(r.username)}</strong></td><td>${r.mastery}%</td><td>${r.accuracy}%</td><td>${r.attempts}</td><td>${r.open_mistakes}</td><td>${date(r.last_login_at)}</td><td><div class="tableActions"><a class="iButton secondary small" href="student.html?student_id=${r.id}">Report</a><button class="iButton small" data-reset="${r.id}">Reset password</button></div></td></tr>`).join(""):`<tr><td colspan="8">No matching students.</td></tr>`;document.querySelectorAll("[data-reset]").forEach(b=>b.onclick=()=>{const r=students.find(x=>x.id===b.dataset.reset);$("resetStudentId").value=r.id;$("resetStudentLabel").textContent=`Reset the school-managed password for ${r.display_name} (@${r.username}).`;$("teacherCredential").classList.add("hidden");$("teacherNewPassword").value="";$("resetDialog").showModal()})}
async function createClass(e){e.preventDefault();await ECHSInstitution.api("institution-api","/classes",{method:"POST",body:JSON.stringify({name:$("className").value,course_key:$("classCourse").value,academic_year:$("academicYear").value,section:$("classSection").value})});close();await refresh()}
function memberList(q=""){const selected=new Set((classData?.students||[]).map(r=>r.id));const rows=accounts.filter(r=>["student","teacher"].includes(r.role)&&(!q||[r.display_name,r.username].some(v=>String(v).toLowerCase().includes(q.toLowerCase()))));$("memberList").innerHTML=rows.map(r=>`<label class="skillRow"><div><strong>${esc(r.display_name)}</strong><small>@${esc(r.username)} · ${esc(r.role)}</small></div><input type="checkbox" data-member="${r.id}" data-role="${r.role}" ${selected.has(r.id)||r.id===current.id?"checked":""}></label>`).join("")}
async function saveMembers(e){e.preventDefault();const checked=[...document.querySelectorAll("[data-member]:checked")],student_ids=checked.filter(x=>x.dataset.role==="student").map(x=>x.dataset.member),teacher_ids=checked.filter(x=>x.dataset.role==="teacher").map(x=>x.dataset.member);await ECHSInstitution.api("institution-api",`/classes/${selectedClass.id}/members`,{method:"POST",body:JSON.stringify({student_ids,teacher_ids})});close();await refresh()}
async function createAssignment(e){e.preventDefault();const payload={class_id:selectedClass.id,title:$("assignmentTitle").value,description:$("assignmentDescription").value,activity_type:$("activityType").value,due_at:$("assignmentDue").value?new Date($("assignmentDue").value).toISOString():null,configuration:{course:selectedClass.course_key,unit:$("assignmentUnit").value,topic:$("assignmentTopic").value,count:Number($("assignmentCountInput").value),minutes:Number($("assignmentMinutes").value),difficulty:$("assignmentDifficulty").value}};await ECHSInstitution.api("institution-api","/assignments",{method:"POST",body:JSON.stringify(payload)});close();await loadClass()}
async function refresh(){await Promise.all([loadAccounts(),loadClasses()]);await loadClass()}
async function init(){current=await ECHSInstitution.requireAuth(["teacher","admin"]);if(!current)return;ECHSInstitution.mountIdentity(current);if(current.role==="admin")$("adminNav").classList.remove("hidden");await refresh();
$("classSelector").onchange=async()=>{selectedClass=classes.find(c=>c.id===$("classSelector").value);await loadClass()};$("studentSearch").oninput=renderStudents;
$("manageClass").onclick=()=>{if(!selectedClass){$("classForm").reset();$("classDialog").showModal()}else{memberList();$("membersDialog").showModal()}};$("newAssignment").onclick=$("heroAssignment").onclick=$("sectionAssignment").onclick=()=>{if(!selectedClass)return alert("Create or select a class first");$("assignmentForm").reset();$("assignmentDialog").showModal()};
$("heroImport").onclick=$("importStudents").onclick=()=>{$("teacherImportForm").reset();csvRows=[];$("teacherRunImport").disabled=true;$("teacherImportResult").innerHTML="";$("importDialog").showModal()};
$("classForm").onsubmit=createClass;$("membersForm").onsubmit=saveMembers;$("memberSearch").oninput=e=>memberList(e.target.value);$("assignmentForm").onsubmit=createAssignment;
$("resetForm").onsubmit=async e=>{e.preventDefault();const p=await ECHSInstitution.api("account-api",`/accounts/${$("resetStudentId").value}/reset-password`,{method:"POST",body:JSON.stringify({password:$("teacherNewPassword").value})});$("teacherCredential").innerHTML=`<strong>New password</strong><p><code>${esc(p.initial_password)}</code></p><p>Give it securely to the student. It cannot be retrieved later.</p>`;$("teacherCredential").classList.remove("hidden")};
$("teacherCsv").onchange=async e=>{csvRows=parseCSV(await e.target.files[0].text()).slice(0,500).map(r=>({...r,role:"student"}));$("teacherImportResult").innerHTML=`<div class="iNotice">${csvRows.length} student rows ready.</div>`;$("teacherRunImport").disabled=!csvRows.length};
$("teacherImportForm").onsubmit=async e=>{e.preventDefault();const p=await ECHSInstitution.api("account-api","/accounts/import",{method:"POST",body:JSON.stringify({rows:csvRows})}),created=p.created||[];$("teacherImportResult").innerHTML=`<div class="iNotice"><strong>${created.length} accounts created.</strong></div><button type="button" class="iButton gold" id="teacherDownloadCreds">Download credentials</button>`;$("teacherDownloadCreds").onclick=()=>download("student-credentials.csv",["display_name,username,initial_password,email,grade",...created.map(r=>[r.display_name,r.username,r.initial_password,r.email,r.grade].map(csvEscape).join(","))].join("\n"));await refresh()}
}
init().catch(e=>{console.error(e);alert(e.message)})
})();
