(function(){
  "use strict";
  const state={kind:"private-bank",file:null,request:null,poll:null};
  const $=id=>document.getElementById(id),tabs=[...document.querySelectorAll("[data-upload-kind]")];
  const drop=$("dropZone"),fileInput=$("zipFile"),summary=$("fileSummary"),nameNode=$("fileName"),metaNode=$("fileMeta"),privateBankFields=$("privateBankFields"),releaseFields=$("releaseFields"),start=$("startUpload"),clear=$("clearUpload"),bar=$("progressBar"),percent=$("progressPercent"),stage=$("progressStage"),history=$("requestList"),clearTerminal=$("clearTerminalRequests");
  const terminalStatuses=new Set(["completed","failed","cancelled"]),formatBytes=value=>{const size=Number(value||0);if(size<1024)return `${size} B`;if(size<1048576)return `${(size/1024).toFixed(1)} KB`;return `${(size/1048576).toFixed(1)} MB`};
  const escapeHTML=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
  const safeURL=value=>{try{const url=new URL(String(value||""),location.href);return url.protocol==="https:"&&url.hostname==="github.com"?url.href:""}catch{return""}},api=(path,options={})=>window.ECHSInstitution.api("upload-manager-api",path,options);
  function setProgress(value,text){const n=Math.max(0,Math.min(100,Number(value||0)));bar.style.width=`${n}%`;percent.textContent=`${n}%`;stage.textContent=text||"Ready"}
  function selectKind(kind){state.kind=kind;tabs.forEach(tab=>tab.classList.toggle("active",tab.dataset.uploadKind===kind));privateBankFields.classList.toggle("hidden",kind!=="private-bank");releaseFields.classList.toggle("hidden",kind!=="course-release");$("managerTitle").textContent=kind==="private-bank"?"Upload a private question bank":"Upload a course unit release";$("managerCopy").textContent=kind==="private-bank"?"Choose one ECHS private-bank ZIP. Large packages are uploaded automatically in free-tier-safe parts and reassembled before validation.":"Choose a reviewed unit ZIP. The processor validates and releases it automatically.";resetFile()}
  async function digest(file){const buffer=await file.arrayBuffer(),hash=await crypto.subtle.digest("SHA-256",buffer);return [...new Uint8Array(hash)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
  function updateStart(){const course=state.kind==="private-bank"?$("bankCourseKey").value:$("courseKey").value;start.disabled=!state.file||!course}
  function resetFile(){state.file=null;state.request=null;fileInput.value="";summary.classList.add("hidden");updateStart();setProgress(0,"Ready for a ZIP package")}
  function acceptFile(file){if(!file)return;if(!file.name.toLowerCase().endsWith(".zip")){alert("Please choose a ZIP package.");return}if(file.size>150*1024*1024){alert("The maximum package size is 150 MB.");return}state.file=file;nameNode.textContent=file.name;metaNode.textContent=`${formatBytes(file.size)} · ZIP package`;summary.classList.remove("hidden");updateStart();setProgress(0,$("bankCourseKey").value||state.kind==="course-release"?"Ready to validate":"Choose the exact target course")}
  function uploadPart(url,blob,fileName,onProgress){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest(),form=new FormData(),part=new Blob([blob],{type:"application/octet-stream"});form.append("cacheControl","3600");form.append("",part,fileName);xhr.open("PUT",url,true);xhr.timeout=15*60*1000;xhr.setRequestHeader("x-upsert","true");xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress(e.loaded,e.total)};xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300)return resolve();let detail="";try{const parsed=JSON.parse(xhr.responseText||"{}");detail=parsed.message||parsed.error||""}catch{detail=(xhr.responseText||"").slice(0,240)}reject(new Error(`Storage upload failed (${xhr.status})${detail?`: ${detail}`:""}`))};xhr.onerror=()=>reject(new Error("Network or browser security error while uploading to private storage"));xhr.ontimeout=()=>reject(new Error("The secure upload timed out. Press Validate and Upload to retry."));xhr.send(form)})}
  async function uploadPlan(created,file){const uploads=Array.isArray(created.uploads)&&created.uploads.length?created.uploads:created.upload?[{...created.upload,start:0,end:file.size,index:0,total:1}]:[];if(!uploads.length)throw new Error("Secure upload URLs were not returned");let completed=0;for(const item of uploads){const startByte=Number(item.start||0),endByte=Number(item.end||file.size),blob=file.slice(startByte,endByte);await uploadPart(item.signed_url,blob,item.name||`${file.name}.part-${String(Number(item.index||0)+1).padStart(3,"0")}`,(loaded)=>{const totalLoaded=completed+loaded,pct=12+Math.round((totalLoaded/file.size)*68);setProgress(pct,`Uploading part ${Number(item.index||0)+1} of ${Number(item.total||uploads.length)} · ${formatBytes(totalLoaded)} of ${formatBytes(file.size)}`)});completed+=blob.size}setProgress(82,"All parts uploaded · verifying package")}
  async function begin(){if(!state.file)return;start.disabled=true;clear.disabled=true;try{const courseKey=state.kind==="private-bank"?$("bankCourseKey").value:$("courseKey").value;if(!courseKey)throw new Error("Choose the exact target course before uploading");setProgress(3,"Calculating SHA-256 fingerprint");const sha=await digest(state.file);setProgress(7,"Preparing secure chunked upload");const payload={kind:state.kind,filename:state.file.name,size:state.file.size,sha256:sha,course_key:courseKey,unit_key:state.kind==="course-release"?$("unitKey").value.trim():""};if(state.kind==="course-release"&&!payload.unit_key)throw new Error("Enter the unit number, for example 4");const created=await api("/requests",{method:"POST",body:payload});state.request=created.request;if(created.duplicate){setProgress(created.request.progress,created.request.stage||"This package is already active or completed");watch(created.request.id);await loadHistory();return}await uploadPlan(created,state.file);const completed=await api(`/requests/${state.request.id}/complete`,{method:"POST",body:{}});state.request=completed.request;setProgress(state.request.progress,state.request.stage);watch(state.request.id);await loadHistory()}catch(error){console.error(error);setProgress(0,error.message||"Upload failed");updateStart();await loadHistory()}finally{clear.disabled=false}}
  function watch(id){clearInterval(state.poll);state.poll=setInterval(async()=>{try{const result=await api(`/requests/${id}`),row=result.request;state.request=row;setProgress(row.progress,row.stage);await loadHistory();if(["completed","pr-opened","failed","cancelled"].includes(row.status)){clearInterval(state.poll);start.disabled=false}}catch(error){console.warn(error)}},5000)}
  function requestCard(row){const url=safeURL(row.github_pr_url),link=url?`<a href="${escapeHTML(url)}" target="_blank" rel="noopener">Open pull request ↗</a>`:"",targets=Array.isArray(row.result?.target_courses)?row.result.target_courses:row.course_key?[row.course_key]:[],route=row.result?.routing_summary,bankName=row.result?.display_name||row.result?.bank_code||"",routeText=route?` · ${Number(route.units?.length||0)} units · ${Number(route.lessons||0)} lessons · ${Number(route.question_mappings||0)} exact routes`:"",result=row.result?.bank_code?`<span>${escapeHTML(bankName)} · ${Number(row.result.questions||0).toLocaleString("en-GB")} questions${targets.length?` · ${escapeHTML(targets.join(", "))}`:""}${escapeHTML(routeText)}</span>`:"",status=String(row.status||"unknown").replace(/[^a-z-]/g,""),remove=terminalStatuses.has(status)?`<button class="historyDelete" type="button" data-delete-request="${escapeHTML(row.id)}">Remove</button>`:"";return `<article class="requestItem"><div class="requestTop"><strong>${escapeHTML(row.original_filename)}</strong><span class="statusPill ${status}">${escapeHTML(String(row.status||"unknown").replaceAll("-"," "))}</span></div><p>${escapeHTML(row.stage||"Waiting")}${row.error_message?` · ${escapeHTML(row.error_message)}`:""}</p><div class="miniTrack"><span style="width:${Math.max(0,Math.min(100,Number(row.progress||0)))}%"></span></div><div class="requestLinks">${link}${result}${remove}</div></article>`}
  async function loadHistory(){try{const result=await api("/requests?limit=20"),rows=result.requests||[];history.innerHTML=rows.length?rows.map(requestCard).join(""):'<div class="emptyHistory">No uploads yet.</div>';clearTerminal.disabled=!rows.some(row=>terminalStatuses.has(String(row.status||"")))}catch{history.innerHTML='<div class="emptyHistory">Could not load upload history.</div>';clearTerminal.disabled=true}}
  async function deleteRequest(id){if(!confirm("Remove this completed or failed upload from the history?"))return;try{await api(`/requests/${id}`,{method:"DELETE"});if(state.request?.id===id)resetFile();await loadHistory()}catch(error){alert(error.message||"Could not remove this upload")}}
  async function clearTerminalHistory(){if(!confirm("Clear all completed, failed, and cancelled upload records?"))return;clearTerminal.disabled=true;try{const result=await api("/requests/terminal",{method:"DELETE"});await loadHistory();setProgress(0,`${Number(result.deleted||0)} history records removed`)}catch(error){alert(error.message||"Could not clear upload history");await loadHistory()}}
  tabs.forEach(tab=>tab.addEventListener("click",()=>selectKind(tab.dataset.uploadKind)));["bankCourseKey","courseKey"].forEach(id=>$(id).addEventListener("change",updateStart));["dragenter","dragover"].forEach(type=>drop.addEventListener(type,event=>{event.preventDefault();drop.classList.add("drag")}));["dragleave","drop"].forEach(type=>drop.addEventListener(type,event=>{event.preventDefault();drop.classList.remove("drag")}));drop.addEventListener("drop",event=>acceptFile(event.dataTransfer.files[0]));fileInput.addEventListener("change",()=>acceptFile(fileInput.files[0]));start.addEventListener("click",begin);clear.addEventListener("click",resetFile);history.addEventListener("click",event=>{const button=event.target.closest("[data-delete-request]");if(button)deleteRequest(button.dataset.deleteRequest)});clearTerminal.addEventListener("click",clearTerminalHistory);(async()=>{try{await window.ECHSInstitution.requireAuth(["teacher","admin"]);await loadHistory();setInterval(loadHistory,15000)}catch{location.href="../../login.html"}})();
})();
