import {chromium} from 'playwright-core';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
const base=process.env.ECHS_PREVIEW_URL||'http://127.0.0.1:4173',out=process.env.ECHS_PREVIEW_OUTPUT||'artifacts/ib-ai-2-3-v5';
const lesson=`${base}/lessons/ib-math-ai/unit-2/lessons/IB_AI_SL_2.3_polynomial_rational_models_ECHS.html`,key='echs:ib-ai:u2:2.3:learn-index';await mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--font-render-hinting=none']});
const report={checks:[],errors:[],screenshots:[]};const check=(name,pass,details='')=>{report.checks.push({name,pass,details});if(!pass)report.errors.push(`${name}: ${details}`);};
async function open(viewport){const context=await browser.newContext({viewport,deviceScaleFactor:1,serviceWorkers:'block',reducedMotion:'reduce'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!/favicon|404|ERR_BLOCKED_BY_CLIENT/i.test(m.text()))errors.push(m.text());});await page.route('https://ti84calc.com/**',route=>route.fulfill({status:200,contentType:'text/html',body:'<!doctype html><html><body style="font:18px system-ui;background:#eef1f4"><div style="margin:24px auto;width:360px;background:#111;padding:24px;border-radius:22px;color:white"><b>TI-84 Plus CE simulator fixture</b><div style="margin-top:20px;background:#e9ecef;color:#111;padding:18px">Y= · GRAPH · CALC · STAT · TABLE</div></div></body></html>'}));await page.goto(lesson,{waitUntil:'domcontentloaded',timeout:45000});await page.waitForFunction(()=>document.body.dataset.rendered==='1'&&window.LESSON_DATA?.slides?.length===80,null,{timeout:30000});await page.waitForTimeout(250);return{context,page,errors};}
async function state(page){return page.evaluate(()=>({bodyOverflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),stageOverflow:Math.max(0,(document.querySelector('.stage')?.scrollWidth||0)-(document.querySelector('.stage')?.clientWidth||0)),raw:((document.getElementById('app')?.innerText||'').match(/\\\(|\\\[|\\\)|\\\]/g)||[]).length,mathErrors:document.querySelectorAll('[data-math-error="true"],.katex-error,.katex .merror').length,emptyVisuals:[...document.querySelectorAll('.pr5-visual')].filter(n=>!n.querySelector('svg')).length,progress:document.getElementById('progress-label')?.textContent?.trim()||'',title:document.querySelector('.slide-title')?.textContent?.trim()||document.querySelector('.pr5-section-open h2')?.textContent?.trim()||''}));}
async function gotoTitle(page,title){const index=await page.evaluate(t=>window.LESSON_DATA.slides.findIndex(s=>s.title===t),title);if(index<0)throw new Error(`Missing slide ${title}`);await page.evaluate(({key,index})=>localStorage.setItem(key,String(index)),{key,index});await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(i=>document.body.dataset.rendered==='1'&&document.getElementById('progress-label')?.textContent?.startsWith(`${i+1} /`),index,{timeout:30000});await page.waitForTimeout(180);return index;}
try{
 const desktop=await open({width:1600,height:900}),{page,context,errors}=desktop;const counts=await page.evaluate(()=>({slides:LESSON_DATA.slides.length,practice:LESSON_DATA.practice.length,quiz:LESSON_DATA.quiz.length,exam:LESSON_DATA.exam.length}));check('release counts',JSON.stringify(counts)===JSON.stringify({slides:80,practice:80,quiz:16,exam:6}),JSON.stringify(counts));
 for(let i=0;i<80;i++){if(i){await page.click('#next-slide');await page.waitForFunction(n=>document.getElementById('progress-label')?.textContent?.startsWith(`${n} /`),i+1,{timeout:10000});await page.waitForTimeout(40);}const s=await state(page);check(`Learn ${i+1}`,s.bodyOverflow<=2&&s.stageOverflow<=2&&s.raw===0&&s.mathErrors===0&&s.emptyVisuals===0,JSON.stringify(s));}
 await gotoTitle(page,'End-behaviour laboratory');await page.locator('[data-end-degree]').evaluate(el=>{el.value='6';el.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('[data-end-a]').evaluate(el=>{el.value='-2';el.dispatchEvent(new Event('input',{bubbles:true}));});const endText=await page.locator('[data-end-verdict]').innerText();check('end lab interaction',endText.includes('even')&&endText.includes('negative')&&endText.includes('down'),endText);
 await gotoTitle(page,'Residual laboratory');await page.click('[data-residual-model="linear"]');const linearVerdict=await page.locator('[data-residual-verdict]').innerText();await page.click('[data-residual-model="cubic"]');const cubicVerdict=await page.locator('[data-residual-verdict]').innerText();check('residual lab compares models',linearVerdict.includes('0.383')&&cubicVerdict.includes('0.995'),`${linearVerdict} | ${cubicVerdict}`);
 await gotoTitle(page,'Fit a cubic model from lists');await page.click('[data-pr5-ti-workflow="cubicreg"]');await page.waitForSelector('#pr5-ti-overlay.open');const coach=await page.locator('[data-coach-body]').innerText();check('CubicReg classroom route',coach.includes('6:CubicReg')&&coach.includes('L₁')&&coach.includes('residual'),coach.slice(0,600));await page.click('[data-coach-mode="follow"]');await page.click('[data-next-key]');check('students-follow mode',await page.locator('[data-coach-mode="follow"].active').count()===1,'mode');await page.click('[data-coach-close]');
 await page.click('#pr5-ti-simulator');await page.waitForSelector('#pr5-ti-dock.open');await page.click('[data-ti-load]');await page.waitForSelector('#pr5-ti-dock iframe[src]');await page.waitForTimeout(250);const geom=await page.evaluate(()=>{const app=document.querySelector('.app-shell').getBoundingClientRect(),dock=document.querySelector('#pr5-ti-dock').getBoundingClientRect();return{appRight:app.right,dockLeft:dock.left,dockRight:dock.right,width:innerWidth};});check('TI-84 dock beside lesson',Math.abs(geom.appRight-geom.dockLeft)<=3&&Math.abs(geom.dockRight-geom.width)<=2,JSON.stringify(geom));const shot=path.join(out,'desktop-polynomial-rational-ti84.png');await page.screenshot({path:shot});report.screenshots.push(shot);await page.click('[data-ti-close]');
 for(const route of ['practice','quiz','exam','review']){await page.click(`[data-route="${route}"]`);await page.waitForTimeout(150);check(`${route} route renders`,(await page.locator('#app').innerText()).trim().length>80,await page.locator('#app').innerText().then(t=>t.slice(0,150)));}
 check('desktop console clean',errors.length===0,errors.join('\n'));await context.close();
 const short=await open({width:1600,height:760});await gotoTitle(short.page,'Audit a factored polynomial');const ss=await state(short.page);check('short-screen visual integrity',ss.bodyOverflow<=2&&ss.stageOverflow<=2&&ss.raw===0&&ss.mathErrors===0&&ss.emptyVisuals===0,JSON.stringify(ss));const shortShot=path.join(out,'short-screen-factored-polynomial.png');await short.page.screenshot({path:shortShot});report.screenshots.push(shortShot);check('short console clean',short.errors.length===0,short.errors.join('\n'));await short.context.close();
 const mobile=await open({width:390,height:844});await mobile.page.click('#pr5-ti-simulator');await mobile.page.waitForSelector('#pr5-ti-dock.open');const mg=await mobile.page.evaluate(()=>{const d=document.querySelector('#pr5-ti-dock').getBoundingClientRect();return{left:d.left,right:d.right,width:d.width,viewport:innerWidth,overflow:document.documentElement.scrollWidth-innerWidth};});check('mobile TI-84 full width',Math.abs(mg.left)<=1&&Math.abs(mg.right-mg.viewport)<=1&&Math.abs(mg.width-mg.viewport)<=1&&mg.overflow<=2,JSON.stringify(mg));const mshot=path.join(out,'mobile-polynomial-rational-ti84.png');await mobile.page.screenshot({path:mshot});report.screenshots.push(mshot);check('mobile console clean',mobile.errors.length===0,mobile.errors.join('\n'));await mobile.context.close();
}finally{await browser.close();}
await writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({checks:report.checks.length,errors:report.errors.length,screenshots:report.screenshots.length},null,2));if(report.errors.length){report.errors.forEach(e=>console.error(`ERROR: ${e}`));process.exit(1);}
