/* Build the canonical Topic 1.7–1.16 lessons from reviewed original content. */
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url),root=new URL('../',import.meta.url),base=new URL('lessons/ap-calculus/unit-1/',root);
const read=p=>fs.readFileSync(new URL(p,root),'utf8'),write=(p,s)=>fs.writeFileSync(new URL(p,root),s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const math=s=>String(s).replace(/\\\((.*?)\\\)/gs,(_,tex)=>`<span class="math" data-tex="${esc(tex)}">${esc(tex)}</span>`);
const original=read('lessons/ap-calculus/unit-1/1-6-algebraic-manipulation.html');
const top=original.slice(0,original.indexOf('<section class="slide"'));
const footer=original.slice(original.indexOf('</main><footer'));
const source=read('data/ap-calculus-update.js'),start=source.indexOf('const updates = ')+16,end=source.indexOf(';\n  updates.forEach',start),updates=JSON.parse(source.slice(start,end));
const manifest=[];
for(let n=7;n<=16;n++){
 const d=require(fileURLToPath(new URL(`assets/lesson-1-${n}-ab.js`,base)));
 const old=updates[0].lessons.find(l=>l.number===`1.${n}`);if(!old)throw Error(`Missing topic ${n}`);
 const slides=[];
 function slide(id,title,body,objective=d.objective,phase='Learn'){slides.push(`<section class="slide" id="${id}" data-title="${esc(title)}"${slides.length?' hidden':''}><div class="slide-inner"><p class="eyebrow">${esc(phase)} · AP Calculus AB · Topic ${d.number}</p><${slides.length?'h2':'h1'} tabindex="-1">${esc(title)}</${slides.length?'h2':'h1'}><p class="objective">${esc(objective)}</p>${math(body)}</div></section>`);}
 const q=id=>`<article class="card question" data-question="${id}"></article>`;
 slide('start',d.title,`<div class="grid"><div class="card accent"><p class="lede">${esc(d.objective)}</p><ul>${d.goals.map(g=>`<li>${esc(g)}</li>`).join('')}</ul><span class="tag">16 checked questions</span><span class="tag">2 written-response tasks</span><span class="tag">Interactive investigation</span><div class="actions"><button class="btn" data-go="investigation">Explore the mathematics</button><button class="btn secondary" data-go="ap-set-1">AP-style practice</button></div><p class="mode-note">Mohammad Abu Ghuwaleh · ECHS Mathematics</p></div>${q('g1')}</div>`);
 d.ideas.forEach((idea,i)=>slide(`concept-${i+1}`,idea.title,`<div class="card accent">${idea.body}</div>${i===1?`<div class="card stack">${q('g2')}</div>`:''}`));
 slide('investigation','Investigate, predict, explain','<div id="unit1Lab" class="card lab-panel"></div>','Change the controls, compare the representations, and justify your prediction.','Investigate');
 d.workedExamples.forEach((example,i)=>slide(`example-${i+1}`,example.title,`<div class="grid"><div class="card accent">${example.body}</div>${q('g'+(i+3))}</div>`));
 for(let i=0;i<6;i++)slide('ap-set-'+(i+1),'AP-style practice · '+(2*i+1)+'–'+(2*i+2),`<div class="grid">${q('ap'+(2*i+1))}${q('ap'+(2*i+2))}</div>`,'Work independently first. Select the best answer and compare the reasoning.','Practise');
 d.frqs.forEach((f,i)=>slide(f.id,'Written response · '+(i+1),`<div class="card" data-frq="${f.id}"></div>`,'State the hypotheses, show the mathematics, and justify your conclusion.','Explain'));
 slide('review','Review your evidence',`<div class="card"><div class="score-summary"><div><span>Questions attempted</span><strong id="attemptedCount">0 / 16</strong></div><div><span>Correct now</span><strong id="correctCount">0</strong></div><div><span>Solutions reviewed</span><strong id="reviewedCount">0</strong></div></div><p id="firstAttemptSummary"></p><p id="frqSummary"></p><p class="save-note">Responses stay in this open lesson. Sign in through ECHS to save on this device for your account.</p><div class="actions"><button class="btn" id="continuePractice">Continue to lesson practice</button><button class="btn secondary" id="resetWork">Reset my lesson work</button><button class="btn outline" id="exportWork">Download my responses</button></div><div id="resetConfirmation" hidden class="notice"><p>Clear your saved answers and written responses for this lesson on this device?</p><button class="btn" id="confirmReset">Clear lesson work</button><button class="btn secondary" id="cancelReset">Keep my work</button></div><p class="mode-note">Written reasoning is reviewed using a classroom rubric. The lesson does not award official AP scores or change course mastery by itself.</p></div>`,'Use first-attempt evidence and your explanations to decide what to revisit.','Reflect');
 slide('alignment','AP topic and official practice',`<div class="grid"><div class="card"><h3>Topic ${d.number} coverage</h3><p>${esc(d.title)}</p><p><strong>Learning objective:</strong> ${esc(d.lo)}<br><strong>Essential knowledge:</strong> ${esc(d.ek)}<br><strong>Mathematical skill:</strong> ${esc(d.skill)}</p><p>Questions are original ECHS practice, mapped to this AP topic. Classroom rubrics support explanation and partial credit; they are not College Board scoring guidelines.</p><a href="https://apcentral.collegeboard.org/media/pdf/ap-calculus-ab-and-bc-course-and-exam-description.pdf#page=${n+37}" target="_blank" rel="noopener">Official AP Calculus framework</a></div><div class="card"><h3>Continue in AP Classroom</h3><p>Open Unit 1, select Topic ${d.number}, and use your teacher’s assigned Topic Questions, AP Daily resources and Progress Checks.</p><div class="back-links"><a href="https://apclassroom.collegeboard.org/25/home?unit=1&subunit=${n}" target="_blank" rel="noopener">AP Classroom · Topic ${d.number}</a><a href="https://apclassroom.collegeboard.org/25/home?type=progress-checks&unit=1" target="_blank" rel="noopener">AP Classroom · Unit 1 Progress Checks</a><a href="../../../index.html?course=ap-calculus-ab#courses">Return to AP Calculus</a></div><p class="mode-note">AP Classroom requires your College Board account and any required teacher assignment. Official questions stay in AP Classroom. Existing companion PDFs are separate resources.</p></div></div>`,'Connect this lesson to the AP framework and your assigned official practice.','Reference');
 let head=top.replace(/data-lesson="1\.6"/,'data-lesson="'+d.number+'"').replace(/<title>.*?<\/title>/,`<title>AP Calculus ${d.number} · ${esc(d.title)} | ECHS</title>`).replace(/<meta name="description"[^>]+>/,`<meta name="description" content="${esc(d.objective)} Original AP-style interactive questions, graphs and written-response practice.">`).replace(/<script defer src="assets\/lesson-1-6-(?:model|questions|labs)\.js[^>]*><\/script>/g,'').replace(/<link rel="stylesheet" href="assets\/lesson-1-6\.css[^>]*>/,'').replace(/<script defer src="assets\/limit-lesson-core\.js[^>]*><\/script>/,`<script defer src="assets/lesson-1-${n}-ab.js?v=20260907-ab1"></script><script defer src="assets/unit1-continuation-ui.js?v=20260907-ab1"></script><script defer src="assets/unit1-continuation-labs.js?v=20260907-ab1"></script><script defer src="assets/unit1-continuation-core.js?v=20260907-ab1"></script><link rel="stylesheet" href="assets/unit1-continuation.css?v=20260907-ab1">`).replace('AP Calculus 1.6</strong>','AP Calculus '+d.number+'</strong>').replace('<span>Algebraic manipulation</span>',`<span>${esc(d.subtitle)}</span>`);
 write(old.url,head+slides.join('\n')+footer);
 manifest.push({topic:d.number,title:d.title,url:old.url,learningObjective:d.lo,essentialKnowledge:d.ek,skill:d.skill,checks:d.questions.length,frqs:d.frqs.length,slides:slides.length,source:'Original ECHS practice; AP Classroom resources linked, not reproduced.'});
}
fs.mkdirSync(new URL('docs/releases/',root),{recursive:true});
write('docs/releases/ap-calculus-1-7-1-16-coverage.json',JSON.stringify({revision:'20260907-ab1',framework:'2026–27 AP Calculus AB CED',lessons:manifest},null,2)+'\n');
console.log(`Built ${manifest.length} canonical lessons, ${manifest.reduce((s,l)=>s+l.checks,0)} checks and ${manifest.reduce((s,l)=>s+l.frqs,0)} written-response tasks.`);
