import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
const root=path.resolve(process.argv[2]||'.');
const rel={base:'lessons/ib-math-ai/unit-2/data/lesson-2.3-v5-build.js',a:'lessons/ib-math-ai/unit-2/data/lesson-2.3-v5-content-a.js',b:'lessons/ib-math-ai/unit-2/data/lesson-2.3-v5-content-b.js',c:'lessons/ib-math-ai/unit-2/data/lesson-2.3-v5-content-c.js',final:'lessons/ib-math-ai/unit-2/data/lesson-2.3-v5-finalize.js',pa:'lessons/ib-math-ai/unit-2/data/lesson-2.3-v5-practice-a.js',pb:'lessons/ib-math-ai/unit-2/data/lesson-2.3-v5-practice-b.js',assess:'lessons/ib-math-ai/unit-2/data/lesson-2.3-v5-assessment.js',graphics:'lessons/ib-math-ai/unit-2/data/lesson-2.3-v5-graphics.js',ti:'lessons/ib-math-ai/unit-2/data/lesson-2.3-v5-ti84.js',html:'lessons/ib-math-ai/unit-2/lessons/IB_AI_SL_2.3_polynomial_rational_models_ECHS.html'};
const read=k=>fs.readFileSync(path.join(root,rel[k]),'utf8');const context={window:{},console};context.window.window=context.window;vm.createContext(context);for(const k of ['base','a','b','c','final','pa','pb','assess'])vm.runInContext(read(k),context,{filename:rel[k]});const d=context.window.LESSON_DATA;const fail=(c,m)=>{if(!c)throw new Error(m);};const unique=(a,m)=>fail(new Set(a).size===a.length,`${m} duplicate count ${a.length-new Set(a).size}`);
fail(d.version==='5.0.0','release mismatch');fail(d.lesson.number==='2.3','lesson mismatch');fail(d.slides.length===80,'expected 80 slides');fail(d.practice.length===80,'expected 80 practice');fail(d.quiz.length===16,'expected 16 quiz');fail(d.exam.length===6,'expected 6 tasks');unique(d.slides.map(s=>s.title),'slide titles');unique(d.practice.map(q=>q.id),'practice IDs');unique(d.practice.map(q=>q.prompt),'practice prompts');unique(d.quiz.map(q=>q.id),'quiz IDs');unique(d.quiz.map(q=>q.prompt),'quiz prompts');unique(d.exam.map(q=>q.id),'task IDs');
for(const level of ['Foundation','Application','Reasoning','Challenge'])fail(d.practice.filter(q=>q.level===level).length===20,`${level} count`);
fail(d.slides.every(s=>s.section&&s.title&&s.kind&&typeof s.html==='string'&&s.html.length>40),'incomplete slide');fail(d.practice.every(q=>q.answer&&q.solution&&q.marks>0&&q.calculator),'incomplete practice');
for(const task of d.exam){const sum=task.parts.reduce((s,p)=>s+Number(p.marks),0);fail(sum===task.total_marks,`${task.id} mark total`);fail(task.parts.every(p=>p.answer&&p.markscheme),`${task.id} incomplete key`);}
const html=read('html');for(const k of ['base','a','b','c','final','pa','pb','assess','graphics','ti'])fail(html.includes(path.basename(rel[k])),`HTML missing ${k}`);
const ids=new Set();for(const slide of d.slides)for(const m of slide.html.matchAll(/data-pr5-visual="([^"]+)"/g))ids.add(m[1]);const graphics=read('graphics');for(const id of ids)fail(graphics.includes(`renderers['${id}']`),`missing renderer ${id}`);fail(ids.size>=50,`expected rich visual set, got ${ids.size}`);
const ti=read('ti');for(const token of ['2:zero','6:CubicReg','PwrReg','5:intersect','TBLSET','TblStart=1.8','https://ti84calc.com/ti84calc','Teacher demo','Students follow','Exam drill'])fail(ti.includes(token),`TI token missing ${token}`);fail(!ti.includes('ECHS GDC'),'ECHS GDC must not appear');
const approx=(a,b,t=1e-6)=>Math.abs(a-b)<=t;const pf=x=>.12*(x+3)*(x-1)**2*(x-4);fail(approx(pf(-3),0)&&approx(pf(1),0)&&approx(pf(4),0),'factored roots');fail(approx(pf(0),-1.44),'factored y intercept');const cubic=x=>.6209596*x**3-5.26114719*x**2+10.97936508*x+18.27575758;fail(approx(cubic(8),87.32857326,1e-5),'cubic prediction');fail(approx(cubic(9),143.61666931,1e-5),'cubic extrapolation');const rat=x=>8/(x-2)+3;fail(approx(rat(-2),1)&&approx(rat(6),5),'rational intersections');fail(approx(rat(1.9),-77,1e-8)&&approx(rat(2.1),83,1e-8),'rational table values');fail(approx(.0326*14**3,89.4544),'power estimate');
const badText=[...d.slides,...d.practice,...d.quiz].map(x=>`${x.title||''} ${x.prompt||''} ${x.answer||''} ${x.html||''}`).join('\n');for(const token of ['g(x)=0.42x+-1','\\rac{','\\qrt{'])fail(!badText.includes(token),`malformed content token ${token}`);
console.log(JSON.stringify({release:d.version,slides:d.slides.length,visuals:ids.size,practice:d.practice.length,levels:Object.fromEntries(['Foundation','Application','Reasoning','Challenge'].map(l=>[l,20])),quiz:d.quiz.length,tasks:d.exam.length,ti84:['zero','cubicreg','pwrreg','intersect','table']},null,2));
