/* Exact mathematical and preservation checks for the limit-law lesson. */
import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),base=new URL('../lessons/ap-calculus/unit-1/',import.meta.url),A=require(new URL('assets/lesson-1-5-model.js',base).pathname),Q=require(new URL('assets/lesson-1-5-questions.js',base).pathname),near=(a,b,t=1e-8)=>assert.ok(Math.abs(a-b)<=t,`${a} should equal ${b}`);
for(const [a,b] of [[2,-3],[0,0],[-4,2],[3,0]]){assert.equal(A.combine(a,b,'linear').value,3*a-2*b);assert.equal(A.combine(a,b,'product').value,a*b);assert.equal(A.combine(a,b,'power').value,a*a);const q=A.combine(a,b,'quotient');assert.equal(q.valid,b!==0);assert.equal(q.value,b===0?null:a/b);}
assert.equal(A.combine(NaN,1,'product'),null);assert.equal(A.combine(1,1,'unknown'),null);
for(const [i,op,l,r,b] of [[0,'product',6,6,6],[0,'quotient',2/3,2/3,2/3],[1,'product',0,0,0],[2,'linear',-3,14,'DNE']]){const s=A.sideResult(i,op);near(s.left,l);near(s.right,r);assert.equal(s.both,b);}assert.equal(A.sideResult(1,'quotient').valid,false);
for(const key of Object.keys(A.roots))for(const n of [2,3]){const r=A.rootCase(key,n);for(const x of [-.01,.01]){const v=r.fn(x);if(n===2&&A.roots[key].rad(x)<0)assert.ok(Number.isNaN(v));else near(v**n,A.roots[key].rad(x));}}assert.equal(A.rootCase('linear',2).domain,'right');assert.equal(A.rootCase('negative',2).domain,'none');assert.equal(A.rootCase('negative',3).value,-2);assert.equal(A.rootCase('square',2).value,0);
for(const [key,c,l,r] of [['holeF',1,3,3],['holeG',1,1,1],['jumpF',2,4,-1],['zeroG',2,0,0],['originalF',-2,1,1],['originalG',1,1,-1]]){const m=A.graphs[key];near(m.fn(c-1e-7),l,1e-6);near(m.fn(c+1e-7),r,1e-6);}near(A.graphs.originalF.fn(1),3);near(A.graphs.originalF.fn(2),4);near(A.graphs.originalG.fn(-2),-1);near(A.graphs.originalG.fn(2),0);near(A.graphs.originalG.fn(4),2);
for(const [key,expected] of [['right',-2],['left',2],['constant',5]])for(const x of [1.9,1.99,2.01,2.1])assert.equal(A.outerH(A.directional[key].fn(x)),expected);assert.equal(A.outerH(A.directional.cross.fn(1.99)),2);assert.equal(A.outerH(A.directional.cross.fn(2.01)),-2);assert.equal(A.directional.cross.both,'DNE');
for(const L of [-2,0,1,4]){assert.equal(A.composite(L,'poly').value,L*L+1);assert.equal(A.composite(L,'root').valid,L>=0);assert.equal(A.composite(L,'reciprocal').valid,L!==0);}
// Independently verify original challenge computations and counterexamples.
assert.deepEqual([(10+4)/2,(10-4)/2],[7,3]);assert.equal(2*9-(9-3),12);assert.equal(2*(3-1)/(3+1),1);assert.deepEqual([Math.sqrt(3*4-2*(-2)),3*5*(-2),(7-(-2))**2,(2*3+3*4)/(4-(-2))],[4,-30,81,3]);assert.deepEqual([(2*4-3)**3,(3*4)*(2*(-3)),Math.sqrt(2*4-4*(-3)),(5*4+2*(-3))/(-3-4),4*(-3+5),7*4**2/(1-(-3))],[125,-72,Math.sqrt(20),-2,8,28]);
for(const x of [-.1,-.01,.01,.1]){const h=t=>t<0?t+4:t>0?t-4:-4;near(h(h(x)),x);assert.equal(Math.sign(x)**2,1);near(Math.sqrt(x*x),Math.abs(x));assert.equal(x/x,1);near(x*x/x,x);const u=25-(5+Math.abs(x)/100)**2;assert.ok(u>-1&&u<0);}
for(const n of [1,3,20]){near(Math.sin(Math.PI/2+2*Math.PI*n),1);near(Math.sin(3*Math.PI/2+2*Math.PI*n),-1);}for(const x of [.1,.01,.001])assert.ok(Math.abs(x*Math.sin(1/x))<=x);
// Bounds used in optional proofs hold for all sampled real A,B,f,g, including zero limits.
for(const a of [-3,0,2])for(const b of [-2,0,4]){const eps=.1,f=a+eps/(4*(Math.abs(b)+1)),g=b-eps/(4*(Math.abs(a)+1));assert.ok(Math.abs(f*g-a*b)<eps);assert.ok(Math.abs(Math.abs(f)-Math.abs(a))<=Math.abs(f-a)+1e-12);}
const ap=Q.questions.filter(q=>q.group==='AP-style MCQ'),ch=Q.questions.filter(q=>q.group.startsWith('Challenge MCQ'));assert.deepEqual(ap.map(q=>q.answer),[2,0,3,1,2,3,0,1,3,2,1,0,2,0,3,1]);assert.deepEqual(ch.map(q=>q.answer),[0,2,1,3,1,2,0,3,1,2,0,3,1,2,0,3,1,2,0,3,1,2,0,3,1,2,0,3,1,2,0,3,1,2,0,3]);assert.equal(Q.questions.length,58);assert.equal(Q.frqs.length,18);for(const q of Q.questions){assert.ok(q.hint&&q.solution);if(q.type==='mcq'){assert.equal(q.choices.length,4);assert.equal(new Set(q.choices).size,4);}}for(const f of Q.frqs){assert.equal(f.parts.length,3);for(const p of f.parts)assert.equal((p.rubric.match(/1 point:/g)||[]).length,3);}
assert.equal(Object.keys(Q.preservedSources).length,73);const all=new Set([...Q.questions,...Q.frqs].map(x=>x.id));for(const target of Object.values(Q.preservedSources))for(const id of Array.isArray(target)?target:[target])assert.ok(all.has(id),id);for(const id of ['1.5-AAP-03','1.5-AAP-06','1.5-AAP-19','1.5-ENR-07','1.5-q-140','hard-15-uniqueness'])assert.ok(Q.preservedSources[id]);
const html=fs.readFileSync(new URL('1-5-algebraic-properties-of-limits.html',base),'utf8');assert.equal((html.match(/class="slide"/g)||[]).length,65);assert.match(html,/LIM-1\.D\.1/);assert.match(html,/mathematical practice 1\.E/);const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(new Set(ids).size,ids.length);assert.deepEqual([...html.matchAll(/data-question="([^"]+)"/g)].map(x=>x[1]).sort(),Q.questions.map(x=>x.id).sort());assert.deepEqual([...html.matchAll(/data-frq="([^"]+)"/g)].map(x=>x[1]).sort(),Q.frqs.map(x=>x.id).sort());const boundary=html.indexOf('id="challenge-start"');for(const q of ch)assert.ok(html.indexOf(`data-question="${q.id}"`)>boundary);assert.ok(html.indexOf('data-frq="ap-frq3"')<boundary);assert.ok(html.indexOf('data-question="exit"')<boundary);assert.ok(!html.includes('data:image'));
const katex=vm.createContext({window:{},console});vm.runInContext(fs.readFileSync(new URL('../lessons/ib-math-ai/unit-1/assets/js/katex-global.js',import.meta.url),'utf8'),katex);const decode=s=>s.replace(/&quot;/g,'"').replace(/&#x27;|&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');const eqs=[...html.matchAll(/data-tex="([^"]+)"/g)].map(m=>decode(m[1]));function walk(v){if(typeof v==='string')eqs.push(...[...v.matchAll(/\\\((.*?)\\\)/gs)].map(m=>m[1]));else if(v&&typeof v==='object')Object.values(v).forEach(walk);}walk(Q);for(const tex of eqs)assert.doesNotThrow(()=>katex.window.katex.renderToString(tex,{throwOnError:true,strict:'ignore'}),tex);
console.log(`AP Calculus 1.5 mathematics: PASS (65 slides, 58 keys, 18 FRQs, 73 retained source entries, ${eqs.length} equations, finite-law hypotheses, exact graphs, root domains, composition, reverse identities and proof bounds)`);
