/* DOM-level interaction regression; no browser, network or production account is used. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {parseHTML}=require(process.env.ECHS_TEST_DOM_MODULE||'linkedom');
const base=new URL('../lessons/ap-calculus/unit-1/',import.meta.url);

function runLesson(n){
const html=fs.readFileSync(new URL(`1-${n}-estimating-limit-values-from-${n===3?"graphs":"tables"}.html`,base),'utf8');
const {window:dom,document}=parseHTML(html);
// LinkeDOM does not implement the browser's select.value setter or input.checked state.
Object.defineProperty(dom.HTMLSelectElement.prototype,'value',{configurable:true,get(){return this.querySelector('option[selected]')?.value??this.querySelector('option')?.value??'';},set(value){for(const o of this.querySelectorAll('option'))o.toggleAttribute('selected',o.value===String(value));}});
Object.defineProperty(dom.HTMLInputElement.prototype,'checked',{configurable:true,get(){return this.hasAttribute('checked');},set(value){this.toggleAttribute('checked',Boolean(value));}});
const storage=new Map();let account={id:'fixture-student-a'},failStorage=false;
const eventTarget=new dom.EventTarget();
const location={pathname:`/ECHS-Math/lessons/ap-calculus/unit-1/1-${n}-estimating-limit-values-from-${n===3?"graphs":"tables"}.html`,search:'?course=ap-calculus&lessonKey=fixture-key&accessKey=fixture-access',hash:''};
const renderedMath=vm.createContext({window:{},console});vm.runInContext(fs.readFileSync(new URL('../lessons/ib-math-ai/unit-1/assets/js/katex-global.js',import.meta.url),'utf8'),renderedMath);
const win={document,LimitLessonModels:require(new URL('assets/limit-lesson-models.js',base).pathname),LimitLessonQuestions:require(new URL(`assets/lesson-1-${n}-questions.js`,base).pathname),ECHSInstitution:{account:()=>account},katex:{render(tex,node){renderedMath.window.katex.renderToString(tex,{throwOnError:true,strict:"ignore"});node.textContent=tex;}},addEventListener:eventTarget.addEventListener.bind(eventTarget),dispatchEvent:eventTarget.dispatchEvent.bind(eventTarget),print(){}};
const scheduled=new Map();let timer=0;
const context=vm.createContext({window:win,document,location,history:{replaceState(_s,_t,url){const value=new URL(url,'https://example.test');assert.equal(value.search,location.search,'Navigation retains protected lesson context');location.hash=value.hash;}},localStorage:{getItem:key=>storage.get(key)||null,setItem(key,value){if(failStorage)throw Error('Storage denied');storage.set(key,value);}},setTimeout:fn=>{scheduled.set(++timer,fn);return timer;},clearTimeout:id=>scheduled.delete(id),console});
for(const file of ['limit-lesson-graphs.js',`lesson-1-${n}-labs.js`,'limit-lesson-core.js'])vm.runInContext(fs.readFileSync(new URL('assets/'+file,base),'utf8'),context);
const $=id=>document.getElementById(id),click=node=>node.dispatchEvent(new dom.Event('click',{bubbles:true}));
const input=(node,value)=>{node.value=String(value);node.dispatchEvent(new dom.Event('input',{bubbles:true}));};
const key=(node,key)=>{const e=new dom.Event('keydown',{bubbles:true,cancelable:true});Object.defineProperty(e,'key',{value:key});node.dispatchEvent(e);};
const current=()=>document.querySelector('.slide:not([hidden])')?.id;
const flush=()=>{const callbacks=[...scheduled.values()];scheduled.clear();for(const fn of callbacks)fn();};
const M=win.LimitLessonModels,Q=win.LimitLessonQuestions,numeric=Q.questions.find(q=>q.type==='number'),part=Q.frqs[0].id+'-0';
assert.equal(document.documentElement.dataset.limitLessonReady,'true');assert.equal(document.querySelectorAll('.slide:not([hidden])').length,1);assert.equal(document.querySelectorAll('[data-check]').length,24);assert.equal(document.querySelectorAll('[data-rubric]').length,9);
assert.equal(current(),'start');click($('nextSlide'));assert.equal(current(),'roadmap');key(document,'ArrowRight');assert.equal(current(),n===3?'routine':'table-routine');const before=current();key($(n===3?'traceDistance':'designLeft'),'ArrowRight');assert.equal(current(),before);
click(document.querySelector('[data-solution="launch"]'));assert.equal($('solution-launch').hidden,true);click(document.querySelector('[data-check="launch"]'));assert.match($('feedback-launch').textContent,/select an answer/);click(document.querySelector('[data-hint="launch"]'));assert.equal($('hint-launch').hidden,false);
input($('answer-'+numeric.id),'');click(document.querySelector(`[data-check="${numeric.id}"]`));assert.match($('feedback-'+numeric.id).textContent,/Enter or select/);input($('answer-'+numeric.id),'1/0');click(document.querySelector(`[data-check="${numeric.id}"]`));assert.match($('feedback-'+numeric.id).textContent,/finite number/);assert.match($('attemptedCount').textContent,/^0\b/);
for(const q of Q.questions){const el=document.querySelector(`[data-question="${q.id}"]`);if(q.type==='number')input(el.querySelector('[data-response]'),q.answer);else{for(const r of el.querySelectorAll('input[type="radio"]'))r.checked=Number(r.value)===q.answer;el.querySelector('input:checked').dispatchEvent(new dom.Event('input',{bubbles:true}));}click(el.querySelector('[data-check]'));assert.match($('feedback-'+q.id).textContent,/Correct/,'Lesson '+n+' answer '+q.id);}
assert.equal($('correctCount').textContent,'24');click(document.querySelector('[data-solution="ap01"]'));assert.equal($('solution-ap01').hidden,false);assert.equal($('reviewedCount').textContent,'1');input($('answer-'+numeric.id),'999');assert.equal($('correctCount').textContent,'23');flush();assert.equal(JSON.parse(storage.get(`echs:ap-calculus:1.${n}:interactive-v1:fixture-student-a`)).answers[numeric.id].value,'999');assert.ok(!storage.has(`echs:ap-calculus:1.${n===3?4:3}:interactive-v1:fixture-student-a`));
if(n===3){
 assert.ok(document.querySelectorAll('svg.graph').length>=20,'Questions include their actual graph figures');input($('traceDistance'),4);input($('traceSide'),'left');assert.equal($('traceX').textContent,'0.9999');assert.equal($('traceY').textContent,'2.9999');click($('traceCapture'));assert.equal($('traceRows').children.length,1);click($('traceCapture'));assert.equal($('traceRows').children.length,1);click($('traceAt'));assert.equal($('traceY').textContent,'6.0000');click($('traceCapture'));assert.equal($('traceRows').children.length,1);input($('traceSide'),'right');assert.equal($('traceY').textContent,'3.0001');click($('traceReveal'));assert.equal($('traceFacts').hidden,false);input($('traceModel'),'jump');assert.equal($('traceRows').children.length,0);assert.equal($('traceFacts').hidden,true);assert.equal($('traceBoth').textContent,'DNE');
 for(const t of M.constructionTasks){input($('buildLeft'),t.left);input($('buildRight'),t.right);$('buildMissing').checked=t.at===null;input($('buildMissing'),'on');if(t.at!==null)input($('buildPoint'),t.at);click($('checkBuild'));assert.match($('buildFeedback').textContent,/Correct/);input($('buildLeft'),t.left===6?5:t.left+1);click($('checkBuild'));assert.match($('buildFeedback').textContent,/Revise/);click($('nextBuild'));}
 $('windowZoom').checked=true;input($('windowZoom'),'on');assert.match($('windowStatus').textContent,/0\.01\b/);input($('windowLeft'),2);input($('windowRight'),2.04);click($('checkWindow'));assert.match($('windowFeedback').textContent,/Correct/);input($('windowRight'),2);assert.equal($('windowFeedback').textContent,'');click($('checkWindow'));assert.doesNotMatch($('windowFeedback').textContent,/Correct/);
 input($('infiniteDistance'),4);input($('infiniteSide'),'left');assert.equal($('infiniteY').textContent,'-1000.0000');assert.match($('infiniteStatus').textContent,/outside/);assert.equal($('infiniteBoth').textContent,'DNE');input($('infiniteModel'),'positiveInfinity');assert.equal($('infiniteY').textContent,'1000000.0000');assert.equal($('infiniteBoth').textContent,'∞');input($('infiniteFinite'),'no');click($('checkInfinite'));assert.match($('infiniteFeedback').textContent,/Correct/);input($('infiniteModel'),'negativeInfinity');assert.equal($('infiniteBoth').textContent,'−∞');
 for(const key of ['oscillation','damping']){input($('oscModel'),key);input($('oscWindow'),.05);input($('oscIndex'),2);assert.equal($('oscSamples').children.length,2);input($('oscPrediction'),key==='oscillation'?'DNE':0);click($('checkOsc'));assert.match($('oscFeedback').textContent,/Correct/);assert.equal($('oscGraph').querySelectorAll('.unresolved-region').length,1);}
 for(const c of [-2,0,1,3]){input($('clinicTarget'),c);const m=M.clinic(c);input($('clinicLeft'),m.left);input($('clinicRight'),m.right);input($('clinicBoth'),M.limit(m));input($('clinicPoint'),m.at);click($('checkClinic'));assert.match($('clinicFeedback').textContent,/Correct/);}
}else{
 click($('checkDesign'));assert.match($('designFeedback').textContent,/exactly three/);input($('designTarget'),-3);input($('designLeft'),'-3.1,-3.01,-3.001');input($('designRight'),'-2.9,-2.99,-2.999');click($('checkDesign'));assert.match($('designFeedback').textContent,/Correct/);assert.equal($('designRows').children.length,3);input($('designLeft'),'-3,-3.01,-3.001');click($('checkDesign'));assert.match($('designFeedback').textContent,/leave the target/);assert.equal($('designRows').children.length,0);
 for(const key of ['hole','square','zero','constant','jump','reciprocal','positiveInfinity']){input($('tableModel'),key);const m=M.tables[key];while(!$('revealRow').disabled)click($('revealRow'));assert.equal($('tableRows').children.length,6);input($('tablePrediction'),M.limit(m));click($('checkTable'));assert.match($('tableFeedback').textContent,/Correct/);assert.equal($('tableAnswer').hidden,false);input($('tablePrediction'),'');assert.equal($('tableAnswer').hidden,true);}
 $('showTablePoint').checked=true;input($('showTablePoint'),'on');assert.match($('tablePoint').textContent,/undefined/);click($('resetTableRows'));assert.equal($('tableRows').children.length,1);
 input($('tableSideLeft'),2);input($('tableSideRight'),5);input($('sideTablePrediction'),'DNE');click($('checkSideTable'));assert.match($('sideTableFeedback').textContent,/Correct/);input($('tableSideRight'),2);input($('tableSidePoint'),6);input($('sideTablePrediction'),2);click($('checkSideTable'));assert.match($('sideTableFeedback').textContent,/Correct/);
 input($('precisionDigits'),2);assert.ok($('precisionRows').textContent.includes('1.00'));input($('precisionDigits'),6);assert.match($('precisionRows').textContent,/1\.000401/);input($('precisionVerdict'),'insufficient');click($('checkPrecision'));assert.match($('precisionFeedback').textContent,/Correct/);
 for(const key of ['hole','sinc','exponential'])for(const mode of ['radians','degrees']){input($('calculatorModel'),key);input($('calculatorAngle'),mode);input($('calculatorH'),.001);input($('calculatorDigits'),8);const m=M.calculatorModel(key,mode);assert.equal($('calculatorRows').children.length,3);input($('calculatorPrediction'),M.limit(m).toFixed(3));click($('checkCalculator'));assert.match($('calculatorFeedback').textContent,/Correct/);assert.equal($('calculatorAngle').disabled,key!=='sinc');}input($('calculatorModel'),'sinc');input($('calculatorAngle'),'degrees');assert.match($('calculatorStatus').textContent,/0\.017453/);input($('calculatorAngle'),'radians');assert.match($('calculatorStatus').textContent,/Radian mode/);
 for(const family of ['zero','upper','lower']){input($('sampleFamily'),family);assert.equal($('sampleRows').children.length,4);const expected=family==='zero'?'0':family==='upper'?'1':'-1';for(const row of $('sampleRows').children)assert.equal(row.lastElementChild.textContent,expected);}click($('compareFamilies'));assert.equal($('familyComparison').hidden,false);assert.equal($('familyRows').children.length,4);input($('samplePrediction'),0);click($('checkSampling'));assert.doesNotMatch($('sampleFeedback').textContent,/Correct/);input($('samplePrediction'),'DNE');click($('checkSampling'));assert.match($('sampleFeedback').textContent,/Correct/);
}
for(const graph of document.querySelectorAll('svg.graph')){assert.doesNotMatch(graph.outerHTML,/NaN|Infinity/);assert.ok(graph.getAttribute('aria-label'));assert.ok(graph.querySelector('title'));}assert.equal(document.querySelectorAll('.math-fallback').length,0,'No authored or generated equation failed');
click(document.querySelector(`[data-rubric="${part}"]`));assert.equal($('rubric-'+part).hidden,true);input($('draft-'+part),'My reasoning uses both one-sided trends and separates the point value.');click(document.querySelector(`[data-rubric="${part}"]`));assert.equal($('rubric-'+part).hidden,false);$('score-'+part).value='3';$('score-'+part).dispatchEvent(new dom.Event('change',{bubbles:true}));assert.match($('frqSummary').textContent,/3 points across 1/);input($('draft-'+part),'Revised: compare both sides and explain the available evidence.');assert.equal($('rubric-'+part).hidden,true);assert.equal($('score-'+part).disabled,true);assert.match($('frqSummary').textContent,/not been automatically graded/);
flush();account={id:'fixture-student-b'};win.dispatchEvent(new dom.Event('focus'));assert.equal($('answer-'+numeric.id).value,'');assert.equal($('draft-'+part).value,'');assert.equal($('solution-ap01').hidden,true);assert.match($('attemptedCount').textContent,/^0\b/);assert.equal($('feedback-ap01').textContent,'');account={id:'fixture-student-a'};win.dispatchEvent(new dom.Event('focus'));assert.equal($('answer-'+numeric.id).value,'999');assert.match($('draft-'+part).value,/Revised/);assert.equal($('solution-ap01').hidden,true);
failStorage=true;input($('answer-'+numeric.id),numeric.answer);click(document.querySelector(`[data-check="${numeric.id}"]`));assert.match($('feedback-'+numeric.id).textContent,/Correct/);assert.match(document.querySelector('.save-note').textContent,/unavailable/);failStorage=false;
click($('resetWork'));assert.equal($('resetConfirmation').hidden,false);click($('cancelReset'));assert.match($('attemptedCount').textContent,/24/);click($('resetWork'));click($('confirmReset'));assert.equal($('answer-'+numeric.id).value,'');assert.equal($('draft-'+part).value,'');assert.match($('attemptedCount').textContent,/^0\b/);
key(document,'End');assert.equal(current(),'alignment');assert.equal($('nextSlide').disabled,true);key(document,'Home');assert.equal(current(),'start');assert.equal($('previousSlide').disabled,true);let progressed=false;const finish=document.createElement('button');finish.setAttribute('data-finish-lesson','');finish.addEventListener('click',()=>progressed=true);document.body.append(finish);click($('continuePractice'));assert.ok(progressed);
const ids=[...document.querySelectorAll('[id]')].map(el=>el.id);assert.equal(new Set(ids).size,ids.length);for(const el of document.querySelectorAll('[aria-controls]'))assert.ok($(el.getAttribute('aria-controls')));
console.log(`AP Calculus 1.${n} interactions: PASS (24 answers, six investigations, rubric gates, real equations, scoped drafts, edited work, navigation, storage denial, reset and protected progression)`);
}
runLesson(3);runLesson(4);
