/* Exact mathematics, complete approach notation, and AP-scope regression checks. */
import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),base=new URL('../lessons/ap-calculus/unit-1/',import.meta.url),A=require(new URL('assets/lesson-1-5-model.js',base).pathname),Q=require(new URL('assets/lesson-1-5-questions.js',base).pathname),near=(a,b,t=1e-8)=>assert.ok(Math.abs(a-b)<=t,`${a} should equal ${b}`);
for(const [a,b] of [[2,-3],[0,0],[-4,2],[3,0]]){assert.equal(A.combine(a,b,'linear').value,3*a-2*b);assert.equal(A.combine(a,b,'product').value,a*b);assert.equal(A.combine(a,b,'power').value,a*a);const q=A.combine(a,b,'quotient');assert.equal(q.valid,b!==0);assert.equal(q.value,b===0?null:a/b);}
assert.equal(A.combine(NaN,1,'product'),null);assert.equal(A.combine(1,1,'unknown'),null);
for(const [i,op,l,r,b] of [[0,'product',6,6,6],[0,'quotient',2/3,2/3,2/3],[1,'product',0,0,0],[2,'linear',-3,14,'DNE']]){const s=A.sideResult(i,op);near(s.left,l);near(s.right,r);assert.equal(s.both,b);}assert.equal(A.sideResult(1,'quotient').valid,false);
for(const key of Object.keys(A.roots))for(const n of [2,3]){const r=A.rootCase(key,n);for(const x of [-.01,.01]){const v=r.fn(x);if(n===2&&A.roots[key].rad(x)<0)assert.ok(Number.isNaN(v));else near(v**n,A.roots[key].rad(x));}}assert.equal(A.rootCase('linear',2).domain,'right');assert.equal(A.rootCase('negative',2).domain,'none');assert.equal(A.rootCase('negative',3).value,-2);assert.equal(A.rootCase('square',2).value,0);
for(const [key,c,l,r] of [['holeF',1,3,3],['holeG',1,1,1],['jumpF',2,4,-1],['zeroG',2,0,0],['innerJump',2,-1,1]]){const m=A.graphs[key];near(m.fn(c-1e-7),l,1e-6);near(m.fn(c+1e-7),r,1e-6);assert.equal(m.fn(c),m.at);}
const M=require(new URL('assets/limit-lesson-models.js',base).pathname);
// Test both composite outcomes independently of the assigned center value.
for(const at of [-5,0,3,8])for(const [key,l,r,b] of [['square',1,1,1],['linear',1,3,'DNE']]){
 const j=A.jumpCase(key,at);assert.deepEqual([j.innerLeft,j.innerRight,j.left,j.right,j.both],[-1,1,l,r,b]);
 near(j.composite(2-1e-7),l,1e-6);near(j.composite(2+1e-7),r,1e-6);assert.equal(j.composite(2),key==='square'?at*at:at+2);
 for(const h of [.1,.01,.001]){assert.ok(A.jumpingInner(2-h)<-1);assert.ok(A.jumpingInner(2+h)>1);near(j.composite(2-h),key==='square'?(-1-h)**2:1-h);near(j.composite(2+h),key==='square'?(1+h)**2:3+h);}
}
const curves=M.graphData(A.graphs.innerJump).series;assert.equal(curves.length,2);assert.ok(curves[0].every(([x,y])=>x<2&&y<-1));assert.ok(curves[1].every(([x,y])=>x>2&&y>1),'No line may bridge the inner jump');
for(const key of ['square','linear']){const g=A.graphs['outer-'+key];assert.equal(g.breaks.length,0);assert.equal(g.marks.length,2);assert.ok(g.marks.every(p=>!p.open));}
for(const L of [-2,0,1,4]){assert.equal(A.composite(L,'poly').value,L*L+1);assert.equal(A.composite(L,'root').valid,L>=0);assert.equal(A.composite(L,'reciprocal').valid,L!==0);}
// Independent arithmetic checks connect selected answers to actual expressions.
const numerical={launch:2+3,'law-check':3*2-2*(-3),'root-check':Math.sqrt(4+5),'compose-check':4**2+1,ap01:12,ap02:2*(-3)**2,ap03:2/-3,ap04:3,ap05:(-3)**3,ap06:Math.cbrt(-8),ap08:(-2)**3-3*(-2)+1,ap09:5/3,ap10:(-3)**2+1,ap11:2*3-(-1),ap13:2*3,ap14:Math.sqrt((-2)**2),ap15:(-1)**2,ch01:(10+4)/2,ch02:12-3,ch03:Math.sqrt((-3-4)**2),ch04:2/3,ch05:10/4,ch06:9-2,ch07:2/3,ch09:(3**2+1)/(3-1),ch11:0};
for(const [id,value] of Object.entries(numerical)){const q=Q.questions.find(q=>q.id===id),answer=q.type==='number'?q.answer:M.parseNumber(q.choices[q.answer].replace(/−/g,'-'));near(answer,value);}
for(const id of ['ap12','ap16']){const q=Q.questions.find(q=>q.id===id);assert.equal(q.choices[q.answer],'DNE');}
assert.deepEqual([(-1)**2,1**2],[1,1]);assert.deepEqual([-1+2,1+2],[1,3]);assert.deepEqual([((-1)**2+3)/(-1+3),(1**2+3)/(1+3)],[2,1]);
assert.deepEqual([(10+4)/2,(10-4)/2,(15+2*3)/7],[7,3,3]);
assert.deepEqual([2*3+1,(3-1)/(3+1),1**2+2*1,4**2+2*4],[7,.5,3,24]);
const ap=Q.questions.filter(q=>q.group==='AP-style MCQ'),ch=Q.questions.filter(q=>q.group.startsWith('Challenge MCQ'));assert.deepEqual(ap.map(q=>q.answer),[2,0,3,1,2,3,0,1,3,2,1,0,2,0,3,1]);assert.deepEqual(ch.map(q=>q.answer),[0,2,1,3,1,2,0,3,1,2,0,3]);assert.equal(Q.questions.length,34);assert.equal(Q.frqs.length,7);assert.equal(ap.length,16);assert.equal(ch.length,12);for(const q of Q.questions){assert.ok(q.hint&&q.solution);if(q.type==='mcq'){assert.equal(q.choices.length,4);assert.equal(new Set(q.choices).size,4);}}for(const f of Q.frqs){assert.equal(f.parts.length,3);for(const p of f.parts)assert.equal((p.rubric.match(/1 point:/g)||[]).length,3);}
assert.equal(Q.revision,'ap-topic-1-5-v2');assert.equal(Q.preservedSources,undefined);
const html=fs.readFileSync(new URL('1-5-algebraic-properties-of-limits.html',base),'utf8');assert.equal((html.match(/class="slide"/g)||[]).length,45);assert.match(html,/LIM-1\.D\.1/);assert.match(html,/mathematical practice 1\.E/);const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(new Set(ids).size,ids.length);assert.deepEqual([...html.matchAll(/data-question="([^"]+)"/g)].map(x=>x[1]).sort(),Q.questions.map(x=>x.id).sort());assert.deepEqual([...html.matchAll(/data-frq="([^"]+)"/g)].map(x=>x[1]).sort(),Q.frqs.map(x=>x.id).sort());const boundary=html.indexOf('id="challenge-start"');for(const q of ch)assert.ok(html.indexOf(`data-question="${q.id}"`)>boundary);assert.ok(html.indexOf('data-frq="ap-frq3"')<boundary);assert.ok(html.indexOf('data-question="exit"')<boundary);assert.ok(!html.includes('data:image'));
const katex=vm.createContext({window:{},console});vm.runInContext(fs.readFileSync(new URL('../lessons/ib-math-ai/unit-1/assets/js/katex-global.js',import.meta.url),'utf8'),katex);const decode=s=>s.replace(/&quot;/g,'"').replace(/&#x27;|&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');const eqs=[...html.matchAll(/data-tex="([^"]+)"/g)].map(m=>decode(m[1]));function walk(v){if(typeof v==='string')eqs.push(...[...v.matchAll(/\\\((.*?)\\\)/gs)].map(m=>m[1]));else if(v&&typeof v==='object')Object.values(v).forEach(walk);}walk(Q);for(const text of [html,JSON.stringify(Q)])assert.doesNotMatch(text,/ε|δ|epsilon|delta|sequence criterion|squeez|induction|optional proof|Beyond AP/i,'Out-of-topic extensions must stay out of the revised lesson');
for(const tex of eqs){assert.doesNotMatch(tex,/\\lim(?!_\{)/,'Every limit operator has a subscript');for(const m of tex.matchAll(/\\lim_\{([^}]*)\}/g))assert.match(m[1],/^[a-z]\\to\s*[^ ]+/,'Each subscript states the variable and approach');}
for(const q of Q.questions)assert.match(q.prompt,/\\lim_\{x\\to/,'Question '+q.id+' states an explicit limit approach');
assert.ok(html.indexOf('id="jump-lab"')<html.indexOf('id="ap-set-1"'));assert.ok(html.includes('data-laws-plot="outer-square"'));assert.ok(html.includes('data-laws-plot="outer-linear"'));
for(const tex of eqs)assert.doesNotThrow(()=>katex.window.katex.renderToString(tex,{throwOnError:true,strict:'ignore'}),tex);
console.log('AP Calculus 1.5 mathematics: PASS (45 slides, 34 keys, 7 FRQs, '+eqs.length+' equations with approach values, AP scope, finite laws, exact jump graphs and composite side limits)');
