/* DOM-level interaction regression; no browser, network or production account is used. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {parseHTML}=require(process.env.ECHS_TEST_DOM_MODULE||'linkedom');
const base=new URL('../lessons/ap-calculus/unit-1/',import.meta.url);
const html=fs.readFileSync(new URL('1-2-defining-limits-and-using-limit-notation.html',base),'utf8');
const {window:dom,document}=parseHTML(html);
// LinkeDOM does not implement the browser's select.value setter or input.checked state.
Object.defineProperty(dom.HTMLSelectElement.prototype,'value',{configurable:true,get(){return this.querySelector('option[selected]')?.value??this.querySelector('option')?.value??'';},set(value){for(const o of this.querySelectorAll('option'))o.toggleAttribute('selected',o.value===String(value));}});
Object.defineProperty(dom.HTMLInputElement.prototype,'checked',{configurable:true,get(){return this.hasAttribute('checked');},set(value){this.toggleAttribute('checked',Boolean(value));}});
const storage=new Map();let account={id:'fixture-student-a'},failStorage=false;
const eventTarget=new dom.EventTarget();
const location={pathname:'/ECHS-Math/lessons/ap-calculus/unit-1/1-2-defining-limits-and-using-limit-notation.html',search:'?course=ap-calculus&lessonKey=fixture-key&accessKey=fixture-access',hash:''};
const renderedMath=vm.createContext({window:{},console});vm.runInContext(fs.readFileSync(new URL('../lessons/ib-math-ai/unit-1/assets/js/katex-global.js',import.meta.url),'utf8'),renderedMath);
const win={document,Calculus12:require(new URL('assets/lesson-1-2-model.js',base).pathname),Calculus12Questions:require(new URL('assets/lesson-1-2-questions.js',base).pathname),ECHSInstitution:{account:()=>account},katex:{render(tex,node){renderedMath.window.katex.renderToString(tex,{throwOnError:true,strict:"ignore"});node.textContent=tex;}},addEventListener:eventTarget.addEventListener.bind(eventTarget),dispatchEvent:eventTarget.dispatchEvent.bind(eventTarget),print(){}};
const scheduled=new Map();let timer=0;
const context=vm.createContext({window:win,document,location,history:{replaceState(_s,_t,url){const value=new URL(url,'https://example.test');assert.equal(value.search,location.search,'Navigation retains protected lesson context');location.hash=value.hash;}},localStorage:{getItem:key=>storage.get(key)||null,setItem(key,value){if(failStorage)throw Error('Storage denied');storage.set(key,value);}},setTimeout:fn=>{scheduled.set(++timer,fn);return timer;},clearTimeout:id=>scheduled.delete(id),console});
vm.runInContext(fs.readFileSync(new URL('assets/lesson-1-2.js',base),'utf8'),context);
const $=id=>document.getElementById(id),click=node=>node.dispatchEvent(new dom.Event('click',{bubbles:true}));
const input=(node,value)=>{node.value=String(value);node.dispatchEvent(new dom.Event('input',{bubbles:true}));};
const key=(node,key)=>{const e=new dom.Event('keydown',{bubbles:true,cancelable:true});Object.defineProperty(e,'key',{value:key});node.dispatchEvent(e);};
const current=()=>document.querySelector('.slide:not([hidden])')?.id;
const flush=()=>{const callbacks=[...scheduled.values()];scheduled.clear();for(const fn of callbacks)fn();};
assert.equal(document.documentElement.dataset.calculus12Ready,'true');assert.equal(document.querySelectorAll('.slide:not([hidden])').length,1);assert.equal(document.querySelectorAll('[data-check]').length,24);assert.equal(document.querySelectorAll('[data-rubric]').length,9);assert.equal(document.querySelectorAll('svg.graph').length,5);
assert.equal(current(),'start');click($('nextSlide'));assert.equal(current(),'roadmap');key(document,'ArrowRight');assert.equal(current(),'symbols');const before=current();key($('approachDistance'),'ArrowRight');key($('notationTarget'),'Home');assert.equal(current(),before);
click(document.querySelector('[data-solution="launch"]'));assert.equal($('solution-launch').hidden,true);click(document.querySelector('[data-check="launch"]'));assert.match($('feedback-launch').textContent,/select an answer/);click(document.querySelector('[data-hint="launch"]'));assert.equal($('hint-launch').hidden,false);
input($('answer-read-output'),'');click(document.querySelector('[data-check="read-output"]'));assert.match($('feedback-read-output').textContent,/Enter or select/);input($('answer-read-output'),'1/0');click(document.querySelector('[data-check="read-output"]'));assert.match($('feedback-read-output').textContent,/finite number/);assert.match($('attemptedCount').textContent,/^0\b/);
for(const q of win.Calculus12Questions.questions){const el=document.querySelector(`[data-question="${q.id}"]`);if(q.type==='number')input(el.querySelector('[data-response]'),q.answer);else{for(const radio of el.querySelectorAll('input[type="radio"]'))radio.checked=Number(radio.value)===q.answer;el.querySelector('input:checked').dispatchEvent(new dom.Event('input',{bubbles:true}));}click(el.querySelector('[data-check]'));assert.match($('feedback-'+q.id).textContent,/Correct/,'Correct answer for '+q.id);}
assert.equal($('correctCount').textContent,'24');click(document.querySelector('[data-solution="ap01"]'));assert.equal($('solution-ap01').hidden,false);assert.equal($('reviewedCount').textContent,'1');
input($('answer-read-target'),'8');assert.equal($('correctCount').textContent,'23');flush();assert.equal(JSON.parse(storage.get('echs:ap-calculus:1.2:interactive-v1:fixture-student-a')).answers['read-target'].value,'8');
input($('approachDistance'),4);input($('approachSide'),'left');assert.equal($('approachInput').textContent,'1.999');assert.equal($('approachOutput').textContent,'3.999');assert.equal($('approachGap').textContent,'0.001');click($('captureInput'));assert.equal($('capturedInputs').children.length,1);click($('captureInput'));assert.equal($('capturedInputs').children.length,1);click($('evaluateTarget'));assert.equal($('approachOutput').textContent,'7');click($('captureInput'));assert.equal($('capturedInputs').children.length,1);input($('approachSide'),'right');assert.equal($('approachInput').textContent,'2.001');assert.equal($('approachOutput').textContent,'4.001');click($('captureInput'));assert.equal($('capturedInputs').children.length,2);click($('clearCaptures'));assert.equal($('capturedInputs').children.length,0);
input($('pointValue'),4);assert.equal($('pointAt').textContent,'4');assert.match($('pointStatus').textContent,/equals/);$('pointMissing').checked=true;input($('pointMissing'),'on');assert.equal($('pointAt').textContent,'undefined');assert.equal($('pointLimit').textContent,'4');assert.equal($('pointValue').disabled,true);$('pointMissing').checked=false;input($('pointMissing'),'on');input($('pointValue'),-2);assert.equal($('pointAt').textContent,'-2');assert.equal($('pointLimit').textContent,'4');
click($('checkNotation'));assert.match($('notationFeedback').textContent,/finite target/);
for(const task of win.Calculus12.notationTasks){input($('notationVariable'),task.variable);input($('notationTarget'),task.target);input($('notationOutput'),task.output);input($('notationSide'),task.side);click($('checkNotation'));assert.match($('notationFeedback').textContent,/Correct/);input($('notationTarget'),task.target+1);click($('checkNotation'));assert.match($('notationFeedback').textContent,/Revise the target/);click($('nextNotation'));assert.equal($('notationTarget').value,'');}
for(const [key,model] of Object.entries(win.Calculus12.models)){input($('representationModel'),key);assert.equal($('representationAnswer').hidden,true);assert.equal($('representationTable').children.length,3);input($('representationPrediction'),win.Calculus12.limit(model));click($('checkRepresentation'));assert.match($('representationFeedback').textContent,/Correct/);assert.equal($('representationAnswer').hidden,false);input($('representationPrediction'),'');assert.equal($('representationAnswer').hidden,true);click($('checkRepresentation'));assert.match($('representationFeedback').textContent,/Enter a number/);}
input($('sideLeft'),-3);input($('sideRight'),6);input($('sidePoint'),0);assert.equal($('sideResult').textContent,'DNE');click($('matchSides'));assert.equal($('sideResult').textContent,'-3');input($('sidePoint'),6);assert.equal($('sideResult').textContent,'-3');input($('sideLeft'),0);input($('sideRight'),0);assert.equal($('sideResult').textContent,'0');
input($('farValue'),-2);input($('localPoint'),9);assert.equal($('localLimit').textContent,'4');$('localZoom').checked=true;input($('localZoom'),'on');assert.match($('localStatus').textContent,/Close view/);assert.equal($('localLimit').textContent,'4');
for(const graph of document.querySelectorAll('svg.graph')){assert.doesNotMatch(graph.outerHTML,/NaN|Infinity/);assert.ok(graph.getAttribute('aria-label'));assert.ok(graph.querySelector('title'));}assert.equal(document.querySelectorAll('.math-fallback').length,0,'No static or dynamic equation failed');
click(document.querySelector('[data-rubric="frq-point-0"]'));assert.equal($('rubric-frq-point-0').hidden,true);input($('draft-frq-point-0'),'The nearby outputs approach 4, but the assigned point value is 7.');click(document.querySelector('[data-rubric="frq-point-0"]'));assert.equal($('rubric-frq-point-0').hidden,false);$('score-frq-point-0').value='3';$('score-frq-point-0').dispatchEvent(new dom.Event('change',{bubbles:true}));assert.match($('frqSummary').textContent,/3 points across 1/);
input($('draft-frq-point-0'),'For x ≠ 2, f(x) = x + 2 approaches 4. At x = 2, f(2) = 7.');assert.equal($('rubric-frq-point-0').hidden,true);assert.equal($('score-frq-point-0').disabled,true);assert.match($('frqSummary').textContent,/not been automatically graded/);
for(const row of document.querySelectorAll('[data-classification]'))row.querySelector('select').value=row.dataset.classification;click($('checkClassification'));assert.match($('classificationSummary').textContent,/6 correct from 6/);
flush();account={id:'fixture-student-b'};win.dispatchEvent(new dom.Event('focus'));assert.equal($('answer-read-target').value,'');assert.equal($('draft-frq-point-0').value,'');assert.equal($('solution-ap01').hidden,true);assert.equal($('rubric-frq-point-0').hidden,true);assert.match($('attemptedCount').textContent,/^0\b/);assert.equal($('feedback-ap01').textContent,'');
account={id:'fixture-student-a'};win.dispatchEvent(new dom.Event('focus'));assert.equal($('answer-read-target').value,'8');assert.match($('draft-frq-point-0').value,/approaches 4/);assert.equal($('solution-ap01').hidden,true);
failStorage=true;input($('answer-read-target'),-3);click(document.querySelector('[data-check="read-target"]'));assert.match($('feedback-read-target').textContent,/Correct/);assert.match(document.querySelector('.save-note').textContent,/unavailable/);failStorage=false;
click($('resetWork'));assert.equal($('resetConfirmation').hidden,false);click($('cancelReset'));assert.match($('attemptedCount').textContent,/24/);click($('resetWork'));click($('confirmReset'));assert.equal($('answer-read-target').value,'');assert.equal($('draft-frq-point-0').value,'');assert.match($('attemptedCount').textContent,/^0\b/);
key(document,'End');assert.equal(current(),'alignment');assert.equal($('nextSlide').disabled,true);key(document,'Home');assert.equal(current(),'start');assert.equal($('previousSlide').disabled,true);
let protectedAction=false;const finish=document.createElement('button');finish.setAttribute('data-finish-lesson','');finish.addEventListener('click',()=>protectedAction=true);document.body.append(finish);click($('continuePractice'));assert.ok(protectedAction,'Continuation delegates to the existing protected platform action');
const ids=[...document.querySelectorAll('[id]')].map(el=>el.id);assert.equal(new Set(ids).size,ids.length);for(const el of document.querySelectorAll('[aria-controls]'))assert.ok($(el.getAttribute('aria-controls')));
console.log('AP Calculus 1.2 UI: PASS (24 answers, six labs, six notation scenarios, real equation rendering, rubric gates, draft invalidation, keyboard, account isolation, storage failure, reset and protected progression)');
