/* DOM-level interaction regression; no browser, network or production account is used. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {parseHTML}=require(process.env.ECHS_TEST_DOM_MODULE||'linkedom');
const base=new URL('../lessons/ap-calculus/unit-1/',import.meta.url);

function runLesson(n=5){
const html=fs.readFileSync(new URL('1-5-algebraic-properties-of-limits.html',base),'utf8');
const {window:dom,document}=parseHTML(html);
// LinkeDOM does not implement the browser's select.value setter or input.checked state.
Object.defineProperty(dom.HTMLSelectElement.prototype,'value',{configurable:true,get(){return this.querySelector('option[selected]')?.value??this.querySelector('option')?.value??'';},set(value){for(const o of this.querySelectorAll('option'))o.toggleAttribute('selected',o.value===String(value));}});
Object.defineProperty(dom.HTMLInputElement.prototype,'checked',{configurable:true,get(){return this.hasAttribute('checked');},set(value){this.toggleAttribute('checked',Boolean(value));}});
const storage=new Map();let account={id:'fixture-student-a'},failStorage=false;
const eventTarget=new dom.EventTarget();
const location={pathname:'/ECHS-Math/lessons/ap-calculus/unit-1/1-5-algebraic-properties-of-limits.html',search:'?course=ap-calculus&lessonKey=fixture-key&accessKey=fixture-access',hash:''};
const renderedMath=vm.createContext({window:{},console});vm.runInContext(fs.readFileSync(new URL('../lessons/ib-math-ai/unit-1/assets/js/katex-global.js',import.meta.url),'utf8'),renderedMath);
const win={document,LimitLessonModels:require(new URL('assets/limit-lesson-models.js',base).pathname),LimitLessonQuestions:require(new URL(`assets/lesson-1-${n}-questions.js`,base).pathname),ECHSInstitution:{account:()=>account},katex:{render(tex,node){renderedMath.window.katex.renderToString(tex,{throwOnError:true,strict:"ignore"});node.textContent=tex;}},addEventListener:eventTarget.addEventListener.bind(eventTarget),dispatchEvent:eventTarget.dispatchEvent.bind(eventTarget),print(){}};
const scheduled=new Map();let timer=0;
const context=vm.createContext({window:win,document,location,history:{replaceState(_s,_t,url){const value=new URL(url,'https://example.test');assert.equal(value.search,location.search,'Navigation retains protected lesson context');location.hash=value.hash;}},localStorage:{getItem:key=>storage.get(key)||null,setItem(key,value){if(failStorage)throw Error('Storage denied');storage.set(key,value);}},setTimeout:fn=>{scheduled.set(++timer,fn);return timer;},clearTimeout:id=>scheduled.delete(id),console});
for(const file of ['limit-lesson-graphs.js','lesson-1-5-model.js',`lesson-1-${n}-labs.js`,'limit-lesson-core.js'])vm.runInContext(fs.readFileSync(new URL('assets/'+file,base),'utf8'),context);
const $=id=>document.getElementById(id),click=node=>node.dispatchEvent(new dom.Event('click',{bubbles:true}));
const input=(node,value)=>{node.value=String(value);node.dispatchEvent(new dom.Event('input',{bubbles:true}));};
const key=(node,key)=>{const e=new dom.Event('keydown',{bubbles:true,cancelable:true});Object.defineProperty(e,'key',{value:key});node.dispatchEvent(e);};
const current=()=>document.querySelector('.slide:not([hidden])')?.id;
const flush=()=>{const callbacks=[...scheduled.values()];scheduled.clear();for(const fn of callbacks)fn();};
const M=win.LimitLessonModels,Q=win.LimitLessonQuestions,numeric=Q.questions.find(q=>q.type==='number'),part=Q.frqs[0].id+'-0';
assert.equal(document.documentElement.dataset.limitLessonReady,'true');assert.equal(document.querySelectorAll('.slide:not([hidden])').length,1);assert.equal(document.querySelectorAll('[data-check]').length,58);assert.equal(document.querySelectorAll('[data-rubric]').length,54);
assert.equal(current(),'start');click($('nextSlide'));assert.equal(current(),'roadmap');key(document,'ArrowRight');assert.equal(current(),'story');const before=current();key($('lawA'),'ArrowRight');assert.equal(current(),before);
click(document.querySelector('[data-solution="launch"]'));assert.equal($('solution-launch').hidden,true);click(document.querySelector('[data-check="launch"]'));assert.match($('feedback-launch').textContent,/select an answer/);click(document.querySelector('[data-hint="launch"]'));assert.equal($('hint-launch').hidden,false);
input($('answer-'+numeric.id),'');click(document.querySelector(`[data-check="${numeric.id}"]`));assert.match($('feedback-'+numeric.id).textContent,/Enter or select/);input($('answer-'+numeric.id),'1/0');click(document.querySelector(`[data-check="${numeric.id}"]`));assert.match($('feedback-'+numeric.id).textContent,/finite number/);assert.match($('attemptedCount').textContent,/^0\b/);
for(const q of Q.questions){const el=document.querySelector(`[data-question="${q.id}"]`);if(q.type==='number')input(el.querySelector('[data-response]'),q.answer);else{for(const r of el.querySelectorAll('input[type="radio"]'))r.checked=Number(r.value)===q.answer;el.querySelector('input:checked').dispatchEvent(new dom.Event('input',{bubbles:true}));}click(el.querySelector('[data-check]'));assert.match($('feedback-'+q.id).textContent,/Correct/,'Lesson '+n+' answer '+q.id);}
assert.equal($('correctCount').textContent,'58');click(document.querySelector('[data-solution="ap01"]'));assert.equal($('solution-ap01').hidden,false);assert.equal($('reviewedCount').textContent,'1');input($('answer-'+numeric.id),'999');assert.equal($('correctCount').textContent,'57');flush();assert.equal(JSON.parse(storage.get(`echs:ap-calculus:1.${n}:interactive-v1:fixture-student-a`)).answers[numeric.id].value,'999');assert.ok(!storage.has(`echs:ap-calculus:1.${n===3?4:3}:interactive-v1:fixture-student-a`));
const A=win.Laws15;
for(const a of [-2,0,2])for(const b of [-3,0,3])for(const op of ['linear','product','power','quotient']){input($('lawA'),a);input($('lawB'),b);input($('lawOperation'),op);const result=A.combine(a,b,op);input($('lawAllowed'),result.valid?'yes':'no');if(result.valid)input($('lawPrediction'),result.value);click($('checkLaw'));assert.match($('lawFeedback').textContent,/Correct/);assert.equal($('lawResult').hidden,false);input($('lawAllowed'),'');assert.equal($('lawResult').hidden,true);click($('checkLaw'));assert.doesNotMatch($('lawFeedback').textContent,/Correct/);assert.equal($('lawRows').children.length,4);}
for(let i=0;i<3;i++)for(const op of ['linear','product','quotient']){input($('sideCase'),i);input($('sideOperation'),op);const s=A.sideResult(i,op);input($('sideAllowed'),s.valid?'yes':'no');if(s.valid){input($('sideLeft'),s.left);input($('sideRight'),s.right);input($('sideBoth'),s.both);}click($('checkSides'));assert.match($('sideFeedback').textContent,/Correct/);assert.ok($('sideFGraph').querySelector('svg'));assert.ok($('sideGGraph').querySelector('svg'));input($('sideAllowed'),'');click($('checkSides'));assert.doesNotMatch($('sideFeedback').textContent,/Correct/);}
for(const key of Object.keys(A.roots))for(const n of [2,3]){input($('rootModel'),key);input($('rootIndex'),n);const r=A.rootCase(key,n);input($('rootDomain'),r.domain);if(r.domain!=='none')input($('rootPrediction'),r.value);click($('checkRoot'));assert.match($('rootFeedback').textContent,/Correct/);assert.equal(Boolean($('rootGraph').querySelector('svg')),r.domain!=='none');input($('rootDomain'),'');click($('checkRoot'));assert.doesNotMatch($('rootFeedback').textContent,/Correct/);}
for(const key of Object.keys(A.quotients)){input($('quotientCase'),key);const q=A.quotients[key];input($('quotientLeft'),q.left);input($('quotientRight'),q.right);input($('quotientBoth'),q.both);click($('checkQuotient'));assert.match($('quotientFeedback').textContent,/Correct/);input($('quotientBoth'),'');click($('checkQuotient'));assert.doesNotMatch($('quotientFeedback').textContent,/Correct/);}
for(const s of A.substitutions){input($('substitutionAllowed'),s.allowed?'yes':'no');if(s.allowed)input($('substitutionPrediction'),s.value);click($('checkSubstitution'));assert.match($('substitutionFeedback').textContent,/Correct/);input($('substitutionAllowed'),'');click($('checkSubstitution'));assert.doesNotMatch($('substitutionFeedback').textContent,/Correct/);click($('nextSubstitution'));}
for(const L of [-2,0,1,4])for(const outer of ['poly','root','reciprocal']){input($('compositionL'),L);input($('compositionOuter'),outer);const c=A.composite(L,outer);input($('compositionAllowed'),c.valid?'yes':'no');if(c.valid)input($('compositionPrediction'),c.value);click($('checkComposition'));assert.match($('compositionFeedback').textContent,/Correct/);input($('compositionAllowed'),'');click($('checkComposition'));assert.doesNotMatch($('compositionFeedback').textContent,/Correct/);assert.equal($('compositionRows').children.length,4);}
for(let i=0;i<3;i++){input($('reverseCase'),i);const r=A.reverse[i];input($('reverseA'),r.answers[0]);input($('reverseB'),r.answers[1]);click($('checkReverse'));assert.match($('reverseFeedback').textContent,/Correct/);assert.equal($('reverseA').previousSibling.textContent,r.labels[0]);input($('reverseA'),'');click($('checkReverse'));assert.doesNotMatch($('reverseFeedback').textContent,/Correct/);}
for(const key of Object.keys(A.directional)){input($('directionMode'),key);input($('directionPrediction'),A.directional[key].both);click($('checkDirection'));assert.match($('directionFeedback').textContent,/Correct/);assert.equal($('directionRows').children.length,4);input($('directionPrediction'),'');click($('checkDirection'));assert.doesNotMatch($('directionFeedback').textContent,/Correct/);}
assert.equal(document.querySelectorAll('[data-laws-plot] svg').length,6,'All retained graph panels render');
for(const f of Q.frqs)for(let i=0;i<3;i++){const id=f.id+'-'+i;click(document.querySelector(`[data-rubric="${id}"]`));assert.equal($('rubric-'+id).hidden,true);input($('draft-'+id),'My written justification names the law and checks its conditions.');click(document.querySelector(`[data-rubric="${id}"]`));assert.equal($('rubric-'+id).hidden,false);assert.equal($('score-'+id).disabled,false);input($('draft-'+id),'');assert.equal($('rubric-'+id).hidden,true);assert.equal($('score-'+id).disabled,true);}
for(const graph of document.querySelectorAll('svg.graph')){assert.doesNotMatch(graph.outerHTML,/NaN|Infinity/);assert.ok(graph.getAttribute('aria-label'));assert.ok(graph.querySelector('title'));}assert.equal(document.querySelectorAll('.math-fallback').length,0,'No authored or generated equation failed');
click(document.querySelector(`[data-rubric="${part}"]`));assert.equal($('rubric-'+part).hidden,true);input($('draft-'+part),'My reasoning uses both one-sided trends and separates the point value.');click(document.querySelector(`[data-rubric="${part}"]`));assert.equal($('rubric-'+part).hidden,false);$('score-'+part).value='3';$('score-'+part).dispatchEvent(new dom.Event('change',{bubbles:true}));assert.match($('frqSummary').textContent,/3 points across 1/);input($('draft-'+part),'Revised: compare both sides and explain the available evidence.');assert.equal($('rubric-'+part).hidden,true);assert.equal($('score-'+part).disabled,true);assert.match($('frqSummary').textContent,/not been automatically graded/);
flush();account={id:'fixture-student-b'};win.dispatchEvent(new dom.Event('focus'));assert.equal($('answer-'+numeric.id).value,'');assert.equal($('draft-'+part).value,'');assert.equal($('solution-ap01').hidden,true);assert.match($('attemptedCount').textContent,/^0\b/);assert.equal($('feedback-ap01').textContent,'');account={id:'fixture-student-a'};win.dispatchEvent(new dom.Event('focus'));assert.equal($('answer-'+numeric.id).value,'999');assert.match($('draft-'+part).value,/Revised/);assert.equal($('solution-ap01').hidden,true);
failStorage=true;input($('answer-'+numeric.id),numeric.answer);click(document.querySelector(`[data-check="${numeric.id}"]`));assert.match($('feedback-'+numeric.id).textContent,/Correct/);assert.match(document.querySelector('.save-note').textContent,/unavailable/);failStorage=false;
click($('resetWork'));assert.equal($('resetConfirmation').hidden,false);click($('cancelReset'));assert.match($('attemptedCount').textContent,/58/);click($('resetWork'));click($('confirmReset'));assert.equal($('answer-'+numeric.id).value,'');assert.equal($('draft-'+part).value,'');assert.match($('attemptedCount').textContent,/^0\b/);
key(document,'End');assert.equal(current(),'alignment');assert.equal($('nextSlide').disabled,true);key(document,'Home');assert.equal(current(),'start');assert.equal($('previousSlide').disabled,true);let progressed=false;const finish=document.createElement('button');finish.setAttribute('data-finish-lesson','');finish.addEventListener('click',()=>progressed=true);document.body.append(finish);click($('continuePractice'));assert.ok(progressed);
const ids=[...document.querySelectorAll('[id]')].map(el=>el.id);assert.equal(new Set(ids).size,ids.length);for(const el of document.querySelectorAll('[aria-controls]'))assert.ok($(el.getAttribute('aria-controls')));
console.log(`AP Calculus 1.${n} interactions: PASS (58 answers, eight investigations, rubric gates, real equations, scoped drafts, edited work, navigation, storage denial, reset and protected progression)`);
}

runLesson();
