/* Mathematical and authored-content regression for AP graph and table estimation. */
import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),base=new URL('../lessons/ap-calculus/unit-1/',import.meta.url),M=require(new URL('assets/limit-lesson-models.js',base).pathname);
const near=(a,b,t=1e-8)=>assert.ok(Math.abs(a-b)<=t,`${a} should equal ${b}`);
const expected={hole:[1,3,3,6],missing:[-1,2,2,null],jump:[2,1,4,3],negative:[-2,-1,-1,3],corner:[0,0,0,0],smooth:[1,1,1,1],closeJump:[0,2,2.04,2]};
for(const [key,[c,l,r,at]] of Object.entries(expected)){const m=M.graphs[key];assert.equal(m.c,c);assert.equal(M.value(m,c),at);assert.equal(M.limit(m,'left'),l);assert.equal(M.limit(m,'right'),r);assert.equal(M.limit(m),l===r?l:'DNE');for(const [side,answer] of [['left',l],['right',r]]){const row=M.sample(m,1e-7,side);assert.ok(side==='left'?row.x<c:row.x>c);near(row.y,answer,1e-6);}for(const h of [0,-1,Infinity])assert.equal(M.sample(m,h,'left'),null);}
for(const [key,sign,power] of [['reciprocal',1,1],['positiveInfinity',1,2],['negativeInfinity',-1,2]]){const m=M.graphs[key];for(const h of [.1,.01,.001]){near(M.sample(m,h,'left').y,sign/(-h)**power,.00001);near(M.sample(m,h,'right').y,sign/h**power,.00001);}assert.equal(M.value(m,0),null);const data=M.graphData(m);assert.equal(data.series.length,2);assert.ok(data.series[0].every(([x])=>x<0));assert.ok(data.series[1].every(([x])=>x>0));}
assert.equal(M.limit(M.graphs.reciprocal),'DNE');assert.equal(M.limit(M.graphs.positiveInfinity),'infinity');assert.equal(M.limit(M.graphs.negativeInfinity),'-infinity');assert.equal(M.sample(M.graphs.endpoint,.1,'left'),null);near(M.sample(M.graphs.endpoint,.01,'right').y,.1);
for(const [c,l,r,at] of [[-2,2,2,4],[0,0,0,0],[1,1,-1,3],[3,1,1,1]]){const m=M.clinic(c);assert.equal(m.left,l);assert.equal(m.right,r);near(M.value(m,c),at);near(M.sample(m,1e-7,'left').y,l,1e-6);near(M.sample(m,1e-7,'right').y,r,1e-6);}
for(const n of [1,10,100]){const s=M.oscillationSamples(n);near(Math.sin(1/s.upper),1);near(Math.sin(1/s.lower),-1);near(s.dampedUpper,s.upper);near(s.dampedLower,-s.lower);assert.ok(s.upper>0&&s.lower>0);}
for(const key of ['oscillation','damping'])for(const span of [.5,.2,.05]){const m=M.graphs[key],data=M.graphData(m,[-span,span]);assert.equal(data.unresolved,span/20);for(const series of data.series)for(const [x,y] of series){assert.ok(Math.abs(x)>=data.unresolved-1e-12);near(y,m.fn(x));assert.ok(Math.abs(y)<=(key==='damping'?Math.abs(x):1)+1e-12);}}
assert.equal(M.inputDesign(-3,'-3.1,-3.01,-3.001','-2.9,-2.99,-2.999').valid,true);assert.equal(M.inputDesign(0,'-.1,-.01,-.001','.1,.01,.001').valid,true);
for(const [l,r] of [['1.9,2,1.99','2.1,2.01,2.001'],['1.999,1.99,1.9','2.1,2.01,2.001'],['1.9,1.99','2.1,2.01,2.001'],['1.9,1.99,NaN','2.1,2.01,2.001'],['1.9,1.99,1.99','2.1,2.01,2.001']])assert.equal(M.inputDesign(2,l,r).valid,false);
for(const [key,c,l,r,at] of [['hole',2,4,4,null],['square',2,4,4,4],['zero',-1,0,0,5],['constant',3,-2,-2,7],['jump',2,1,4,3],['subtle',0,1,1.0004,null]]){const m=M.tables[key];assert.equal(m.c,c);assert.equal(M.value(m,c),at);const rows=M.tableRows(m);assert.equal(rows.length,3);for(const row of rows){assert.ok(row.left.x<c&&row.right.x>c);}near(M.sample(m,1e-7,'left').y,l,1e-6);near(M.sample(m,1e-7,'right').y,r,1e-6);}
for(const row of M.tableRows(M.tables.subtle,[.0001,.00001,.000001])){assert.equal(M.format(row.left.y,2),'1.00');assert.equal(M.format(row.right.y,2),'1.00');assert.notEqual(M.format(row.left.y,6),M.format(row.right.y,6));assert.notEqual(M.format(row.left.x,10),'0.0000000000');}
near(M.calculatorModel('sinc','radians').fn(.001),.9999998333333416,1e-12);near(M.calculatorModel('sinc','degrees').fn(.001),Math.PI/180,1e-10);near(M.calculatorModel('exponential').fn(.001),.693387462581,1e-12);near(M.calculatorModel('exponential').fn(-.001),.692907009547,1e-12);assert.equal(M.calculatorModel('invalid'),null);
for(const n of [1,10,100,1000]){const s=M.aliasSamples(n);near(Math.sin(Math.PI/s.zero.x),0,1e-10);near(Math.sin(Math.PI/s.upper.x),1);near(Math.sin(Math.PI/s.lower.x),-1);assert.ok(s.upper.x>0&&s.lower.x>0);}
const listed=[1.9,1.99,2.01,2.1],f=x=>x+2,g=x=>listed.includes(x)?x+2:8;for(const x of listed)near(f(x),g(x));for(const h of [.009,.001,.0001]){near(g(2-h),8);near(g(2+h),8);}
for(const s of ['',' ','1/0','NaN','2+2','0x10','DNE!','9'.repeat(400)+'/2'])assert.equal(M.parseAnswer(s),null);for(const [s,a] of [['0',0],['-3/2',-1.5],['−1',-1],['DNE','DNE'],['undefined','undefined'],['+∞','infinity'],['−infinity','-infinity']])assert.equal(M.parseAnswer(s),a);assert.ok(!M.correctAnswer('',0));assert.ok(!M.correctAnswer('DNE','infinity'));assert.ok(!M.correctAnswer('undefined','DNE'));
const katex=vm.createContext({window:{},console});vm.runInContext(fs.readFileSync(new URL('../lessons/ib-math-ai/unit-1/assets/js/katex-global.js',import.meta.url),'utf8'),katex);
const decode=s=>s.replace(/&quot;/g,'"').replace(/&#x27;|&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');let equationCount=0;
for(const n of [3,4]){const type=n===3?'graphs':'tables',html=fs.readFileSync(new URL(`1-${n}-estimating-limit-values-from-${type}.html`,base),'utf8'),Q=require(new URL(`assets/lesson-1-${n}-questions.js`,base).pathname);assert.equal(Q.questions.length,24);const mcqs=Q.questions.filter(q=>q.group==='AP-style MCQ');assert.equal(mcqs.length,16);assert.deepEqual(mcqs.map(q=>q.answer),[2,0,3,1,2,3,0,1,3,2,1,0,2,0,3,1]);for(const q of Q.questions){assert.ok(q.hint&&q.solution);if(q.type==='mcq'){assert.equal(q.choices.length,4);assert.equal(new Set(q.choices).size,4);}}assert.equal(Q.frqs.length,3);for(const f of Q.frqs){assert.equal(f.parts.length,3);for(const p of f.parts)assert.equal((p.rubric.match(/1 point:/g)||[]).length,3);}
 const numeric=n===3?{'read-left':3,'read-right':3,'read-both':3,'read-point':6,'endpoint-check':0,'exit-limit':-1}:{'table-left':2,'table-right':2,'table-point':9,'sides-check':'DNE','exit-estimate':1.5};for(const [id,a] of Object.entries(numeric))assert.equal(Q.questions.find(q=>q.id===id).answer,a);
 const equations=[...html.matchAll(/data-tex="([^"]+)"/g)].map(m=>decode(m[1]));const walk=v=>{if(typeof v==='string')equations.push(...[...v.matchAll(/\\\((.*?)\\\)/gs)].map(m=>m[1]));else if(v&&typeof v==='object')Object.values(v).forEach(walk);};walk(Q);equations.push(...Object.values(M.tables).map(m=>m.tex));for(const tex of equations)assert.doesNotThrow(()=>katex.window.katex.renderToString(tex,{throwOnError:true,strict:'ignore'}),tex);equationCount+=equations.length;
 assert.equal((html.match(/class="slide"/g)||[]).length,35);const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);assert.deepEqual([...html.matchAll(/data-question="([^"]+)"/g)].map(m=>m[1]).sort(),Q.questions.map(q=>q.id).sort());assert.match(html,/LIM-1\.C/);assert.match(html,/mathematical practice 2\.B/);assert.ok(!html.includes('data:image'));
 const legacyName=n===3?'1-3-properties-of-limits':'1-4-limits-of-composite-functions',legacy=fs.readFileSync(new URL('../lessons/ap-calculus/'+legacyName+'.html',import.meta.url),'utf8');let redirected;vm.runInNewContext(legacy.match(/<script>([\s\S]*?)<\/script>/)[1],{URL,location:{href:`https://example.test/ECHS-Math/lessons/ap-calculus/${legacyName}.html?course=ap-calculus&lessonKey=l${n}&accessKey=a${n}#slide=4`,replace:url=>redirected=url},document:{getElementById:()=>({})}});assert.equal(redirected,`https://example.test/ECHS-Math/lessons/ap-calculus/unit-1/1-${n}-estimating-limit-values-from-${type}.html?course=ap-calculus&lessonKey=l${n}&accessKey=a${n}#slide=4`);
}
const runtime=fs.readFileSync(new URL('assets/limit-lesson-core.js',base),'utf8');assert.match(runtime,/\[data-finish-lesson\]/);assert.doesNotMatch(runtime,/markCompleted|recordAttempt|echs_math_complete/);
console.log(`AP Calculus 1.3/1.4: PASS (70 slides, 48 keys, 32 MCQs, six FRQs, ${equationCount} equations, graph branches, oscillation, numerical models, precision, sampling and protected progression)`);
