/* Independently checked algebra, answer keys, source order, and equation rendering. */
import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),base=new URL('../lessons/ap-calculus/unit-1/',import.meta.url),A=require(new URL('assets/lesson-1-6-model.js',base).pathname),Q=require(new URL('assets/lesson-1-6-questions.js',base).pathname);
const near=(a,b,t=1e-8)=>assert.ok(Math.abs(a-b)<=t,`${a} should equal ${b}`);
for(const [co,c,quot,rem] of [[[1,3,0,-3,-1],-1,[1,2,-2,-1],0],[[1,-5,3,9,-8],3,[1,-2,-3,0],-8],[[1,-5,3,9,0],3,[1,-2,-3,0],0]]){const d=A.synthetic(co,c);assert.deepEqual(d.quotient,quot);assert.equal(d.remainder,rem);for(const x of [-4,-1,0,1,3,5])near(A.polynomial(co,x),(x-c)*A.polynomial(d.quotient,x)+d.remainder);}
for(const n of [1,2,3,5,7])for(const a of [-3,-1,0,2])for(const x of [-4,-.5,0,1,3]){near((x-a)*A.powerSum(x,a,n),x**n-a**n,1e-7);if(n>1)near(A.powerSum(a,a,n),n*a**(n-1));else assert.equal(A.powerSum(a,a,n),1);}
for(const a of [-8,-1,0,1,8])for(const x of [-27,-2,.25,2,27]){near((Math.cbrt(x)-Math.cbrt(a))*A.rootFactor(x,a),x-a);if(x!==a)near(A.cubeQuotient(x,a),(Math.cbrt(x)-Math.cbrt(a))/(x-a));}assert.equal(A.cubeQuotient(8,8),null);
for(const f of A.factors)for(const x of [-4,-1,0,2,5])near(x*x+f.b*x+f.k,(x-f.r)*(x-f.s));
for(const c of [-2,1,3])for(const at of [null,-4,0,6]){const m=A.hole(c,at);assert.ok(m.range[0]<=(at??2*c)&&m.range[1]>=(at??2*c));for(const x of [c-.1,c+.1])near(m.fn(x),(x*x-c*c)/(x-c));}
for(let a=-8;a<=3;a+=.25){const p=A.productCase(a);assert.equal(9+3*a+p.b,0);assert.equal(9*a*a+6*p.product+p.b*p.b,81);assert.ok(9*a*a+p.b*p.b>0);assert.ok(p.product<27/2);assert.ok(p.product<=27/4);assert.equal(p.gap,27/4-p.product);for(const sign of [-1,1]){const x=3+sign*.00001,v=(x+3)/(x*x+a*x+p.b),label=sign<0?p.left:p.right;assert.equal(Math.sign(v),label==='infinity'?1:-1);}}
const eq=A.productCase(-1.5);assert.equal(eq.b,-4.5);assert.equal(eq.product,6.75);assert.equal(eq.left,'-infinity');assert.equal(eq.right,'infinity');assert.equal(A.productCase(-6).right,'infinity');assert.equal(A.productCase(-6).left,'infinity');
const ap=[{i:1,c:3,f:x=>(x*x-9)/(x-3),a:6},{i:2,c:2,f:x=>(x*x+x-6)/(x-2),a:5},{i:3,c:1,f:x=>(x*x-1)/(x*x-5*x+4),a:-2/3},{i:4,c:4,f:x=>(Math.sqrt(x+5)-3)/(x-4),a:1/6},{i:5,c:4,f:x=>(x-4)/(Math.sqrt(x)-2),a:4},{i:6,c:3,f:x=>(1/x-1/3)/(x-3),a:-1/9},{i:7,c:0,f:x=>(1-Math.cos(x)**2)/Math.sin(x),a:0},{i:8,c:0,f:x=>Math.tan(x)/Math.sin(x),a:1},{i:9,c:2,f:x=>(x*x+4)/(x+2),a:2},{i:11,c:0,f:x=>(Math.sqrt(9+x)-3)/x,a:1/6},{i:12,c:2,f:x=>(x*x-4)/(x*x-x-2),a:4/3},{i:13,c:1,f:x=>(1/(x+1)-.5)/(x-1),a:-.25},{i:14,c:0,f:x=>Math.sin(2*x)/Math.sin(x),a:2}];for(const p of ap)for(const sign of [-1,1])near(p.f(p.c+sign*1e-5),p.a,5e-5);
const ch=[{c:2,f:x=>(x**7-128)/(x-2),a:448,t:.08},{c:-1,f:x=>(x**4+3*x**3-3*x-1)/(x+1),a:2,t:1e-3},{c:2,f:x=>(x*x+4*x+4),a:16,t:1e-3},{c:2,f:x=>(x**3-8)/(Math.sqrt(x+2)-2),a:48,t:.003},{c:8,f:x=>(Math.cbrt(x)-2)/(x-8),a:1/12,t:1e-5},{c:-8,f:x=>(Math.cbrt(x)+2)/(x+8),a:1/12,t:1e-5},{c:0,f:x=>(Math.sqrt(3+Math.sqrt(9+x))-Math.sqrt(6))/x,a:1/(12*Math.sqrt(6)),t:1e-5},{c:0,f:x=>(Math.sqrt(1+x)+Math.sqrt(1-x)-2)/(x*x),a:-.25,t:1e-5},{c:0,f:x=>Math.sin(3*x)/Math.sin(5*x),a:.6,t:1e-5},{c:0,f:x=>(1-Math.cos(4*x))/(x*Math.sin(2*x)),a:4,t:1e-5},{c:0,f:x=>(Math.tan(2*x)-Math.sin(2*x))/x**3,a:4,t:1e-4},{c:0,f:x=>(Math.sqrt(1+Math.sin(3*x))-1)/x,a:1.5,t:1e-3}];for(const p of ch)for(const sign of [-1,1])near(p.f(p.c+sign*1e-4),p.a,p.t);
// Parameter and common-root identities verify full written solutions.
for(const x of [-2,0,1,2,3,5]){near(x*x+8*x-20,(x-2)*(x+10));near(x**3-27*x+54,(x-3)**2*(x+6));}for(const u of [.9,1.1])near((u**3-u**4)/(u**6-1),-(u**3)/(u**5+u**4+u**3+u*u+u+1));
const apKeys=[2,0,3,1,2,3,0,1,3,2,1,0,2,0,3,1],chKeys=[1,2,0,3,2,1,3,0,1,3,0,2,1,3,0,2];assert.deepEqual(Q.questions.filter(q=>q.group==='AP-style MCQ').map(q=>q.answer),apKeys);assert.deepEqual(Q.questions.filter(q=>q.group.startsWith('Challenge MCQ')).map(q=>q.answer),chKeys);assert.equal(Q.questions.length,38);assert.equal(Q.frqs.length,9);for(const q of Q.questions){assert.ok(q.hint&&q.solution);if(q.type==='mcq'){assert.equal(q.choices.length,4);assert.equal(new Set(q.choices).size,4);}}for(const f of Q.frqs){assert.equal(f.parts.length,3);for(const p of f.parts)assert.equal((p.rubric.match(/1 point:/g)||[]).length,3);}
const proof=Q.frqs.find(f=>f.id==='ch-frq6');assert.match(proof.context,/x\+3/);assert.match(proof.parts[1].rubric,/9a\^2\+6ab\+b\^2=81/);assert.match(proof.parts[1].rubric,/81-6ab=9a\^2\+b\^2>0/);assert.match(proof.parts[1].rubric,/27\/2/);assert.match(proof.parts[2].prompt,/Optional/);
const html=fs.readFileSync(new URL('1-6-algebraic-manipulation.html',base),'utf8');assert.equal((html.match(/class="slide"/g)||[]).length,44);assert.match(html,/LIM-1\.E\.1/);assert.match(html,/mathematical practice 1\.C/);const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);assert.deepEqual([...html.matchAll(/data-question="([^"]+)"/g)].map(m=>m[1]).sort(),Q.questions.map(q=>q.id).sort());assert.deepEqual([...html.matchAll(/data-frq="([^"]+)"/g)].map(m=>m[1]).sort(),Q.frqs.map(f=>f.id).sort());const boundary=html.indexOf('id="challenge-start"');for(const q of Q.questions.filter(q=>q.group.startsWith('Challenge')))assert.ok(html.indexOf(`data-question="${q.id}"`)>boundary);for(const f of Q.frqs.filter(f=>f.group==='AP-style FRQ'))assert.ok(html.indexOf(`data-frq="${f.id}"`)<boundary);assert.ok(html.indexOf('data-question="exit"')<boundary);assert.ok(!html.includes('data:image'));
const katex=vm.createContext({window:{},console});vm.runInContext(fs.readFileSync(new URL('../lessons/ib-math-ai/unit-1/assets/js/katex-global.js',import.meta.url),'utf8'),katex);const decode=s=>s.replace(/&quot;/g,'"').replace(/&#x27;|&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');const equations=[...html.matchAll(/data-tex="([^"]+)"/g)].map(m=>decode(m[1]));function walk(v){if(typeof v==='string')equations.push(...[...v.matchAll(/\\\((.*?)\\\)/gs)].map(m=>m[1]));else if(v&&typeof v==='object')Object.values(v).forEach(walk);}walk(Q);for(const tex of equations)assert.doesNotThrow(()=>katex.window.katex.renderToString(tex,{throwOnError:true,strict:'ignore'}),tex);
console.log(`AP Calculus 1.6 mathematics: PASS (44 slides, 38 keys, 9 FRQs, ${equations.length} equations; factorization, remainders, radicals, trigonometry, parameters, requested squaring proof and strict-bound counterexample)`);
