/* DOM-level interaction regression; no browser, network or production account is used. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {parseHTML}=require(process.env.ECHS_TEST_DOM_MODULE||'linkedom');
const base=new URL('../lessons/ap-calculus/unit-1/',import.meta.url);
const html=fs.readFileSync(new URL('1-1-can-change-occur-at-an-instant.html',base),'utf8');
const {window:dom,document}=parseHTML(html);
// LinkeDOM does not implement the browser's select.value setter or input.checked state.
Object.defineProperty(dom.HTMLSelectElement.prototype,'value',{configurable:true,get(){return this.querySelector('option[selected]')?.value??this.querySelector('option')?.value??'';},set(value){for(const o of this.querySelectorAll('option'))o.toggleAttribute('selected',o.value===String(value));}});
Object.defineProperty(dom.HTMLInputElement.prototype,'checked',{configurable:true,get(){return this.hasAttribute('checked');},set(value){this.toggleAttribute('checked',Boolean(value));}});
const storage=new Map();let account={id:'fixture-student-a'},failStorage=false;
const eventTarget=new dom.EventTarget();
const location={pathname:'/ECHS-Math/lessons/ap-calculus/unit-1/1-1-can-change-occur-at-an-instant.html',search:'?course=ap-calculus&lessonKey=fixture-key&accessKey=fixture-access',hash:''};
const win={document,Calculus11:require(new URL('assets/lesson-1-1-model.js',base).pathname),Calculus11Questions:require(new URL('assets/lesson-1-1-questions.js',base).pathname),ECHSInstitution:{account:()=>account},katex:{render(tex,node){node.textContent=tex;}},addEventListener:eventTarget.addEventListener.bind(eventTarget),dispatchEvent:eventTarget.dispatchEvent.bind(eventTarget),print(){}};
const scheduled=new Map();let timer=0;
const context=vm.createContext({window:win,document,location,history:{replaceState(_s,_t,url){const value=new URL(url,'https://example.test');assert.equal(value.search,location.search,'Navigation retains protected lesson context');location.hash=value.hash;}},localStorage:{getItem:key=>storage.get(key)||null,setItem(key,value){if(failStorage)throw Error('Storage denied');storage.set(key,value);}},setTimeout:fn=>{scheduled.set(++timer,fn);return timer;},clearTimeout:id=>scheduled.delete(id),console});
vm.runInContext(fs.readFileSync(new URL('assets/lesson-1-1.js',base),'utf8'),context);
const $=id=>document.getElementById(id),click=node=>node.dispatchEvent(new dom.Event('click',{bubbles:true}));
const input=(node,value)=>{node.value=String(value);node.dispatchEvent(new dom.Event('input',{bubbles:true}));};
const key=(node,key)=>{const e=new dom.Event('keydown',{bubbles:true,cancelable:true});Object.defineProperty(e,'key',{value:key});node.dispatchEvent(e);};
const current=()=>document.querySelector('.slide:not([hidden])')?.id;
const flush=()=>{const callbacks=[...scheduled.values()];scheduled.clear();for(const fn of callbacks)fn();};
assert.equal(document.documentElement.dataset.calculus11Ready,'true');assert.equal(document.querySelectorAll('.slide:not([hidden])').length,1);assert.equal(document.querySelectorAll('[data-check]').length,20);assert.equal(document.querySelectorAll('[data-rubric]').length,9);
assert.ok(document.querySelectorAll('svg.graph').length>=8,'All investigations and question graphs render');
for(const graph of document.querySelectorAll('svg.graph'))assert.doesNotMatch(graph.outerHTML,/NaN|Infinity/);
assert.equal(current(),'start');click($('nextSlide'));assert.equal(current(),'roadmap');key(document,'ArrowRight');assert.equal(current(),'classify');
const before=current();key($('secantA'),'ArrowRight');assert.equal(current(),before,'Range keys change the control, not the slide');key($('calcAt'),'Home');assert.equal(current(),before);
click(document.querySelector('[data-solution="launch"]'));assert.equal($('solution-launch').hidden,true,'No solution before an attempt');click(document.querySelector('[data-check="launch"]'));assert.match($('feedback-launch').textContent,/select an answer/);
click(document.querySelector('[data-hint="launch"]'));assert.equal($('hint-launch').hidden,false);
input($('answer-bike-distance'),'');click(document.querySelector('[data-check="bike-distance"]'));assert.match($('feedback-bike-distance').textContent,/Enter or select/);
input($('answer-bike-distance'),'1/0');click(document.querySelector('[data-check="bike-distance"]'));assert.match($('feedback-bike-distance').textContent,/finite number/);
assert.match($('attemptedCount').textContent,/^0\b/);
for(const q of win.Calculus11Questions.questions){const el=document.querySelector(`[data-question="${q.id}"]`);if(q.type==='number')input(el.querySelector('[data-response]'),q.answer);else{for(const radio of el.querySelectorAll('input[type="radio"]'))radio.checked=Number(radio.value)===q.answer;el.querySelector('input:checked').dispatchEvent(new dom.Event('input',{bubbles:true}));}click(el.querySelector('[data-check]'));assert.match($('feedback-'+q.id).textContent,/Correct/,'Correct answer for '+q.id);}
assert.equal($('correctCount').textContent,'20');click(document.querySelector('[data-solution="ap01"]'));assert.equal($('solution-ap01').hidden,false);assert.equal($('reviewedCount').textContent,'1');
input($('answer-bike-distance'),'1800');assert.equal($('correctCount').textContent,'19','Edited answers no longer retain correct status');flush();assert.equal(JSON.parse(storage.get('echs:ap-calculus:1.1:interactive-v1:fixture-student-a')).answers['bike-distance'].value,'1800','An unchecked draft is saved');
input($('secantA'),2);input($('secantB'),2);assert.equal($('secantResult').textContent,'undefined');assert.match($('secantExplanation').textContent,/0\/0/);input($('secantB'),3);assert.equal($('secantResult').textContent,'5.000 m/s');input($('secantModel'),'falling');assert.equal($('secantResult').textContent,'-5.000 m/s');
input($('bikeTime'),5);assert.equal($('bikePosition').textContent,'700.0 m');assert.equal($('bikeDistance').textContent,'1300.0 m');input($('bikeTime'),0);assert.match($('bikeAverageSpeed').textContent,/undefined/);input($('bikeTime'),8);assert.equal($('bikeAverageSpeed').textContent,'237.50 m/min');
input($('dropShrink'),3);input($('dropSide'),'left');assert.equal($('dropSlope').textContent,'22.2400 ft/s');click($('dropCapture'));assert.equal($('capturedRates').children.length,1);click($('dropCapture'));assert.equal($('capturedRates').children.length,1,'No duplicate captured interval');click($('dropZero'));assert.match($('dropSlope').textContent,/undefined/);click($('dropCapture'));assert.equal($('capturedRates').children.length,1);input($('dropSide'),'right');assert.equal($('dropSlope').textContent,'22.5600 ft/s');click($('dropCompare'));assert.equal($('dropTangent').textContent,'22.4000 ft/s');
input($('tangentSlope'),4);click($('checkTangent'));assert.match($('tangentFeedback').textContent,/Correct/);input($('tangentModel'),'cube');input($('tangentSlope'),0);click($('checkTangent'));assert.match($('tangentFeedback').textContent,/crosses/);
assert.match($('calcTable').textContent,/-4\.798514/);input($('calcAt'),0);assert.equal($('calcTable').children.length,0);assert.match($('calculatorFeedback').textContent,/inside/);input($('calcModel'),'moon');assert.equal($('calcAt').value,'7');assert.equal($('calcTable').children.length,3);
input($('cornerShrink'),3);assert.equal($('cornerLeft').textContent,'-1.000 m/s');assert.equal($('cornerRight').textContent,'1.000 m/s');assert.equal($('cornerCenter').textContent,'0.000 m/s');
click(document.querySelector('[data-rubric="frq-tank-0"]'));assert.equal($('rubric-frq-tank-0').hidden,true);input($('draft-frq-tank-0'),'The amount decreases by 60 litres in 8 minutes, so the average rate is -7.5 L/min.');click(document.querySelector('[data-rubric="frq-tank-0"]'));assert.equal($('rubric-frq-tank-0').hidden,false);assert.equal($('score-frq-tank-0').disabled,false);$('score-frq-tank-0').value='3';$('score-frq-tank-0').dispatchEvent(new dom.Event('change',{bubbles:true}));assert.match($('frqSummary').textContent,/3 points across 1/);
for(const row of document.querySelectorAll('[data-classification]'))row.querySelector('select').value=row.dataset.classification;click($('checkClassification'));assert.match($('classificationSummary').textContent,/5 correct from 5/);
flush();account={id:'fixture-student-b'};win.dispatchEvent(new dom.Event('focus'));assert.equal($('answer-bike-distance').value,'');assert.equal($('draft-frq-tank-0').value,'');assert.equal($('solution-ap01').hidden,true);assert.equal($('rubric-frq-tank-0').hidden,true);assert.match($('attemptedCount').textContent,/^0\b/);assert.equal($('feedback-ap01').textContent,'','Another account never sees prior answer feedback');
account={id:'fixture-student-a'};win.dispatchEvent(new dom.Event('focus'));assert.equal($('answer-bike-distance').value,'1800');assert.match($('draft-frq-tank-0').value,/-7\.5/);assert.equal($('solution-ap01').hidden,true,'Solutions start concealed after account restore');
failStorage=true;input($('answer-bike-distance'),1900);click(document.querySelector('[data-check="bike-distance"]'));assert.match($('feedback-bike-distance').textContent,/Correct/);assert.match(document.querySelector('.save-note').textContent,/unavailable/);failStorage=false;
click($('resetWork'));assert.equal($('resetConfirmation').hidden,false);click($('cancelReset'));assert.match($('attemptedCount').textContent,/20/);click($('resetWork'));click($('confirmReset'));assert.equal($('answer-bike-distance').value,'');assert.equal($('draft-frq-tank-0').value,'');assert.match($('attemptedCount').textContent,/^0\b/);
key(document,'End');assert.equal(current(),'alignment');assert.equal($('nextSlide').disabled,true);key(document,'Home');assert.equal(current(),'start');assert.equal($('previousSlide').disabled,true);
const ids=[...document.querySelectorAll('[id]')].map(el=>el.id);assert.equal(new Set(ids).size,ids.length,'Generated question, rubric and graph IDs remain unique');
for(const el of document.querySelectorAll('[aria-controls]'))assert.ok($(el.getAttribute('aria-controls')),el.getAttribute('aria-controls'));
console.log('AP Calculus 1.1 UI: PASS (actual lesson scripts, all 20 answer checks, 6 graph investigations, rubric gates, navigation, scoped drafts, reset, denied storage)');
