/* DOM-level interaction regression; no browser, network or production account is used. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {parseHTML}=require(process.env.ECHS_TEST_DOM_MODULE||'linkedom');
const base=new URL('../lessons/ap-calculus/unit-1/',import.meta.url);

function runLesson(n=6){
const html=fs.readFileSync(new URL('1-6-algebraic-manipulation.html',base),'utf8');
const {window:dom,document}=parseHTML(html);
// LinkeDOM does not implement the browser's select.value setter or input.checked state.
Object.defineProperty(dom.HTMLSelectElement.prototype,'value',{configurable:true,get(){return this.querySelector('option[selected]')?.value??this.querySelector('option')?.value??'';},set(value){for(const o of this.querySelectorAll('option'))o.toggleAttribute('selected',o.value===String(value));}});
Object.defineProperty(dom.HTMLInputElement.prototype,'checked',{configurable:true,get(){return this.hasAttribute('checked');},set(value){this.toggleAttribute('checked',Boolean(value));}});
const storage=new Map();let account={id:'fixture-student-a'},failStorage=false;
const eventTarget=new dom.EventTarget();
const location={pathname:'/ECHS-Math/lessons/ap-calculus/unit-1/1-6-algebraic-manipulation.html',search:'?course=ap-calculus&lessonKey=fixture-key&accessKey=fixture-access',hash:''};
const renderedMath=vm.createContext({window:{},console});vm.runInContext(fs.readFileSync(new URL('../lessons/ib-math-ai/unit-1/assets/js/katex-global.js',import.meta.url),'utf8'),renderedMath);
const win={document,LimitLessonModels:require(new URL('assets/limit-lesson-models.js',base).pathname),LimitLessonQuestions:require(new URL(`assets/lesson-1-${n}-questions.js`,base).pathname),ECHSInstitution:{account:()=>account},katex:{render(tex,node){renderedMath.window.katex.renderToString(tex,{throwOnError:true,strict:"ignore"});node.textContent=tex;}},addEventListener:eventTarget.addEventListener.bind(eventTarget),dispatchEvent:eventTarget.dispatchEvent.bind(eventTarget),print(){}};
const scheduled=new Map();let timer=0;
const context=vm.createContext({window:win,document,location,history:{replaceState(_s,_t,url){const value=new URL(url,'https://example.test');assert.equal(value.search,location.search,'Navigation retains protected lesson context');location.hash=value.hash;}},localStorage:{getItem:key=>storage.get(key)||null,setItem(key,value){if(failStorage)throw Error('Storage denied');storage.set(key,value);}},setTimeout:fn=>{scheduled.set(++timer,fn);return timer;},clearTimeout:id=>scheduled.delete(id),console});
for(const file of ['limit-lesson-graphs.js','lesson-1-6-model.js',`lesson-1-${n}-labs.js`,'limit-lesson-core.js'])vm.runInContext(fs.readFileSync(new URL('assets/'+file,base),'utf8'),context);
const $=id=>document.getElementById(id),click=node=>node.dispatchEvent(new dom.Event('click',{bubbles:true}));
const input=(node,value)=>{node.value=String(value);node.dispatchEvent(new dom.Event('input',{bubbles:true}));};
const key=(node,key)=>{const e=new dom.Event('keydown',{bubbles:true,cancelable:true});Object.defineProperty(e,'key',{value:key});node.dispatchEvent(e);};
const current=()=>document.querySelector('.slide:not([hidden])')?.id;
const flush=()=>{const callbacks=[...scheduled.values()];scheduled.clear();for(const fn of callbacks)fn();};
const M=win.LimitLessonModels,Q=win.LimitLessonQuestions,numeric=Q.questions.find(q=>q.type==='number'),part=Q.frqs[0].id+'-0';
assert.equal(document.documentElement.dataset.limitLessonReady,'true');assert.equal(document.querySelectorAll('.slide:not([hidden])').length,1);assert.equal(document.querySelectorAll('[data-check]').length,38);assert.equal(document.querySelectorAll('[data-rubric]').length,27);
assert.equal(current(),'start');click($('nextSlide'));assert.equal(current(),'roadmap');key(document,'ArrowRight');assert.equal(current(),'routine');const before=current();key($('holeDistance'),'ArrowRight');assert.equal(current(),before);
click(document.querySelector('[data-solution="launch"]'));assert.equal($('solution-launch').hidden,true);click(document.querySelector('[data-check="launch"]'));assert.match($('feedback-launch').textContent,/select an answer/);click(document.querySelector('[data-hint="launch"]'));assert.equal($('hint-launch').hidden,false);
input($('answer-'+numeric.id),'');click(document.querySelector(`[data-check="${numeric.id}"]`));assert.match($('feedback-'+numeric.id).textContent,/Enter or select/);input($('answer-'+numeric.id),'1/0');click(document.querySelector(`[data-check="${numeric.id}"]`));assert.match($('feedback-'+numeric.id).textContent,/finite number/);assert.match($('attemptedCount').textContent,/^0\b/);
for(const q of Q.questions){const el=document.querySelector(`[data-question="${q.id}"]`);if(q.type==='number')input(el.querySelector('[data-response]'),q.answer);else{for(const r of el.querySelectorAll('input[type="radio"]'))r.checked=Number(r.value)===q.answer;el.querySelector('input:checked').dispatchEvent(new dom.Event('input',{bubbles:true}));}click(el.querySelector('[data-check]'));assert.match($('feedback-'+q.id).textContent,/Correct/,'Lesson '+n+' answer '+q.id);}
assert.equal($('correctCount').textContent,'38');click(document.querySelector('[data-solution="ap01"]'));assert.equal($('solution-ap01').hidden,false);assert.equal($('reviewedCount').textContent,'1');input($('answer-'+numeric.id),'999');assert.equal($('correctCount').textContent,'37');flush();assert.equal(JSON.parse(storage.get(`echs:ap-calculus:1.${n}:interactive-v1:fixture-student-a`)).answers[numeric.id].value,'999');assert.ok(!storage.has(`echs:ap-calculus:1.${n===3?4:3}:interactive-v1:fixture-student-a`));
const A=win.Algebra16;
for(const d of A.diagnosis){input($('diagnosisForm'),d.form);input($('diagnosisMethod'),d.method);click($('checkDiagnosis'));assert.match($('diagnosisFeedback').textContent,/Correct/);input($('diagnosisMethod'),'');assert.equal($('diagnosisFeedback').textContent,'');click($('checkDiagnosis'));assert.doesNotMatch($('diagnosisFeedback').textContent,/Correct/);click($('nextDiagnosis'));}
for(let i=0;i<A.factors.length;i++){const f=A.factors[i];input($('factorCase'),i);input($('factorRoot'),f.s);input($('factorLimit'),f.r-f.s);click($('checkFactor'));assert.match($('factorFeedback').textContent,/Correct/);assert.equal($('factorResult').hidden,false);input($('factorLimit'),'');assert.equal($('factorResult').hidden,true);click($('checkFactor'));assert.doesNotMatch($('factorFeedback').textContent,/Correct/);}
for(const c of [-2,1,3])for(const at of ['missing',-4,6]){input($('holeTarget'),c);input($('holePoint'),at);input($('holeDistance'),4);input($('holePrediction'),2*c);click($('checkHole'));assert.match($('holeFeedback').textContent,/Correct/);assert.equal($('holeRows').children.length,2);assert.ok($('holeGraph').querySelector('svg'));assert.match($('holeCenter').textContent,new RegExp(at==='missing'?'undefined':String(at)));}
for(const [mode,a] of [['numerator','1/6'],['denominator',4]]){input($('radicalCase'),mode);input($('radicalPartner'),'plus');input($('radicalPrediction'),a);click($('checkRadical'));assert.match($('radicalFeedback').textContent,/Correct/);assert.equal($('radicalResult').hidden,false);input($('radicalPartner'),'minus');assert.equal($('radicalResult').hidden,true);click($('checkRadical'));assert.doesNotMatch($('radicalFeedback').textContent,/Correct/);}
for(const c of [2,3,4]){input($('fractionTarget'),c);input($('fractionA'),-1);input($('fractionB'),c);input($('fractionPrediction'),`-1/${c*c}`);click($('checkFraction'));assert.match($('fractionFeedback').textContent,/Correct/);input($('fractionA'),'');click($('checkFraction'));assert.doesNotMatch($('fractionFeedback').textContent,/Correct/);}
for(let i=0;i<3;i++){input($('trigCase'),i);input($('trigRewrite'),A.trig[i].choice);input($('trigPrediction'),A.trig[i].limit);click($('checkTrig'));assert.match($('trigFeedback').textContent,/Correct/);assert.equal($('trigResult').hidden,false);input($('trigPrediction'),'');assert.equal($('trigResult').hidden,true);click($('checkTrig'));assert.doesNotMatch($('trigFeedback').textContent,/Correct/);}
for(const [index,row] of [[0,[1,2,-2,-1,0]],[1,[1,-2,-3,0,-8]],[2,[1,-2,-3,0,0]]]){input($('syntheticCase'),index);input($('syntheticEntry'),'');click($('checkSynthetic'));assert.doesNotMatch($('syntheticFeedback').textContent,/Correct/);for(const value of row){input($('syntheticEntry'),value);click($('checkSynthetic'));assert.match($('syntheticFeedback').textContent,/Correct/);}assert.equal($('checkSynthetic').disabled,true);assert.match($('syntheticConclusion').textContent,/Remainder/);click($('resetSynthetic'));assert.equal($('checkSynthetic').disabled,false);assert.ok($('syntheticTable').textContent.includes('?'));}
for(const a of [-8,0,1,8]){input($('cubeTarget'),a);input($('cubeMultiplier'),'correct');input($('cubePrediction'),a===0?'infinity':1/(3*Math.cbrt(a)**2));click($('checkCube'));assert.match($('cubeFeedback').textContent,/Correct/);assert.equal($('cubeResult').hidden,false);input($('cubePrediction'),'DNE');assert.equal($('cubeResult').hidden,true);click($('checkCube'));assert.doesNotMatch($('cubeFeedback').textContent,/Correct/);}input($('cubeTarget'),0);input($('cubeMultiplier'),'sum');input($('cubePrediction'),'infinity');click($('checkCube'));assert.match($('cubeFeedback').textContent,/Correct/);
for(const a of [-8,-6,-1.5,0,3]){input($('productA'),a);const p=A.productCase(a);assert.equal(Number($('productB').textContent),p.b);assert.equal(Number($('productValue').textContent),p.product);assert.equal(Number($('productGap').textContent),p.gap);input($('productClaim'),'sharp');click($('checkProduct'));assert.match($('productFeedback').textContent,/Correct/);input($('productClaim'),'strict');click($('checkProduct'));assert.doesNotMatch($('productFeedback').textContent,/Correct/);if(a===-1.5)assert.equal($('productGap').textContent,'0');if(a===-6)assert.match($('productSides').textContent,/both sides are positive/);}
// Each of the 27 written parts independently gates its rubric and self-assessment.
for(const f of Q.frqs)for(let i=0;i<3;i++){const id=f.id+'-'+i;click(document.querySelector(`[data-rubric="${id}"]`));assert.equal($('rubric-'+id).hidden,true);input($('draft-'+id),'An original explanation with an exact equivalent expression.');click(document.querySelector(`[data-rubric="${id}"]`));assert.equal($('rubric-'+id).hidden,false);assert.equal($('score-'+id).disabled,false);input($('draft-'+id),'');assert.equal($('rubric-'+id).hidden,true);assert.equal($('score-'+id).disabled,true);}
for(const graph of document.querySelectorAll('svg.graph')){assert.doesNotMatch(graph.outerHTML,/NaN|Infinity/);assert.ok(graph.getAttribute('aria-label'));assert.ok(graph.querySelector('title'));}assert.equal(document.querySelectorAll('.math-fallback').length,0,'No authored or generated equation failed');
click(document.querySelector(`[data-rubric="${part}"]`));assert.equal($('rubric-'+part).hidden,true);input($('draft-'+part),'My reasoning uses both one-sided trends and separates the point value.');click(document.querySelector(`[data-rubric="${part}"]`));assert.equal($('rubric-'+part).hidden,false);$('score-'+part).value='3';$('score-'+part).dispatchEvent(new dom.Event('change',{bubbles:true}));assert.match($('frqSummary').textContent,/3 points across 1/);input($('draft-'+part),'Revised: compare both sides and explain the available evidence.');assert.equal($('rubric-'+part).hidden,true);assert.equal($('score-'+part).disabled,true);assert.match($('frqSummary').textContent,/not been automatically graded/);
flush();account={id:'fixture-student-b'};win.dispatchEvent(new dom.Event('focus'));assert.equal($('answer-'+numeric.id).value,'');assert.equal($('draft-'+part).value,'');assert.equal($('solution-ap01').hidden,true);assert.match($('attemptedCount').textContent,/^0\b/);assert.equal($('feedback-ap01').textContent,'');account={id:'fixture-student-a'};win.dispatchEvent(new dom.Event('focus'));assert.equal($('answer-'+numeric.id).value,'999');assert.match($('draft-'+part).value,/Revised/);assert.equal($('solution-ap01').hidden,true);
failStorage=true;input($('answer-'+numeric.id),numeric.answer);click(document.querySelector(`[data-check="${numeric.id}"]`));assert.match($('feedback-'+numeric.id).textContent,/Correct/);assert.match(document.querySelector('.save-note').textContent,/unavailable/);failStorage=false;
click($('resetWork'));assert.equal($('resetConfirmation').hidden,false);click($('cancelReset'));assert.match($('attemptedCount').textContent,/38/);click($('resetWork'));click($('confirmReset'));assert.equal($('answer-'+numeric.id).value,'');assert.equal($('draft-'+part).value,'');assert.match($('attemptedCount').textContent,/^0\b/);
key(document,'End');assert.equal(current(),'alignment');assert.equal($('nextSlide').disabled,true);key(document,'Home');assert.equal(current(),'start');assert.equal($('previousSlide').disabled,true);let progressed=false;const finish=document.createElement('button');finish.setAttribute('data-finish-lesson','');finish.addEventListener('click',()=>progressed=true);document.body.append(finish);click($('continuePractice'));assert.ok(progressed);
const ids=[...document.querySelectorAll('[id]')].map(el=>el.id);assert.equal(new Set(ids).size,ids.length);for(const el of document.querySelectorAll('[aria-controls]'))assert.ok($(el.getAttribute('aria-controls')));
console.log(`AP Calculus 1.${n} interactions: PASS (38 answers, nine investigations, rubric gates, real equations, scoped drafts, edited work, navigation, storage denial, reset and protected progression)`);
}

runLesson();
