-- Class-specific lesson visibility with automatic sequential progression.
create table if not exists public.lesson_catalog (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  access_key text not null,
  course_key text not null,
  unit_index integer not null check (unit_index >= 0),
  unit_title text not null default '',
  topic text not null,
  title text not null,
  position integer not null check (position >= 0),
  url text not null default '',
  is_ready boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (organization_id, access_key)
);

create index if not exists lesson_catalog_course_position_idx
  on public.lesson_catalog(organization_id, course_key, position);

create table if not exists public.lesson_access_overrides (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  class_id uuid not null references public.classes(id) on delete cascade,
  access_key text not null,
  state text not null check (state in ('shown', 'hidden')),
  updated_by uuid references public.accounts(id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key (class_id, access_key)
);

create index if not exists lesson_access_overrides_org_class_idx
  on public.lesson_access_overrides(organization_id, class_id);

create table if not exists public.lesson_completions (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  account_id uuid not null references public.accounts(id) on delete cascade,
  access_key text not null,
  course_key text not null,
  unit_index integer not null check (unit_index >= 0),
  topic text not null,
  title text not null default '',
  completed_at timestamptz not null,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (account_id, access_key)
);

create index if not exists lesson_completions_account_course_idx
  on public.lesson_completions(account_id, course_key, completed_at desc);

alter table public.lesson_catalog enable row level security;
alter table public.lesson_access_overrides enable row level security;
alter table public.lesson_completions enable row level security;

comment on table public.lesson_catalog is
  'Server-side ordered ready-lesson catalog used for fail-closed student visibility.';
comment on table public.lesson_access_overrides is
  'Per-class teacher/admin shown or hidden overrides. Absence means automatic progression.';
comment on table public.lesson_completions is
  'Authenticated student lesson-completion evidence paired with completed practice sessions for progression.';

-- Seed the current ready-lesson catalog for every existing organization.
insert into public.lesson_catalog (
  organization_id, access_key, course_key, unit_index, unit_title, topic, title, position, url, is_ready
)
select organization.id, seed.*
from public.organizations organization
cross join (values
    ('ap-calculus::0::0', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '0', 'Welcome to AP Calculus · First Day, Diagnostic & Success Plan', 0, 'lessons/ap-calculus/course-launch/AP_Calculus_Lesson_0_First_Day_Diagnostic_ECHS.html', true),
    ('ap-calculus::0::1.1', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.1', 'Can Change Occur at an Instant?', 1, 'lessons/ap-calculus/unit-1/1-1-can-change-occur-at-an-instant.html', true),
    ('ap-calculus::0::1.2', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.2', 'Defining Limits and Using Limit Notation', 2, 'lessons/ap-calculus/unit-1/1-2-defining-limits-and-using-limit-notation.html', true),
    ('ap-calculus::0::1.3', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.3', 'Estimating Limit Values from Graphs', 3, 'lessons/ap-calculus/unit-1/1-3-estimating-limit-values-from-graphs.html', true),
    ('ap-calculus::0::1.4', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.4', 'Estimating Limit Values from Tables', 4, 'lessons/ap-calculus/unit-1/1-4-estimating-limit-values-from-tables.html', true),
    ('ap-calculus::0::1.5', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.5', 'Determining Limits Using Algebraic Properties of Limits', 5, 'lessons/ap-calculus/unit-1/1-5-algebraic-properties-of-limits.html', true),
    ('ap-calculus::0::1.6', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.6', 'Determining Limits Using Algebraic Manipulation', 6, 'lessons/ap-calculus/unit-1/1-6-algebraic-manipulation.html', true),
    ('ap-calculus::0::1.7', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.7', 'Selecting Procedures for Determining Limits', 7, 'lessons/ap-calculus/unit-1/1-7-selecting-limit-procedures.html', true),
    ('ap-calculus::0::1.8', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.8', 'Determining Limits Using the Squeeze Theorem', 8, 'lessons/ap-calculus/unit-1/1-8-squeeze-theorem.html', true),
    ('ap-calculus::0::1.9', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.9', 'Connecting Multiple Representations of Limits', 9, 'lessons/ap-calculus/unit-1/1-9-multiple-representations-of-limits.html', true),
    ('ap-calculus::0::1.10', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.10', 'Exploring Types of Discontinuities', 10, 'lessons/ap-calculus/unit-1/1-10-types-of-discontinuities.html', true),
    ('ap-calculus::0::1.11', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.11', 'Defining Continuity at a Point', 11, 'lessons/ap-calculus/unit-1/1-11-continuity-at-a-point.html', true),
    ('ap-calculus::0::1.12', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.12', 'Confirming Continuity over an Interval', 12, 'lessons/ap-calculus/unit-1/1-12-continuity-over-an-interval.html', true),
    ('ap-calculus::0::1.13', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.13', 'Removing Discontinuities', 13, 'lessons/ap-calculus/unit-1/1-13-removing-discontinuities.html', true),
    ('ap-calculus::0::1.14', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.14', 'Connecting Infinite Limits and Vertical Asymptotes', 14, 'lessons/ap-calculus/unit-1/1-14-infinite-limits-and-vertical-asymptotes.html', true),
    ('ap-calculus::0::1.15', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.15', 'Connecting Limits at Infinity and Horizontal Asymptotes', 15, 'lessons/ap-calculus/unit-1/1-15-limits-at-infinity-and-horizontal-asymptotes.html', true),
    ('ap-calculus::0::1.16', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.16', 'Working with the Intermediate Value Theorem', 16, 'lessons/ap-calculus/unit-1/1-16-intermediate-value-theorem.html', true),
    ('ap-calculus::0::1.R', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.R', 'Unit 1 Review: Limits and Continuity', 17, 'reviews/ap-calculus/unit-1/unit-1-comprehensive-review.pdf', true),
    ('ap-calculus::0::1.A', 'ap-calculus', 0, 'Unit 1: Limits and Continuity', '1.A', 'Unit 1 Assessment: Limits and Continuity', 18, 'lessons/ap-calculus/unit-1/unit-1-assessment.html', true),
    ('ap-calculus::1::2.1', 'ap-calculus', 1, 'Unit 2: Differentiation—Definition and Fundamental Properties', '2.1', 'Rates of Change and Tangent Lines', 19, 'lessons/ap-calculus/unit-2/2-1-rates-of-change-and-tangent-lines.html', true),
    ('ap-calculus::1::2.2', 'ap-calculus', 1, 'Unit 2: Differentiation—Definition and Fundamental Properties', '2.2', 'Tangent Lines and the Derivative', 20, 'lessons/ap-calculus/unit-2/2-2-tangent-lines-and-the-derivative.html', true),
    ('ap-calculus::1::2.3', 'ap-calculus', 1, 'Unit 2: Differentiation—Definition and Fundamental Properties', '2.3', 'The Derivative: Graphs, Differentiability, and Continuity', 21, 'lessons/ap-calculus/unit-2/2-3-derivative-graphs-differentiability-continuity.html', true),
    ('ap-calculus::1::2.4', 'ap-calculus', 1, 'Unit 2: Differentiation—Definition and Fundamental Properties', '2.4', 'Basic Derivative Rules', 22, 'lessons/ap-calculus/unit-2/2-4-basic-derivative-rules.html', true),
    ('ap-calculus::1::2.5', 'ap-calculus', 1, 'Unit 2: Differentiation—Definition and Fundamental Properties', '2.5', 'Product and Quotient Rules', 23, 'lessons/ap-calculus/unit-2/2-5-product-and-quotient-rules.html', true),
    ('ap-calculus::1::2.R', 'ap-calculus', 1, 'Unit 2: Differentiation—Definition and Fundamental Properties', '2.R', 'Unit 2 Review: Differentiation: Definition and Fundamental Properties', 24, 'reviews/ap-calculus/unit-2/unit-2-comprehensive-review.pdf', true),
    ('ap-calculus::1::2.A', 'ap-calculus', 1, 'Unit 2: Differentiation—Definition and Fundamental Properties', '2.A', 'Unit 2 Assessment: Differentiation: Definition and Fundamental Properties', 25, 'lessons/ap-calculus/unit-2/unit-2-assessment.html', true),
    ('ap-calculus::2::3.1', 'ap-calculus', 2, 'Unit 3: Differentiation- Composite, Implicit and Inverse Functions', '3.1', 'The Chain Rule', 26, 'lessons/ap-calculus/unit-3/3-1-chain-rule.html', true),
    ('ap-calculus::2::3.2', 'ap-calculus', 2, 'Unit 3: Differentiation- Composite, Implicit and Inverse Functions', '3.2', 'Implicit Differentiation', 27, 'lessons/ap-calculus/unit-3/3-2-implicit-differentiation.html', true),
    ('ap-calculus::2::3.3', 'ap-calculus', 2, 'Unit 3: Differentiation- Composite, Implicit and Inverse Functions', '3.3', 'Inverse Function and Inverse Trigonometric Derivatives', 28, 'lessons/ap-calculus/unit-3/3-3-inverse-function-and-inverse-trig-derivatives.html', true),
    ('ap-calculus::2::3.R', 'ap-calculus', 2, 'Unit 3: Differentiation- Composite, Implicit and Inverse Functions', '3.R', 'Unit 3 Review: Differentiation: Composite, Implicit, and Inverse Functions', 29, 'reviews/ap-calculus/unit-3/unit-3-comprehensive-review.pdf', true),
    ('ap-calculus::2::3.A', 'ap-calculus', 2, 'Unit 3: Differentiation- Composite, Implicit and Inverse Functions', '3.A', 'Unit 3 Assessment: Differentiation: Composite, Implicit, and Inverse Functions', 30, 'lessons/ap-calculus/unit-3/unit-3-assessment.html', true),
    ('ap-calculus::3::4.1', 'ap-calculus', 3, 'Unit 4: Contextual Applications of Differentiation', '4.1', 'Interpretations of the Derivative', 31, 'lessons/ap-calculus/unit-4/4-1-interpretations-of-the-derivative.html', true),
    ('ap-calculus::3::4.2', 'ap-calculus', 3, 'Unit 4: Contextual Applications of Differentiation', '4.2', 'Straight Line Motion', 32, 'lessons/ap-calculus/unit-4/4-2-straight-line-motion.html', true),
    ('ap-calculus::3::4.3', 'ap-calculus', 3, 'Unit 4: Contextual Applications of Differentiation', '4.3', 'Other Rates of Change', 33, 'lessons/ap-calculus/unit-4/4-3-other-rates-of-change.html', true),
    ('ap-calculus::3::4.4', 'ap-calculus', 3, 'Unit 4: Contextual Applications of Differentiation', '4.4', 'Related Rates', 34, 'lessons/ap-calculus/unit-4/4-4-related-rates.html', true),
    ('ap-calculus::3::4.5', 'ap-calculus', 3, 'Unit 4: Contextual Applications of Differentiation', '4.5', 'Linear Approximation', 35, 'lessons/ap-calculus/unit-4/4-5-linear-approximation.html', true),
    ('ap-calculus::3::4.6', 'ap-calculus', 3, 'Unit 4: Contextual Applications of Differentiation', '4.6', 'L’Hôpital’s Rule', 36, 'lessons/ap-calculus/unit-4/4-6-lhopitals-rule.html', true),
    ('ap-calculus::3::4.R', 'ap-calculus', 3, 'Unit 4: Contextual Applications of Differentiation', '4.R', 'Unit 4 Review: Contextual Applications of Differentiation', 37, 'reviews/ap-calculus/unit-4/unit-4-comprehensive-review.pdf', true),
    ('ap-calculus::3::4.A', 'ap-calculus', 3, 'Unit 4: Contextual Applications of Differentiation', '4.A', 'Unit 4 Assessment: Contextual Applications of Differentiation', 38, 'lessons/ap-calculus/unit-4/unit-4-assessment.html', true),
    ('ap-calculus::4::5.1', 'ap-calculus', 4, 'Unit 5: Analytical Applications of Differentiation', '5.1', 'Mean Value Theorem', 39, 'lessons/ap-calculus/unit-5/5-1-mean-value-theorem.html', true),
    ('ap-calculus::4::5.2–5.5 · I', 'ap-calculus', 4, 'Unit 5: Analytical Applications of Differentiation', '5.2–5.5 · I', 'Derivative Graph Analysis — Part 1', 40, 'lessons/ap-calculus/unit-5/5-2-to-5-5-derivative-graph-analysis-part-1.html', true),
    ('ap-calculus::4::5.2–5.5 · II', 'ap-calculus', 4, 'Unit 5: Analytical Applications of Differentiation', '5.2–5.5 · II', 'Derivative Graph Analysis — Part 2: Challenge Questions', 41, 'lessons/ap-calculus/unit-5/5-2-to-5-5-derivative-graph-analysis-part-2.html', true),
    ('ap-calculus::4::5.10', 'ap-calculus', 4, 'Unit 5: Analytical Applications of Differentiation', '5.10', 'Optimization Problems', 42, 'lessons/ap-calculus/unit-5/5-10-optimization-problems.html', true),
    ('ap-calculus::4::5.R', 'ap-calculus', 4, 'Unit 5: Analytical Applications of Differentiation', '5.R', 'Unit 5 Review: Analytical Applications of Differentiation', 43, 'reviews/ap-calculus/unit-5/unit-5-comprehensive-review.pdf', true),
    ('ap-calculus::4::5.A', 'ap-calculus', 4, 'Unit 5: Analytical Applications of Differentiation', '5.A', 'Unit 5 Assessment: Analytical Applications of Differentiation', 44, 'lessons/ap-calculus/unit-5/unit-5-assessment.html', true),
    ('ap-precalculus::0::0', 'ap-precalculus', 0, 'Unit 1: Polynomial and Rational Functions', '0', 'Welcome to AP Precalculus · First Day, Diagnostic & Success Plan', 0, 'lessons/ap-precalculus/course-launch/AP_Precalculus_Lesson_0_First_Day_Diagnostic_ECHS.html', true),
    ('ap-precalculus::0::1', 'ap-precalculus', 0, 'Unit 1: Polynomial and Rational Functions', '1', '1.1 Change in Tandem', 1, 'lessons/ap-precalculus/unit-1/AP_Precalculus_1.1_Change_in_Tandem_ECHS_Refined.html', true),
    ('ap-precalculus::0::2', 'ap-precalculus', 0, 'Unit 1: Polynomial and Rational Functions', '2', '1.2 Rates of Change', 2, 'lessons/ap-precalculus/unit-1/AP_Precalculus_1.2_Rates_of_Change_ECHS_Refined.html', true),
    ('ap-precalculus::0::3', 'ap-precalculus', 0, 'Unit 1: Polynomial and Rational Functions', '3', '1.3 Rates of Change in Linear and Quadratic Functions', 3, 'lessons/ap-precalculus/unit-1/AP_Precalculus_1.3_Rates_of_Change_in_Linear_and_Quadratic_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::0::4', 'ap-precalculus', 0, 'Unit 1: Polynomial and Rational Functions', '4', '1.4 Polynomial Functions and Rates of Change', 4, 'lessons/ap-precalculus/unit-1/AP_Precalculus_1.4_Polynomial_Functions_and_Rates_of_Change_ECHS_Refined.html', true),
    ('ap-precalculus::0::5', 'ap-precalculus', 0, 'Unit 1: Polynomial and Rational Functions', '5', '1.5 Polynomial Functions and Complex Zeros', 5, 'lessons/ap-precalculus/unit-1/AP_Precalculus_1.5_Polynomial_Functions_and_Complex_Zeros_ECHS_Refined.html', true),
    ('ap-precalculus::0::6', 'ap-precalculus', 0, 'Unit 1: Polynomial and Rational Functions', '6', '1.6 Polynomial Functions and End Behavior', 6, 'lessons/ap-precalculus/unit-1/AP_Precalculus_1.6_Polynomial_Functions_and_End_Behavior_ECHS_Refined.html', true),
    ('ap-precalculus::0::7', 'ap-precalculus', 0, 'Unit 1: Polynomial and Rational Functions', '7', '1.7 Rational Functions and End Behavior', 7, 'lessons/ap-precalculus/unit-1/AP_Precalculus_1.7_Rational_Functions_and_End_Behavior_ECHS_Refined.html', true),
    ('ap-precalculus::0::8', 'ap-precalculus', 0, 'Unit 1: Polynomial and Rational Functions', '8', '1.8 Rational Functions and Zeros', 8, 'lessons/ap-precalculus/unit-1/AP_Precalculus_1.8_Rational_Functions_and_Zeros_ECHS_Refined.html', true),
    ('ap-precalculus::0::9', 'ap-precalculus', 0, 'Unit 1: Polynomial and Rational Functions', '9', '1.9 Rational Functions and Vertical Asymptotes', 9, 'lessons/ap-precalculus/unit-1/AP_Precalculus_1.9_Rational_Functions_and_Vertical_Asymptotes_ECHS_Refined.html', true),
    ('ap-precalculus::0::10', 'ap-precalculus', 0, 'Unit 1: Polynomial and Rational Functions', '10', '1.10 Rational Functions and Holes', 10, 'lessons/ap-precalculus/unit-1/AP_Precalculus_1.10_Rational_Functions_and_Holes_ECHS_Refined.html', true),
    ('ap-precalculus::0::11', 'ap-precalculus', 0, 'Unit 1: Polynomial and Rational Functions', '11', '1.11 Equivalent Representations of Polynomial and Rational Expressions', 11, 'lessons/ap-precalculus/unit-1/AP_Precalculus_1.11_Equivalent_Representations_of_Polynomial_and_Rational_Expressions_ECHS_Refined.html', true),
    ('ap-precalculus::0::12', 'ap-precalculus', 0, 'Unit 1: Polynomial and Rational Functions', '12', '1.12 Transformations of Functions', 12, 'lessons/ap-precalculus/unit-1/AP_Precalculus_1.12_Transformations_of_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::0::13', 'ap-precalculus', 0, 'Unit 1: Polynomial and Rational Functions', '13', '1.13 Function Model Selection and Assumption Articulation', 13, 'lessons/ap-precalculus/unit-1/AP_Precalculus_1.13_Function_Model_Selection_and_Assumption_Articulation_ECHS_Refined.html', true),
    ('ap-precalculus::0::14', 'ap-precalculus', 0, 'Unit 1: Polynomial and Rational Functions', '14', '1.14 Function Model Construction and Application', 14, 'lessons/ap-precalculus/unit-1/AP_Precalculus_1.14_Function_Model_Construction_and_Application_ECHS_Refined.html', true),
    ('ap-precalculus::1::15', 'ap-precalculus', 1, 'Unit 2: Exponential and Logarithmic Functions', '15', '2.1 Change in Arithmetic and Geometric Sequences', 15, 'lessons/ap-precalculus/unit-2/AP_Precalculus_2.1_Change_in_Arithmetic_and_Geometric_Sequences_ECHS_Refined.html', true),
    ('ap-precalculus::1::16', 'ap-precalculus', 1, 'Unit 2: Exponential and Logarithmic Functions', '16', '2.2 Change in Linear and Exponential Functions', 16, 'lessons/ap-precalculus/unit-2/AP_Precalculus_2.2_Change_in_Linear_and_Exponential_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::1::17', 'ap-precalculus', 1, 'Unit 2: Exponential and Logarithmic Functions', '17', '2.3 Exponential Functions', 17, 'lessons/ap-precalculus/unit-2/AP_Precalculus_2.3_Exponential_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::1::18', 'ap-precalculus', 1, 'Unit 2: Exponential and Logarithmic Functions', '18', '2.4 Exponential Function Manipulation', 18, 'lessons/ap-precalculus/unit-2/AP_Precalculus_2.4_Exponential_Function_Manipulation_ECHS_Refined.html', true),
    ('ap-precalculus::1::19', 'ap-precalculus', 1, 'Unit 2: Exponential and Logarithmic Functions', '19', '2.5 Exponential Function Context and Data Modeling', 19, 'lessons/ap-precalculus/unit-2/AP_Precalculus_2.5_Exponential_Function_Context_and_Data_Modeling_ECHS_Refined.html', true),
    ('ap-precalculus::1::20', 'ap-precalculus', 1, 'Unit 2: Exponential and Logarithmic Functions', '20', '2.6 Competing Function Model Validation', 20, 'lessons/ap-precalculus/unit-2/AP_Precalculus_2.6_Competing_Function_Model_Validation_ECHS_Refined.html', true),
    ('ap-precalculus::1::21', 'ap-precalculus', 1, 'Unit 2: Exponential and Logarithmic Functions', '21', '2.7 Composition of Functions', 21, 'lessons/ap-precalculus/unit-2/AP_Precalculus_2.7_Composition_of_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::1::22', 'ap-precalculus', 1, 'Unit 2: Exponential and Logarithmic Functions', '22', '2.8 Inverse Functions', 22, 'lessons/ap-precalculus/unit-2/AP_Precalculus_2.8_Inverse_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::1::23', 'ap-precalculus', 1, 'Unit 2: Exponential and Logarithmic Functions', '23', '2.9 Logarithmic Expressions', 23, 'lessons/ap-precalculus/unit-2/AP_Precalculus_2.9_Logarithmic_Expressions_ECHS_Refined.html', true),
    ('ap-precalculus::1::24', 'ap-precalculus', 1, 'Unit 2: Exponential and Logarithmic Functions', '24', '2.10 Inverses of Exponential Functions', 24, 'lessons/ap-precalculus/unit-2/AP_Precalculus_2.10_Inverses_of_Exponential_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::1::25', 'ap-precalculus', 1, 'Unit 2: Exponential and Logarithmic Functions', '25', '2.11 Logarithmic Functions', 25, 'lessons/ap-precalculus/unit-2/AP_Precalculus_2.11_Logarithmic_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::1::26', 'ap-precalculus', 1, 'Unit 2: Exponential and Logarithmic Functions', '26', '2.12 Logarithmic Function Manipulation', 26, 'lessons/ap-precalculus/unit-2/AP_Precalculus_2.12_Logarithmic_Function_Manipulation_ECHS_Refined.html', true),
    ('ap-precalculus::1::27', 'ap-precalculus', 1, 'Unit 2: Exponential and Logarithmic Functions', '27', '2.13 Exponential and Logarithmic Equations and Inequalities', 27, 'lessons/ap-precalculus/unit-2/AP_Precalculus_2.13_Exponential_and_Logarithmic_Equations_and_Inequalities_ECHS_Refined.html', true),
    ('ap-precalculus::1::28', 'ap-precalculus', 1, 'Unit 2: Exponential and Logarithmic Functions', '28', '2.14 Logarithmic Function Context and Data Modeling', 28, 'lessons/ap-precalculus/unit-2/AP_Precalculus_2.14_Logarithmic_Function_Context_and_Data_Modeling_ECHS_Refined.html', true),
    ('ap-precalculus::1::29', 'ap-precalculus', 1, 'Unit 2: Exponential and Logarithmic Functions', '29', '2.15 Semi-log Plots', 29, 'lessons/ap-precalculus/unit-2/AP_Precalculus_2.15_Semi_log_Plots_ECHS_Refined.html', true),
    ('ap-precalculus::2::1', 'ap-precalculus', 2, 'Unit 3: Trigonometric and Polar Functions', '1', '3.1 Periodic Phenomena', 30, 'lessons/ap-precalculus/unit-3/AP_Precalculus_3.1_Periodic_Phenomena_ECHS_Refined.html', true),
    ('ap-precalculus::2::2', 'ap-precalculus', 2, 'Unit 3: Trigonometric and Polar Functions', '2', '3.2 Sine, Cosine, and Tangent', 31, 'lessons/ap-precalculus/unit-3/AP_Precalculus_3.2_Sine_Cosine_and_Tangent_ECHS_Refined.html', true),
    ('ap-precalculus::2::3', 'ap-precalculus', 2, 'Unit 3: Trigonometric and Polar Functions', '3', '3.3 Sine and Cosine Function Values', 32, 'lessons/ap-precalculus/unit-3/AP_Precalculus_3.3_Sine_and_Cosine_Function_Values_ECHS_Refined.html', true),
    ('ap-precalculus::2::4', 'ap-precalculus', 2, 'Unit 3: Trigonometric and Polar Functions', '4', '3.4 Sine and Cosine Function Graphs', 33, 'lessons/ap-precalculus/unit-3/AP_Precalculus_3.4_Sine_and_Cosine_Function_Graphs_ECHS_Refined.html', true),
    ('ap-precalculus::2::5', 'ap-precalculus', 2, 'Unit 3: Trigonometric and Polar Functions', '5', '3.5 Sinusoidal Functions', 34, 'lessons/ap-precalculus/unit-3/AP_Precalculus_3.5_Sinusoidal_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::2::6', 'ap-precalculus', 2, 'Unit 3: Trigonometric and Polar Functions', '6', '3.6 Sinusoidal Function Transformations', 35, 'lessons/ap-precalculus/unit-3/AP_Precalculus_3.6_Sinusoidal_Function_Transformations_ECHS_Refined.html', true),
    ('ap-precalculus::2::7', 'ap-precalculus', 2, 'Unit 3: Trigonometric and Polar Functions', '7', '3.7 Sinusoidal Function Context and Data Modeling', 36, 'lessons/ap-precalculus/unit-3/AP_Precalculus_3.7_Sinusoidal_Function_Context_and_Data_Modeling_ECHS_Refined.html', true),
    ('ap-precalculus::2::8', 'ap-precalculus', 2, 'Unit 3: Trigonometric and Polar Functions', '8', '3.8 The Tangent Function', 37, 'lessons/ap-precalculus/unit-3/AP_Precalculus_3.8_The_Tangent_Function_ECHS_Refined.html', true),
    ('ap-precalculus::2::9', 'ap-precalculus', 2, 'Unit 3: Trigonometric and Polar Functions', '9', '3.9 Inverse Trigonometric Functions', 38, 'lessons/ap-precalculus/unit-3/AP_Precalculus_3.9_Inverse_Trigonometric_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::2::10', 'ap-precalculus', 2, 'Unit 3: Trigonometric and Polar Functions', '10', '3.10 Trigonometric Equations and Inequalities', 39, 'lessons/ap-precalculus/unit-3/AP_Precalculus_3.10_Trigonometric_Equations_and_Inequalities_ECHS_Refined.html', true),
    ('ap-precalculus::2::11', 'ap-precalculus', 2, 'Unit 3: Trigonometric and Polar Functions', '11', '3.11 The Secant, Cosecant, and Cotangent Functions', 40, 'lessons/ap-precalculus/unit-3/AP_Precalculus_3.11_The_Secant_Cosecant_and_Cotangent_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::2::12', 'ap-precalculus', 2, 'Unit 3: Trigonometric and Polar Functions', '12', '3.12 Equivalent Representations of Trigonometric Functions', 41, 'lessons/ap-precalculus/unit-3/AP_Precalculus_3.12_Equivalent_Representations_of_Trigonometric_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::2::13', 'ap-precalculus', 2, 'Unit 3: Trigonometric and Polar Functions', '13', '3.13 Trigonometry and Polar Coordinates', 42, 'lessons/ap-precalculus/unit-3/AP_Precalculus_3.13_Trigonometry_and_Polar_Coordinates_ECHS_Refined.html', true),
    ('ap-precalculus::2::14', 'ap-precalculus', 2, 'Unit 3: Trigonometric and Polar Functions', '14', '3.14 Polar Function Graphs', 43, 'lessons/ap-precalculus/unit-3/AP_Precalculus_3.14_Polar_Function_Graphs_ECHS_Refined.html', true),
    ('ap-precalculus::2::15', 'ap-precalculus', 2, 'Unit 3: Trigonometric and Polar Functions', '15', '3.15 Rates of Change in Polar Functions', 44, 'lessons/ap-precalculus/unit-3/AP_Precalculus_3.15_Rates_of_Change_in_Polar_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::3::1', 'ap-precalculus', 3, 'Unit 4: Functions Involving Parameters, Vectors, and Matrices', '1', '4.1 — Parametric Functions', 45, 'lessons/ap-precalculus/unit-4/AP_Precalculus_4.1_Parametric_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::3::2', 'ap-precalculus', 3, 'Unit 4: Functions Involving Parameters, Vectors, and Matrices', '2', '4.2 — Parametric Functions Modeling Planar Motion', 46, 'lessons/ap-precalculus/unit-4/AP_Precalculus_4.2_Parametric_Functions_Modeling_Planar_Motion_ECHS_Refined.html', true),
    ('ap-precalculus::3::3', 'ap-precalculus', 3, 'Unit 4: Functions Involving Parameters, Vectors, and Matrices', '3', '4.3 — Parametric Functions and Rates of Change', 47, 'lessons/ap-precalculus/unit-4/AP_Precalculus_4.3_Parametric_Functions_and_Rates_of_Change_ECHS_Refined.html', true),
    ('ap-precalculus::3::4', 'ap-precalculus', 3, 'Unit 4: Functions Involving Parameters, Vectors, and Matrices', '4', '4.4 — Parametrically Defined Circles and Lines', 48, 'lessons/ap-precalculus/unit-4/AP_Precalculus_4.4_Parametrically_Defined_Circles_and_Lines_ECHS_Refined.html', true),
    ('ap-precalculus::3::5', 'ap-precalculus', 3, 'Unit 4: Functions Involving Parameters, Vectors, and Matrices', '5', '4.5 — Implicitly Defined Functions', 49, 'lessons/ap-precalculus/unit-4/AP_Precalculus_4.5_Implicitly_Defined_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::3::6', 'ap-precalculus', 3, 'Unit 4: Functions Involving Parameters, Vectors, and Matrices', '6', '4.6 — Conic Sections', 50, 'lessons/ap-precalculus/unit-4/AP_Precalculus_4.6_Conic_Sections_ECHS_Refined.html', true),
    ('ap-precalculus::3::7', 'ap-precalculus', 3, 'Unit 4: Functions Involving Parameters, Vectors, and Matrices', '7', '4.7 — Parametrization of Implicitly Defined Functions', 51, 'lessons/ap-precalculus/unit-4/AP_Precalculus_4.7_Parametrization_of_Implicitly_Defined_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::3::8', 'ap-precalculus', 3, 'Unit 4: Functions Involving Parameters, Vectors, and Matrices', '8', '4.8 — Vectors', 52, 'lessons/ap-precalculus/unit-4/AP_Precalculus_4.8_Vectors_ECHS_Refined.html', true),
    ('ap-precalculus::3::9', 'ap-precalculus', 3, 'Unit 4: Functions Involving Parameters, Vectors, and Matrices', '9', '4.9 — Vector-Valued Functions', 53, 'lessons/ap-precalculus/unit-4/AP_Precalculus_4.9_Vector_Valued_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::3::10', 'ap-precalculus', 3, 'Unit 4: Functions Involving Parameters, Vectors, and Matrices', '10', '4.10 — Matrices', 54, 'lessons/ap-precalculus/unit-4/AP_Precalculus_4.10_Matrices_ECHS_Refined.html', true),
    ('ap-precalculus::3::11', 'ap-precalculus', 3, 'Unit 4: Functions Involving Parameters, Vectors, and Matrices', '11', '4.11 — The Inverse and Determinant of a Matrix', 55, 'lessons/ap-precalculus/unit-4/AP_Precalculus_4.11_The_Inverse_and_Determinant_of_a_Matrix_ECHS_Refined.html', true),
    ('ap-precalculus::3::12', 'ap-precalculus', 3, 'Unit 4: Functions Involving Parameters, Vectors, and Matrices', '12', '4.12 — Linear Transformations and Matrices', 56, 'lessons/ap-precalculus/unit-4/AP_Precalculus_4.12_Linear_Transformations_and_Matrices_ECHS_Refined.html', true),
    ('ap-precalculus::3::13', 'ap-precalculus', 3, 'Unit 4: Functions Involving Parameters, Vectors, and Matrices', '13', '4.13 — Matrices as Functions', 57, 'lessons/ap-precalculus/unit-4/AP_Precalculus_4.13_Matrices_as_Functions_ECHS_Refined.html', true),
    ('ap-precalculus::3::14', 'ap-precalculus', 3, 'Unit 4: Functions Involving Parameters, Vectors, and Matrices', '14', '4.14 — Matrices Modeling Contexts', 58, 'lessons/ap-precalculus/unit-4/AP_Precalculus_4.14_Matrices_Modeling_Contexts_ECHS_Refined.html', true),
    ('ib-math-ai::0::0', 'ib-math-ai', 0, 'Unit 1: Number and Algebra', '0', 'Welcome to IB Math AI · First Day, Diagnostic & Success Plan', 0, 'lessons/ib-math-ai/course-launch/IB_Math_AI_Lesson_0_First_Day_Diagnostic_ECHS.html', true),
    ('ib-math-ai::0::1.1', 'ib-math-ai', 0, 'Unit 1: Number and Algebra', '1.1', 'Scientific Notation, Approximation and Error', 1, 'lessons/ib-math-ai/unit-1/lessons/IB_AI_SL_1.1_standard_form_ECHS.html', true),
    ('ib-math-ai::0::1.2', 'ib-math-ai', 0, 'Unit 1: Number and Algebra', '1.2', 'Arithmetic Sequences and Series', 2, 'lessons/ib-math-ai/unit-1/lessons/IB_AI_SL_1.2_arithmetic_sequences_ECHS.html', true),
    ('ib-math-ai::0::1.3', 'ib-math-ai', 0, 'Unit 1: Number and Algebra', '1.3', 'Geometric Sequences and Series', 3, 'lessons/ib-math-ai/unit-1/lessons/IB_AI_SL_1.3_geometric_sequences_ECHS.html', true),
    ('ib-math-ai::0::1.4', 'ib-math-ai', 0, 'Unit 1: Number and Algebra', '1.4', 'Financial Applications', 4, 'lessons/ib-math-ai/unit-1/lessons/IB_AI_SL_1.4_financial_models_ECHS.html', true),
    ('ib-math-ai::0::1.5', 'ib-math-ai', 0, 'Unit 1: Number and Algebra', '1.5', 'Exponent Laws and Logarithms', 5, 'lessons/ib-math-ai/unit-1/lessons/IB_AI_SL_1.5_logarithms_ECHS.html', true),
    ('ib-math-ai::0::1.6', 'ib-math-ai', 0, 'Unit 1: Number and Algebra', '1.6', 'Technology for Equations and Systems', 6, 'lessons/ib-math-ai/unit-1/lessons/IB_AI_SL_1.6_technology_equations_ECHS.html', true),
    ('ib-math-ai::1::2.1', 'ib-math-ai', 1, 'Unit 2: Functions', '2.1', 'Functions, Domain, Range, and Representations', 7, 'lessons/ib-math-ai/unit-2/lessons/IB_AI_SL_2.1_functions_domain_range_representations_ECHS.html', true),
    ('ib-math-ai::1::2.2', 'ib-math-ai', 1, 'Unit 2: Functions', '2.2', 'Linear and Quadratic Models', 8, 'lessons/ib-math-ai/unit-2/lessons/IB_AI_SL_2.2_linear_quadratic_models_ECHS.html', true),
    ('ib-math-ai::1::2.3', 'ib-math-ai', 1, 'Unit 2: Functions', '2.3', 'Polynomial and Rational Models', 9, 'lessons/ib-math-ai/unit-2/lessons/IB_AI_SL_2.3_polynomial_rational_models_ECHS.html', true),
    ('ib-math-ai::1::2.4', 'ib-math-ai', 1, 'Unit 2: Functions', '2.4', 'Exponential and Logarithmic Models', 10, 'lessons/ib-math-ai/unit-2/lessons/IB_AI_SL_2.4_exponential_logarithmic_models_ECHS.html', true),
    ('ib-math-ai::1::2.5', 'ib-math-ai', 1, 'Unit 2: Functions', '2.5', 'Transformations, Composition, and Inverses', 11, 'lessons/ib-math-ai/unit-2/lessons/IB_AI_SL_2.5_transformations_composition_inverses_ECHS.html', true),
    ('ib-math-ai::1::2.6', 'ib-math-ai', 1, 'Unit 2: Functions', '2.6', 'Regression, Technology, and Model Validation', 12, 'lessons/ib-math-ai/unit-2/lessons/IB_AI_SL_2.6_regression_technology_validation_ECHS.html', true),
    ('ib-math-ai::3::4.1', 'ib-math-ai', 3, 'Unit 4: Statistics and Probability', '4.1', 'Data, Populations, Samples, and Bias', 13, 'lessons/ib-math-ai/unit-4/lessons/IB_AI_SL_4.1_data_populations_samples_bias_ECHS.html', true),
    ('ib-math-ai::3::4.2', 'ib-math-ai', 3, 'Unit 4: Statistics and Probability', '4.2', 'Measures of Centre, Spread, and Outliers', 14, 'lessons/ib-math-ai/unit-4/lessons/IB_AI_SL_4.2_centre_spread_outliers_ECHS.html', true),
    ('ib-math-ai::3::4.3', 'ib-math-ai', 3, 'Unit 4: Statistics and Probability', '4.3', 'Frequency Tables, Grouped Data, and Cumulative Frequency', 15, 'lessons/ib-math-ai/unit-4/lessons/IB_AI_SL_4.3_frequency_grouped_cumulative_data_ECHS.html', true),
    ('ib-math-ai::3::4.4', 'ib-math-ai', 3, 'Unit 4: Statistics and Probability', '4.4', 'Correlation, Regression, and Interpretation', 16, 'lessons/ib-math-ai/unit-4/lessons/IB_AI_SL_4.4_correlation_regression_interpretation_ECHS.html', true),
    ('ib-math-ai::3::4.5', 'ib-math-ai', 3, 'Unit 4: Statistics and Probability', '4.5', 'Sets, Venn Diagrams, and Probability Language', 17, 'lessons/ib-math-ai/unit-4/lessons/IB_AI_SL_4.5_sets_venn_probability_language_ECHS.html', true),
    ('ib-math-ai::3::4.6', 'ib-math-ai', 3, 'Unit 4: Statistics and Probability', '4.6', 'Probability Rules and Two-Way Tables', 18, 'lessons/ib-math-ai/unit-4/lessons/IB_AI_SL_4.6_probability_rules_tables_ECHS.html', true),
    ('ib-math-ai::3::4.7', 'ib-math-ai', 3, 'Unit 4: Statistics and Probability', '4.7', 'Conditional Probability and Independent Events', 19, 'lessons/ib-math-ai/unit-4/lessons/IB_AI_SL_4.7_conditional_probability_independence_ECHS.html', true),
    ('ib-math-ai::3::4.8', 'ib-math-ai', 3, 'Unit 4: Statistics and Probability', '4.8', 'Tree Diagrams, Bayes, and Sequential Events', 20, 'lessons/ib-math-ai/unit-4/lessons/IB_AI_SL_4.8_tree_diagrams_bayes_sequential_events_ECHS.html', true),
    ('ib-math-ai::3::4.9', 'ib-math-ai', 3, 'Unit 4: Statistics and Probability', '4.9', 'Discrete Random Variables and Expected Value', 21, 'lessons/ib-math-ai/unit-4/lessons/IB_AI_SL_4.9_discrete_random_variables_expected_value_ECHS.html', true),
    ('ib-math-ai::3::4.10', 'ib-math-ai', 3, 'Unit 4: Statistics and Probability', '4.10', 'Binomial Distribution and Repeated Trials', 22, 'lessons/ib-math-ai/unit-4/lessons/IB_AI_SL_4.10_binomial_distribution_repeated_trials_ECHS.html', true),
    ('ib-math-ai::3::4.11', 'ib-math-ai', 3, 'Unit 4: Statistics and Probability', '4.11', 'Normal Distribution, Probabilities, and Quantiles', 23, 'lessons/ib-math-ai/unit-4/lessons/IB_AI_SL_4.11_normal_distribution_probabilities_quantiles_ECHS.html', true),
    ('ib-math-ai::3::4.12', 'ib-math-ai', 3, 'Unit 4: Statistics and Probability', '4.12', 'Inferential Statistics, Hypotheses, and Significance', 24, 'lessons/ib-math-ai/unit-4/lessons/IB_AI_SL_4.12_inferential_statistics_hypotheses_significance_ECHS.html', true),
    ('ib-math-ai::3::4.13', 'ib-math-ai', 3, 'Unit 4: Statistics and Probability', '4.13', 'Two-Sample t-Tests for Comparing Means', 25, 'lessons/ib-math-ai/unit-4/lessons/IB_AI_SL_4.13_two_sample_t_tests_means_ECHS.html', true),
    ('ib-math-ai::3::4.14', 'ib-math-ai', 3, 'Unit 4: Statistics and Probability', '4.14', 'Chi-Square Test for Independence', 26, 'lessons/ib-math-ai/unit-4/lessons/IB_AI_SL_4.14_chi_square_independence_ECHS.html', true),
    ('ib-math-ai::3::4.15', 'ib-math-ai', 3, 'Unit 4: Statistics and Probability', '4.15', 'Chi-Square Goodness-of-Fit Test', 27, 'lessons/ib-math-ai/unit-4/lessons/IB_AI_SL_4.15_chi_square_goodness_of_fit_ECHS.html', true),
    ('ib-math-ai::4::5.1', 'ib-math-ai', 4, 'Unit 5: Calculus', '5.1', 'Limits and Rates of Change', 28, 'lessons/ib-math-ai/unit-5/lessons/IB_AI_SL_5.1_limits_rates_change_ECHS.html', true),
    ('ib-math-ai::4::5.2', 'ib-math-ai', 4, 'Unit 5: Calculus', '5.2', 'Differentiation Rules and Derivative Functions', 29, 'lessons/ib-math-ai/unit-5/lessons/IB_AI_SL_5.2_derivatives_rules_functions_ECHS.html', true),
    ('ib-math-ai::4::5.3', 'ib-math-ai', 4, 'Unit 5: Calculus', '5.3', 'Tangents and Normals', 30, 'lessons/ib-math-ai/unit-5/lessons/IB_AI_SL_5.3_tangents_normals_ECHS.html', true),
    ('ib-math-ai::4::5.4', 'ib-math-ai', 4, 'Unit 5: Calculus', '5.4', 'Curve Behaviour and Stationary Points', 31, 'lessons/ib-math-ai/unit-5/lessons/IB_AI_SL_5.4_curve_behaviour_stationary_points_ECHS.html', true),
    ('ib-math-ai::4::5.5', 'ib-math-ai', 4, 'Unit 5: Calculus', '5.5', 'Optimisation and Modelling', 32, 'lessons/ib-math-ai/unit-5/lessons/IB_AI_SL_5.5_optimisation_modelling_ECHS.html', true),
    ('ib-math-ai::4::5.6', 'ib-math-ai', 4, 'Unit 5: Calculus', '5.6', 'Antidifferentiation and Accumulation', 33, 'lessons/ib-math-ai/unit-5/lessons/IB_AI_SL_5.6_antidifferentiation_accumulation_ECHS.html', true),
    ('ib-math-ai::4::5.7', 'ib-math-ai', 4, 'Unit 5: Calculus', '5.7', 'Area and the Trapezoidal Rule', 34, 'lessons/ib-math-ai/unit-5/lessons/IB_AI_SL_5.7_area_trapezoidal_rule_ECHS.html', true),
    ('ib-math-ai::5::6.1', 'ib-math-ai', 5, 'Unit 6: Exploration, Technology, and Exam Practice', '6.1', 'Technology Fluency Routines', 35, 'lessons/ib-math-ai/unit-6/lessons/IB_AI_SL_6.1_technology_fluency_routines_ECHS.html', true),
    ('ib-math-ai::5::6.2', 'ib-math-ai', 5, 'Unit 6: Exploration, Technology, and Exam Practice', '6.2', 'IA Question Design', 36, 'lessons/ib-math-ai/unit-6/lessons/IB_AI_SL_6.2_ia_question_design_ECHS.html', true),
    ('grade-9::0::0.1', 'grade-9', 0, 'Unit 0: Diagnostic & Algebra Bridge', '0.1', '0.1 Entry Diagnostic & Mathematical Profile', 0, 'lessons/pathways/grade-9/unit-0/g9-0.1-entry-diagnostic-mathematical-profile.html', true),
    ('grade-9::0::0.2', 'grade-9', 0, 'Unit 0: Diagnostic & Algebra Bridge', '0.2', '0.2 Number and Expression Fluency', 1, 'lessons/pathways/grade-9/unit-0/g9-0.2-number-expression-fluency.html', true),
    ('grade-9::0::0.3', 'grade-9', 0, 'Unit 0: Diagnostic & Algebra Bridge', '0.3', '0.3 Exponent Rules & Equation Solving', 2, 'lessons/pathways/grade-9/unit-0/g9-0.3-exponent-equation-repair.html', true),
    ('grade-9::1::1.1', 'grade-9', 1, 'Unit 1: Linear Relationships, Equations & Inequalities', '1.1', '1.1 Algebraic Expressions & Multi-Step Equations', 3, 'lessons/pathways/grade-9/unit-1/g9-1.1-algebraic-expressions-multi-step-equations.html', true),
    ('grade-9::1::1.2', 'grade-9', 1, 'Unit 1: Linear Relationships, Equations & Inequalities', '1.2', '1.2 Literal Equations & Formula Rearrangement', 4, 'lessons/pathways/grade-9/unit-1/g9-1.2-literal-equations-formula-rearrangement.html', true),
    ('grade-9::1::1.3', 'grade-9', 1, 'Unit 1: Linear Relationships, Equations & Inequalities', '1.3', '1.3 Slope and Rate of Change', 5, 'lessons/pathways/grade-9/unit-1/g9-1.3-slope-rate-of-change.html', true),
    ('grade-9::1::1.4', 'grade-9', 1, 'Unit 1: Linear Relationships, Equations & Inequalities', '1.4', '1.4 Representations of Linear Functions', 6, 'lessons/pathways/grade-9/unit-1/g9-1.4-representations-of-linear-functions.html', true),
    ('grade-9::1::1.5', 'grade-9', 1, 'Unit 1: Linear Relationships, Equations & Inequalities', '1.5', '1.5 Linear Inequalities', 7, 'lessons/pathways/grade-9/unit-1/g9-1.5-linear-inequalities.html', true),
    ('grade-9::1::1.6', 'grade-9', 1, 'Unit 1: Linear Relationships, Equations & Inequalities', '1.6', '1.6 Linear Modeling & Residual Thinking', 8, 'lessons/pathways/grade-9/unit-1/g9-1.6-linear-modeling-residual-thinking.html', true),
    ('grade-9::2::2.1', 'grade-9', 2, 'Unit 2: Systems, Absolute Value & Piecewise Models', '2.1', '2.1 Systems by Graphing and Substitution', 9, 'lessons/pathways/grade-9/unit-2/g9-2.1-systems-graphing-substitution.html', true),
    ('grade-9::2::2.2', 'grade-9', 2, 'Unit 2: Systems, Absolute Value & Piecewise Models', '2.2', '2.2 Systems by Elimination', 10, 'lessons/pathways/grade-9/unit-2/g9-2.2-systems-elimination.html', true),
    ('grade-9::2::2.3', 'grade-9', 2, 'Unit 2: Systems, Absolute Value & Piecewise Models', '2.3', '2.3 Systems in Three Variables', 11, 'lessons/pathways/grade-9/unit-2/g9-2.3-systems-three-variables.html', true),
    ('grade-9::2::2.4', 'grade-9', 2, 'Unit 2: Systems, Absolute Value & Piecewise Models', '2.4', '2.4 Systems of Inequalities', 12, 'lessons/pathways/grade-9/unit-2/g9-2.4-systems-of-inequalities.html', true),
    ('grade-9::2::2.5', 'grade-9', 2, 'Unit 2: Systems, Absolute Value & Piecewise Models', '2.5', '2.5 Absolute Value Equations & Inequalities', 13, 'lessons/pathways/grade-9/unit-2/g9-2.5-absolute-value-equations-inequalities.html', true),
    ('grade-9::2::2.6', 'grade-9', 2, 'Unit 2: Systems, Absolute Value & Piecewise Models', '2.6', '2.6 Piecewise-Defined Functions', 14, 'lessons/pathways/grade-9/unit-2/g9-2.6-piecewise-defined-functions.html', true),
    ('grade-9::3::3.1', 'grade-9', 3, 'Unit 3: Function Language & Multiple Representations', '3.1', '3.1 Relations, Functions & Function Notation', 15, 'lessons/pathways/grade-9/unit-3/g9-3.1-relations-functions-function-notation.html', true),
    ('grade-9::3::3.2', 'grade-9', 3, 'Unit 3: Function Language & Multiple Representations', '3.2', '3.2 Domain, Range & Interval Notation', 16, 'lessons/pathways/grade-9/unit-3/g9-3.2-domain-range-interval-notation.html', true),
    ('grade-9::3::3.3', 'grade-9', 3, 'Unit 3: Function Language & Multiple Representations', '3.3', '3.3 Increasing, Decreasing, Extrema & Intercepts', 17, 'lessons/pathways/grade-9/unit-3/g9-3.3-increasing-decreasing-extrema-intercepts.html', true),
    ('grade-9::3::3.4', 'grade-9', 3, 'Unit 3: Function Language & Multiple Representations', '3.4', '3.4 Transformations of Parent Functions', 18, 'lessons/pathways/grade-9/unit-3/g9-3.4-transformations-parent-functions.html', true),
    ('grade-9::3::3.5', 'grade-9', 3, 'Unit 3: Function Language & Multiple Representations', '3.5', '3.5 Average Rate of Change', 19, 'lessons/pathways/grade-9/unit-3/g9-3.5-average-rate-of-change.html', true),
    ('grade-9::3::3.6', 'grade-9', 3, 'Unit 3: Function Language & Multiple Representations', '3.6', '3.6 Composition and Inverse Concepts', 20, 'lessons/pathways/grade-9/unit-3/g9-3.6-composition-inverse-concepts.html', true),
    ('grade-9::4::4.1', 'grade-9', 4, 'Unit 4: Quadratic Functions & Equations', '4.1', '4.1 Quadratic Patterns & Graph Features', 21, 'lessons/pathways/grade-9/unit-4/g9-4.1-quadratic-patterns-graph-features.html', true),
    ('grade-9::4::4.2', 'grade-9', 4, 'Unit 4: Quadratic Functions & Equations', '4.2', '4.2 Three Forms of a Quadratic', 22, 'lessons/pathways/grade-9/unit-4/g9-4.2-three-forms-quadratic.html', true),
    ('grade-9::4::4.3', 'grade-9', 4, 'Unit 4: Quadratic Functions & Equations', '4.3', '4.3 Factoring Quadratics', 23, 'lessons/pathways/grade-9/unit-4/g9-4.3-factoring-quadratics.html', true),
    ('grade-9::4::4.4', 'grade-9', 4, 'Unit 4: Quadratic Functions & Equations', '4.4', '4.4 Completing the Square', 24, 'lessons/pathways/grade-9/unit-4/g9-4.4-completing-the-square.html', true),
    ('grade-9::4::4.5', 'grade-9', 4, 'Unit 4: Quadratic Functions & Equations', '4.5', '4.5 Quadratic Formula, Discriminant & Complex Numbers', 25, 'lessons/pathways/grade-9/unit-4/g9-4.5-quadratic-formula-discriminant-complex-numbers.html', true),
    ('grade-9::4::4.6', 'grade-9', 4, 'Unit 4: Quadratic Functions & Equations', '4.6', '4.6 Quadratic Inequalities', 26, 'lessons/pathways/grade-9/unit-4/g9-4.6-quadratic-inequalities.html', true),
    ('grade-9::4::4.7', 'grade-9', 4, 'Unit 4: Quadratic Functions & Equations', '4.7', '4.7 Quadratic Modeling & Optimization', 27, 'lessons/pathways/grade-9/unit-4/g9-4.7-quadratic-modeling-optimization.html', true),
    ('grade-9::5::5.1', 'grade-9', 5, 'Unit 5: Polynomial Functions & Algebra', '5.1', '5.1 Polynomial Operations', 28, 'lessons/pathways/grade-9/unit-5/g9-5.1-polynomial-operations.html', true),
    ('grade-9::5::5.2', 'grade-9', 5, 'Unit 5: Polynomial Functions & Algebra', '5.2', '5.2 Factoring Beyond Quadratics', 29, 'lessons/pathways/grade-9/unit-5/g9-5.2-factoring-beyond-quadratics.html', true),
    ('grade-9::5::5.3', 'grade-9', 5, 'Unit 5: Polynomial Functions & Algebra', '5.3', '5.3 Zeros, Factors & Multiplicity', 30, 'lessons/pathways/grade-9/unit-5/g9-5.3-zeros-factors-multiplicity.html', true),
    ('grade-9::5::5.4', 'grade-9', 5, 'Unit 5: Polynomial Functions & Algebra', '5.4', '5.4 Polynomial Division & Theorems', 31, 'lessons/pathways/grade-9/unit-5/g9-5.4-polynomial-division-theorems.html', true),
    ('grade-9::5::5.5', 'grade-9', 5, 'Unit 5: Polynomial Functions & Algebra', '5.5', '5.5 Polynomial Graphs & End Behavior', 32, 'lessons/pathways/grade-9/unit-5/g9-5.5-polynomial-graphs-end-behavior.html', true),
    ('grade-9::6::6.1', 'grade-9', 6, 'Unit 6: Rational & Radical Foundations', '6.1', '6.1 Rational Expressions & Restrictions', 33, 'lessons/pathways/grade-9/unit-6/g9-6.1-rational-expressions-restrictions.html', true),
    ('grade-9::6::6.2', 'grade-9', 6, 'Unit 6: Rational & Radical Foundations', '6.2', '6.2 Rational Equations', 34, 'lessons/pathways/grade-9/unit-6/g9-6.2-rational-equations.html', true),
    ('grade-9::6::6.3', 'grade-9', 6, 'Unit 6: Rational & Radical Foundations', '6.3', '6.3 Radicals & Rational Exponents', 35, 'lessons/pathways/grade-9/unit-6/g9-6.3-radicals-rational-exponents.html', true),
    ('grade-9::6::6.4', 'grade-9', 6, 'Unit 6: Rational & Radical Foundations', '6.4', '6.4 Radical Equations', 36, 'lessons/pathways/grade-9/unit-6/g9-6.4-radical-equations.html', true),
    ('grade-9::7::7.1', 'grade-9', 7, 'Unit 7: Exponential Functions & Sequences', '7.1', '7.1 Arithmetic and Geometric Sequences', 37, 'lessons/pathways/grade-9/unit-7/g9-7.1-arithmetic-geometric-sequences.html', true),
    ('grade-9::7::7.2', 'grade-9', 7, 'Unit 7: Exponential Functions & Sequences', '7.2', '7.2 Exponential Functions', 38, 'lessons/pathways/grade-9/unit-7/g9-7.2-exponential-functions.html', true),
    ('grade-9::7::7.3', 'grade-9', 7, 'Unit 7: Exponential Functions & Sequences', '7.3', '7.3 Equivalent Exponential Forms', 39, 'lessons/pathways/grade-9/unit-7/g9-7.3-equivalent-exponential-forms.html', true),
    ('grade-9::7::7.4', 'grade-9', 7, 'Unit 7: Exponential Functions & Sequences', '7.4', '7.4 Growth/Decay Modeling & Family Comparison', 40, 'lessons/pathways/grade-9/unit-7/g9-7.4-growth-decay-modeling-family-comparison.html', true),
    ('grade-9::8::8.1', 'grade-9', 8, 'Unit 8: Right-Triangle Trigonometry & Coordinate Applications', '8.1', '8.1 Right Triangles, Similarity & Pythagorean Relationships', 41, 'lessons/pathways/grade-9/unit-8/g9-8.1-right-triangles-similarity-pythagorean-relationships.html', true),
    ('grade-9::8::8.2', 'grade-9', 8, 'Unit 8: Right-Triangle Trigonometry & Coordinate Applications', '8.2', '8.2 Sine, Cosine & Tangent Ratios', 42, 'lessons/pathways/grade-9/unit-8/g9-8.2-sine-cosine-tangent-ratios.html', true),
    ('grade-9::8::8.3', 'grade-9', 8, 'Unit 8: Right-Triangle Trigonometry & Coordinate Applications', '8.3', '8.3 Inverse Trigonometry', 43, 'lessons/pathways/grade-9/unit-8/g9-8.3-inverse-trigonometry.html', true),
    ('grade-9::8::8.4', 'grade-9', 8, 'Unit 8: Right-Triangle Trigonometry & Coordinate Applications', '8.4', '8.4 Applied Trigonometry', 44, 'lessons/pathways/grade-9/unit-8/g9-8.4-applied-trigonometry.html', true),
    ('grade-9::9::9.1', 'grade-9', 9, 'Unit 9: AP Readiness Integration & Placement', '9.1', '9.1 Function Toolkit Synthesis', 45, 'lessons/pathways/grade-9/unit-9/g9-9.1-function-toolkit-synthesis.html', true),
    ('grade-9::9::9.2', 'grade-9', 9, 'Unit 9: AP Readiness Integration & Placement', '9.2', '9.2 Model Selection Across Families', 46, 'lessons/pathways/grade-9/unit-9/g9-9.2-model-selection-across-families.html', true),
    ('grade-9::9::9.3', 'grade-9', 9, 'Unit 9: AP Readiness Integration & Placement', '9.3', '9.3 AP-Style Multiple Representations', 47, 'lessons/pathways/grade-9/unit-9/g9-9.3-ap-style-multiple-representations.html', true),
    ('grade-9::9::9.4', 'grade-9', 9, 'Unit 9: AP Readiness Integration & Placement', '9.4', '9.4 Cumulative AP Readiness Capstone', 48, 'lessons/pathways/grade-9/unit-9/g9-9.4-cumulative-ap-readiness-capstone.html', true),
    ('algebra-2::0::R0.1', 'algebra-2', 0, 'R0: Diagnostic & Precision Repair', 'R0.1', 'R0.1 Common Entry Diagnostic', 0, 'lessons/pathways/grade-10/path-b/unit-r0/g10b-r0.1-common-entry-diagnostic.html', true),
    ('algebra-2::0::R0.2', 'algebra-2', 0, 'R0: Diagnostic & Precision Repair', 'R0.2', 'R0.2 Algebra Precision Repair', 1, 'lessons/pathways/grade-10/path-b/unit-r0/g10b-r0.2-algebra-precision-repair.html', true),
    ('algebra-2::0::R0.3', 'algebra-2', 0, 'R0: Diagnostic & Precision Repair', 'R0.3', 'R0.3 Function Notation, Domain & Representations', 2, 'lessons/pathways/grade-10/path-b/unit-r0/g10b-r0.3-function-notation-domain-representations.html', true),
    ('algebra-2::0::R0.4', 'algebra-2', 0, 'R0: Diagnostic & Precision Repair', 'R0.4', 'R0.4 Systems & Right-Triangle Trig Spot Repair', 3, 'lessons/pathways/grade-10/path-b/unit-r0/g10b-r0.4-systems-right-triangle-trig-spot-repair.html', true),
    ('algebra-2::1::R1.1', 'algebra-2', 1, 'R1: Polynomial & Rational Foundations', 'R1.1', 'R1.1 Rates of Change Foundations', 4, 'lessons/pathways/grade-10/path-b/unit-r1/g10b-r1.1-rates-of-change-foundations.html', true),
    ('algebra-2::1::R1.2', 'algebra-2', 1, 'R1: Polynomial & Rational Foundations', 'R1.2', 'R1.2 Quadratic Equation Mastery', 5, 'lessons/pathways/grade-10/path-b/unit-r1/g10b-r1.2-quadratic-equation-mastery.html', true),
    ('algebra-2::1::R1.3', 'algebra-2', 1, 'R1: Polynomial & Rational Foundations', 'R1.3', 'R1.3 Quadratic Functions, Forms & Inequalities', 6, 'lessons/pathways/grade-10/path-b/unit-r1/g10b-r1.3-quadratic-functions-forms-inequalities.html', true),
    ('algebra-2::1::R1.4', 'algebra-2', 1, 'R1: Polynomial & Rational Foundations', 'R1.4', 'R1.4 Polynomial Operations & Factoring', 7, 'lessons/pathways/grade-10/path-b/unit-r1/g10b-r1.4-polynomial-operations-factoring.html', true),
    ('algebra-2::1::R1.5', 'algebra-2', 1, 'R1: Polynomial & Rational Foundations', 'R1.5', 'R1.5 Polynomial Division & Theorems', 8, 'lessons/pathways/grade-10/path-b/unit-r1/g10b-r1.5-polynomial-division-theorems.html', true),
    ('algebra-2::1::R1.6', 'algebra-2', 1, 'R1: Polynomial & Rational Foundations', 'R1.6', 'R1.6 Polynomial Zeros, Multiplicity & Complex Roots', 9, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R1.6', true),
    ('algebra-2::1::R1.7', 'algebra-2', 1, 'R1: Polynomial & Rational Foundations', 'R1.7', 'R1.7 Polynomial End Behavior & Standard Graph Construction', 10, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R1.7', true),
    ('algebra-2::1::R1.8', 'algebra-2', 1, 'R1: Polynomial & Rational Foundations', 'R1.8', 'R1.8 Rational Expressions & Equations', 11, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R1.8', true),
    ('algebra-2::1::R1.9', 'algebra-2', 1, 'R1: Polynomial & Rational Foundations', 'R1.9', 'R1.9 Rational Functions: Zeros, Holes & Asymptotes', 12, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R1.9', true),
    ('algebra-2::1::R1.10', 'algebra-2', 1, 'R1: Polynomial & Rational Foundations', 'R1.10', 'R1.10 Transformations & Introductory Model Choice', 13, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R1.10', true),
    ('algebra-2::2::R2.1', 'algebra-2', 2, 'R2: Exponential & Logarithmic Foundations', 'R2.1', 'R2.1 Arithmetic & Geometric Sequences', 14, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R2.1', true),
    ('algebra-2::2::R2.2', 'algebra-2', 2, 'R2: Exponential & Logarithmic Foundations', 'R2.2', 'R2.2 Exponent Laws, Radicals & Rational Exponents', 15, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R2.2', true),
    ('algebra-2::2::R2.3', 'algebra-2', 2, 'R2: Exponential & Logarithmic Foundations', 'R2.3', 'R2.3 Exponential Functions & Transformations', 16, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R2.3', true),
    ('algebra-2::2::R2.4', 'algebra-2', 2, 'R2: Exponential & Logarithmic Foundations', 'R2.4', 'R2.4 Exponential Modeling', 17, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R2.4', true),
    ('algebra-2::2::R2.5', 'algebra-2', 2, 'R2: Exponential & Logarithmic Foundations', 'R2.5', 'R2.5 Composition of Functions', 18, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R2.5', true),
    ('algebra-2::2::R2.6', 'algebra-2', 2, 'R2: Exponential & Logarithmic Foundations', 'R2.6', 'R2.6 Inverse Functions', 19, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R2.6', true),
    ('algebra-2::2::R2.7', 'algebra-2', 2, 'R2: Exponential & Logarithmic Foundations', 'R2.7', 'R2.7 Logarithms as Inverses', 20, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R2.7', true),
    ('algebra-2::2::R2.8', 'algebra-2', 2, 'R2: Exponential & Logarithmic Foundations', 'R2.8', 'R2.8 Logarithm Properties & Change of Base', 21, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R2.8', true),
    ('algebra-2::2::R2.9', 'algebra-2', 2, 'R2: Exponential & Logarithmic Foundations', 'R2.9', 'R2.9 Exponential & Logarithmic Equations', 22, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R2.9', true),
    ('algebra-2::2::R2.10', 'algebra-2', 2, 'R2: Exponential & Logarithmic Foundations', 'R2.10', 'R2.10 Comparing Models & Regression', 23, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R2.10', true),
    ('algebra-2::2::R2.11', 'algebra-2', 2, 'R2: Exponential & Logarithmic Foundations', 'R2.11', 'R2.11 Semi-Log Plot Preview', 24, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R2.11', true),
    ('algebra-2::3::R3.1', 'algebra-2', 3, 'R3: Trigonometric & Polar Foundations', 'R3.1', 'R3.1 Radians & Standard Position', 25, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R3.1', true),
    ('algebra-2::3::R3.2', 'algebra-2', 3, 'R3: Trigonometric & Polar Foundations', 'R3.2', 'R3.2 Unit Circle Coordinates & Special Angles', 26, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R3.2', true),
    ('algebra-2::3::R3.3', 'algebra-2', 3, 'R3: Trigonometric & Polar Foundations', 'R3.3', 'R3.3 Sine, Cosine & Tangent Values', 27, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R3.3', true),
    ('algebra-2::3::R3.4', 'algebra-2', 3, 'R3: Trigonometric & Polar Foundations', 'R3.4', 'R3.4 Parent Sine & Cosine Graphs', 28, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R3.4', true),
    ('algebra-2::3::R3.5', 'algebra-2', 3, 'R3: Trigonometric & Polar Foundations', 'R3.5', 'R3.5 Sinusoidal Transformations', 29, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R3.5', true),
    ('algebra-2::3::R3.6', 'algebra-2', 3, 'R3: Trigonometric & Polar Foundations', 'R3.6', 'R3.6 Sinusoidal Modeling', 30, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R3.6', true),
    ('algebra-2::3::R3.7', 'algebra-2', 3, 'R3: Trigonometric & Polar Foundations', 'R3.7', 'R3.7 The Tangent Function', 31, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R3.7', true),
    ('algebra-2::3::R3.8', 'algebra-2', 3, 'R3: Trigonometric & Polar Foundations', 'R3.8', 'R3.8 Secant, Cosecant & Cotangent', 32, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R3.8', true),
    ('algebra-2::3::R3.9', 'algebra-2', 3, 'R3: Trigonometric & Polar Foundations', 'R3.9', 'R3.9 Inverse Trigonometric Functions', 33, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R3.9', true),
    ('algebra-2::3::R3.10', 'algebra-2', 3, 'R3: Trigonometric & Polar Foundations', 'R3.10', 'R3.10 Trigonometric Equations', 34, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R3.10', true),
    ('algebra-2::3::R3.11', 'algebra-2', 3, 'R3: Trigonometric & Polar Foundations', 'R3.11', 'R3.11 Core Trigonometric Identities', 35, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R3.11', true),
    ('algebra-2::3::R3.12', 'algebra-2', 3, 'R3: Trigonometric & Polar Foundations', 'R3.12', 'R3.12 Polar Coordinates', 36, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R3.12', true),
    ('algebra-2::3::R3.13', 'algebra-2', 3, 'R3: Trigonometric & Polar Foundations', 'R3.13', 'R3.13 Polar Graphs & Rate Language Preview', 37, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R3.13', true),
    ('algebra-2::4::R4.1', 'algebra-2', 4, 'R4: Function Synthesis & AP Transition', 'R4.1', 'R4.1 Transformations Across Families', 38, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R4.1', true),
    ('algebra-2::4::R4.2', 'algebra-2', 4, 'R4: Function Synthesis & AP Transition', 'R4.2', 'R4.2 Composition & Inverse Synthesis', 39, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R4.2', true),
    ('algebra-2::4::R4.3', 'algebra-2', 4, 'R4: Function Synthesis & AP Transition', 'R4.3', 'R4.3 Covariation & Rates Across Families', 40, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R4.3', true),
    ('algebra-2::4::R4.4', 'algebra-2', 4, 'R4: Function Synthesis & AP Transition', 'R4.4', 'R4.4 Model Selection, Regression & Limitations', 41, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R4.4', true),
    ('algebra-2::4::R4.5', 'algebra-2', 4, 'R4: Function Synthesis & AP Transition', 'R4.5', 'R4.5 Multiple Representations & AP Habits', 42, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R4.5', true),
    ('algebra-2::4::R4.6', 'algebra-2', 4, 'R4: Function Synthesis & AP Transition', 'R4.6', 'R4.6 Cumulative Readiness Studio', 43, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R4.6', true),
    ('algebra-2::4::R4.B', 'algebra-2', 4, 'R4: Function Synthesis & AP Transition', 'R4.B', 'R4.B Grade 11 AP Readiness Benchmark', 44, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R4.B', true),
    ('algebra-2::5::R5.1', 'algebra-2', 5, 'R5: AP Precalculus Launch', 'R5.1', 'R5.1 AP Preview: Change in Tandem & Rates', 45, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R5.1', true),
    ('algebra-2::5::R5.2', 'algebra-2', 5, 'R5: AP Precalculus Launch', 'R5.2', 'R5.2 AP Preview: Polynomial/Rational Reasoning', 46, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R5.2', true),
    ('algebra-2::5::R5.3', 'algebra-2', 5, 'R5: AP Precalculus Launch', 'R5.3', 'R5.3 AP Preview: Exponential & Logarithmic Thinking', 47, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R5.3', true),
    ('algebra-2::5::R5.4', 'algebra-2', 5, 'R5: AP Precalculus Launch', 'R5.4', 'R5.4 AP Preview: Trigonometric & Polar Thinking', 48, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R5.4', true),
    ('algebra-2::5::R5.5', 'algebra-2', 5, 'R5: AP Precalculus Launch', 'R5.5', 'R5.5 AP Mathematical Practices Familiarization', 49, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R5.5', true),
    ('algebra-2::5::R5.6', 'algebra-2', 5, 'R5: AP Precalculus Launch', 'R5.6', 'R5.6 Final AP Readiness Benchmark & Summer Bridge', 50, 'lessons/pathways/lesson.html?grade=10&path=pathB&lesson=R5.6', true)
) as seed(access_key, course_key, unit_index, unit_title, topic, title, position, url, is_ready)
on conflict (organization_id, access_key) do update set
  course_key = excluded.course_key,
  unit_index = excluded.unit_index,
  unit_title = excluded.unit_title,
  topic = excluded.topic,
  title = excluded.title,
  position = excluded.position,
  url = excluded.url,
  is_ready = excluded.is_ready,
  updated_at = now();
